### ISSUE TITLE
Mod not recognizing my Microphone

### ISSUE THREAD

**Issue by maxes195** [henkelmax/simple-voice-chat#10]
**Bug description**
I attempted to use this mod on my modded Minecraft server but have run into an issue on my PC where the mod doesn't seem to recognize my microphone. I notice it's not working because the voice testing button is inoperable, near the end of these log files you can see the error.

**Steps to reproduce the issue**
1. join a configured server
2. open the voice menu
3. press the voice test button
4. see that test hasn't worked

**Expected behavior**
I expected to be able to test my mic using the menu

**Log files**
https://gist.github.com/maxes195/5e19095bae4cb05f6ca88fa6601c5b06

**Versions**
- Minecraft version 1.16.4
- Forge version 35.1.11
- Mod version 1.0.3

**Other mods**
I'm running this on a semi heavy mod server but I've also tested this with only this mod on the server and client and have found the same issue.

**Comment by henkelmax** [comment]
There is no indication in your logs that your microphone isn't working. But it seems that your client is not able to connect to the voice chat server. Please make sure the port is opened on the server.
Can you send a video showing this issue.

**Comment by ajlittle** [comment]
Have the exact same issue, happens to everyone on the server. Let me know if you need my logs too.
https://streamable.com/qid7yb

**Comment by henkelmax** [comment]
@ajlittle can you send me the logs of the server and your client?

**Comment by ajlittle** [comment]
server: https://gist.github.com/ajlittle/44604bcad6cd4d40ce8ae13614d62b3b

client: https://gist.github.com/ajlittle/268f8e27aba7877092733ae5ba03a607

**Comment by maxes195** [comment]
the issue shown in ajlittles video is the same that would be shown if I were to record one. My server provider allocates ports for my server but it seems to be having issues, I've sent a ticket in to them about it. I'll update here if that yields any results.

**Comment by henkelmax** [comment]
@ajlittle you seem to have the same issue. Please check that your port is actually forwarded.

**Comment by henkelmax** [comment]
> the issue shown in ajlittles video is the same that would be shown if I were to record one. My server provider allocates ports for my server but it seems to be having issues, I've sent a ticket in to them about it. I'll update here if that yields any results.

Are you sure the port is UDP?

**Comment by henkelmax** [comment]
In the latest version the voice chat GUI should not open up when there is no connection to the voice chat server.

**Comment by ajlittle** [comment]
server: https://gist.github.com/ajlittle/0a636a234928942121d87fad479701b5
client: https://gist.github.com/ajlittle/997bee0c8d952246644b61adc8cd4697

Updated the plugin, the port is forwarded through UDP but it still doesn't work. not too sure what to do.

**Comment by henkelmax** [comment]
I'm sorry, but your logs are completely spammed with errors from other mods. Can you try it without other mods?

**Comment by ajlittle** [comment]
Server: https://gist.github.com/ajlittle/9538e5a8a75c1bc3589cf0be7d093b8a
Client: https://gist.github.com/ajlittle/6d40bddf16c79bd5d81e71f4488e3d7d

**Comment by henkelmax** [comment]
It seems that your client is able to send data to the server, but not the other way around.
I have no clue what causes this. 
Does this happen to every player on your server?

**Comment by ajlittle** [comment]
Yup

**Comment by henkelmax** [comment]
Maybe this is a configuration issue of your server. It seems that it blocks outgoing UDP packets.

**Comment by maxes195** [comment]
I'm still talking with my server providers but they're response times are terrible. the error I'm continuing to get on the server side is in here, it starts at 3410 
https://gist.github.com/maxes195/0c33c662983a6ef50d98bb258c7fdbda
and the client gives this error
VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection

**Comment by henkelmax** [comment]
```
[29Dec2020 03:29:50.244] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:156]: java.io.IOException: Operation not permitted (sendto failed)
[29Dec2020 03:29:50.244] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:156]: 	at java.net.PlainDatagramSocketImpl.send(Native Method)
[29Dec2020 03:29:50.245] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:156]: 	at java.net.DatagramSocket.send(DatagramSocket.java:693)
[29Dec2020 03:29:50.245] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:156]: 	at de.maxhenkel.voicechat.voice.common.NetworkMessage.sendTo(NetworkMessage.java:143)
[29Dec2020 03:29:50.245] [VoiceChatPacketProcessingThread/INFO] [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:156]: 	at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:110)
```

I think Minecraft server providers purposefully prevent sending network data except the normal Minecraft networking, so you can't use their servers for other stuff.

I also don't think that they will change that, unfortunately...

**Comment by ajlittle** [comment]
Server host responded with this:
"I would check with them that the plugin is setup to bind and send data from the IP it is allocated and not the main system IP, this is what needs to be done to ensure correct communication on our setup."
Would there be a way to bind the IP to a specific one?

**Comment by maxes195** [comment]
well I sent them that little snippet of code to see what they say. I know they allow plugins / mods like dynamap to run on they're servers so I don't see why this would be any different but I'll see.

**Comment by henkelmax** [comment]
@ajlittle

> Would there be a way to bind the IP to a specific one?

I added an option to bind the voice chat server to a specific IP. It is located in the server config.

Let me know if it works for you.

**Comment by ajlittle** [comment]
Works perfectly now, thanks.

**Comment by henkelmax** [comment]
Great!

**Comment by maxes195** [comment]
It seems it is probably the provider to blame, do you know of any server providers that are confirmed to work? Thanks for all your help in diagnosing the issue!

**Comment by henkelmax** [comment]
Unfortunately I don't use a Minecraft server provider.
But it seems that the provider @ajlittle uses, works.

**Comment by ajlittle** [comment]
Yup, I'm using BisectHosting and binding my IP to the dedicated IP they gave me and it works like a charm.

**Comment by AVisannoying** [comment]
So I recently switched to windows 11 and all of a sudden my simple voice chat mod stop recognizing my mic and it is only happening with me not the other members of the server

**Comment by LolItsHaiech** [comment]
Hey, I had this problem. make sure you enabled the microphone in the control panel>sounds
and make sure you allow minecraft to access the microphone in settings>privacy>microphone

**Comment by darkguyidk** [comment]
I had this problem, playing on smp.playpixels.net, my logs are here: [https://mclo.gs/bJMtRvt](https://mclo.gs/bJMtRvt)
