### ISSUE TITLE
Bind error

### ISSUE THREAD

**Issue by Stigee** [henkelmax/simple-voice-chat#101]
**Bug description**
The mod shows that it is working, but when i join in the server, it still shows me a message: "Voice chat unavailable"

**Steps to reproduce the issue**
Join in the server

**Expected behavior**
I expected it to just dont show that message and work normally.

**Log files**
[INFO] .... [voicechat/]: Server started at port 24454
...
[INFO] .... [voicechat/]: Sent secret to Stige_
...
[INFO] ....>.... [minecraft/DedicatedServer]: Client not connected

**Versions**
- Minecraft version 1.16.4
- Forge version 35.1.4
- Mod version 1.1.7

So what should i do to fix this?

**Comment by henkelmax** [comment]
Read the FAQ and the wiki.

**Comment by Stigee** [comment]
But the problem is that i already opened the ports, and everything is right.

**Comment by henkelmax** [comment]
Clearly not.

**Comment by Stigee** [comment]
And the voicemod even shows that it started at port 24454

**Comment by henkelmax** [comment]
That doesn't mean the port is actually forwarded.

**Comment by Stigee** [comment]
Ok, i was really wrong, sorry for loosing your time :/

**Comment by Mikq123** [comment]
em can i ask how to open the ports on icehost?
