### ISSUE TITLE
Make 1.16.3

### ISSUE THREAD

**Issue by nik4nao** [henkelmax/simple-voice-chat#103]
mods i use in my server are all 1.16.3, and would make the entire server better if this was 1.16.3, since forge has to be specific

**Describe the solution you'd like**
make it 1.16.3

**Describe alternatives you've considered**
this is the only working voice chat mod in recent versions that arent 1.5.2 or lower

**Additional context**
none

**Comment by henkelmax** [comment]
Just look into the files section
