### ISSUE TITLE
[Fabric] Voice chat unavailable

### ISSUE THREAD

**Issue by AllOutJay** [henkelmax/simple-voice-chat#104]
**Bug description**
The lovely error "Voice chat unavailable" is being received by friends and myself on Fabric. Server console does say "Server started at port 24455", "Sent secret to _____", & "Disconnecting client  ______", but I still get "Voice chat unavailable". Running "/voicechat test _____" results in the output "Client not connected" either. This is visible in the log below.

**Steps to reproduce the issue**
1. Server port was added and edited in the config to 24455.
2. Mod was installed on the Fabric server.
3. Mod was installed on the client.
4. Restart the server and client.
5. Log in to the server, pressing v or caps lock leads to "Voice chat unavailable".

**Expected behavior**
I expected the ability to see the voice chat menu or talk.

**Log files**
[Log here](https://gist.github.com/AllOutJay/8f9abab290c0b54788db55abaeb350a8).

**Versions**
- Minecraft version: 1.16.5
- Fabric version: 1.16.5, Fabric Loader 0.11.3
- Mod version: 1.16.5-1.0.16

**Other mods**
Server & client side: fabric-api-0.30.3+1.16

**Side note**
Server host has attempted to see why, and looked into doing Netcat, but they said Netcat wouldn't help as the servers are in containers unless they are mistaken or has something to do with their docker.

Someone else on the host said they were able to successfully install it, but they are using Forge. So I am not sure if there is a notable difference there between the 2 to where Forge would only work and Fabric wouldn't.

**Comment by henkelmax** [comment]
There is no difference between forge and fabric in this regard. It seems that your port isn't forwarded correctly, or the voice chat is not bound to the correct IP.

**Comment by MrConfuzled** [comment]
**Me and my friend are using https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/download/3459642 for Minecraft on a free minecraft server hosting website called aternos.org and we are having issues that when pressing "v" or "m" it says "Voice chat unavailable"**

**Comment by henkelmax** [comment]
> **Me and my friend are using https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/download/3459642 for Minecraft on a free minecraft server hosting website called aternos.org and we are having issues that when pressing "v" or "m" it says "Voice chat unavailable"**

Visit the discord for help. This is not a bug.
