### ISSUE TITLE
Voice chat not working like it should

### ISSUE THREAD

**Issue by CinnamonShaey** [henkelmax/simple-voice-chat#105]
i have a server on bisect hosting and had it working fine we do have mods, but im not sure thats the problem, when i join with the mods i can use voice mod fine, but when he join with the same mods and stuff, he gets timed out it says on the console, whilei can still use it...

**Comment by henkelmax** [comment]
Use the provided templates.

**Comment by CinnamonShaey** [comment]
> Use the provided templates.

what templates?

**Comment by henkelmax** [comment]
https://github.com/henkelmax/simple-voice-chat/issues/new/choose
