### ISSUE TITLE
Failed to send packet.

### ISSUE THREAD

**Issue by GJungle1** [henkelmax/simple-voice-chat#109]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**
https://i.imgur.com/IeHCF3F.png
Please help!

**Comment by GJungle1** [comment]
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/6146063/latest.log)

**Comment by GJungle1** [comment]
server ^

**Comment by GJungle1** [comment]
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/6146066/latest.log)
Client

**Comment by henkelmax** [comment]
Your hoster does not seem to allow to use custom ports.
