### ISSUE TITLE
More details

### ISSUE THREAD

**Issue by PowWow06** [henkelmax/simple-voice-chat#11]
So after looking everywhere on your mod description, I can't possibly find how to install it. You guys never mention if it has to be a forge server. Very hard to understand for beginners. A small tutorial video would be VERY appreciated!

**Comment by PowWow06** [comment]
You guys mention a *config* file, could it be more precise on where to find that config file?

**Comment by henkelmax** [comment]
> So after looking everywhere on your mod description, I can't possibly find how to install it. You guys never mention if it has to be a forge server. Very hard to understand for beginners. A small tutorial video would be VERY appreciated!

It is installed like every other forge mod. No extra explaination needed.

> You guys mention a config file, could it be more precise on where to find that config file?

Next time please use the issue template:

>  Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before reporting issues

The only setup needed is to forward port 24454/UDP. But that is also stated in the description.

**Comment by PowWow06** [comment]
Alright, thank you!

**Comment by henkelmax** [comment]
No problem. If you have any other questions, let me know.
