### ISSUE TITLE
A video explaining how to fix voice chat unavailable 

### ISSUE THREAD

**Issue by Euse22** [henkelmax/simple-voice-chat#111]
I have no idea how to use netcat. And the wiki isnt really clear on how to install netcat on my client or the server.

**Comment by henkelmax** [comment]
I already explained this a lot.
There is no single way to solve these problems.
If you don't understand it through the wiki, I can't help you.
There are too many requests for help and I can't help everybody.
Use google or ask someone that knows how to forward a port.
