### ISSUE TITLE
can't use voice chat on fabric

### ISSUE THREAD

**Issue by zaze06** [henkelmax/simple-voice-chat#112]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
the mod can't connect to the server

**Steps to reproduce the issue**
1. install fabric (1.16.5)
2. get a server on shockbyte
3. set the server version on shockbyte to fabric 
4. add simple voice chat to bother the server and client(s)
5. start server and client
6. stop server after it is done
5. add port to the server and set the port to the new port in the config fo then mod
6. add the servers IP and port to the setting for the mod
7. start-server
8. connect to the server and the not connected icon shuöd be present

**Expected behavior**
The mot get connected to the server

**Log files**
server: https://gist.github.com/zaze06/3862c1fd14d3cdd7db8e232e801606f2 (all the missing states if because I didn't change the world before removing all mods)
if clint log is needed tell me

**Versions**
- Minecraft version: 1.16.5
- Fabric version: 0.11.3
- Mod version: 1.0.18

**Other mods**
mods on the client: jumploader(i use curse forge so I have a forge but I have a fabric pack), fabric-API and voice chat
mods on the server: fabric-API and voice mod

**where i downloaded from**
I Downloaded the mod from the curse forge page so it's not a nonligit download

**Comment by zaze06** [comment]
btw I'm soon going to bed so I may not be awake to answer some questions

**Comment by henkelmax** [comment]
I said this multiple times now. I can't help everybody that isn't able to forward the port correctly.
Please do every step in the wiki or ask your hoster about the port forwarding.
