### ISSUE TITLE
Spigot Plugin(Hear me out)

### ISSUE THREAD

**Issue by GJungle1** [henkelmax/simple-voice-chat#113]
**Is your feature request related to a problem? Please describe.**
its a feature request, Is there a possibility to make a Spigot Plugin, that will act as a mod on a server-side. For example, there is a plugin on a server, and I have the mod on the client, I can't speak to others who also have the mod installed. That way we don't have to install the mod on the server but have to install it on the client. Instead of server mod, there will be a server plugin
**Describe the solution you'd like**
I just did
**Describe alternatives you've considered**
Maybe add support for SBukkit but It's not that important.
**Additional context**

**Comment by henkelmax** [comment]
This is completely useless, since there are tools that allow you to use Forge/Fabric in combination with Spigot.
I have already enough to do maintaining two different modloaders.

**Comment by fantahund** [comment]
You can try this version.

https://github.com/Brokkonaut/simple-voice-chat

Branch: master-spigot

**Comment by KPidS** [comment]
We just released Plasmo Voice. It's a proximity Voice Chat mod with a server-side made with Spigot. It's based on Simple Voice Chat. You don't need to sacrifice Spigot plugins and the convenience of players who don't use mods. Besides that, it's just a great proximity voice chat with 3D audio and lots of features.

https://www.spigotmc.org/resources/plasmo-voice-server.91064/

Check it out, you might find it useful.
