### ISSUE TITLE
Looping on "Trying to authenticate voice connection" (mac os)

### ISSUE THREAD

**Issue by bdunogier** [henkelmax/simple-voice-chat#116]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**
Yes. Many times. And the wiki. And the issue about Mac OS and the microphone permissions :)

**Bug description**
I get "Voice chat unavailable". Others on the server can use the mod fine, meaning that the server is (probably) well configured. Unlike them, I play on a macbook (10.15.7).

In the log, I get `[23:13:21] [VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection` line every second or so. According to the admin, he gets this in the server log:
```
[16:18:11] [VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection
[16:18:11] [main/INFO]: Setting sample rate to 16000 Hz, mic read size to 1000 and data length to 900 bytes
[16:18:11] [main/INFO]: Loaded 1192 advancements
[16:18:11] [VoiceChatClientThread/INFO]: Server acknowledged authentication
[16:19:11] [VoiceChatClientThread/INFO]: Received ping xxx-xxx-xxx, sending pong...
```

**Steps to reproduce the issue**
1. Installed voice chat
2. Tried the PTT or settings keys

**Expected behavior**
The voice chat client gets connected.

**Log files**
```
[23:10:57] [VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection
[23:10:57] [main/INFO]: Setting sample rate to 48000 Hz, codec to VOIP and frame size to 1920 byte
```

And many other voice connection lines.

**Versions**
- 1.16.5
- Fabric loader 1.11.3
- voicechat-1.16.5-1.1.1

P.S. The others really love your mod, great work.

**Comment by henkelmax** [comment]
Please send me your full logs.

**Comment by bdunogier** [comment]
https://gist.github.com/bdunogier/53c300cc71c9a050c6a4c8b9b8a8c9ac

I have left the host & ip on purpose as they may be relevant. I don't have direct access to the server logs, but I can try to get my hands on them if it helps.

**Comment by henkelmax** [comment]
Yeah, the server logs would help. It would also be helpful if you include the server config contents.
Do you have a windows computer, that you can try it with? I just want to rule out that it is caused by your network.

**Comment by bdunogier** [comment]
Yes, I do have a windows computer, and I indeed wanted to try with it to see if it was the OS or my network. I'll let you know, and I'll gather some data about the server I'll also try without the other mods. Thank you for your quick reaction 👍

**Comment by bdunogier** [comment]
Alright. It was PEBKAC, not a bug on your side... our server isn't running the very latest version, and it was failing to connect because of this (.09 vs .11). Maybe a more informative message would help, but in any case, it is connected now. I guess I'm back to not having a microphone because of the mac.

Thank you for your help, and sorry for wasting your time.
