### ISSUE TITLE
I can't connect to the server

### ISSUE THREAD

**Issue by KoenDe3e** [henkelmax/simple-voice-chat#117]
So I know half of the bug reports are the same issue, but i can't connect to the voicemod port when the server is open.  I tested it with netcat, and it worked. But only when i tested with a lower port (1085). It didn't work with the port 24454.
So I use the 1085 now but it still doesn't work.
It isn't a problem with port forwarding, because I am on the same LAN network as my raspberry pi.
Also i tested with excactly the same config on my PC and it did work there.
How does this work and do you have a solution?
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/6177243/latest.log)

**Comment by henkelmax** [comment]
It seems that you can't connect at all to the server. This is not an issue of the voicechat mod.

**Comment by KoenDe3e** [comment]
I can connect to the server, just not the voice mod. I think you misunderstood me.

**Comment by henkelmax** [comment]
According to your logs, you didn't connect to the server.

**Comment by KoenDe3e** [comment]
No, I didn't because I used telnet to check if the port was open.
Also I did this multiple times when I did login, and it still didn't work.

**Comment by henkelmax** [comment]
Then send me the logs of that.

**Comment by KoenDe3e** [comment]
Wait a sec i will get them

**Comment by KoenDe3e** [comment]
[2021-03-21-4.log](https://github.com/henkelmax/simple-voice-chat/files/6177307/2021-03-21-4.log)

**Comment by henkelmax** [comment]
I also need the logs of the client.
But it seems like the voice chat port is not forwarded correctly.
Have you checked everything? Have you bound the ip correctly?

**Comment by KoenDe3e** [comment]
I am on the same LAN connection as the raspberry pi, so port forwarding can't be an issue

**Comment by KoenDe3e** [comment]
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/6177324/latest.log)

**Comment by henkelmax** [comment]
That doesn't mean anything. Your PI has a firewall and most likely your PC too.

**Comment by KoenDe3e** [comment]
My pi does not have a firewall, and i turned it off for my PC

**Comment by henkelmax** [comment]
Nevermind. Just saw your client logs. Which version of the mod are you using?

**Comment by KoenDe3e** [comment]
The latest

**Comment by henkelmax** [comment]
Latest doesn't say anything. I need an exact version number of the client and the server.
It seems that you are using a different version on your client.

**Comment by KoenDe3e** [comment]
Oh yeah, I just saw. But i'm now testing with both 1.1.1 and i have the same problem, I will send a new log of both my client and my  server.

**Comment by henkelmax** [comment]
Next time, please use the provided template, this would make it much easier identifying the problem!

**Comment by KoenDe3e** [comment]
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/6177336/latest.log)
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/6177337/latest.log)

**Comment by henkelmax** [comment]
Seems to work fine, but your port setup is still not working.
Have you tried running your server on your PC?

**Comment by KoenDe3e** [comment]
Yes, it did work on my PC.
But as i am saying I am on the same LAN network as the PI so port setup shouldn't be a problem right?
And if it is a problem, do you know what to change?

**Comment by KoenDe3e** [comment]
I just have 0.0.0.0 as bind adress

**Comment by henkelmax** [comment]
Since it is working with your PC, it's not a bug of the mod. So you have to figure it out by yourself. I'm not a network technician!

**Comment by KoenDe3e** [comment]
Do you know what is the problem, according to the logs?
Is it just the port that doesnt work?

**Comment by KoenDe3e** [comment]
Maybe it is an idea to make a video tutorial of how to setup the mod, it would make this all 10 times easier.

**Comment by henkelmax** [comment]
https://github.com/henkelmax/simple-voice-chat/issues/111
