### ISSUE TITLE
On the server configs, there are no configs

### ISSUE THREAD

**Issue by DeckerExpert** [henkelmax/simple-voice-chat#118]
**Bug description**
In the folder of where the configs are supposed to be in, there isnt any.

**Steps to reproduce the issue**
1. Go find your server configs
2. Find nothing

**Expected behavior**
I expected to find the server configs to configure some stuff, but there isnt any.

**Versions**
- 1.16.5
- 36.1.0
- 1.0.18

**Other mods**
None. Only this one voice chat mod.

**Comment by henkelmax** [comment]
Read the FAQ, like the template says.

**Comment by DeckerExpert** [comment]
Oh sorry, my mistake. I misread that part. 
Thanks for informing me.
