### ISSUE TITLE
when connecting the port it breaks the server and the server wont start

### ISSUE THREAD

**Issue by Branban** [henkelmax/simple-voice-chat#122]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Whenever I add the mod everything is fine but the second I open the port it breaks everything and the server shuts off and wont turn on

**Steps to reproduce the issue**
1. open the port

**Expected behavior**
server will not open and will shut off immediately

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue
The server didnt give any information

**Versions**
- Minecraft version
- Forge version
- Mod version

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
AutoRegLib
Cosmetic Armor Reworked 
Doggy Talents
Morpheus 
Pogfish
Quark
Vivecraft Forge Extensions
Camera 
Create
MrCrayFish Furnature Mod
JEI
Netherite Horse Armor
Sit
Spiders 2.0
XercaMusic
and simple Voice chat

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
What do you mean with "Open the port"?
Please send me your logs.

**Comment by henkelmax** [comment]
Closed due to inactivity.
