### ISSUE TITLE
A microphone entity/block entity to increase the volume of a players microphone output

### ISSUE THREAD

**Issue by Gitberham** [henkelmax/simple-voice-chat#123]
I think a good addition to the simple voice chat mod is if there was a microphone entity/block entity that amplifies the sound of a player's voice to a bigger radius. This radius should be able to be configured in the server config.

**Comment by henkelmax** [comment]
This mod intentionally does not add blocks or entities, to make it compatible with vanilla clients.
Besides this you can amplify your microphone in the settings.
