### ISSUE TITLE
Fabric Source Code

### ISSUE THREAD

**Issue by ZeoNight** [henkelmax/simple-voice-chat#126]
Hello, i was gonna use this mod in a server but we dont really want the icons in it. The server is fabric and we can **NOT** change it. I was gonna edit the sourcecode abit to remove the icons. If you can give the fabric sourcecode. I will be pleased. Or maybe remove the icons for me and give the version? Thanks.

**Comment by henkelmax** [comment]
Just look into the branches!
https://github.com/henkelmax/simple-voice-chat/tree/master-fabric

**Comment by ZeoNight** [comment]
Sorry! Didnt see it.
