### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by ZeoNight** [henkelmax/simple-voice-chat#128]
How to compile the project? Sorry if im asking dumb questions. My IDE doesnt show them.

**Comment by henkelmax** [comment]
I'm sorry, but I can't help you with that. Use google to find out how to compile or run a gradle project.

**Comment by ZeoNight** [comment]
Hey another question. Whats this opus4j libary? my maven couldnt find it.

**Comment by henkelmax** [comment]
Yeah I forgot to push it to my maven. It should work now.

https://maven.maxhenkel.de/#artifact/de.maxhenkel.opus4j/opus4j/1.0.0

**Comment by ZeoNight** [comment]
Intellij didnt refresh yet waiting.

**Comment by henkelmax** [comment]
You can go to File -> Invalidate Caches/Restart -> Invalidate and Restart

**Comment by ZeoNight** [comment]
while building Error: No obfuscation mapping for @Inject target renderLabelIfPresent
    @Inject(at = @At("HEAD"), method = "renderLabelIfPresent")
    ^

**Comment by ZeoNight** [comment]
EntityRenderMixin btw.

**Comment by henkelmax** [comment]
I'm sorry, but you'll have to figure that out by yourself. See the fabric documentation for reference.

**Comment by ZeoNight** [comment]
I couldnt figure it out. Can you please help?

**Comment by ZeoNight** [comment]
I saw a few options like `remap=false` but they just lead to other errors.

**Comment by henkelmax** [comment]
I have no clue what the problem is, I can't blindly tell you what to do. You have to figure it out yourself.

**Comment by ZeoNight** [comment]
Fixed it.

**Comment by ZeoNight** [comment]
Hey! fabric-group branch seems to be updated 5 days ago tho fabric-master is 10 days ago. Whats the diffrence?

**Comment by henkelmax** [comment]
I am working on a group chat feature for the hermits. But that is still in development and not stable.
