### ISSUE TITLE
Dedicated IP (continue)

### ISSUE THREAD

**Issue by K9Kr** [henkelmax/simple-voice-chat#129]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**

You answered that I dont need to buy dedicated IP. But how do I open port on Minecraft Server hosting site when support said this: "You don't have to port forward on our hosting. All you need to do is to go to the "Network" section of your game panel and click on "Create Allocation" which will create a random port for you. However, if you are in need of a specific port, you will need to buy a dedicated ip addon"

Sorry, I dont want to be annyoing and everything but I really want SImple Voice Chat to work on my server because I have been looking really forward to it

**Comment by henkelmax** [comment]
OK, but this might be something that is due to the implementation of your hoster.
If your hoster says so, yes.
But in general this mod does not need a dedicated IP.

If you have any more questions, please ask them to your hoster.
