### ISSUE TITLE
Implement a dropdown menu to change playback and recording devices.

### ISSUE THREAD

**Issue by ajlittle** [henkelmax/simple-voice-chat#13]
**Is your feature request related to a problem? Please describe.**
Currently, the mod uses the clients default playback and recording device to handle audio, and this leads to players being unable to hear each other without changing settings sometimes.

**Describe the solution you'd like**
A dropdown menu for choosing the playback devices/recording devices in the voice chats settings.

**Comment by henkelmax** [comment]
Let me know if it works for you.

**Comment by ajlittle** [comment]
Works perfectly.

**Comment by henkelmax** [comment]
Great!
