### ISSUE TITLE
High CPU Usage when muted 

### ISSUE THREAD

**Issue by uood5** [henkelmax/simple-voice-chat#131]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
When muted in-game CPU usage is around 10% more than when unmuted (On a Ryzen 3700x). Does not occur when muted & deafened.

**Steps to reproduce the issue**
1. Join Fabric server with SVC installed
2. Mute using mute keybind
3. Observe higher CPU usage

Problem is present no matter which codec is used.

**Expected behavior**
No increase in CPU usage when muted.

**Log files**
No log files as the game doesn't crash.

**Versions**
- Minecraft 1.16.5
- Fabric loader 11.2
- Fabric API 0.30.0

**Other mods**
The problem occurs no matter what mods are installed.

**Screenshots (Optional)**
Normal CPU Usage:
![Normal CPU Usage](https://user-images.githubusercontent.com/81475832/112723699-d2da5880-8f07-11eb-8485-9ccb778df7e5.png)
CPU usage when muted:
![CPU usage when muted](https://user-images.githubusercontent.com/81475832/112723731-ebe30980-8f07-11eb-8f03-a0c5cab65286.png)

**Comment by henkelmax** [comment]
Which mod version are you using?
I need the logs of your client, no matter if it crashed.

**Comment by henkelmax** [comment]
Nevermind. I found the issue.

**Comment by henkelmax** [comment]
It should be fixed in the latest version. Please let me know if it works for you.
For me the CPU usage just increased about 5-10%, so I didn't notice it.

**Comment by uood5** [comment]
Thank you! I only noticed it myself because my CPU cooler fans would ramp up slightly when muted.

**Comment by uood5** [comment]
Hi, I am not able to test if the update fixes the issue for me as only the Forge version has updated. Once the fabric one is fixed as well I will let you know :)

**Comment by henkelmax** [comment]
I updated every version. Take a closer look at the files section.

**Comment by uood5** [comment]
Sorry, didn't see. The issue is now definitely fixed though! Thank you for your swift response, have a great weekend.

**Comment by henkelmax** [comment]
Thank you!
