### ISSUE TITLE
Voicechat unavailable for everyone

### ISSUE THREAD

**Issue by Yucareux** [henkelmax/simple-voice-chat#133]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
We changed to another server provider, and since then voicechat is not working for anyone.

**Steps to reproduce the issue**
There are not steps, since voicechat is just not working

**Expected behavior**
Voicechat should be working for everyone

**Log files**
[latestUser.log](https://github.com/henkelmax/simple-voice-chat/files/6216847/latestUser.log)
[latestServer.log](https://github.com/henkelmax/simple-voice-chat/files/6216848/latestServer.log)

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.1.0
- Mod version: 1.1.0 (also tested on 1.1.1)

**Other mods**
There are a plenty of mods installed, but voicechat was working perfectly, the problem came in when we changed server provider.

**Screenshots (Optional)**
No screenshots

**Comment by henkelmax** [comment]
As I said multiple times. This is not a bug. You didn't forward your port correctly. Ask your hoster on how to forward a port.
