### ISSUE TITLE
Microphone turns on when you don't need to

### ISSUE THREAD

**Issue by Strongleong** [henkelmax/simple-voice-chat#137]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**
Done

**Bug description**
I set the push-to-speak button to 'v' and when I write in a text chat and press the push-to-talk button the microphone turns on. 

**Steps to reproduce the issue**
1. Open text chat
2. Press the push-to-talk button
3. ???
4. Profit!

**Expected behavior**
Not enabling mic.

**Log files**
(I don't think it is necessary)

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.1.0
- Mod version: 1.1.2

**Other mods**
None

**Screenshots (Optional)**
![2021-03-29_15 52 06](https://user-images.githubusercontent.com/17177071/112864254-60ce6300-9103-11eb-96c5-6739050c3be6.png)

**Comment by henkelmax** [comment]
This is intended behavior. I purposefully added this mechanic so that you can still talk while in GUIs. You can prevent this by assigning the key to a key that doesn't type anything for example your mouse back button.

**Comment by Strongleong** [comment]
So I think it needs to be an option. Just one tiny checkbox

**Comment by henkelmax** [comment]
I may add that in the future, but its not my priority, since every other voice chat software (Like TeamSpeak) works like that.
