### ISSUE TITLE
unknown custom packet identifier: voicechat:default

### ISSUE THREAD

**Issue by RandomUser1107** [henkelmax/simple-voice-chat#138]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**

set the server ip, and the port but i'm getting the error in the title on the client side along with trying to authenticate, and serverside i'm getting  VoiceChatPacketProcessingThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:188]: at java.net.DatagramSocket.send(DatagramSocket.java:693)

**Comment by henkelmax** [comment]
Please send me your full logs.

**Comment by RandomUser1107** [comment]
https://pastebin.com/nNsKQrye

those were the server logs

**Comment by RandomUser1107** [comment]
[B#625]  [23:52:30.960] [Render thread/INFO] [voicechat/]: Received secret 
[B#625]  [23:52:30.960] [Render thread/INFO] [voicechat/]: Connecting to server: 'ip204.ip-51-81-174.us:6095' 
[B#625]  [23:52:31.014] [Render thread/WARN] [network.play.ClientPlayNetHandler/]: Unknown custom packet identifier: voicechat:default 
[B#625]  [23:52:31.014] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:32.017] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:33.018] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:34.018] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:35.018] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:36.018] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:37.019] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:38.019] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:39.020] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:40.020] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:41.020] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:41.204] [Render thread/WARN] [network.play.ClientPlayNetHandler/]: Unknown custom packet identifier: voicechat:default 
[B#625]  [23:52:41.204] [Render thread/INFO] [voicechat/]: Received secret 
[B#625]  [23:52:41.204] [Render thread/INFO] [voicechat/]: Disconnecting client 
[B#625]  [23:52:41.205] [Render thread/INFO] [voicechat/]: Connecting to server: 'ip204.ip-51-81-174.us:6095' 
[B#625]  [23:52:41.205] [Render thread/WARN] [network.play.ClientPlayNetHandler/]: Unknown custom packet identifier: voicechat:default 
[B#625]  [23:52:41.205] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:42.205] [VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection 
[B#625]  [23:52:42.671] [Render thread/INFO] [gui.NewChatGui/]: [CHAT] [Server: Saved the game] 
[B#625]  [23:52:42.726] [Render thread/INFO] [STDOUT/]: [xaero.common.XaeroMinimapSession:cleanup:67]: Minimap session finalized. 
[B#625]  [23:52:42.738] [Render thread/INFO] [voicechat/]: Disconnecting client 


and those are the client logs from connecting to disconnect

**Comment by henkelmax** [comment]
> java.io.IOException: Operation not permitted (sendto failed)

It seems that your hoster does not allow custom ports.
