### ISSUE TITLE
Players can't use voice chat

### ISSUE THREAD

**Issue by iAlfa** [henkelmax/simple-voice-chat#14]
**Bug Description:**
Me and my friend was testing out the mod when we weren't able to use the mod, whenever we tried pressing the "V" button, "Voice Chat Unavailable" pops up.

I have read the closed issue #10 but I am unsure if I have the same issues with them regarding this. As I can't seem to bind a specific IP (not sure if it's the `server.properties`) nor know what IP to bind.

**Log File**
Both my client and server logs are in this link.
https://gist.github.com/iAlfa/7532b074c05a59cdaf596c3c376887e4

**Comment by henkelmax** [comment]
This is definitely related to #10
The IP bind option is in the server config of the mod.
You have to ask your server hoster for specific information.

**Comment by henkelmax** [comment]
With the IP, the hoster assigns to you to use port forwardings. I think this depends on every individual hoster. Maybe they have an FAQ or something on their website.

**Comment by iAlfa** [comment]
Alright! Thank you.

**Comment by henkelmax** [comment]
No problem!
