### ISSUE TITLE
Microphone not being detected

### ISSUE THREAD

**Issue by Viseper** [henkelmax/simple-voice-chat#141]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Logging onto the server, it says that voice is connected. I can hear everyone and they seem to have no problems. However whenever I try to speak, it does not register my microphone. No symbol appears when using push-to-talk and when I try to enable microphone testing, the button does not work. Upon checking the client side logs, it says No Microphone but I have a microphone that does work with other software.

This is a lightly modded 1.16.5 server. No one else has this problem. I've tried restarting minecraft, multiple times. I've tested the Microphone with other apps. I've double checked configs and have reviewed the logs. I've also tested using voice detection as well and have tried changing the selected microphone. Switching between default and the actual mic but nothing changes.

**Steps to reproduce the issue**
1. Connect to server
2. Wait for authentication
3. Try to speak
4. Open voice chat settings
5. Click enable microphone testing

**Expected behavior**
Upon pushing the push-to-talk button, the symbol should appear and the other players should be able to hear me. Pressing enable microphone testing should result in me being able to myself.

**Log files**
Most of the errors can be found near the bottom of the log but these are the entire logs from server boot up to server close and client boot up to client close.
https://gist.github.com/Viseper/a6ee353e8b717aa0992408b9f061f8a1

**Versions**
- 1.16.5
- Fabric 0.11.2-1.16.5
- 1.16.5-1.1.5

I hope this covers everything.

**Comment by henkelmax** [comment]
Is your main microphone listed in the select microphone menu?

**Comment by Viseper** [comment]
Yes it is.

**Comment by henkelmax** [comment]
Have you selected that microphone?
Do you have any other microphone that you can try out?

**Comment by Viseper** [comment]
Yes, I did select that microphone. Unfortunately, I do not have any other microphones to try out.

**Comment by henkelmax** [comment]
Can you try it without any other mods installed?

**Comment by henkelmax** [comment]
> line with format PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported

It seems that your microphone is not supported by the audio format of the voice chat mod.

**Comment by Viseper** [comment]
Well that is annoying. What specifications do I need, to use the voice chat mod?

**Comment by henkelmax** [comment]
As the log message says:

> line with format PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported

**Comment by Viseper** [comment]
Okay thanks. I guess since the mic is not supported. Then there is not much I can do untill I get a new microphone.
Thank you for your time.

**Comment by henkelmax** [comment]
No problem!
