### ISSUE TITLE
"Voice chat unavailable"

### ISSUE THREAD

**Issue by CringusTenFajny** [henkelmax/simple-voice-chat#146]
I'm getting this error every time I want to open voice chat settings. My hosting is Shockbyte. Can someone help me?
![image](https://user-images.githubusercontent.com/53151845/113507909-71d90300-954d-11eb-9c7a-50cdabd5109d.png)

**Comment by henkelmax** [comment]
Duplicate of #112, #104, #98, #97, #115, #124 and many others.
