### ISSUE TITLE
Feature request : whisper while sneaking

### ISSUE THREAD

**Issue by buckTarle** [henkelmax/simple-voice-chat#149]
As we discuss about the vocal distance we should use when playing a mini-game I'm working on, we thought it would be really nice if we could whisper.

Maybe when you sneak, distance you can be heard get divided by 10 or something like that.

Could be another key user choose.
Dividing factor might also be an option.

I think it could be a really neat feature to had.
I might have a look at the code to see if i can submit a pull request but I never tried minecraft mods and my java is not on point.

Anyway, great mod thanks

**Comment by henkelmax** [comment]
I don't think this feature would add much to the game. Just more complexity (It is called SIMPLE Voice Chat). Also people wouldn't understand why they are quieter while sneaking and wouldn't understand why others can't hear them.
