### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by Ozzxx** [henkelmax/simple-voice-chat#155]
The server crashes on startup when Simple Voice Chat version 1.2.0 is installed on a Fabric 1.16.5 server.
[Here's the server logs](https://pastebin.com/sec5EK7u)

**A complete list of all the mods I have installed:**
- Artifacts 3.2.0
- Autoconfig1u 3.3.1
- BetterCaves 1.1
- Bettersleepplus 2.4.0
- Cardinal Components API 2.8.0
- Cloth Config 4.11.19
- Convenient Mobgriefing 2.0.0
- Cosmetic Armor 1.0.0
- Croptopia 1.3.3
- Curios Fabric 0.0.13
- Disableportals 0.2.0
- DontBurnMyStuff 1.0.0
- Endermen Are Friends 1.0.1
- Environmental Armor 1.3.0
- Extraorigins 1.16.5-11
- Fabric API 0.32.9
- Fabric Pigsteel Mod 1.2.4
- FabricHomes 0.1.3
- GoFish 1.2.1-beta
- InstantLava 1.2.1
- InventorySorter 1.7.8
- LuckPerms 5.3.21
- Moborigins 1.3.1
- No Sneaking Over Magma 1.0.6
- Origins 0.7.0
- Origins Classes 1.1.1
- Originsumbrellas 1.1.0
- Pehkui 2.0.0
- Respawnablepets 1.16.5-2
- SimpleBackpack 1.0.38
- Stop Strider Suffering 1.2
- Suitablystackablestew 1.1.1
- Terrestria 2.2.0
- TransparentCosmetics 1.2.0
- Trinkets 2.6.7
- Unsaddle Pigs 1.2
- Voicechat 1.2.0
- YungsApi 1.16.5-2

Thank you to whoever is looking into this issue! ♥

**Comment by henkelmax** [comment]
> java.net.BindException: Cannot assign requested address (Bind failed)

You bound to the wrong address.
Leave it to the default value if you don't need to bind it to a specific address.
