### ISSUE TITLE
Encryption using Opus

### ISSUE THREAD

**Issue by LuxPoseidon** [henkelmax/simple-voice-chat#156]
**Is your feature request related to a problem? Please describe.**
Not so much a problem just curiosity, I do Cyber Security for a living.

**Describe the solution you'd like**
I was reading up on Opus as you are using their functionality for this mod, they have a 'opusenc' function to encrypt traffic, notably, encryption does take server resources don't worry I get that. My question is there any way a fork of the mod could be made to include this functionality here on Github? Would be a great addition and I would love to try it out. Let me know what you guys are thinking/if you are already trying would love to converse about it.

**Comment by henkelmax** [comment]
An encryption feature is already in the works.
Unfortunately I can't just use the opus encryption, since there are also other packets that need to be encrypted.
