### ISSUE TITLE
 do not install the mod on the server

### ISSUE THREAD

**Issue by TofaToP** [henkelmax/simple-voice-chat#16]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Installing the mod for clients only, launching a separate server for voice chat

**Describe alternatives you've considered**
There are no alternatives

**Additional context**

I ask about this, because there is no stable kernel for 1.16.4, and therefore I want the mod to be required to install only clients, and the server was started separately from the minecraft server

**Comment by henkelmax** [comment]
This is not possible, as the voice chat server needs the minecraft server for the position of the players and sending authentication tokens.
