### ISSUE TITLE
[Suggestion] More ways to connect 

### ISSUE THREAD

**Issue by ModdedPro** [henkelmax/simple-voice-chat#164]
**Is your feature request related to a problem? Please describe.**
Its only possible to use this on a supported server not on other servers that you don't own with a few friends also forge is far from the best when it comes to minecraft jars

**Describe the solution you'd like**
Support for spigot plugins and external (just jar) program to run instead of something like mumble 

**Describe alternatives you've considered**
I was looking to use this on my SMP but I don't think that forge or fabric is a good idea to use forge on a SMP so anything but forge (as long as its stable and has good performance)

**Additional context**
I can help make both the JAR application and plugin but I'm finding it hard to figure out exactly how the voice server is run so I just need someone to point out where the important stuff are (I have a lot of experience with coding application and plugins but not mods my name is only applies to in game NOT coding)

**Comment by henkelmax** [comment]
https://github.com/plasmoapp/plasmo-voice
