### ISSUE TITLE
Dynamic Sound Filters mod compatibility

### ISSUE THREAD

**Issue by DerpNerb** [henkelmax/simple-voice-chat#165]
I would love compatibility with the Dynamic Sound Filters mod! 

That mod adds:
- Reverb in caves and the nether
- Muffled sounds when submerged in water or lava
- Sounds become quieter when behind walls (Especially Wool or Sponge)

I would love to have these filters applied to voices as well! It would be so cool and more immersive!

Mod:
[https://www.curseforge.com/minecraft/mc-mods/dynamic-sound-filters](url)

**Comment by henkelmax** [comment]
Duplicate of #96, #114, #150 and #143

**Comment by DerpNerb** [comment]
:(
