### ISSUE TITLE
VC Works for me but not others

### ISSUE THREAD

**Issue by ItsRealityTv** [henkelmax/simple-voice-chat#17]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

I can use VC but no one else that connect to the server cannot. I get the menu and the icon, however others either get JUST the menu and no voice icon or "voice chat unavailable." I have done the port forwarding for 24454 and made sure the mod is in the server. Any idea what the problem can be. 

**Versions**
- MC: 1.16.4
- Forge: 35.1.4
- Mod version: 1.0.1/1.0.5/1.0.6

**Comment by henkelmax** [comment]
Please fill out the complete bug template and provide log files of your server and the clients that have this problem.
