### ISSUE TITLE
VPN breaks voice chat?

### ISSUE THREAD

**Issue by Personzoo** [henkelmax/simple-voice-chat#172]
So I've labelled this as a question because I don't know if it's really a bug or not. I host my own server but I also use PIA as a VPN. When people connect to my server they cannot connect to voice unless I disable the VPN. I've tried allowing different programs to bypass the VPN but I really don't know what I could allow that would let it work or if there's some other thing blocking it. It's not a dire issue, I can run my computer without a VPN, I was just wondering if this is the sort of thing you'd have the answer to or if I'd be better off asking a PIA forum. Is there something the mod uses that I could allow through my VPN that would make it work? I've tried using PIA's request port feature and assigning voice to that port, but it still doesn't work, so I don't think it's a port issue, but rather something else that the mod uses.

Thanks!

**Comment by henkelmax** [comment]
VPNs usually don't allow forwarding ports and if they do it might not always work as you want. I would recommend not using a VPN when hosting a server.

**Comment by Personzoo** [comment]
I figured this was the case but it was worth a shot. Thanks!

**Comment by henkelmax** [comment]
No problem
