### ISSUE TITLE
Client crashing

### ISSUE THREAD

**Issue by Greenwolf20** [henkelmax/simple-voice-chat#174]
**Bug description**
The client has been crashing randomly for all players on a server with roughly 10 players. We have tried 4 versions of simple voice chat and yet can't find a solution to the issue. The earliest log of the same crash i can find is from 5 march which is the same day the server opened. Crashes only happen during when people are near suggesting something relating to the voice chat but just glancing over the logs it seems related to when someone is talking and maybe even rendering the talk icon over their head? 

The crash seems kinda rare, I usually crash 1-2 times during a 5 hour session and for others it is similar. And finding steps to reproduce it is difficult when everyone is just focusing on playing. One thing I haven't been able to test yet is if disabling icons with H makes you not crash. I can try that and see if I can get it to crash next session.

**Steps to reproduce the issue**
1. Be near other players with the mod, possibly talking

**Expected behavior**
Client not crashing when near other players with the mod and being able to talk and see icons

**Log files**
2021-04-27 with version 1.21
https://gist.github.com/Greenwolf20/efb2bcc866c1f7e04bfa82e172a168c5

2021-04-24 with version 1.21
https://gist.github.com/Greenwolf20/41138d41076510208e7b6712e1fe05f0

2021-03-05 Earliest log with same issue with version 1.0.9
https://gist.github.com/Greenwolf20/f54aeae5208c9bf5c27c57f76a8f1830

**Versions**
- Minecraft version 1.16.5
- Fabric version 0.32.0+ 1.16
- Mod version 1.0.9, 1.0.16, 1.1.1, 1.2.1

**Other mods**
This happens to all players, even those with only fabric and the voicemod.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Nevermind, I think I found the issue.

**Comment by Greenwolf20** [comment]
We are updating the server and clients to 1.3.4 now and here's a crash report from a player without optifine or anything else:
https://gist.github.com/Greenwolf20/91c79b93e1bfd1704435d89e61eab856

Great to hear if you found the issue!

**Comment by henkelmax** [comment]
Please use the latest version:
https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/3293244

**Comment by Greenwolf20** [comment]
Yes we just saw you uploaded 1.3.5, damn you are fast! Good job!
