### ISSUE TITLE
Unknown custom packet identifier: voicechat:default

### ISSUE THREAD

**Issue by OiCMudkips** [henkelmax/simple-voice-chat#175]
**Bug description**
Getting `Unknown custom packet identifier: voicechat:default` error when clients attempt to connect to the server

**Steps to reproduce the issue**
Clients aren't able to authenticate with the voice server (maybe due to `Unknown custom packet identifier: voicechat:default`, see logs for details), so clients aren't able to voice chat (they see a `Voice chat unavailable` message).

I'm using a hosting service for this Forge server, but I think I set up the ports correctly since it looks like the voicechat server starts up correctly (it's sending secrets correctly).

**Expected behavior**
Clients are able to authenticate and voice chat

**Log files**
Filtered client logs: https://gist.github.com/OiCMudkips/80ccf568f9f1d6a3c5eb0c18ff8c0235
Filtered server logs: https://gist.github.com/OiCMudkips/4efc037b0e03b825d37cbda32d5f6490

**Versions**
- Minecraft 1.16.5
- Forge 36.1.12
- Mod version 1.1.5
- Java 8

**Other mods**
Based on the error not sure if this is relevant but:
https://gist.github.com/OiCMudkips/e8ecfe30c85953ffc46f690d980aa830

**Comment by henkelmax** [comment]
This message is completely normal.
