### ISSUE TITLE
Im having a problem

### ISSUE THREAD

**Issue by JohnGiant** [henkelmax/simple-voice-chat#176]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**
When i open Minecraft i get this error even though i have the API Could not find required mod: voicechat requires {fabricloader @ [>=0.11.2]} Help Please

**Comment by IAmSneak** [comment]
Simple Voice Chat requires a newer version of fabric modloader itself (not a newer version of fabric api). You can download it from [here](https://fabricmc.net/use/) or if you have the .exe version you can just run that, select the version and download the newest one.
