### ISSUE TITLE
I am able to hear my friend but my friend is unable to hear me

### ISSUE THREAD

**Issue by Euroam** [henkelmax/simple-voice-chat#177]
Hello, i am playing a modpack in 1.16.3, i have installed the version 1.0.1 to match the game version

So, i am able to hear my friend talking but he is unable to hear me

some more info: 
I launched the server myself on a pc and i am connected to the same network as the server, the icon that indicates me talking is being displayed as well

The option to select microphone is not there, minecraft is getting input as well, i used the enable minecraft testing option

so i would like to know if there is something wrong i am doing or if there is a bug

**Comment by henkelmax** [comment]
I'm sorry, but I don't support that version anymore. Please consider updating to 1.16.5

**Comment by Euroam** [comment]
the modpack doesnt work on 1.16.5 and i have tried the latest version of simple voice chat it crashes the server

**Comment by henkelmax** [comment]
No, sorry all these bugs have been fixed in later versions.
