### ISSUE TITLE
Toggle Mute & Dropdowns for Speaker/Microphone Choice

### ISSUE THREAD

**Issue by ajlittle** [henkelmax/simple-voice-chat#18]
**Is your feature request related to a problem? Please describe.**
Currently, when using the voice detection mode, people have to switch back to push to talk in order to mute their microphone.

And with the choose speaker/microphone being separate menus instead of dropdown boxes, people will have a hard time finding the proper speaker/microphone if they have more than 5 devices of the same type active on their computer.

**Describe the solution you'd like**
A keybind to toggle mute your microphone, updating the voice chat icon at the bottom left of the screen with a red slash through it to indicate having your microphone muted.

And for choosing speakers/microphones, using dropdown menus will decrease the time troubleshooting users have to go through to see if their microphone/speaker is set to the right device.

**Other**
Literally every single person on my server loves the fact that there's local voice chat, when it works it works really well and increases everyone's immersion by a lot, probably one of my favorite mods to date.

**Comment by henkelmax** [comment]
> And with the choose speaker/microphone being separate menus instead of dropdown boxes, people will have a hard time finding the proper speaker/microphone if they have more than 5 devices of the same type active on their computer.

What difference would a dropdown make?

> And for choosing speakers/microphones, using dropdown menus will decrease the time troubleshooting users have to go through to see if their microphone/speaker is set to the right device.

There is no dropdown UI component in Minecraft, and I don't want to build one from scratch.

**Comment by henkelmax** [comment]
The mute feature is now added. It should be available in the latest version.
