### ISSUE TITLE
Too Large Packets / Instant Kick From Server

### ISSUE THREAD

**Issue by redstonerblast** [henkelmax/simple-voice-chat#180]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
So in a modpack server I'm setting up this is one of the mods I'm using, however when joining the server I get instantly kicked

**Steps to reproduce the issue**
Not known

**Expected behavior**
Join server and packets send over fine.

**Log files**
Client : [08:27:06] [Netty Client IO #1/ERROR]: Received too large message, debug print below!

Server : [13.05 08:27:05] [Server] [Server thread/INFO] [voicechat/]: Sent secret to Redstonerblast
             [13.05 08:27:06] [Disconnect] redstonerblast has disconnected, reasonDisconnected

**Versions**
- 1.16.5
- 36.1.1
- Latest Alpha, And Latest Beta

**Other mods**
Doesn't seem to have effect.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/38005232/118134267-59b79780-b3c7-11eb-931d-e8150cde5048.png)

**Comment by henkelmax** [comment]
Please send the complete logs of the client and server.

**Comment by redstonerblast** [comment]
Seems to have been a compat issue rather than just the mod itself, sorry for wasting ur time.
