### ISSUE TITLE
There is no config 

### ISSUE THREAD

**Issue by xxpeafowlxx** [henkelmax/simple-voice-chat#184]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
There isnt a config for the voice chat mod, no matter what version i happen to install it doesnt generate a config file for it. Its not on server or client config. Ive restarted the server many times but no matter what i seem to do there is nothing that generates it.
ive done /reload aswell.

**Steps to reproduce the issue**
1. Download mod
2. See there is no config generated

**Expected behavior**
The config should have the voicechats config. 

**Log files**
Please provide log files of the game session in which the problem occurred.
https://gist.github.com/xxpeafowlxx/de42606bd143d08ebcf0e55eb64e340d

**Versions**
- 1.16.5
- Fabric version: 0.11.3 (1.16.5)
- Mod version: [fabric] 1.3.10 crashes the server, so im using [fabric] 1.1.5 since it was the most downloaded (both are for 1.16.5)

**Other mods**
I took off all of my mods and had just the singular voice chat mod on, but its still didnt generate a config file.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/67216992/118968402-3d12f500-b9af-11eb-9cd2-deb2513bc151.png)
![image](https://user-images.githubusercontent.com/67216992/118968529-5ddb4a80-b9af-11eb-8a29-263cb04f78ac.png)
^ server and client configs.

**Comment by henkelmax** [comment]
Please make sure that the config folder has the correct access rights/filesystem permissions.

Also please try removing the mycommands mod, since it creates a lot of errors in the logs.

**Comment by xxpeafowlxx** [comment]
Im unsure how to see/make the permissions work. Ive removed mycommands mod.

**Comment by henkelmax** [comment]
> Im unsure how to see/make the permissions work. Ive removed mycommands mod.

Does it work without the mod?
If not, please send me the logs of that

**Comment by henkelmax** [comment]
Please send me the full logs.

**Comment by xxpeafowlxx** [comment]
Im not sure what you mean? Full logs? As far as im aware these are the only logs i know of. I didnt know there was a client log. How can i access that? By full logs do you mean like a longer copy paste? (Apologies, im really not good at this sort of stuff.)

**Comment by henkelmax** [comment]
In your `.minecraft` folder and in your server folder, the logs are located in the logs directory. Please send me the debug.log of both.

**Comment by xxpeafowlxx** [comment]
The debug log of the client one is really long aswell, and severely outdated it'd seem

**Comment by henkelmax** [comment]
> Non-Fabric mod JAR at "/home/145610/userdata/fabric/mods/voicechat-1.16.5-1.1.5.jar", ignoring

You are using the forge version

**Comment by xxpeafowlxx** [comment]
Thank you! But when i add the fabric version, it does something else. It says i need fabric loader 0.11.2 in which i have 0.11.3 Does the latest fabric download support 0.11.3?

**Comment by henkelmax** [comment]
Please make sure you have the latest fabric api installed

**Comment by xxpeafowlxx** [comment]
Okay, it seems to be working now but now it just doesnt load the servers spawn or let me stop it. Has this happened before in another issue?

**Comment by henkelmax** [comment]
I have no clue what you mean

**Comment by xxpeafowlxx** [comment]
when a server starts it does 'preparing spawn area' but it gets stuck on 0% now.
