### ISSUE TITLE
Ability to hide icons for all players via config file

### ISSUE THREAD

**Issue by VirusBLITZ** [henkelmax/simple-voice-chat#186]
-Ability to hide icons for all players via config file-

So basecally I need a way to hide the icons next to the names for everyone, this could either be done through a config file or just hiding the icon for players that are not in the same team.

Thanks already,

**Comment by henkelmax** [comment]
Only every individual player can hide its icons client side.
You can do it with the `/team` command. But that would also hide the names of the players.

**Comment by VirusBLITZ** [comment]
nvm, my bad... It just shows the voicechat icon of players that are not connected when the name is hidden
