### ISSUE TITLE
Server crashes - Forge 1.16.4 

### ISSUE THREAD

**Issue by Bienkie** [henkelmax/simple-voice-chat#187]
Hey! I do not know if this is due to a previously mentioned issue but i did check. My server keeps crashing saying it cant bind to the IP but I have tried leaving the bind_ip thing blank, putting it in, and putting it in with the port on the end as well. Any help you could give would be greatly appreciated! TIA  This is what the server console says!

[ERROR] .... [voicechat/]: Failed to bind to address ''

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:61]: java.net.BindException: Address already in use (Bind failed)

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:61]: at java.net.PlainDatagramSocketImpl.bind0(Native Method)

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:61]: at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:61]: at java.net.DatagramSocket.bind(DatagramSocket.java:392)

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:61]: at java.net.DatagramSocket.<init>(DatagramSocket.java:242)

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:61]: at java.net.DatagramSocket.<init>(DatagramSocket.java:299)

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:61]: at de.maxhenkel.voicechat.voice.server.Server.run(Server.java:57)

**Comment by henkelmax** [comment]
If you don't have a bind address, please leave it as the default value (`0.0.0.0`)

**Comment by Bienkie** [comment]
Even when it is on 0.0.0.0 it says “Address already in use” 🙈

**Comment by henkelmax** [comment]
Then you have a voicechat server (or something else) already running on that port

**Comment by Bienkie** [comment]
Sorted - thanks a bunch! :P
