### ISSUE TITLE
Voice chat unavailable

### ISSUE THREAD

**Issue by Ruben1719** [henkelmax/simple-voice-chat#19]
I have the next problem: 
![image](https://user-images.githubusercontent.com/67429811/103786870-39548680-503d-11eb-8524-f36653306489.png)
Servers and in solo LAN games.
What should I do?

**Comment by henkelmax** [comment]
Please have a look at #10

**Comment by Ruben1719** [comment]
I've been trying but I can't solve it, I'm trying it in my Single player world with LAN enabled and hamachi connection, my friend join using an IP like --> 127.0.0.1:5892

**Comment by Ruben1719** [comment]
![image](https://user-images.githubusercontent.com/67429811/103789170-fd6ef080-503f-11eb-8abc-2db711717d77.png)
MODS

**Comment by Ruben1719** [comment]
![image](https://user-images.githubusercontent.com/67429811/103789290-1e374600-5040-11eb-985f-0fc8f0ff3ec4.png)

**Comment by henkelmax** [comment]
The voice chat only works with dedicated servers. You have to start the server separately to the client.

**Comment by Ruben1719** [comment]
Okey, thx!

**Comment by henkelmax** [comment]
No problem!
Let me know if you face any issues with your server.

**Comment by phivumop** [comment]
can you guys help me ?
i have the voice chat unavailable error too. i play singleplayer connect radmin with my friend. Thanks
