### ISSUE TITLE
How to figure out Voice Chat Unavailable issue 

### ISSUE THREAD

**Issue by HudsonIs3pic** [henkelmax/simple-voice-chat#192]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**
I am using Shockbyte server Hosting, and the server provider isn't being really helpful, they are answering a question I already solved. If someone can help me set this up so it is working, that would be great. I was looking at the instructions earlier and i am very confused on what I should do. If someone needs more description to help me, please ask. Also, I am using a mac if that changes things :)

**Comment by henkelmax** [comment]
You should take a look at #24
For everything else read the wiki and ask the support of your hoster.

**Comment by HudsonIs3pic** [comment]
> You should take a look at #24
> For everything else read the wiki and ask the support of your hoster.

My problem is, i cantt find out if the mic is working or not, because the mod wont work, ive read the part of the wiki that talks about my issue, and the solution says it only works when you arent using server hosting. but, if i were to input the commands it says i need to input, where would i put them?

**Comment by henkelmax** [comment]
I have no clue what you man.

If you see a plug icon on the bottom left, the voice chat is not connected.
If people just can't hear you, its #24

**Comment by HudsonIs3pic** [comment]
> I have no clue what you man.
> 
> If you see a plug icon on the bottom left, the voice chat is not connected.
> If people just can't hear you, its #24

okay, the voice chat is not connected, on the wiki it says this:
On your server run nc -lup <YOUR VOICECHAT PORT>
On your client run nc -u <YOUR SERVER ADDRESS> <YOUR VOICECHAT PORT>
where am i supposed to run these 2 commands,

Im sorry if im being a pain, i am not good with this server stuff. if there is a discord for this mod so i can find someone's help that had this issue before, could you let me know. sorry lol

**Comment by henkelmax** [comment]
As the wiki says: Ask the support of your hoster.

**Comment by HudsonIs3pic** [comment]
> As the wiki says: Ask the support of your hoster.

okay, sorry, ive already done that 3 times with no answers, but ill try again
