### ISSUE TITLE
Voice Chat Connection Issue

### ISSUE THREAD

**Issue by RobertoLaDiablo** [henkelmax/simple-voice-chat#194]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**

i may have looked over something, i do appologize, but i installed the mod, opened my port, edited the server config, and validated client config.

on my end i can see the pic working properly, it even tests properly, but my friends cant connect to voice, it keeps saying voice chat unavailable and "Client not Connected" when i do /voicechat test
![2021-05-26_13 27 25](https://user-images.githubusercontent.com/42939435/119707064-b9cb2680-be28-11eb-8589-9b3ac1a61ce4.png)

**Comment by henkelmax** [comment]
Please read the wiki.

**Comment by RobertoLaDiablo** [comment]
read the wiki nothing in it is explaining my situation on whats going on would definitely appreciate a better response than "read the wiki"

**Comment by henkelmax** [comment]
So, you have tried everything that was stated in the wiki?

**Comment by RobertoLaDiablo** [comment]
yes even the netcat thing i can connect but other players ive sent the mod to that paly on the server are not able to use it, it keeps saying cannot connect to voicechat

**Comment by henkelmax** [comment]
What was the result of the netcat thing?

**Comment by RobertoLaDiablo** [comment]
Same exact results I could use it perfectly but others couldn't connect

**Comment by henkelmax** [comment]
Did netcat work with the people that couldn't connect?
