### ISSUE TITLE
Client crash after player death (may be conflict with Corpse)

### ISSUE THREAD

**Issue by Tander** [henkelmax/simple-voice-chat#198]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
One of my players experience a strange crash which I'm not able to reproduce, but maybe you still can't fix it.
Since he died on my server, he can't join without crashing. Looks like it may be a conflict between Simple Voice Chat and Corpse mods.

**Steps to reproduce the issue**
Unfortunately, can't reproduce it myself.

**Log files**
https://paste.gg/p/anonymous/5c2a7e5449ee49df8a0b752ba2ee116c

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.24
- Mod version 1.3.9

**Other mods**
Link to modpack we're playing: https://www.curseforge.com/minecraft/modpacks/elittle-wind/files/3327815

**Comment by henkelmax** [comment]
Thank you for reporting this issue. It should be fixed in the next version.
