### ISSUE TITLE
Mod won't connect when the server IP includes the port.

### ISSUE THREAD

**Issue by Cosmiiko** [henkelmax/simple-voice-chat#2]
**Bug description**
An error occurs when attempting to use the mod on a server when the IP used to connect to the server already includes a port, preventing the mod from connecting and working. See line 54 and 112 from the logs.

**Steps to reproduce the issue**
1. Have a minecraft server setup with the mod
2. Connect to the server, _including the port at the end of the IP (eg: 127.0.0.1:25565)_
3. Attempt to use the mod (press V)

**Expected behavior**
To succeed at connecting to the server. The mod just needs to remove the port from the IP obtained from `minecraft.getCurrentServerData().serverIP` before adding its own port at the end.

**Log files**
[Here](https://gist.github.com/Cosmiiko/2a494d960ce5bc40efa55e15cd3b2638#file-latest-log-L54)

**Versions**
- Minecraft version: 1.16.3
- Forge version: 34.1.42
- Mod version: voicechat-1.16.3-1.0.0

**Other mods**
None. Simple voice chat was the only one installed, both on the server and client.

**Comment by henkelmax** [comment]
Thank you for reporting this issue! The new version should be up on curseforge soon.
