### ISSUE TITLE
Voice mod 1.15.2 ERROR

### ISSUE THREAD

**Issue by Mad5keleton** [henkelmax/simple-voice-chat#200]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Everytime i get the voice mod 1.15.2 time i start, my game crashes in the mod loading screen. The second time i try is works.

**Steps to reproduce the issue**
1. Instal forge 1.15.2
2. Place the voice mod 1.15.2 in the mods folder
3. Open Minecraft Launcher and PLAY
4. Minecraft starts loding screan
5. Crash mid loading screen

**Expected behavior**
I expect the mods to load like normal and the game to open like normal

**Log files**
https://gist.github.com/Mad5keleton/38bd05cea91a1c3fcbb7552975492513

**Versions**
- Minecraft version 1.15.2
- Forge version 1.15.2 - 31.2.50 | 1.15.2 - 31.2.30
- Mod version 1.15.2-1.0.2 | 1.15.2-1.0.1 | 1.15.2-1.0.0

**Other mods**
No other mods.

**Screenshots (Optional)**
The game dosent even start the first time.

**Comment by henkelmax** [comment]
Please send me the complete logs.
