### ISSUE TITLE
Still give me an error about "FAILED TO BIND TO PORT!"

### ISSUE THREAD

**Issue by Mad5keleton** [henkelmax/simple-voice-chat#201]
So i read the wiki and did everyting it said, I tried to bind the port and IP Adress for my server that I created on my own Computer, I fixed my "Address" but it still give me an error about "FAILED TO BIND TO PORT!" what can i do??

**Comment by henkelmax** [comment]
Please send me the contents of your config and your logs.

**Comment by Mad5keleton** [comment]
Logs: -Debug: https://gist.github.com/Mad5keleton/e542c8c2778e9b30676088af3f235f17
-Latest: https://gist.github.com/Mad5keleton/6b8f27cc89f5a15a150d75c46d744b63

Server config: https://gist.github.com/Mad5keleton/4d3b84f43dcfa22041baafcb1443e68c
Voice mod config: https://gist.github.com/Mad5keleton/8a2f94a106334d7f53de6be772befe90

**Comment by Mad5keleton** [comment]
I closed it on accident, but i reopen it.

**Comment by henkelmax** [comment]
You are running another minecraft server (or any application running on that port) on the same port.
This is not an error of the voice chat mod.
