### ISSUE TITLE
[Solution Post] How you can fix SVC not using microphone on macOS.

### ISSUE THREAD

**Issue by StupidRepo** [henkelmax/simple-voice-chat#205]
# Note: This is a solution post so it's not a question, bug or anything like that. It's to help people with an issue.

So, if you're having issues with Simple Voice Chat (SVC, as I'll call it, for now) not picking up/using your microphone on macOS, people have found a fix so here I'll explain that.

Now, first of all, I'm going to go through how this happens and how to fix this issue.

So, let's continue:

## How this happens

Now, I don't know HOW/WHY this really happens but it seems that, when launching Minecraft.app, it doesn't seem to trigger something that allows you to be heard through SVC.

## How to fix this

People have found a way to fix it (*[ahem...][really?]*) and so I'll explain it now. If you launch Minecraft.app through the Terminal.app it fixes this. Maybe Terminal.app gives it some permissions as the Terminal has a lot of permissions in your Privacy + Security tab (which can be found in System Preferences.app)

So, what's the code to launch Minecraft.app through Terminal.app? Well, first let's make a shortcut to run Minecraft so we don't forget. 

[Download this file][file 1], unzip it unless it's automatically unzipped by Safari (***it's zipped so it can be uploaded to GitHub***) and drag `Minecraft.command` onto your Desktop. This shortcut will actually contain the code but if you don't trust the file, I'll put the code below.

Anyways, now you can double-click on `Minecraft.command` at anytime to launch Minecraft.app THROUGH Terminal.app which then your Microphone will be picked up.

If you don't trust this file, I don't blame you so here is the code inside this `.command` file:

`/Applications/Minecraft.app/Contents/MacOS/launcher` - simple, really.

## How do I put this in my Dock?

Currently, you can't. If you want, you can try something called AppleScript and a script launcher (that sticks in your Top-bar so you can click on it to get all scripts in that folder, and then click on that script to run it) to automate it.

[really?]: #24
[file 1]: https://github.com/henkelmax/simple-voice-chat/files/6603956/UNZIP.zip

**Comment by StupidRepo** [comment]
Aww crap, really didn't want to assign anyone :/

**Comment by henkelmax** [comment]
This solution was already proposed in #24.
You can put your post there, but it doesn't seem to work for everyone.

**Comment by StupidRepo** [comment]
> This solution was already proposed in #24.

I know.

> You can put your post there, but it doesn't seem to work for everyone.

Oh ok.
