### ISSUE TITLE
IP Will Not Bind & Voice Chat Unavailable

### ISSUE THREAD

**Issue by Jackalope6062** [henkelmax/simple-voice-chat#206]
**Bug description**
I have started a 1.16.5 Forge server through PebbleHost. I have been through all of the troubleshooting steps on the Wiki, read through all of the questions in the FAQ, followed several tutorials on how to install the mod on the server, but my problem continues to occur.

I started by installing the mod onto my Minecraft client as well as onto my server. I then created/assigned a port for the mod in the voicechat-server.toml file. Upon starting up the server, I did see that the mod successfully connected to the port I assigned to it (8161), but the mod only displayed the "Voice Chat Unavailable" error in-game.

I then realized that I hadn't changed the bind address from it's default 0.0.0.0, so I changed it to my server's IP (example: 12.345.678.910). After doing that however, the server would not start and the console displayed that the mod failed to bind the IP.
*See Image in the Screenshots Section

**Steps to reproduce the issue**
1. Install the Simple Voice Chat mod version [1.16.5-1.3.11](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/3336077) client-side and server-side
2. Create a port for the mod and assign that port to the mod in the server's voicechat.server.toml file
3. Bind the Minecraft server's IP to the mod in the same file
4. Attempt to start the server
5. See error

**Expected behavior**
I expected the mod to bind to the IP correctly.

**Log files**
Line 64 of this [log](https://mcpaste.io/499e0e16752071bb)
^This link shows the same log shown in the screenshot below

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.0
- Mod version 1.3.11 (I also tried using version 1.4.0)

**Other mods**
No other mods were being used when the error occurred.

**Screenshot**
*Image mentioned above:
![image](https://user-images.githubusercontent.com/85464094/120944837-34832400-c6fc-11eb-8cad-6240f96e02e3.png)

**Comment by henkelmax** [comment]
> 06.06 19:48:58 [Server] VoiceChatServerThread/ERROR [voicechat/]: Failed to bind to address '**.**.**.**'

This not a valid IP address.

If you have questions about the IP and forwarding the port, ask your server hoster and/or read the wiki

**Comment by MarioChefCazan** [comment]
do i need to put the public or private ip?
