### ISSUE TITLE
Server install not creating config file for mod

### ISSUE THREAD

**Issue by DuskWRLD** [henkelmax/simple-voice-chat#211]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Mod not creating config folder on server install

**Steps to reproduce the issue**
1. Install Simple Voice Chat in your server (currently a paid server.pro one)
2. Restart server
3. Then there is no config folder which is necessary to change the port to an open one

**Expected behavior**
The install should've made a config folder / file

**Log files**
- 

**Versions**
- Mc Version 1.17
- Fabric version 0.34.9 1.17
- Mod version 1.17 latest

**Other mods**
Fabric api 0.34.9 1.17

**Screenshots (Optional)**
-

**Comment by henkelmax** [comment]
Please send me your logs.

**Comment by DuskWRLD** [comment]
[INFO] Loading for game Minecraft 1.17

[INFO] [FabricLoader] Loading 48 mods: fabric-networking-blockentity-v0@0.2.11+a02b4463d5, fabric-screen-handler-api-v1@1.1.8+a02b4463d5, minecraft@1.17, fabric-renderer-api-v1@0.4.2+a02b4463d5, fabric-keybindings-v0@0.2.2+36b77c3ed5, voicechat@1.17-1.0.1, fabric-command-api-v1@1.1.1+a02b4463d5, fabricloader@0.11.3, fabric-screen-api-v1@1.0.3+b7ab6121d5, fabric-tool-attribute-api-v1@1.2.12+b7ab6121d5, fabric-renderer-indigo@0.4.8+a02b4463d5, fabric-structure-api-v1@1.1.10+be9da310d5, fabric-containers-v0@0.1.12+a02b4463d5, fabric-object-builder-api-v1@1.10.9+b7ab6121d5, fabric-dimensions-v1@2.0.10+a02b4463d5, java@16, fabric-item-api-v1@1.2.4+a02b4463d5, fabric-events-interaction-v0@0.4.8+a02b4463d5, fabric-crash-report-info-v1@0.1.5+be9da310d5, fabric-game-rule-api-v1@1.0.6+a02b4463d5, fabric-entity-events-v1@1.1.0+a02b4463d5, fabric-api-base@0.3.0+a02b4463d5, fabric-rendering-v0@1.1.2+92519afad5, fabric-key-binding-api-v1@1.0.4+a02b4463d5, fabric-rendering-v1@1.6.0+a02b4463d5, fabric-rendering-data-attachment-v1@0.1.5+a02b4463d5, fabric-resource-loader-v0@0.4.7+b7ab6121d5, fabric-textures-v0@1.0.6+a02b4463d5, fabric-content-registries-v0@0.2.2+a02b4463d5, fabric-tag-extensions-v0@1.1.4+a02b4463d5, fabric-biome-api-v1@3.1.11+9e521e13d5, fabric-rendering-fluids-v1@0.1.13+a02b4463d5, fabric-registry-sync-v0@0.7.9+a02b4463d5, fabric-commands-v0@0.2.2+92519afad5, fabric-blockrenderlayer-v1@1.1.5+a02b4463d5, fabric-lifecycle-events-v1@1.4.4+a02b4463d5, fabric-mining-levels-v0@0.1.3+92519afad5, fabric-renderer-registries-v1@3.2.0+a02b4463d5, fabric-networking-api-v1@1.0.11+b7ab6121d5, fabric-events-lifecycle-v0@0.2.1+92519afad5, fabric-loot-tables-v1@1.0.4+a02b4463d5, fabric@0.34.9+1.17, fabric-models-v0@0.3.0+a02b4463d5, fabric-item-groups-v0@0.2.10+b7ab6121d5, fabric-particles-v1@0.2.4+a02b4463d5, fabric-object-builders-v0@0.7.3+a02b4463d5, fabric-networking-v0@0.3.2+92519afad5, fabric-api-lookup-api-v1@1.0.2+a02b4463d5

[INFO] SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/gs-41336/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER

[WARNING] The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.

[INFO] Compatibility level set to JAVA_16

[WARNING] @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value

[INFO] Compatibility version 4

[WARNING] @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zzh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

[INFO] Applied 0 biome modifications to 0 of 81 new biomes in 91.27 ms

[INFO] Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

[INFO] Found new data pack Fabric Mods, loading it automatically

[WARNING] Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]

[WARNING] Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]

[WARNING] Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]

[WARNING] Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]

[WARNING] Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]

[INFO] Reloading ResourceManager: Default, Fabric Mods (Fabric Tool Attribute API (v1))

[INFO] Loaded 7 recipes

[INFO] Loaded 1137 advancements

[INFO] Starting minecraft server version 1.17

[INFO] Loading properties

[INFO] Default game type: SURVIVAL

[INFO] Generating keypair

[INFO] Starting Minecraft server on *:41336

[INFO] Using epoll channel type

[INFO] Preparing level "world"

[INFO] Preparing start region for dimension minecraft:overworld

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 0%

[INFO] Preparing spawn area: 11%

[INFO] Preparing spawn area: 27%

[INFO] Preparing spawn area: 27%

[INFO] Preparing spawn area: 34%

[INFO] Preparing spawn area: 61%

[INFO] Preparing spawn area: 68%

[INFO] Preparing spawn area: 69%

[INFO] Preparing spawn area: 70%

[INFO] Preparing spawn area: 71%

[INFO] Preparing spawn area: 74%

[INFO] Preparing spawn area: 75%

[INFO] Preparing spawn area: 75%

[INFO] Preparing spawn area: 79%

[INFO] Preparing spawn area: 83%

[INFO] Preparing spawn area: 83%

[INFO] Preparing spawn area: 84%

[INFO] Preparing spawn area: 84%

[INFO] Preparing spawn area: 85%

[INFO] Preparing spawn area: 86%

[INFO] Preparing spawn area: 86%

[INFO] Preparing spawn area: 89%

[INFO] Preparing spawn area: 89%

[INFO] Preparing spawn area: 92%

[INFO] Preparing spawn area: 94%

[INFO] Preparing spawn area: 96%

[INFO] Preparing spawn area: 99%

[INFO] Time elapsed: 22119 ms

[INFO] Done (22.370s)! For help, type "help"

[INFO] Starting GS4 status listener

[INFO] Thread Query Listener started

[INFO] Query running on 0.0.0.0:41336

[INFO] Server started at port 24454

[INFO] UUID of player DuskWRLD is b55c2924-05a9-4f59-8671-9e46b0cef9c3

[INFO] DuskWRLD[/85.147.53.183:51113] logged in with entity id 100 at (-6.5, 64.0, -138.5)

[INFO] DuskWRLD joined the game

[INFO] Sent secret to DuskWRLD

op duskwrld

[INFO] Made DuskWRLD a server operator

[INFO] DuskWRLD lost connection: Disconnected

[INFO] DuskWRLD left the game

[INFO] Disconnecting client DuskWRLD

**Comment by henkelmax** [comment]
Please don't paste the logs into the issue section. Please create a github gist link.

**Comment by DuskWRLD** [comment]
https://gist.github.com/DuskWRLD/1114c3f54cb93e347a69efd4099f1c6f does this work then?

**Comment by henkelmax** [comment]
> https://gist.github.com/DuskWRLD/1114c3f54cb93e347a69efd4099f1c6f does this work then?

Yes, thank you.

Where did you look for the config?

**Comment by DuskWRLD** [comment]
I checked every file and folder in the server, since I didn't find it in the /world folder where I was told it would be.

**Comment by DuskWRLD** [comment]
Also, what would the name for the folder have been if it were there?

**Comment by henkelmax** [comment]
It is located in `.minecraft/config/voicechat`

**Comment by DuskWRLD** [comment]
The folder is indeed there in my personal client. Shouldn't there be a file also in the server though? If not, how would I make it so me and my friends can hear eachother? Do we all just set the same port in our personal client?

**Comment by henkelmax** [comment]
Of course the config should be there on the server.
Please double check the location on the server.

**Comment by DuskWRLD** [comment]
Now that you have told me what to look for I indeed found it xD 
Do I just change the default port in the config to one of the open ports to fix it then?

**Comment by henkelmax** [comment]
> Now that you have told me what to look for I indeed found it xD

Next time please follow the bug template and read the FAQ before opening a new issue!

> Do I just change the default port in the config to one of the open ports to fix it then?

Yes
