### ISSUE TITLE
Server Started but Port Unavailable

### ISSUE THREAD

**Issue by beanbeanjuice** [henkelmax/simple-voice-chat#213]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
It says that the port was opened, but it does not work. I've contacted PebbleHost and they've said `0.0.0.0` is the correct IP to use. Using the server's built-in IP leads to the server crashing upon a connection. When I use `0.0.0.0`, I'm able to join the server, but not use voice chat.

Doing `/voicechat join beangroup` works.
Doing `/voicechat test beanbeanjuice` does not work. (beanbeanjuice is my username).
- This gives me the error `Client not connected` which leads me to believe that this is a client-side issue. I have no touched my client-side settings.

**Log files**
[Console Log](https://gist.github.com/beanbeanjuice/675efefea2bd5ba681c5155229b84db4)

**Versions**
- 1.17
- Fabric v0.11.3
- 1.0.2

**Other mods**
Fabric API v0.34.9 for 1.17

**Comment by henkelmax** [comment]
Please send me the debug logs of your server and client.

**Comment by henkelmax** [comment]
Closed due to inactivity.
