### ISSUE TITLE
Proximity Chat not working

### ISSUE THREAD

**Issue by LarsStuhlmacher** [henkelmax/simple-voice-chat#214]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
I tried using the mod in the 1.17 version. Group chat works just fine but the proximity chat doesn't work at all. We can hear each other when we are in the same group but when standen next to each other and not being in any group it doesn't work anymore.

**Expected behavior**

**Log files**
My log: https://gist.github.com/LarsStuhlmacher/d73f4d7cf395c3a020322fd7e422f3ce
My friends log: https://gist.github.com/AkoHero/edd035f7f4d4b85e2ecfe6df7718227a
My server log: https://gist.github.com/LarsStuhlmacher/854b8cbb6439632107abd57c1bab2d7b

**Versions**
- Minecraft version: 1.17
- Fabric version: 0.7.3
- Mod version: 1.17-1.0.3

**Other mods**
We are using a bunch of mods but it shouldn't really be a problem. My guess is that it would be one of these:
- [conjuring](https://www.curseforge.com/minecraft/mc-mods/conjuring)
- [dark enchanting](https://www.curseforge.com/minecraft/mc-mods/dark-enchanting)
- [dualriders](https://www.curseforge.com/minecraft/mc-mods/dual-riders)
- [Trinkets and some addons](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric)
- [veinmining](https://www.curseforge.com/minecraft/mc-mods/vein-mining-fabric)

Thank you for your time :)

**Comment by henkelmax** [comment]
Can you try if this also happens with version 1.17-1.0.2?

**Comment by LarsStuhlmacher** [comment]
Haven't tried that yet, im gonna try this later this day

**Comment by henkelmax** [comment]
Thank you!

**Comment by henkelmax** [comment]
Please also try version 1.17-1.0.4.

**Comment by LarsStuhlmacher** [comment]
Alright.
Sorry for this late reply.

I tried the version 1.0.2 and it worked no problems with proximity, also tried 1.0.4 as you asked and it also works just fine.
Thank you for your mod. I really like it!
