### ISSUE TITLE
doesnt bind to address and 0.0.0.0 also doesnt work

### ISSUE THREAD

**Issue by T0TOR** [henkelmax/simple-voice-chat#216]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
if i bind a ip to the mod is says it doesnt bind to address

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
just to bind to the address

**Log files**
https://paste.shockbyte.com/uwulucuqaxulibuzerah.

**Versions**
- Minecraft version 1.16.5
- Forge version 1.16.5 - 36.1.0
- Mod version 1.16.5-1.3.11

**Other mods**
TerraForged-1.16.5-0.2.10
ServerTabInfo-1.16.4-1.3.3
randompatches-2.4.4-forge
polymorph-forge-1.16.5-0.24
performant-1.16.2-5-3.66m
OptiFine_1.16.5_HD_U_G8
MouseTweaks-2.14-mc1.16.2
Morpheus-1.16.5-4.2.70
lazydfu-0.1.3
konkrete_1.1.6_MC_1.16.2-1.16.5
JEITweaker-1.16.5-1.0.1.27
FpsReducer-mc1.16.5-1.19
ferritecore-2.0.4-forge
dynviewdist-1.9
create-mc1.16.5_v0.3.1c
CraftTweaker-1.16.5-7.1.0.313
ClientTweaks_1.16.3-5.3.0
citadel-1.6.3
chocolate-1.3.0-1.16.4
CAC+MOD+[1.16.5]+[2021.2-pre4]
**Screenshots (Optional)**

**Comment by henkelmax** [comment]
> 10.06 14:08:39 [Server] VoiceChatServerThread/ERROR [voicechat/]: Failed to bind to address '135.148.73.34'

If you are using a server hoster and binding to the default address doesn't work, the best way is to contact the support of your hoster, since this highly depends on their setup.
