### ISSUE TITLE
Version reported by Fabric mismatches the Curseforge version

### ISSUE THREAD

**Issue by UnlimitedCookies** [henkelmax/simple-voice-chat#219]
**Bug description**
The recent versions of simple voice chat do not show the corresponding version in mod menu.

**Steps to reproduce the issue**
1. Download the newest version of simple voice chat for 1.17.
2. Observe version of the mod with mod menu or inside multimc.

I used 1.17-1.0.4
Fabric said that I use 1.17-1.0.1

**Expected behavior**
That the version I use matches the one displayed by fabric.

**Log files**
Not relevant.

**Versions**
- Minecraft version 1.17
- Mod version 1.17-1.0.4

**Other mods**
Fabric Loader
Fabric API
Optifine
OptiFabric
Mod Menu

**Comment by henkelmax** [comment]
Thank you for reporting this issue. It should be fixed with the next version.
