### ISSUE TITLE
Mod crashes server when putting IP

### ISSUE THREAD

**Issue by gnatNguyen** [henkelmax/simple-voice-chat#22]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
The server hosting site allows ports to be opened for this mod (I confirmed with a moderator), which I put for 8032. Everything loads up fine when the IP address to bind is left empty, however this leads to voice chat unavailable ingame. If I do put the IP address(I tried it with the server's IP standalone, and its IP plus the server port), the server crashes at around the end of the startup.

**Steps to reproduce the issue**
1. Put IP in for bind_address
2. Launch server up
3. Server crashes
4. See error below in the server side logs

**Log files**
SERVER SIDE LOG
https://mcpaste.io/08d44bf76b4c8407

*ERROR IS SHOWN IN LINE: 967

- Minecraft version: 1.16.4
- Forge version: 35.1.29
- Mod version: 1.1.1

This error occurred with the bunch of other mods installed on All The Mods 6. However, I did remove all mods to just run the voice chat mod by itself, and it still resulted in the error shown in the logs.

**Comment by henkelmax** [comment]
Don't include the port in the IP config option. There is another config option for the port.

**Comment by gnatNguyen** [comment]
I am putting a specified port, for example, port = 8080. For the bind_address =; I tried the server's IP without the port (xx.xx.xxx) and with the server's port(xx.xx.xxx:PORT). That port howerver is NOT the 8080 from earlier. On a second note, is the IP supposed to be in quotations or just a bind_address = xx.xx.xxx?

**Comment by henkelmax** [comment]
The bind IP is a string in quotations.
