### ISSUE TITLE
Question about being simultaneously able to use the proximity chat and broadcast.

### ISSUE THREAD

**Issue by VolterMC** [henkelmax/simple-voice-chat#222]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**
Can this mod be configured in such a way that I could have voice activated proximity chat, but I could press a PTT button to talk to all the players on the server, regardless of their distance to myself?

**Comment by henkelmax** [comment]
That's what group chats are for.
