### ISSUE TITLE
Client Crash after normal Start.

### ISSUE THREAD

**Issue by ghost** [henkelmax/simple-voice-chat#224]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Just a crash after starting the Client.

**Steps to reproduce the issue**
1. Starting Minecraft
2. Crash after Start

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).
https://pastebin.com/JnuZJtej

**Versions**
- Minecraft version: 1.16.5
- Fabric version: 0.11.6
- Mod version: 1.15.5

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
You can see the List in the Crashlog

**Screenshots (Optional)**
Screenshots of the issue.
![VoiceChat Crash](https://user-images.githubusercontent.com/4640928/122679809-9491c400-d1ec-11eb-9d4b-be749c881e7b.PNG)

**Comment by henkelmax** [comment]
Does this happen without any other mods?
Which fabric API version are you using?

**Comment by henkelmax** [comment]
Unfortunately I am not able to reproduce this issue, but I may have an idea what's causing this problem. Can you please unzip the following file and try that version of the mod:

[voicechat-1.16.5-1.5.6-test.zip](https://github.com/henkelmax/simple-voice-chat/files/6682661/voicechat-1.16.5-1.5.6-test.zip)

**Comment by ghost** [comment]
Same Problem. :/
https://pastebin.com/sQFJP2qm

FabricAPI: 0.35.1+1.16

**Comment by henkelmax** [comment]
> Same Problem. :/
> https://pastebin.com/sQFJP2qm
> 
> FabricAPI: 0.35.1+1.16

Even without any other mods?

**Comment by ghost** [comment]
Hmm... Works without other Mods and newest FabricAPI Version.

**Comment by henkelmax** [comment]
Can you please check which mod in combination with the voice chat mod crashes the game?

**Comment by ghost** [comment]
I'll try to find the Issue and will report you if I found it.

**Comment by henkelmax** [comment]
> I'll try to find the Issue and will report you if I found it.

Awesome! Thank you!

**Comment by ghost** [comment]
Found the Reason!
kubejs-fabric-1605.3.10-build.25.jar

After deleting this Mod. The Client start without problems.

**Comment by henkelmax** [comment]
Thank you for your help. It should be fixed in the latest version. I also created an issue report to the Architectury API, so this will not happen for any other mods.

**Comment by ghost** [comment]
Sounds good. Thank you for the fast fix. :D
