### ISSUE TITLE
Specifying IP address on Client Side

### ISSUE THREAD

**Issue by sfxworks** [henkelmax/simple-voice-chat#228]
Hello,

I have noticed that your project does not allow specifying the IP address of the server. Specifically, in your discord, this user pointed it out to me.
![image](https://user-images.githubusercontent.com/5921035/122878270-90a59500-d305-11eb-9c3b-9da4fea406e3.png)

I would like the ability to specify the IP address of the voice server. We at MC Server Hosting use a different IP address for port forwarding.

**Comment by henkelmax** [comment]
I think the better approach would be to set the IP the voice chat should connect to in the server config and the client gets this information sent from the server. This would be much easier, because not every client would need to specify the IP.

**Comment by mjwells2002** [comment]
https://github.com/henkelmax/simple-voice-chat/pull/229

**Comment by mjwells2002** [comment]
i quickly made this feature with a server side config value sent in the initialization leaving the server side config blank defaults back to using the minecraft servers ip

**Comment by henkelmax** [comment]
That was quick :D
I requested some changes.
