### ISSUE TITLE
Voice chat unavailable 

### ISSUE THREAD

**Issue by lightonair** [henkelmax/simple-voice-chat#234]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**
Can't get this to work properly. Says "Voice chat unavailable" I have opened PORTS on my server. Please HELP!!
![image](https://user-images.githubusercontent.com/86599922/123617600-0c7f7000-d825-11eb-97f3-501999cf1f09.png)

**Comment by henkelmax** [comment]
For help please visit the discord server.
