### ISSUE TITLE
Refuses to work, but packets are receieved.

### ISSUE THREAD

**Issue by Apprisco** [henkelmax/simple-voice-chat#236]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Purpur, latest version, on pterodactyl.
Made sure player ips are probably passed through, forwarded the ports and added allocations.

**Expected behavior**
Voice chat should be enabled, but it isn't.

**Log files**
![image](https://user-images.githubusercontent.com/34324909/123895904-90f3ff00-d99b-11eb-8cd7-61f88440cf74.png)
mc logs:
![image](https://user-images.githubusercontent.com/34324909/123895921-99e4d080-d99b-11eb-98b5-f414ee03a0fa.png)
Getting spammed with auth packets, only on this server meaning the client is receiving packets from the voice server/
On the other hand, the packet never seems to get authenticated from the client back to the server.

**Versions**
1.17
fabric 1.17
purpur 1.17

**Comment by henkelmax** [comment]
This is not a bug.
For help with the voice chat, please visit the discord.
