### ISSUE TITLE
Server Port

### ISSUE THREAD

**Issue by ShilohMC** [henkelmax/simple-voice-chat#238]
So I installed the mod and I saw you had to set up your server port with it, I use shockbyte (yes ik possibly the worst server hosting) and I'm not sure if I am able to use this mod with it. When I have the mod installed it says "Voice chat not available".

**Comment by henkelmax** [comment]
https://shockbyte.com/billing/knowledgebase/269/How-to-Setup-Simple-Voice-Chat-on-your-Minecraft-Server.html
