### ISSUE TITLE
GL ERROR @Render

### ISSUE THREAD

**Issue by DDR-Khat** [henkelmax/simple-voice-chat#239]
**Bug description**
Game client logs is getting repeatedly spammed with Render thread errors. Keys all seem to function fine with my configuration but the error happens still? Maybe it's due to me un-binding a few keys, as it is reporting INVALID KEY -1

**Steps to reproduce the issue**
1. Install the Mod with the mentioned version of Minecraft and Fabric
2. Boot up the game and load into any (single/multiplayer) world.
3. Press literally ANY button.
4. Close the game, review your logs file. (Or if you have the game's console log open, watch it in real time)

**Expected behavior**
Not to have a bunch of INVALID KEY errors (:

**Log files**
https://gist.github.com/DDR-Khat/11a5977119c24dd5de95ddc90b2f6c15

**Versions**
- Minecraft version **[1.17.1-RC1]**
- Forge version [Fabric Version: 1.17.1-rc1 Loader version: 0.11.6]
- Mod version [1.17-1.2.3]

**Other mods**
I have narrowed down that Simple Voice Chat causes this problem independant of all other mods, but you can find a list of all involved within the log file's header.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
You are using and old 1.17 version of the mod for 1.17.1-rc1.
Please use the mod version that was made for that MC version: https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/3373055

**Comment by DDR-Khat** [comment]
Well, I am dense! I could've sworn I'd grabbed the latest version. Must've only grabbed the most recently updated _(not what I normally do, kinda embarrassing)_
Sorry, and thanks!

**Comment by DDR-Khat** [comment]
Unfortunately, I've grabbed the latest version that you linked to and the issue **also** exists there. And it is indeed what I confirmed.

The moment you specifically unbind a key to have no input, it'll begin spamming the console with that log.

![image](https://user-images.githubusercontent.com/66983153/124243912-4ea2fd00-db16-11eb-86a8-932da2160854.png)

**Comment by henkelmax** [comment]
I am not able to reproduce these issues. This is most likely caused by another mod.

**Comment by DDR-Khat** [comment]
https://gist.github.com/DDR-Khat/7b1c909870c7194724eba1eac541e70f I can confirm it is DEFINITELY this mod and not caused by a seperate one. And is explicitly because of unbinding a key. This is done by picking a key in the configuration menu and pressing ESC, as you can see in the screenshot above with the "push to talk" key.
If I re-bind that key, the error goes.

**Comment by henkelmax** [comment]
> https://gist.github.com/DDR-Khat/7b1c909870c7194724eba1eac541e70f I can confirm it is DEFINITELY this mod and not caused by a seperate one. And is explicitly because of unbinding a key. This is done by picking a key in the configuration menu and pressing ESC, as you can see in the screenshot above with the "push to talk" key.
> If I re-bind that key, the error goes.

Then please remove every mod except voice chat and Fabric API, use the vanilla launcher and try it again.
I did exactly what you said and nothing happens.

**Comment by DDR-Khat** [comment]
If you look at the GIST I linked above, that is exactly what I have done in that log. I have explicitly booted the game with only Fabric and simple voice chat. The issue still occurs. I am otherwise not sure what I am doing differently from yourself.

**Comment by henkelmax** [comment]
> If you look at the GIST I linked above, that is exactly what I have done in that log. I have explicitly booted the game with only Fabric and simple voice chat. The issue still occurs. I am otherwise not sure what I am doing differently from yourself.

Then just remove also the voice chat and try it again. Maybe this is a general issue with fabric API or even MC itself.

**Comment by DDR-Khat** [comment]
https://gist.github.com/DDR-Khat/a7222b0768c4753cf548bc4547899a8a As requested.

**Comment by henkelmax** [comment]
> https://gist.github.com/DDR-Khat/a7222b0768c4753cf548bc4547899a8a As requested.

Please check if this also occurs in 1.17.

**Comment by DDR-Khat** [comment]
https://gist.github.com/DDR-Khat/5908464229475b8813b6585b6c94b5ab -- Vanilla log [1.17.1]

https://gist.github.com/DDR-Khat/b968fe071b004241eb7097e8ca97925b -- MultiMC log [1.17]

Both with the exact same problem still, sorry to say.

**Comment by henkelmax** [comment]
Which OS are you using?

**Comment by DDR-Khat** [comment]
![image](https://user-images.githubusercontent.com/66983153/124274972-d0f0e880-db39-11eb-84e3-9f3d27dc284b.png)

**Comment by henkelmax** [comment]
Sorry, but I'm not able to reproduce this error. Does it have any effect of the ability to play this mod?

**Comment by DDR-Khat** [comment]
It doesn't make any gameplay problems, the alerts still come up and I can just bind it to a key I wouldn't use I guess, but ideally having those buttons unbound would be nice as otherwise I'm gonna end up with a bunch of log files with tons of this entry making looking through them really difficult if I need to find out previous things.

I suppose I could grab a copy of the git, throw it into IntelliJ and run Minecraft through that to see if I can get a more detailed error problem. You are certain that you are un-binding a key like I said? (Sorry to sound like I'm asking a dumb obvious question here). As it's explicitly occurring because of the key being unbound.

**Comment by henkelmax** [comment]
Yeah, I tried unbinding. No errors...
Would be nice if you can test it in the dev environment

**Comment by DDR-Khat** [comment]
I believe I may have narrowed down what is causing the problem.
I did infact run in the development enviroment, and those GL errors did not occur.
I've noticed the one thing that appears to be different...

``"C:\Program Files\Java\jdk-16.0.1\bin\java.exe"`` is the dev enviroment.

``"C:\Program Files\Java\jdk-16.0.1\bin\javaw.exe"`` seems to be everywhere else.

[Edit] This is a false positive. There must be something else different here. [/Edit]

**Comment by henkelmax** [comment]
Good to know. I will test it without dev environment too.

**Comment by DDR-Khat** [comment]
I should clarify that these occurs do not occur at the title screen or menus. Only when you are in any world.

**Comment by henkelmax** [comment]
> I should clarify that these occurs do not occur at the title screen or menus. Only when you are in any world.

Yeah I tried it in a non dev environment and also when in a world. Still no error.

What GPU are you using?

Would also be worth a try testing to reset a keybind created by another fabric mod.

**Comment by DDR-Khat** [comment]
![image](https://user-images.githubusercontent.com/66983153/124285155-91c89480-db45-11eb-908a-54e822d588f4.png)
Any other fabric mod happily allows binding to any keys, this is the first time I've ever had such an OpenGL error before which has left me rather confused as to why your mod is having this problem -- Especially as from a casual glance over the code I don't see why it would provide a RENDER error about key bindings?

And it seems to be explicitly about a NULL binding, which is what becomes the weirdest part.

**Comment by henkelmax** [comment]
That's so weird... Does this happen if you try to reset a keybinding that has no key by default or for keybinds that have a default key?

**Comment by DDR-Khat** [comment]
I have identified it more specifically! It is a null binding on the Push-to-Talk !! I sat and unbound each and every key carefuilly. And the error suddenly occurs on having Push-to-talk null.

**Comment by henkelmax** [comment]
So it only happens with the push to talk key?
I think I have a hunch what it could be! Thank you!

**Comment by henkelmax** [comment]
The issue should be fixed in the upcoming version.
