### ISSUE TITLE
BadPaddingException occurs randomly

### ISSUE THREAD

**Issue by Moocow9m** [henkelmax/simple-voice-chat#242]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Randomly, while voice activation is on, it will throw this exception and sometimes crash the client. It has not been tested without krypton, but is random enough to be hard to replicate, so a test could not be conducted. Player can also be alone on the server and exception will still happen.

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
Packets that are incomplete or corrupted should be handled in a try catch and probably discarded rather than crashing the client.

**Log files**
https://gist.github.com/Moocow9m/82450152b278f487555a524d88e2288c

**Versions**
- 1.17
- Fabric 0.11.6
- 1.2.3

**Other mods**
krypton@0.1.3
fabric-api-0.36.0+1.17

**Comment by henkelmax** [comment]
Please update to the latest mod version

**Comment by Moocow9m** [comment]
Latest version gives same error
