### ISSUE TITLE
 I see why you would do this but

### ISSUE THREAD

**Issue by fooeyround** [henkelmax/simple-voice-chat#244]
I am on 1.17.1 because I made and have mods for it and it is more stable than 1.17 but the server I play on is 1.17 and when I connect I cant join because the version on the server is older and I cant get it on 1.17.1 because of obvious reasons, I have multiconnect to join servers, its by earthcomputer.

**Comment by JackTGG** [comment]
Its fine that it is but why is it invalid?

**Comment by fooeyround** [comment]
okay neverminded bye
