### ISSUE TITLE
Client Disconnects from Server

### ISSUE THREAD

**Issue by HermitCree** [henkelmax/simple-voice-chat#246]
**Bug description**
Every time I join my server with simple voice chat enabled, I stay on the server for about twenty seconds and then crash. This only happens on the server when Simple Voice Chat is installed, when I uninstall it the problem goes away.

**Steps to reproduce the issue**
1. Join a server with Simple Voice Chat
2. Wait about 20 seconds
3. Crash

**Expected behavior**
I expected to be able to remain on the server for more than 20 seconds before crashing.

**Log files**
https://gist.github.com/HermitCree/57657cfc2bb76a206590a77fe848186c

**Versions**
- Minecraft Version 1.16.5
- Forge Version 36.1.32
- Simple Voice Chat Version 1.6.12

**Other mods**
None.

**Comment by henkelmax** [comment]
I need the server logs.

**Comment by HermitCree** [comment]
Gotcha!
https://gist.github.com/HermitCree/93dd58821116c4c89d9a8747a692423e

**Comment by henkelmax** [comment]
The full logs

**Comment by HermitCree** [comment]
Okay! Sorry!
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/6793359/latest.log)

**Comment by henkelmax** [comment]
This does not seem to be an issue of the voice chat mod.
`HermitCree lost connection: Timed out`

Please try if this happens without the mod installed.

**Comment by HermitCree** [comment]
When I uninstall the mod from the server and my client, the crash does not happen.

**Comment by henkelmax** [comment]
There are no crashes or errors.
Is this happening to every player on the server or just you?
I also need the full logs of the client.

**Comment by HermitCree** [comment]
It is only happening to me. And here are the full client logs.
[2021-07-09-1.log.gz](https://github.com/henkelmax/simple-voice-chat/files/6793612/2021-07-09-1.log.gz)

**Comment by henkelmax** [comment]
Sorry, but I can't find any crash or similar. It might be just an issue of your system.

**Comment by HermitCree** [comment]
Okay. Thank you for your help! I guess it's back to work lol.
