### ISSUE TITLE
opus class not found on Apple Silicon M1 native aarm64 jdk client 

### ISSUE THREAD

**Issue by jason-green-io** [henkelmax/simple-voice-chat#248]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Plugin on Apple Silicon M1 Macs using a native aarm64 jdk doesn't find opus class. 

**Steps to reproduce the issue**
Connect to server with a  native aarm64 client.
Logs complain about not finding opus.

**Expected behavior**
Plugin works as expected

**Log files**

https://gist.github.com/jason-green-io/47ef1d42dab647a469952214e285ec64

**Versions**
- Minecraft version 1.17.1
- Fabric fabric@0.36.1+1.17
- Mod version 1.17.1-1.0.0

**Other mods**	
- minihud@0.19.0-dev.20210608.211830
	- modmenu@2.0.0-beta.7
	- voicechat@1.17.1-1.0.0

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
There are currently no natives for Apple silicon. You need to run Minecraft with Rosetta.

**Comment by greener-dot-ca** [comment]
opus supports Apple Silicon, how difficult is it for you to create the required native? I may be able to create a universal dyld that includes aarm64 and x86 .. worse case, if I replace the native with a universal one in the jar, would that "just work"?

**Comment by henkelmax** [comment]
> opus supports Apple Silicon, how difficult is it for you to create the required native? I may be able to create a universal dyld that includes aarm64 and x86 .. worse case, if I replace the native with a universal one in the jar, would that "just work"?

If you are able to compile opus for darwin-arm, I can include it in the mod.

**Comment by greener-dot-ca** [comment]
How would you like me to send you the dylib?

Edit:
How about I create a pull request over at opus4j with an appropriately named native?

**Comment by henkelmax** [comment]
> How would you like me to send you the dylib?

I think the best thing would be if you can join our discord server:

https://discord.gg/4dH2zwTmyX
