### ISSUE TITLE
My friend keeps getting kicked for "Badly compressed packet - size of 2 is below server threshold of 256" when the mod is installed.

### ISSUE THREAD

**Issue by iT3g4n** [henkelmax/simple-voice-chat#249]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
When my friend joins my server, he cannot join with voicechat mod installed and it gives this error: `Badly compressed packet - size of 2 is below server threshold of 256`

**Steps to reproduce the issue**
1. Install all the mods

**Expected behaviour**
He should be able to play normally at least with the mod.

**Log files**
coming in a couple hours my friend had to go (sorry I know that they're important :/)

**Versions**
- 1.17
- Fabric 0.11.6
- 1.4.5

**Other mods**
Optifabric - 1.11.9
Optifine - pre24
Fabric API - 0.36.1

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/68778866/125157229-8edf2c80-e161-11eb-9a64-5a474231952e.png)

Oh and I can join just fine with the exact same connecting ip.

**Comment by henkelmax** [comment]
This happens if you are in offline mode. Please set `online-mode=true`

**Comment by iT3g4n** [comment]
thank you but i don't think i can do that, another friend of mine doesn't have premium minecraft yet. Oh well. Thank you anyway :(

**Comment by brawaru** [comment]
Try setting `network-compression-threshold` to `0` in `server.properties`.

**Comment by yebanme** [comment]
> thank you but i don't think i can do that, another friend of mine doesn't have premium minecraft yet. Oh well. Thank you anyway :(

Have you found a suitable solution, because I also have this problem

**Comment by iT3g4n** [comment]
> Try setting `network-compression-threshold` to `0` in `server.properties`.

no its just the plugin. thanks anyway

**Comment by buttowskii** [comment]
I also have this problem. Same mods, and I can't put it online=true :/

**Comment by henkelmax** [comment]
We don't support pirating the game. There won't be a fix.

**Comment by brawaru** [comment]
Thing is, `online-mode` is a **built-in** feature that was not meant for pirating the game per se, but rather to be able to play Minecraft in offline conditions (like LAN parties). So while you might think you're supporting anti-piracy by WONT-FIXing this issue, you're take away the real world case. I remember also Bungeecord requires all the servers to be offline, does the plugin work there? More, pirates will simply overcome this issue by replacing Minecraft's authentication library.

So I don't see why you would be so reluctant to fix this bug. Piracy is not really your concern in this case: server is unpatched (well, asides from Paper/Spigot/Bukkit/etc patches) and in valid intended condition (it's configuration changed); neither you're affiliated with Mojang or Microsoft to care. You can't distinguish either — I am a licenced player, can download a server and set it to `online-mode=false` (for whatever purpose), then launch my legitimate copy of the game through official launcher and connect to that server, so am I pirate? Of course not. Won't get into polemics about morality of piracy, but [there's that](https://twitter.com/notch/status/157261795139125248).

**Comment by henkelmax** [comment]
> Thing is, online-mode is a built-in feature that was not meant for pirating the game per se, but rather to be able to play Minecraft in offline conditions (like LAN parties).

LAN worlds don't work with the voice chat anyways.
If you are on a LAN party, you don't need the voice chat anyways.

> I remember also Bungeecord requires all the servers to be offline, does the plugin work there? More, pirates will simply overcome this issue by replacing Minecraft's authentication library.

Bungeecord and velocity actually works with the voice chat.

> Won't get into polemics about morality of piracy, but there's that.

You are quoting a tweet from 2012, by a person that is not at all associated to the game anymore.

Additionally the network traffic is not encrypted at all when using offline mode, meaning everyone can hijack your voice chat connection or hear what you are saying.

There is really no reason at all why we should support offline mode!

**Comment by brawaru** [comment]
> If you are on a LAN party, you don't need the voice chat anyways.

Why? You can sit pretty much at different PCs, far from each other to hear — LAN parties aren't limited to sitting next to each other, it can be a mass event too.

> Additionally the network traffic is not encrypted at all when using offline mode, meaning everyone can hijack your voice chat connection or hear what you are saying.

Nobody would need to hijack and fake someone's voice chat in a blocky game, unless it's some Hacking 101 class. Plus with going to `offline-mode` you're agreeing with that risk, you then get a prompt at each start of the server.

> There is really no reason at all why we should support offline mode!

It's a valid server configuration, though? Your plugin doesn't need authentication (only UUIDs, I think, which offline mode supplies), there's only that bug that it tries to compress (or doesn't?) the packets when `online-mode=false` servers are uncompressed (they don't establish it per protocol).

**Comment by henkelmax** [comment]
You can argue as long as you want. I won't fix it. If it is so important to you, you can create a pull request fixing it and I will happily merge it. But I have better stuff to do than fixing an issue that 99% affects people pirating the game.

**Comment by brawaru** [comment]
I didn't want to argue, sorry, just to get other point across.

> you can create a pull request fixing it and I will happily merge it

This is fine. I unfortunately don't have experience with modded Minecraft, but others might — so this is a good thing to hear. Also, I couldn't reproduce this issue in latest version of the mod/plugin for 1.17.1.

**Comment by iT3g4n** [comment]
> You can argue as long as you want. I won't fix it. If it is so important to you, you can create a pull request fixing it and I will happily merge it. But I have better stuff to do than fixing an issue that 99% affects people pirating the game.

If somebody does this I love u

**Comment by okzerus** [comment]
> We don't support pirating the game. There won't be a fix.

I don't care about necroposting, I don't even know this mod, I even restored the password for this account, and every of these was done just to say how am I fucking sick of you.
Brawaru described EVERYTHING, and he's RIGHT, the only reason you can't fix the plugin is that your stupid mug just DOESN'T WANT to fix the plugin!
why are there people like you living on the earth, oh my god!

**Comment by Apollo4545** [comment]
> You can argue as long as you want. I won't fix it. If it is so important to you, you can create a pull request fixing it and I will happily merge it. But I have better stuff to do than fixing an issue that 99% affects people pirating the game.


Having the same issue with server members who don't pirate the game. 
Nor do they use the VC mod. So I'm going to assume it has nothing to do with being in offline mode... especially since the server is in online mode. 

If you find the Answer, let me know. Otherwise, get off your high horse.
