### ISSUE TITLE
Microphone not working in Windows 10 OS

### ISSUE THREAD

**Issue by wolten65** [henkelmax/simple-voice-chat#253]
So when i install the mod on my aternos server and i download forge 1.16.5 same version also, i also have another mod called Mr.Crafish's Gun Mod adn Obfucate the mod works its just that we cant hear eachother, we also put the port of the server in the voicechat file. It sometimes also tells voice chat unavailable but if we rejoin it will come, we just cant hear eachother.Please someone help me, Thanks In Advance!

**Comment by henkelmax** [comment]
Please fill out the bug template.
