### ISSUE TITLE
Is there a command to stop the voice chat server?

### ISSUE THREAD

**Issue by SplendidAlakey** [henkelmax/simple-voice-chat#254]
MC version 1.17.1
SVC version 1.0.6
Fabric API version 0.37.0

I am running my MC server on a Ubuntu screen, when I stop the server it does not stop the voice chat server, and I am forced to detach the screen, kill it and start a new one. This makes sure the voice chat server restarts as well, otherwise it will crash the server due to being unable to be bound to 0.0.0.0, since the previous session is still on. Is there a command to stop the voice chat server that I missed in the FAQ? If not, could you possibly add it in the future releases?

**Comment by henkelmax** [comment]
The voice chat server automatically starts and stops with the minecraft server. No additional commands needed.
