### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by CommandCracker8** [henkelmax/simple-voice-chat#257]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Ok well I had my ticket closed because I didn't use a template but none of the templates applied!
Here is what my issue said:

Hi! I need some help. I have two questions:

1: How do I use the Bukkit/Spigot/Paper versions of the mod found [Here](https://www.curseforge.com/minecraft/bukkit-plugins/simple-voice-chat/)? Do I just install it and then the players who connect to my server still use the mod? This would be good, as it would mean I don't need a Fabric server and I can then install plugins. Plus I could use Paper to improve performance.

2: Any idea why the little microphone icon won't appear in the corner of my screen? Even why I try PTT it doesn't show. Also, I can't talk to anyone else on my server that has to mod installed, but they can talk to me and other poeple. It seems like the mod can't get my microphone input. And yes, I've selected my microphone correctly! It was working yesterday but now it doesn't work!

Any help is greatly appreciated!

**Steps to reproduce the issue**
I don't know how to reproduce question 2.

**Expected behavior**
idk what to put here

**Log files**
The only useful thing from the logs is: ` Mic unavailable javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported. `

**Versions**
- Minecraft version: 1.17.1
- Forge/Fabric version: Is this not the same as the Minecraft version?
- Mod version: Most recent at the time of writing this

**Other mods**
Optifabric

**Screenshots (Optional)**
N/A (I think)

**Comment by henkelmax** [comment]
Please visit the discord for help

**Comment by CommandCracker8** [comment]
OK!

**Comment by CommandCracker8** [comment]
Could you reply to my message please @henkelmax ? It's https://discord.com/channels/854659575324344340/858034045564878858/865957051179335741
