### ISSUE TITLE
I cannot edit the server config

### ISSUE THREAD

**Issue by Phyroks** [henkelmax/simple-voice-chat#26]
**Bug description**
Whenever I edit the serverconfig, it resets itself after a server restart. 

**Steps to reproduce the issue**
1. Go to '/world/serverconfig/voicechat-server.toml'
2. I set sample rate to "44100"
3. I set distance to 8.0 and fade distance to 4.0
4. Restart the server to update the settings

**Expected behavior**
The server starts and the configuration is accepted

**Log files**
https://pastebin.com/xSRrVXhW

**Versions**
- 1.16.4
- Forge 35.1.4
- 1.1.3

**Comment by henkelmax** [comment]
I did the same thing you did and it worked fine.
Can you send me the contents of your server config after you changed it?
Also please send me the debug logs, as your logs contain nothing.

**Comment by Phyroks** [comment]
Debug log: https://pastebin.com/79YqVPpt
Content: https://pastebin.com/i1GqS1CC

**Comment by henkelmax** [comment]
It seems you changed the config while the server was running:

`[17Jan2021 11:29:26.881] [Thread-1/DEBUG] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Config file voicechat-server.toml changed, sending notifies`

Please make sure you haven't opened the config in some text editor, while starting the server.

Are you able to reproduce this issue?

**Comment by henkelmax** [comment]
Closed due to inactivity
