### ISSUE TITLE
Mod not working on a server with OmgServ

### ISSUE THREAD

**Issue by TaianRmos** [henkelmax/simple-voice-chat#260]
Good morning,
I've been trying to install the simple voice chat mod on my OmgServ server, and the mod keep failling when I install it.

I use the Fabric version of the mod, I have first installed Fabric on my pc, with FrabicAPI, Optifine and Optifabric for the 1.17.1 version of minecraft. I then installed the simple voice chat mod for fabric 1.17.1 by putting it in the 'mod' folder of minecraft.

Then, I put the Fabric version for 1.17.1 on my server, and I added FabricAPI and the simple voice chat mod in the 'mod' folder once again. The mod wasn't working.

I saw that you had to fix the port by yourself, so I opened a port on my server and changed it in the voice chat properties file, but the problem is still here. When I log on my server, there is the little icon saying that it's not working, and when I click on 'v' it says "Voice chat unavailable".

Also, after checking my server console, I checked if the mod was on the right port, and it is the case (as you can see on the first image), and there is this weird repeating process where the mod authenticates me, then my "time is out", my player is reconnected and it sends me a secret. 

I sent a message to my assistance service, but they are not able to solve my problem. 

Could you help me fixing this problem ? Don't hesitate to ask me for more details if I forgot something.
Thank you !

![Sans titre 2](https://user-images.githubusercontent.com/87705384/126326569-8e5d178e-ee48-49cd-b4a6-9b5a579fb3f6.png)
![Sans titre](https://user-images.githubusercontent.com/87705384/126326608-f94bf3bb-7f74-44d8-ae0e-2dca5e1fbb0e.png)

**Comment by henkelmax** [comment]
This is not a bug.
For help, please visit the discord server.
