### ISSUE TITLE
Voice Chat Not Connected

### ISSUE THREAD

**Issue by sonjah45** [henkelmax/simple-voice-chat#261]
**Bug description**
I'm not really sure what the bug is but the voice chat won't connect for anyone who joins the server and  I know for a fact that I'm on the right port, my console said that it started the mod on port 24454. So I'm confused as to what the problem is. I am using shockbyte server hosting (I know it's not a great host). I've followed the steps to setting everything up. I'm not really sure if this is a bug but I would really appreciate some help. I have also looked at the page on how to trouble shoot this problem on the wiki and I don't see anything besides connecting to the right port.

**Comment by henkelmax** [comment]
This is not a bug.
Visit the discord for support.
