### ISSUE TITLE
Releases in Github

### ISSUE THREAD

**Issue by sixwheeledbeast** [henkelmax/simple-voice-chat#264]
Just a simple request for having release jars here on github. 
This would be so helpful as dealing with downloads on curseforge is a pain.
Many thanks for your work.

**Comment by henkelmax** [comment]
There is no way to order different releases for different mc versions. I also can't pack them into a single release. This would be a complete mess to find the correct jar file.
You can compile the jar yourself, but I won't publish anything here on GitHub.

**Comment by sixwheeledbeast** [comment]
That is a shame. 
I can understand a single release being an issue. Other fabric mods including the API deal with this as having one release but separate jars per version. Which seems to work logically https://github.com/gnembon/fabric-carpet/releases for example. This may not work for yourself but just a suggestion.

The download links on curseforge are not possible to use when setting up on a headless server. Hence my request, to avoid the need of downloading via a browser and getting it to the server by some other means. 

If this is not a option where can information be found on how to compile? 
This maybe a solution if possible headless with minimal dependences for the server machine.
Many thanks.

**Comment by henkelmax** [comment]
> The download links on curseforge are not possible to use when setting up on a headless server. Hence my request, to avoid the need of downloading via a browser and getting it to the server by some other means.

Of course this is possible. You can either upload it to your server via SCP or FTP or you can just copy the download link (https://media.forgecdn.net/files/...) with the browser of your local machine.
There is also a rest API with direct download links, which makes it possible to completely automate the downloading of the latest version or any other version: https://addons-ecs.forgesvc.net/api/v2/addon/416089/files/

So just saying that it is not possible is complete BS.

**Comment by sixwheeledbeast** [comment]
I was not aware of these. The all link locations provided on the site 403, there is no BS intended... 
I shall look into those, thanks.

**Comment by henkelmax** [comment]
> The all link locations provided on the site 403

Which site?

**Comment by K0-RR** [comment]
>dealing with downloads on curseforge is a pain

What about [Modrinth](https://modrinth.com)?

**Comment by henkelmax** [comment]
> What about [Modrinth](https://modrinth.com)?

I already have an account there, but I'm waiting for them to enable monetization.
