### ISSUE TITLE
microphone not connecting

### ISSUE THREAD

**Issue by 14jjbeddoes** [henkelmax/simple-voice-chat#266]
I am using fabric 0.11.6 on 1.17 on a server.
I connect on my client and my mic doesn't connect
I found this in my log
Mic unavailable javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian not supported.

**Comment by henkelmax** [comment]
This is not a bug. Your microphone is not supported or used by another process.
Visit the discord for more help.
