### ISSUE TITLE
Microphone not working in Linux

### ISSUE THREAD

**Issue by edwloef** [henkelmax/simple-voice-chat#268]
I can't correctly select which microphone to use while running on Pop!_OS. The choices given to me are [default]. [plugw:0,0], [plugw:1,0] and [plugw:2,0]

Minecraft version 1.17
Mod version: voicechat-fabric-1.17.1-1.1.6

**Comment by edwloef** [comment]
I can, however, set the input correctly using pavucontrol.

**Comment by henkelmax** [comment]
Please visit the discord for help.
