### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by PyTexa247** [henkelmax/simple-voice-chat#269]
Hello, when i start my server with the mod the server crashes, this is what comes out on the console when crashing
11.08 15:48:40 [Server] Server thread/INFO Preparing level "MundoForge"
11.08 15:48:40 [Server] Server thread/INFO Preparing start region for dimension minecraft:overworld
11.08 15:48:41 [Server] Server thread/INFO Preparing spawn area: 0%
11.08 15:48:41 [Server] Server thread/INFO Preparing spawn area: 0%
11.08 15:48:41 [Server] Worker-Main-13/INFO Preparing spawn area: 0%
11.08 15:48:41 [Server] Server thread/WARN Skipping BlockEntity with id gravestone:gravestone
11.08 15:48:41 [Server] Server thread/WARN Skipping Entity with id alexsmobs:gazelle
11.08 15:48:41 [Server] Server thread/WARN Skipping Entity with id alexsmobs:gazelle
11.08 15:48:41 [Server] Server thread/WARN Skipping Entity with id alexsmobs:gazelle
11.08 15:48:41 [Server] Server thread/WARN Skipping Entity with id alexsmobs:gazelle
11.08 15:48:41 [Server] Server thread/WARN Skipping Entity with id alexsmobs:gazelle
11.08 15:48:41 [Server] Server thread/INFO Time elapsed: 1370 ms
11.08 15:48:41 [Server] Startup Done (1.534s)! For help, type "help"
11.08 15:48:41 [Server] VoiceChatServerThread/ERROR [voicechat/]: Failed to bind to address '0.0.0.0'
11.08 15:48:41 [Server] VoiceChatServerThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:72]: java.net.BindException: Address already in use (Bind failed)
11.08 15:48:41 [Server] VoiceChatServerThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:72]: at java.net.PlainDatagramSocketImpl.bind0(Native Method)
11.08 15:48:41 [Server] VoiceChatServerThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:72]: at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)
11.08 15:48:41 [Server] VoiceChatServerThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:72]: at java.net.DatagramSocket.bind(DatagramSocket.java:392)
11.08 15:48:41 [Server] VoiceChatServerThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:72]: at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
11.08 15:48:41 [Server] VoiceChatServerThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:72]: at java.net.DatagramSocket.<init>(DatagramSocket.java:299)
11.08 15:48:41 [Server] VoiceChatServerThread/INFO [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server:run:72]: at de.maxhenkel.voicechat.voice.server.Server.run(Server.java:61)
11.08 15:48:41 [Server] Server thread/ERROR Couldn't load server icon
11.08 15:48:41 [Server] INFO java.lang.IllegalStateException: Shutdown in progress
11.08 15:48:41 [Server] INFO at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66) ~[?:1.8.0_292] {}
11.08 15:48:41 [Server] INFO at java.lang.Runtime.addShutdownHook(Runtime.java:211) ~[?:1.8.0_292] {}
11.08 15:48:41 [Server] INFO at com.sun.imageio.stream.StreamCloser$2.run(StreamCloser.java:101) ~[?:1.8.0_292] {re:classloading}
11.08 15:48:41 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_292] {}
11.08 15:48:41 [Server] INFO at com.sun.imageio.stream.StreamCloser.addToQueue(StreamCloser.java:84) ~[?:1.8.0_292] {re:classloading}
11.08 15:48:41 [Server] INFO at javax.imageio.stream.FileCacheImageOutputStream.<init>(FileCacheImageOutputStream.java:95) ~[?:1.8.0_292] {}
11.08 15:48:41 [Server] INFO at com.sun.imageio.spi.OutputStreamImageOutputStreamSpi.createOutputStreamInstance(OutputStreamImageOutputStreamSpi.java:68) ~[?:1.8.0_292] {re:classloading}
11.08 15:48:41 [Server] INFO at javax.imageio.ImageIO.createImageOutputStream(ImageIO.java:419) ~[?:1.8.0_292] {}
11.08 15:48:41 [Server] INFO at javax.imageio.ImageIO.write(ImageIO.java:1583) ~[?:1.8.0_292] {}
11.08 15:48:47 [Multicraft] Skipped 8 lines due to rate limit (30/s)
11.08 15:48:47 [Server] Server thread/INFO ThreadedAnvilChunkStorage (MundoForge): All chunks are saved
11.08 15:48:47 [Server] Server thread/INFO Saving chunks for level 'ServerLevel[MundoForge]'/minecraft:the_nether
11.08 15:48:47 [Server] Server thread/INFO ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
11.08 15:48:47 [Server] Server thread/INFO Saving chunks for level 'ServerLevel[MundoForge]'/minecraft:the_end
11.08 15:48:47 [Server] Server thread/INFO ThreadedAnvilChunkStorage (DIM1): All chunks are saved
11.08 15:48:47 [Server] Server thread/INFO ThreadedAnvilChunkStorage (MundoForge): All chunks are saved
11.08 15:48:47 [Server] Server thread/INFO ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
11.08 15:48:47 [Server] Server thread/INFO ThreadedAnvilChunkStorage (DIM1): All chunks are saved
11.08 15:48:47 [Multicraft] Server shut down (running)
11.08 15:48:47 [Multicraft] Not restarting crashed server.
11.08 15:48:47 [Multicraft] Looks like a crash, check the server console. Return value: 1
11.08 15:48:47 [Multicraft] Server stopped
I try to start with only the mod and without others and same

**Comment by PyTexa247** [comment]
I tried a oldest forge and SimpleVoiceMod and same

**Comment by henkelmax** [comment]
This is not a bug.
Please read the wiki before reporting anything.
Also please follow the provided issue template.
