### ISSUE TITLE
Kicked instantly upon joining.

### ISSUE THREAD

**Issue by ollie7671** [henkelmax/simple-voice-chat#27]
Whenever I attempt to join the server that I am hosting (with only the voice chat mod enabled) I am kicked from the server instantly. I was wondering if there was a simple solution or if I am just missing something completely.

Thanks!

[debug.log](https://github.com/henkelmax/simple-voice-chat/files/5827764/debug.log)

**Comment by henkelmax** [comment]
Please fill out the bug template and don't forget the debug logs of your client.

**Comment by henkelmax** [comment]
Closed due to inactivity.
