### ISSUE TITLE
Microphone unavailable

### ISSUE THREAD

**Issue by Vlnicius** [henkelmax/simple-voice-chat#272]
**Bug description**
So I'm making a modpack with some friends that uses the simple voice chat, however whenever I join to the sever there is a mensage saying that my microphone is unvalible try restart your computer, but it only happens to me, my microphone is working in other apps like discord and zoom. I can hear the other but I can even test my mic 'cause its unvalible. What I have to do?

**Steps to reproduce the issue**
1. Open the Minecraft
2. Join to the server
3. See error "[Simple voice chat] Your micrhophone is unavailable, try restart your computer

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.2.2
- Mod version:  [Forge][1.16.5]1.16.5-1.7.7

**Other mods**
OptiFine
Security Craft
Antique Atlas
Crafting Dead
Desolation
Enchanced Celestial
Guard Villagers
The Lost Cities
Mob Sunscreen
Traveler's Backpack
vending machine
Zombie Extreme
Just Enough Item
Cloth Config API
Stoneholm
Architectury API
FTB Library
Corpse
Crafting Dead Survival
Tough as nails
Item Filters
FTB Quests
FTB Teams
Immersive Engineering
Immersive Petroleum
pam's harvestcraft 2 crops
pam's harvestcraft 2 foodcore
pam's harvestcraft 2 foodextended
pam's harvestcraft 2 trees
Serene Seasons
Better Weather
Simple Voice Chat

**Comment by henkelmax** [comment]
This is not a bug. Please read the wiki and join the Discord server if you have questions.
