### ISSUE TITLE
A Weird Pattern when somebody connects locally

### ISSUE THREAD

**Issue by Caty15** [henkelmax/simple-voice-chat#273]
**Bug Description**
This error occurs when another computer connects locally to the server. I'm hosting the server from my PC. both me and the other computer connect with the IPV6 address, (everyone else with the IPV4). my computer (the host) connects and works fine. but the other PC doesn't. when they press V, it says "voice chat unavailable." even though everyone else works. they are on the correct version of forge and the mod. when I run /voicechat test (player), it says "request timed out." the console was making weird patterns involving timeouts and reconnecting the player holly1005 (the pc that didn't work.)

**Expected behavior**

**Log files**
Taken down

**Versions**
- MC 1.16.5
- Forge 36.1.0
- Mod v1.5.5

**Other mods**
None.

**Comment by henkelmax** [comment]
This is not a bug.
Please join the discord for help.
