### ISSUE TITLE
Server Config file Properties Description

### ISSUE THREAD

**Issue by ghost** [henkelmax/simple-voice-chat#278]
**Is your feature request related to a problem? Please describe.**
I'm trying to setup the server side of a Fabric server.  I couldn't find any description of the various options, especially the networking parts.

**Describe the solution you'd like**
An addition to the Wiki, or descriptions in the config file describing the option

**Describe alternatives you've considered**

**Additional context**

**Comment by henkelmax** [comment]
The java properties configuration implementation does not allow for comments above entries. Thus I created the descriptions in the wiki
