### ISSUE TITLE
Voice chat unavailable - Failure to send packet

### ISSUE THREAD

**Issue by H-Duck** [henkelmax/simple-voice-chat#28]
**Bug description**
I believe I have the mod set up correctly on my server, I have forwarded the port using the server host's provided system, however using /voicechat test [username] sends the error "Failure to send packet: Operation not permitted (sendto failed)", and trying to access the settings sends the error "Voice chat unavailable"

**Log files**
latest.log from client: https://gist.github.com/H-Duck/9226ab989fb9e408d497cd7e180cfc00

**Versions**
- 1.16.5
- Forge version
- 1.0.0

**Other mods**
Create v0.3e

**Comment by henkelmax** [comment]
Please also send me the logs of your server.
It seems that you minecraft hoster doesn't allow UDP connections.

**Comment by H-Duck** [comment]
Ah, I'll try to look into that to see if I can sort it.
Here's the server's latest log: https://gist.github.com/H-Duck/b66a0d9c2eb9c60d46d9b1ad261f42c4

**Comment by henkelmax** [comment]
> Here's the server's latest log: https://gist.github.com/H-Duck/b66a0d9c2eb9c60d46d9b1ad261f42c4

Yes! this is definitely a problem with your hoster.
