### ISSUE TITLE
Crashes on custom Minecraft launchers

### ISSUE THREAD

**Issue by Binair-Dev** [henkelmax/simple-voice-chat#281]
**Bug description**
When i click disconnect from server or normal world, i got an exception ("java.lang.NullPointerException: mouseClicked event handler").

**Steps to reproduce the issue**
1. Launch minecraft using a custom made launcher
2. Create a world/Join a server
3. Wait a few seconds
4. Disconnect, try to get back to the Main menu
5. And here is the error, the Minecraft client crash and report you the error.

**Expected behavior**
A little fix ? ^^

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can check the crash report on: https://pastebin.com/0jHUZ80d

**Versions**
- 1.16.5
- Fabric version
- Mod version: voicechat-fabric-1.16.5-1.10.0

**Other mods**

1. fabric-api-0.34.6+1.16
2. malilib-fabric-1.16.4-0.10.0-dev.21+arne.5
3. optifabric-1.11.20
4. OptiFine_1.16.5_HD_U_G8
5. rich-presence-mod-1.0.1 (A custom one that i can provide)

**Adds**
[crash-2021-10-01_11.29.26-client.txt](https://github.com/henkelmax/simple-voice-chat/files/7265942/crash-2021-10-01_11.29.26-client.txt)

**Comment by henkelmax** [comment]
Does this happen without optifine?

**Comment by Binair-Dev** [comment]
Yeah, i tried even with just the voice chat mod, and still the same issue, no problems with other mods :/

**Comment by henkelmax** [comment]
Please send me the logs of the crash without any other mods.
I also need to have the source code of your launcher.

EDIT: It might be cause by your game profile not having a UUID. You might be missing the command line parameter to set your players UUID.

**Comment by Binair-Dev** [comment]
I added you on discord to make it easyer (B_nair#5982)

**Comment by henkelmax** [comment]
Join the discord server of the mod then.
