### ISSUE TITLE
[Feature Request] disable mod for servers with strict packet limiting settings

### ISSUE THREAD

**Issue by MissGamerz** [henkelmax/simple-voice-chat#282]
**Is your feature request related to a problem? Please describe.**
When joining packet limiting servers like my own or hypixel we stop packets from being sent and kick players (hypixel sends them to a limbo server) this means when changing servers from a voice mod server to hypixel you have to close the client disable the mod and restart but then moving back you have to enable it again this is not efficient 

**Describe the solution you'd like**
a solution to the would be whitelisting/blacklisting servers in the client config to allow for these types of servers, and also allow the mod to not send a packet on join therefore bypassing this protection on servers and essentially being disabled for the duration of them being on that server.

easiest way to identify the server would be the IP that the client connects with such as "hypixel.net"

**Comment by henkelmax** [comment]
The mod only sends one packet to the server to check if voice chat is installed. Does this really get you kicked from Hypixel?

**Comment by MissGamerz** [comment]
you get sent to limbo until you disable the mod, on our vanilla network we do similar things

**Comment by henkelmax** [comment]
Unfortunately there is no other way to detect if a server uses voice chat. It seems pretty dumb to not let a player join a server just because of one packet...

**Comment by MissGamerz** [comment]
I'm aware of this this is why I suggested what I did

**Comment by MissGamerz** [comment]
Just a extra note it may seem dumb that's security for you we have no way of telling what packets are for outside of normal Minecraft behaviour, bearing in mind we have to deal with things like packet aura, nuker, duping, and so on without creating exceptions for each and every mod in existence that would be dumb

Plus most of this packet limit stuff is built right into paper spigot and enabled by default. It's not the count that matters what matters is it's not normal (as in normal Minecraft network traffic)

**Comment by henkelmax** [comment]
I don't know what you mean with that. There are no packets spammed by this mod, so I don't know what you mean with packet limit.
Voice chat sends one packet to check if the server has the voice chat mod installed.
This mod uses minecrafts vanilla plugin messaging system, so servers that don't understand the voice chat packets just ignore them.

**Comment by henkelmax** [comment]
Closed due to inactivity

**Comment by MissGamerz** [comment]
Wymmm I've explained the problem with a solution 

Am I supposed to fix it???

I'm waiting on you

**Comment by henkelmax** [comment]
If you want to join servers with this weird way of handling plugin messaging, go and disable the mod before joining the server.

**Comment by MissGamerz** [comment]
All I asked for was a way to blacklist some servers so the mod wouldn't interact with them.......
