### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by ghost** [henkelmax/simple-voice-chat#284]
**Bug description**
When I try to join a server with the mod, it says connection lost

**Steps to reproduce the issue**
1. Open Minecraft 1.17.1
2. Click on Multiplayer
3. Join a server with the plugin
4. See the error: Connection Lost

**Expected behavior**
Im supposed to be able to join with no problems

**Log files**
https://gist.github.com/SkeppyFan123/93a1d3619ff8fc85b6342b55c0401f16
**Versions**
- 1.17.1
- Fabric 1.17.1
- 1.17.1

**Other mods**
Fabric API

**Comment by henkelmax** [comment]
Please provide the correct log files. (From the server `logs/latest.log`)

Does it happen without voice chat?

Are you using the bukkit version of the mod on your server or fabric?

**Comment by henkelmax** [comment]
Closed due to inactivitay
