### ISSUE TITLE
Status in Tab List

### ISSUE THREAD

**Issue by aidanashman08** [henkelmax/simple-voice-chat#285]
I can never tell if someone is online in voice chat when I log in. I have to find the person, see if they are AFK or not, and if not, invite them to a group or talk through proximity.

I suggest an indicator that shows up in the tab list that will show the current status of the player. If they are online, show the speaking symbol (the one that appears on the side of their nametag), if they are muted show the muted sign, if they are running the mod but are muted or deafened, show the according symbols. Lastly if the person is not connected to the mod, show the not connected sign (the one with the power cord with the line through it.

I have tried to set up scoreboard systems to show their name in color, but that feels less like true vanilla minecraft.

If you need help understanding what I'm asking, load up lunar client and log into Hypixel. The people running lunar will have an indicator next to their name in tab showing that they are using the Lunar Client.

Thanks for the amazing mod,
AmazingAidan25

**Comment by henkelmax** [comment]
I understand why you want this feature, but unfortunately this would conflict with https://github.com/henkelmax/status.
You can check the connection of a player with the `/voicechat test <name>` command.
I also don't think most people want more icons in their tablist.
