### ISSUE TITLE
Voice chat unavailable

### ISSUE THREAD

**Issue by lyk0** [henkelmax/simple-voice-chat#287]
If i join my own server my simple voice chat works but when my friends joined it says voice chat unavailable I already configure the port still the same I did other test used my other laptop using the same wifi still saay voice chat unavailable 

port:56280
Server console logs
09.10 10:22:06 [Server] VoiceChatPacketProcessingThread/WARN Failed to read packet from /180.190..........:24393
09.10 10:22:06 [Server] VoiceChatPacketProcessingThread/INFO Successfully authenticated player 1954f749-5685-3b67-a652-5cad03768dc2
09.10 10:22:07 [Server] VoiceChatPacketProcessingThread/INFO Player d9970ebe-6c65-364b-8c3d-cd80a3925fcf timed out
09.10 10:22:07 [Server] VoiceChatPacketProcessingThread/INFO Reconnecting player lyk
09.10 10:22:07 [Server] VoiceChatPacketProcessingThread/INFO Sent secret to lyk
09.10 10:22:07 [Server] VoiceChatPacketProcessingThread/INFO Successfully authenticated player d9970ebe-6c65-364b-8c3d-cd80a3925fcf
09.10 10:22:17 [Server] VoiceChatPacketProcessingThread/INFO Player 1954f749-5685-3b67-a652-5cad03768dc2 timed out
09.10 10:22:17 [Server] VoiceChatPacketProcessingThread/INFO Reconnecting player Shinooo_
09.10 10:22:17 [Server] VoiceChatPacketProcessingThread/INFO Sent secret to Shinooo_
09.10 10:22:17 [Server] VoiceChatPacketProcessingThread/WARN Failed to read packet from /180.190.......:24418
09.10 10:22:17 [Server] VoiceChatPacketProcessingThread/INFO Successfully authenticated player 1954f749-5685-3b67-a652-5cad03768dc2
09.10 10:22:18 [Server] VoiceChatPacketProcessingThread/INFO Player d9970ebe-6c65-364b-8c3d-cd80a3925fcf timed out
09.10 10:22:18 [Server] VoiceChatPacketProcessingThread/INFO Reconnecting player lyk
09.10 10:22:18 [Server] VoiceChatPacketProcessingThread/INFO Sent secret to lyk
09.10 10:22:18 [Server] VoiceChatPacketProcessingThread/INFO Successfully authenticated player d9970ebe-6c65-364b-8c3d-cd80a3925fcf
09.10 10:22:28 [Server] VoiceChatPacketProcessingThread/INFO Player 1954f749-5685-3b67-a652-5cad03768dc2 timed out
09.10 10:22:28 [Server] VoiceChatPacketProcessingThread/INFO Reconnecting player Shinooo_
09.10 10:22:28 [Server] VoiceChatPacketProcessingThread/INFO Sent secret to Shinooo_
09.10 10:22:28 [Server] VoiceChatPacketProcessingThread/WARN Failed to read packet from /180.190......:24454
09.10 10:22:28 [Server] VoiceChatPacketProcessingThread/INFO Successfully authenticated player 1954f749-5685-3b67-a652-5cad03768dc2
09.10 10:22:29 [Server] VoiceChatPacketProcessingThread/INFO Player d9970ebe-6c65-364b-8c3d-cd80a3925fcf timed out
09.10 10:22:29 [Server] VoiceChatPacketProcessingThread/INFO Reconnecting player lyk
09.10 10:22:29 [Server] VoiceChatPacketProcessingThread/INFO Sent secret to lyk
09.10 10:22:29 [Server] VoiceChatPacketProcessingThread/INFO Successfully authenticated player d9970ebe-6c65-364b-8c3d-cd80a3925fcf
09.10 10:22:39 [Server] VoiceChatPacketProcessingThread/INFO Player 1954f749-5685-3b67-a652-5cad03768dc2 timed out
09.10 10:22:39 [Server] VoiceChatPacketProcessingThread/INFO Reconnecting player Shinooo_
09.10 10:22:39 [Server] VoiceChatPacketProcessingThread/INFO Sent secret to Shinooo_
09.10 10:22:39 [Server] VoiceChatPacketProcessingThread/WARN Failed to read packet from /180.190......:24474
09.10 10:22:39 [Server] VoiceChatPacketProcessingThread/INFO Successfully authenticated player 1954f749-5685-3b67-a652-5cad03768dc2
09.10 10:22:40 [Server] VoiceChatPacketProcessingThread/INFO Player d9970ebe-6c65-364b-8c3d-cd80a3925fcf timed out
09.10 10:22:40 [Server] VoiceChatPacketProcessingThread/INFO Reconnecting player lyk
09.10 10:22:40 [Server] VoiceChatPacketProcessingThread/INFO Sent secret to lyk
09.10 10:22:40 [Server] VoiceChatPacketProcessingThread/INFO Successfully authenticated player d9970ebe-6c65-364b-8c3d-cd80a3925fcf

**Comment by henkelmax** [comment]
This is not a bug. If you need help, visit the discord.
