### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by InfinityZ25** [henkelmax/simple-voice-chat#288]
It is extremely difficult to read the code and try to interpret what does what. I'm trying to add new functionalities (such as server-side silencing, real-time adjustable voice reach, and custom GUI icons to symbolize more data) and I'm finding it difficult to keep track of what does what or where to begin looking at things. Your mod is cool, the code however is a bit hectic. 

Better documentation, such as comments on your code, would definitely help understand the intricate mechanisms that you've designed. Alternatively, rewriting the project and simplifying unnecessary pieces of your design could also help ( I'm willing to collab on this one -- there's no reason for you to have 69 different branches. A common, multi-module Gradle project will suffice.)

**Comment by henkelmax** [comment]
I'm not intending to add documentation to the code.
The code is only on GitHub for people that want to look into it (To ensure for people that there are no hidden features or backdoors/To check if the encryption is actually secure/...).
It is not intended for adding features or even republishing it. Thus also the license "All Rights Reserved".

**Comment by InfinityZ25** [comment]
Did not see a license file anywhere

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/136821533-8096000f-85eb-4472-a691-20495c4a2b7b.png)
It is also All Rights Reserverd by default on GitHub

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
![image](https://user-images.githubusercontent.com/13237524/136821706-e35ea663-0a96-400d-96df-40974b1d6b4f.png)

**Comment by henkelmax** [comment]
Also this for reference:
https://github.com/henkelmax/simple-voice-chat/issues/196#issuecomment-914975648
