### ISSUE TITLE
Simple Voice Chat, cut outs

### ISSUE THREAD

**Issue by StoraAS** [henkelmax/simple-voice-chat#289]
Hi,

This is mor a help needed request, but bug was the closest.
I´m having problem  with cut outs on my set up.
(Java 17.1, Fabrics)
I have read the Wiki, and searched for information. 
I think it might be a connection problem, we are a family playing on the same connection, and I would like to try to lower the bit rate.
However, I cant find this setting anywhere and no reference in the Wiki.

Is there anyone who can give me directions?

Thanks for a great feature!

Best regards
Stora AS

**Comment by henkelmax** [comment]
Visit the discord for help. Bug reports are the wrong place.
