### ISSUE TITLE
(PacketPlayInDifficultyChange) Error

### ISSUE THREAD

**Issue by EvaRaud** [henkelmax/simple-voice-chat#290]
Hello guys
Some players on our server can't join after moving to new hosting

log
![image](https://user-images.githubusercontent.com/92093142/137098527-8624e34d-e1b3-46a6-9644-df6d69b82c7e.png)

We see in chat that he joins but server kicks him in 1 second.

80% off all players can join easily from 1st attempt
But other 20% nope

They see that on their screen
![image](https://user-images.githubusercontent.com/92093142/137098420-d69aa59c-c8c3-47c0-b3f9-6164da70735e.png)

**Comment by henkelmax** [comment]
Please fill out the issue template correctly.
You are missing the logs and the mod/loader/minecraft versions.

Is your server running in offline mode?

**Comment by EvaRaud** [comment]
Yes
offine mode

**Comment by henkelmax** [comment]
We don't support pirating the game.

**Comment by EvaRaud** [comment]
We're using official minecraft

**Comment by henkelmax** [comment]
Then enable online mode and it will work.

**Comment by EvaRaud** [comment]
That problem is still here without offline mode

**Comment by EvaRaud** [comment]
We tried that

**Comment by henkelmax** [comment]
Then enable online mode and send me the logs and fill out the but template like already stated.
