### ISSUE TITLE
BungeeCord compatibility

### ISSUE THREAD

**Issue by teunjojo** [henkelmax/simple-voice-chat#294]
# BungeeCord compatibility
### The problem
When using a Spigot server with Simple Voice Chat it works wonderfully, but when you add Bungeecord on top off it, the voice chat stops working.

### The solution
The solution would be to make the plugin compatible with Bungeecord

### Alternative
You could also make it so that the plugin bypasses bungee.

**Comment by henkelmax** [comment]
The mod is already compatible with bungeecord and velocity. Read the wiki for more information. If you have more questions visit the discord server.
