### ISSUE TITLE
Causes Internal Server Error with Hypixel Server

### ISSUE THREAD

**Issue by NaiNonTH** [henkelmax/simple-voice-chat#296]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
It took almost forever to find the cause of this issue. So when you installed the Simple Voice Chat mod and play the Hypixel Server, It will send you to a limbo. with the Internal Server Error.

**Steps to reproduce the issue**
1. Install Simple Voice Chat
2. Launch the game
3. Join Hypixel server
4. It will send you to limbo with Internal Server Error

**Expected behavior**
After joining the Hypixel server, The game should run fine and not just send into limbo thing.

**Log files**
*no log provided*

**Versions**
- Minecraft version: 1.17.1
- Forge/Fabric version: Fabric Loader 0.11.7
- Mod version: 2.1.5

**Other mods**

![1635223654594](https://user-images.githubusercontent.com/61338902/138810601-e157e86a-a954-43f8-a582-f441a4806eab.jpg)
![1635223667332](https://user-images.githubusercontent.com/61338902/138810602-f4b4fa09-0fd8-4a5d-bc39-09fc6c152d84.jpg)

**Comment by henkelmax** [comment]
This is 100% Hypixels fault. They just send every client sending custom plugin messages to limbo.
I have no intention on fixing it, since sending plugin messages is completely within the vanilla minecraft specification.
Every minecraft server is supposed to ignore plugin messages that they don't know.

**Comment by NaiNonTH** [comment]
Ok. Maybe I'll try reporting this issue to Hypixel and see if they're going to fix this thing here

**Comment by henkelmax** [comment]
Don't get your hopes too high, they most likely did that on purpose.
