### ISSUE TITLE
Can't start Minecraft Launcher once patched on MacOS

### ISSUE THREAD

**Issue by cursefroge** [henkelmax/simple-voice-chat#297]
When patching launcher on MacOS, keychain requests are spammed.
When using the newest version of the mod, it opens a patching window to drop your Minecraft launcher. I did this, and it spammed "Minecraft wants to use your confidential information stored in "mojangTokenService" in your keychain." How do I unpatch the launcher? It appears this problem is caused by Minecraft retrieving the token from keychain, but not being trusted as the hash of the patched version dosen't match the hash of the normal version.

**Comment by cursefroge** [comment]
Also, I did try reinstalling the launcher.

**Comment by mjwells2002** [comment]
reinstalling the launcher does undo the patch but this prompt will still show as the launcher signature has changed before 

it went from
mojang signature -> unsigned 
this prompts this popup to appear the next time you load
then when you reinstalled it it went from
unsigned -> mojang signature
this prompts the popup to show again

to stop it from showing just enter your login password and click always allow
