### ISSUE TITLE
Key binding "M" collides with Xaero's Map

### ISSUE THREAD

**Issue by Brona13** [henkelmax/simple-voice-chat#299]
Problem:
Key binding "M" collides with Xaero's Map.

Possible solution:
Possibility to create own mappings, for ex. in config file.

Hi there, I'd love to use your mod as on my little server we lack voice chat. We've tried to use Discord, but sometimes it is so lagging that there is no fun in using it. Can you point me to where I can possibly change the binding?

**Comment by henkelmax** [comment]
Just rebind the key, whats the issue??

**Comment by Brona13** [comment]
Ha, never need to change this in particullar. Didn't know key bindings actually apend at the end of that list. Just did it and it works. Sorry for too easy question and thank you for kicking me in the right direction. Cheers.
