### ISSUE TITLE
Mic not working & Newer versions of the mods (2.1.6&2.1.7) crashes on startup of my minecraft (im on MacOS)

### ISSUE THREAD

**Issue by TheLasMods** [henkelmax/simple-voice-chat#302]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
So when i join with version 2.0.0 it works but my mic doesnt get detected and when i use 2.1.6 or 2.1.7 it crashes and has this message but i dont think this count as a crash (btw i use azul java bc my mac java doesnt have a java 16 and im using multimc to lauch the minecraft):

<img width="518" alt="Screenshot 2021-11-11 at 10 20 42 am" src="https://user-images.githubusercontent.com/94093827/141231396-a59bee89-f662-4635-985f-839eff36dcb7.png">

**Steps to reproduce the issue**
1. in multi mc, Go to 'Play'
2. Click on (or it will already pop up) 'Minecraft Log'
3. wait

**Expected behavior**
So i thought it would launch and goes to the minecraft window but it just crashed

**Log files**
so here's the error if u dont see the screenshot,
[10:20:31] [Render thread/INFO]: Running MacOS microphone permission check
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000181eb3f64, pid=17375, tid=259
#
# JRE version: OpenJDK Runtime Environment Zulu16.32+15-CA (16.0.2+7) (build 16.0.2+7)
# Java VM: OpenJDK 64-Bit Server VM Zulu16.32+15-CA (16.0.2+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# C  [libsystem_platform.dylib+0xf64]  _platform_strlen+0x4
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#

**Versions**
- Minecraft version 1.17.1
- Fabric version 0.12.5
- Mod version 2.0.0 (mic doesnt detect), 2.1.6 and 2.1.7 (Crash)

**Other mods**
So i fixed a bit of the mods by turning off native minecraft ( performance boost for my m1 mac) and turning off opti fabric and optifine

**Screenshots (Optional)**
The only screenshot is on bug description.

note: i havent tried it in the plugins yet so idk if it does the same or not

**Comment by henkelmax** [comment]
Are you using the vanilla minecraft launcher or are you using another launcher?
Are you using any third party software to make it work on M1?
Is it working with 2.1.5?

**Comment by greener-dot-ca** [comment]
For users on M1 using the native lwjgl wrapper script in MultiMC, with 1.17.1-2.1.8 and disabling the microphone workaround in the config, launching the instance via command line using MultiMC's `--launch <instance>` flag will get Terminal to request microphone access. It's a lot of hoops, but it works.
