### ISSUE TITLE
MY LAUNCHER IS GONE

### ISSUE THREAD

**Issue by ToxicAesthetic** [henkelmax/simple-voice-chat#303]
Hello, im writing this cause i tried out the mod, and i know it said that use at your own risk, but i love this mod so much, is there any way to fix the signature on mac? please please please help me out, im having a horrible panic moment right now

**Comment by ToxicAesthetic** [comment]
Quick more info, i downloaded the launcher twice and redid it, but i logged back in and it did not open the microsoft login

**Comment by henkelmax** [comment]
Please fill out the bug template.
