### ISSUE TITLE
Crowdin for localisation & licence-related questions

### ISSUE THREAD

**Issue by brawaru** [henkelmax/simple-voice-chat#304]
**Is your feature request related to a problem? Please describe.**

Localisation / internalisation is an important aspect of software development. It allows more people to enjoy your creation without need to learn unfamiliar languages. I find your mod absolutely amazing and it certainly deserves more attention! I see that you made the mod localisable, but to do so you have to create pull requests. This approach makes it difficult to really collaborate and effectively proofread translations, plus sets a huge barrier for people willing to contribute back, since it requires getting familiar with Git and JSON file format.

**Describe the solution you'd like**

Frankly, it doesn't have to be this way! Since your project is _almost_ open source, you can set up an integration with Crowdin — (alert! alert! one's opinion ahead) one of the best collaboration tools for localisation, used successfully by [Hypixel](https://crowdin.com/project/hypixel), [Mojang](https://crowdin.com/project/minecraft), [NameMC](https://namemc.com/) and [many others](https://crowdin.com/projects).

Crowdin supports free and open source software and provides free of charge licences [on request](https://crowdin.com/page/open-source-project-setup-request), but they have a few requirements, so let's see how well this project fits them:

- ❕ **You have created a translation project in Crowdin.**
  You will need to create a project on Crowdin, this will give you insight on how things done and allow to set up everything beforehand.
- ❌ **The project is licensed under an approved license from an open-source initiative**.
  This project is missing a LICENSE file with appropriate OSI-approved licence.
  Mod has ‘All Rights Reserved’ licence on CurseForge, which is not an appropriate licence.
  You might be able to re-licence the code, however contributors weren't required to sign CLA granting you the right to change the licence, so you will need to contact them and get their agreement.
- ✅ **Your project's source code is publicly available for download.**
  Everyone can access the code here on GitHub.
- ✅ **You do not have any commercial products related to the open-source project you are requesting a license for.**
  I didn't find any paid features, and donations do not count towards it.
- ❔ **You are the project lead.**
  Person creating a project on Crowdin and sending a request needs to be project lead.
- ✅ **You have been working on your open-source project for at least three months.**
  This project was created a year ago with first commit dating [10 June 2020](https://github.com/henkelmax/simple-voice-chat/commit/74f9e6d45f0350514289b2d958f45acd44d2f390).
- ✅ **You have an active community of collaborators.**
  At least 6 people contributed to this project [according to GitHub](https://github.com/henkelmax/simple-voice-chat/graphs/contributors).
- ✅ **You keep the "News" section of your website up to date.**
  The project does not have a site, but all documentations and changelogs are up-to-date.
- ✅ **You release updated builds on a regular basis.**
  Up-to-date mod downloads are available on CurseForge.

Asides from licence there are really no problems with receiving free access from Crowdin. I'm not sure if you have any reasons to keep this project All Rights Reserved while providing access to source code and assets, but if that's because you don't want others to simply fork your project, then close source and pretend it's their mod, you might opt into a less-permissive licence that forbids sublicensing and requires source code to be open, e.g. LGPL; however if that's not an issue you can go with permissive licences like MIT. This also will give contributors some peace of mind that they're contributing their code into a good cause.

The integration itself is quite smooth (from personal experience): you can either pull translations manually using the CLI tool, or better, make Crowdin continuously compose pull requests with new translations. You will be able to set up file name appropriately and import existing translations, reports will give you ability to credit people who contributed to the project. They even have a badge to embed in readme. Neat!

**Describe alternatives you've considered**

- Using Weblate instead: requires self-hosting and has awful user experience, which will turn away potential contributors.
- Using Transifex instead: has similar licence requirements as Crowdin, provides poor-er UX, which can turn away potential contributors.
- Not using anything: has problems described in the first paragraph; that is: huge entry barrier, difficult collaboration.

**Additional context**

× not applicable.

_P.S. That sounds like some kind of advertisement, but I'm not affiliated with Crowdin in any way and just advocating for crowdsourced localisations in software and found it to be the most amazing tool for it :D_

**Comment by henkelmax** [comment]
I already stated why this project does not have an open source license (https://github.com/henkelmax/simple-voice-chat/issues/196#issuecomment-914975648).
If people want to translate it, they can create a pull request. But I will not change the license just because of crowdin.

**Comment by brawaru** [comment]
Whoops, my bad for not looking up the licence issue, sorry. Regards Crowdin — welp, that's unfortunate. As a translator I find it irritating to have to edit raw JSON/YAML files for translations and submitting them via patches. But well, your project — your rules, somebody will align to them, and in fact [already did for Russian](https://github.com/henkelmax/simple-voice-chat/blob/1.17.1/common/src/main/resources/assets/voicechat/lang/ru_ru.json), though I already see some issues in it. Thanks for your time.
