### ISSUE TITLE
Not working when bundled with FastLogin

### ISSUE THREAD

**Issue by Zjaun** [henkelmax/simple-voice-chat#305]
**Bug description**

The mod doesn't work well when bundled with FastLogin Plugin in servers. Removing FastLogin will restore things back to normal.

**Steps to reproduce the issue**
1. Install both ProtocolLib and SimpleVoiceChat in your server
2. Works fine
3. Install FastLogin
4. Error

**Expected behavior**
Will work perfectly fine.

**Versions**

Minecraft Version: 1.17.1
Fabric Version: 0.11.7-1.17.1
Mod version: 2.1.10

**Other mods**
1. FastLogin

**Comment by henkelmax** [comment]
This has already been fixed in 2.1.11:
https://www.curseforge.com/minecraft/bukkit-plugins/simple-voice-chat/files/3527532
