### ISSUE TITLE
Are you considering adapting to cross-version group servers?

### ISSUE THREAD

**Issue by XiaoHuiHui233** [henkelmax/simple-voice-chat#307]
This mod is awesome, and it works very well on our server. But our servers are group servers, and there are multiple servers of different mc versions. So a problem arises. Since this mod will forcefully kick out the player with incompatible mod version, when the player switches to a different mc version of the server, he must restart the game and switch the client version, which is very inconvenient.
A solution that is not elegant at all but available is to not install this mod on both versions of the client. But this is putting the cart before the horse, and we can't get the convenience brought by the mod. We tested that this mod works well between group servers of the same mc version. We have also noticed that the compatibility relationship between different mod versions is declared in the introduction of the mod. Is it possible to provide mods with the same version for different mc versions to support direct compatibility in cross-server environments?
There is another tiny problem. In group servers, a more efficient voice service approach is to use a centralized (or distributed, but that is more troublesome) Client/Server model. Only one server can serve multiple compatible versions of clients. Compared with the current setting of a mod server for each mc server, this can reduce the resource occupation of the server. Although this is not a serious or urgent problem, the current resource usage of the mod is minimal. So I’m here to start a discussion. Is there a better solution that can elegantly solve the compatibility problem and improve the efficiency of the service at the same time?
Look forward to your reply. Thanks.

**Comment by henkelmax** [comment]
It seems that you are using an outdated versions. You won't get kicked with an incompatible client anymore.

Cross version compatibility is theoretically a thing, but the 1.16.5 version is not under development anymore, so it will only work on 1.17+

**Comment by XiaoHuiHui233** [comment]
So if my group server contains 1.16.5 and 1.17.1, 1.16.5 will not have the ability to cross versions, but 1.17.1 has this ability, even if there is a 1.18 server in the future, it will be compatible at that time?

**Comment by henkelmax** [comment]
Technically yes, but I won't promise anything.

**Comment by XiaoHuiHui233** [comment]
So is there some possibility to put the latest version of the code in the past version (such as 1.16.5) for manual compilation, and then the generated mod can successfully interact with the latest cross-version mod. What I mean is that if the mod itself does not modify the original features, is such a modification possible?

**Comment by henkelmax** [comment]
Nope, I dropped 1.16.5, since it doesn't work with the new project structure and build toolchain of version 2.x.x.

**Comment by XiaoHuiHui233** [comment]
It seems that this is not good news for our 1.16.5 players, but thank you very much for your answers.

**Comment by henkelmax** [comment]
No problems. If you have more questions about the technical stuff, you can visit the Discord server.
