### ISSUE TITLE
Console Warning Spam

### ISSUE THREAD

**Issue by Pinkhron** [henkelmax/simple-voice-chat#310]
**Bug description**
When I start up the server it starts spitting out this warning "[voicechat] Failed to read packet from [server ip]" every ~30 seconds. The plugin still works, but I want this warning to stop flooding my console.

**Steps to reproduce the issue**
1. Start the server up

**Log files**
[WARNING]  [voicechat] Failed to read packet from /[server ip] (Sends over and over)

**Versions**
- 1.17.1
- Fabric version
- 2.1.0

**Other mods**
ServerListPlus, ProtocolLib

**Comment by henkelmax** [comment]
This is completely intended. There is traffic arriving at your server from another application. Please change your port or find out what is causing this.
