### ISSUE TITLE
Separate Speaker Off icon for GUI and Display Name uses.

### ISSUE THREAD

**Issue by yurisuika** [henkelmax/simple-voice-chat#311]
It would be nice if you could have different textures be used for these two cases. No other icons are used in two different situations like this (perhaps the Disconnected is as well; I have not experienced it and have not checked the code).

In my use case in particular, I make the display name look like it is some Unicode symbol extension of the username string with a 25% black transparent background with the off-white iconography. This of course results in the Speaker/Whisper GUI needing to be styled the same if I want consistency, while I could have some more fitting designs to the other parts of the GUI than just solid black and off-white if there were more textures.

**Comment by henkelmax** [comment]
Can you please explain which cases you mean?

**Comment by yurisuika** [comment]
The file being speaker_off.png which is shown in two different places; one being next to the display name of the character when the player has their voice chat disabled, and the other being shown in the lower left corner when you have your own voice chat disabled.

**Comment by henkelmax** [comment]
If I would change that, all existing resource packs would break. It is also not nice having the same texture twice.
I could add an event to the voice chat API to hide these icons.

**Comment by yurisuika** [comment]
It would give more flexibility to resource packs, though. Just because you may desire the same icon being used in two different situations does not mean it fits the stylization of various resource packs. One is on a player's nameplate hovering over them, the other pops up statically in the HUD. In what I am to achieve, making the nameplate appear as though it is not an image but rather a text extension of the player's name, forcing one texture in these two different situations does not provide the results of having a decent looking GUI, and I would wager that the majority of resource pack creators would take this flexibility over potentially having two similar textures any day of the week.

As for breaking resource packs, I noticed the mod changed and added GUI textures and added new icon textures when I updated it from what I last used on 1.16 to 1.18. It was no problem, I simply changed whatever textures were required and added new ones. What I am proposing is the addition of a single texture, which is a far cry from the amount of aforementioned work. I am certain this would be a welcomed addition for any resource pack creator.

Having buttons to toggle the GUI elements denotes a choice by the player who does not necessarily want icons to be hidden. I want to be able to provide the best experience to the user if they so desire to let all of the GUI be shown. So let the burden be on the resource pack creator to grudgingly come up with another 256 pixels. If you think that most will just want it to look the same, well then they have to copy-paste and change the file name, which is less work than Peter Gibbons does in a day. It isn't as though we don't add all kinds of textures and models every time a Minecraft update comes out or we find a new mod that we want to play with. Seriously, don't worry about it; we will be fine. It will make us happy!
