### ISSUE TITLE
Compatibility for sound physics mods

### ISSUE THREAD

**Issue by EysseW** [henkelmax/simple-voice-chat#313]
I think it would be great to have compatibility with sound physics mods like 
[https://www.curseforge.com/minecraft/mc-mods/sound-physics-fabric](url) or [https://www.curseforge.com/minecraft/mc-mods/dynamic-sound-filters](url) or [https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings](url)
I mean, just imagine being in a cave with somebody and hearing his voice echo around it or hear people worse when their behind a wall. This last example would work great in things like [https://last-life-smp.fandom.com/wiki/Last_Life](url) . It makes personal conversations way more emmersive.

**Comment by henkelmax** [comment]
There already is compatibility

**Comment by EysseW** [comment]
> There already is compatibility
Mod compatibilty, but the sound physics aren't used on the voice chat sounds, right? If so, please tell me how to set it up!

**Comment by henkelmax** [comment]
Of course it is. It just works.

**Comment by EysseW** [comment]
you guys are fucking amazing. Thanks!
