### ISSUE TITLE
Friends cannot hear me while using Simple Voice Chat

### ISSUE THREAD

**Issue by Treetalk1** [henkelmax/simple-voice-chat#317]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Friends cannot hear me while using Simple Voice Chat, but I can hear them.

**Steps to reproduce the issue**
1. Attempt to speak
2. Friends will not hear you
3. You can hear them.
4. When you check the mod options, and test the mic, the green bar flashes.

**Expected behavior**
My friends can hear me when I speak through the mic.

**Log files**
https://gist.github.com/Treetalk1/15ebfff8b1c83b19b0537e9d70150b6d

**Versions**
- Minecraft version 1.18
- Fabric 0.12.8-1.18
- voicechat-frabric-1.18-2.1.17.jar
**Other mods**
Fabric Mod Menu
OptiFabric
Optifine
Xaeros Minimap
Fabric API

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
I think that's not a bug. It is most likely something that's not configured correctly.
Please join the discord for help.
