### ISSUE TITLE
Still getting the "Voice chat unavailable" message 

### ISSUE THREAD

**Issue by Cloudknight419** [henkelmax/simple-voice-chat#318]
**Bug description**
The Voice chat unavailable and crossed out plug sign icon on fabric
with Aternos

**Steps to reproduce the issue**
1. Download 'Mod version 1.10.0 for fabric'
2. Set up 'Port etc as on the wiki'
3. Enter server
4. Press keybound button 'Voice chat unavailable'

**Expected behavior**
All of my other friends voice chat is working mine is the only one not working
so I expected it to work
**Log files**

[16:39:17] [User Authenticator #10/INFO]: UUID of player 2michaelrocks is 0604189c-fd3e-4714-a5d3-8a7073fc57e1
--
253 | [16:39:18] [Server thread/INFO]: 2michaelrocks[/172.58.88.52:41888] logged in with entity id 2887 at (881.7624999880791, 63.0, 295.34745693738415)
254 | [16:39:18] [Server thread/INFO]: 2michaelrocks joined the game
255 | [16:39:18] [Netty Epoll Server IO #0/INFO]: Received secret request of 2michaelrocks
256 | [16:39:18] [Netty Epoll Server IO #0/INFO]: Sent secret to 2michaelrocks
257 | [16:39:32] [User Authenticator #11/INFO]: UUID of player MR_MR_CORNDOG is abb710ad-84b9-4659-a262-585497e4121d
258 | [16:39:32] [Server thread/INFO]: MR_MR_CORNDOG[/108.39.125.169:61641] logged in with entity id 2992 at (1015.7459939925392, 64.0, 230.05235162658903)
259 | [16:39:32] [Server thread/INFO]: MR_MR_CORNDOG joined the game
260 | [16:39:36] [Netty Epoll Server IO #2/INFO]: Received secret request of MR_MR_CORNDOG
261 | [16:39:36] [Netty Epoll Server IO #2/INFO]: Sent secret to MR_MR_CORNDOG
262 | [16:39:45] [VoiceChatPacketProcessingThread/INFO]: Successfully authenticated player abb710ad-84b9-4659-a262-585497e4121d

**Versions**
- Minecraft 1.16.5
- Fabric 0.42.0+1.16
- Mod version 1.10.0

**Other mods**
Curseforge modpack file
[Origins-1.3.zip](https://github.com/henkelmax/simple-voice-chat/files/7657289/Origins-1.3.zip)

**Comment by henkelmax** [comment]
This is not a bug. Visit the discord if you want help setting it up.
