### ISSUE TITLE
[Bukkit] Add a "help" command

### ISSUE THREAD

**Issue by rhystedstone** [henkelmax/simple-voice-chat#319]
**Is your feature request related to a problem? Please describe.**
It's almost impossible to guess what subcommands have been made for SimpleVoiceChat - all you receive is "Invalid command syntax".

**Describe the solution you'd like**
A `/voicechat help` subcommand would allow anyone to see valid subcommands and syntax, rather than an unhelpful message.

**Describe alternatives you've considered**
A possible alternative is to improve the unhelpful message with the correct syntax, or an "Unknown Subcommand" message at least.

**Additional context**
I think the `plugin.yml` file may be incomplete:
![image](https://user-images.githubusercontent.com/12123847/144938342-3ad3243f-38b0-4db5-9597-495456f4d0e6.png)

**Comment by henkelmax** [comment]
Please read the wiki for commands.
But I won't add any other commands to bukkit, since it is a pain to do with the bukkit API.
