### ISSUE TITLE
Nothing working, but it says it should.

### ISSUE THREAD

**Issue by groovyshrimp** [henkelmax/simple-voice-chat#32]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Everything I've treid, I can't be heard in-game or hear people. My input/output is fine, the mic test works perfectly, but I can't hear or speak to people.

**Steps to reproduce the issue**
I don't know, it just happened.

**Expected behavior**
To be easily heard and to hear people in-game.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).
I can't get the logs, the owner of the server is away.
**Versions**
- Minecraft version - 1.16.4
- Forge version - 1.16.4-35.1.37
- Mod version - 1.16.4-1.1.3

**Other mods**
Oh The Biomes You'll Go - 1.1.6
Create - v0.3e
FastLeafDecay - v22.1
Just Enough Items - 7.6.1.65
Morpheus - 4.2.68
OptiFine - HD U G6
Better Spiders - 2.0 - 1.0.4
TravelersBackpack - 5.3.8
Xaeros Minimap - 21.0.0
**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please use the provided issue template and read the wiki.

**Comment by snowclimb** [comment]
The troubleshooting says "You can test if it works by clicking the Enable microphone testing button." and when they are testing it works fine. But when they try speaking it doesn't work

**Comment by henkelmax** [comment]
Have you read the wiki?

**Comment by snowclimb** [comment]
https://modrepo.de/minecraft/voicechat/wiki ?

**Comment by henkelmax** [comment]
Exactly

**Comment by snowclimb** [comment]
![image](https://user-images.githubusercontent.com/52582114/105540907-e7735800-5cee-11eb-94f0-c3df178074e9.png)
When they click this button they hear their input working. But when they actually try to talk to us in-game it just doesn't work. It's most likely something wrong with their connection to us as we have heard them in small amounts, 
Is it a possibility to use the "/voicechat test <PLAYERNAME>" you did for that other version on 1.16.4 or should that work

**Comment by snowclimb** [comment]
We are using 1.1.3 for 1.16.4 btw

**Comment by henkelmax** [comment]
As I already said. I can't help you if you don't fill out the bug template. Make sure your logs include the client and the server side and also the test command.

**Comment by snowclimb** [comment]
I believe they are working on that, Thanks for responding quickly by the way.

**Comment by henkelmax** [comment]
Without the logs I can't help you. If you can't get the server logs, at least send me your client logs.

**Comment by henkelmax** [comment]
Closed due to inactivity
