### ISSUE TITLE
MacOS Patcher support for ATLauncher

### ISSUE THREAD

**Issue by GhostIsBeHere** [henkelmax/simple-voice-chat#321]
**Is your feature request related to a problem? Please describe.**
I am attempting to patch ATLauncher on MacOS with the built-in patcher, but I'm unsure of how to use it.

**Describe the solution you'd like**
Provide instructions for patching ATLauncher

**Describe alternatives you've considered**
Add a disclaimer that ATLauncher cannot be patched

**Additional context**
I attempted to patch ATLauncher by following the CurseForge instructions, but there was no Minecraft application in the ATLauncher folder. I then just tried dragging the ATLauncher application onto the patcher and restarting, but to no effect

**Comment by henkelmax** [comment]
It should work as every other launcher. If it doesn't I don't know how to patch it either. And I don't own a mac.

**Comment by GhostIsBeHere** [comment]
I can probably just use MultiMC. Thanks anyways!

**Comment by henkelmax** [comment]
> I can probably just use MultiMC. Thanks anyways!

Yeah I would recommend using multimc anyways.
