### ISSUE TITLE
not a bug need help

### ISSUE THREAD

**Issue by stormer2019** [henkelmax/simple-voice-chat#322]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
there was no option for not getting it to work so here i am.

**Steps to reproduce the issue**
dont know how the port opening workfs oon mcprohosting with this mod. doesnt seem to work.

**Expected behavior**
cant connect

**Log files**
-

**Versions**
1.18

**Other mods**
fabric.lib

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please visit the discord if you need help. This is the wrong place.

**Comment by stormer2019** [comment]
dicord told me to hopen something here first
.....
great

**Comment by henkelmax** [comment]
> dicord told me to hopen something here first ..... great

What?
