### ISSUE TITLE
Sound physics remastered works with simple voice chat EVEN beter

### ISSUE THREAD

**Issue by EysseW** [henkelmax/simple-voice-chat#323]
I really love the fact I can hear my friend echo in caves and realisticly and stuff, but could you guys add the feature to be able to hear yourself echo and such as well? I think it would really add to the emmersiveness.

**Comment by henkelmax** [comment]
This is not possible without major modifications. It would also be really annoying having a delay in your own sound. I Really don't think anyone would use this practically.
