### ISSUE TITLE
1.16.5-1.7.8 caused issues with server

### ISSUE THREAD

**Issue by Dr3mmy** [henkelmax/simple-voice-chat#326]
We added the 1.16.5-1.7.8 jar to my Vault Hunters mod and the server wouldn't connect.
Admin removed the mod and was able to show the server connected in the server list screen.
I removed it from my instance folder and also was able to reconnect to the server.

**Comment by henkelmax** [comment]
1. Fill out the bug template
2. Did you read the wiki?
3. If you are just not able to connect to the voicechat, this isn't a bug. Visit the discord if you need help.

**Comment by Dr3mmy** [comment]
It wasn’t that we couldn’t connect to voice chat, the jar was not allowing us to connect to the server. 

We literally could not get on the server until the jar was removed from the mods list.

**Comment by henkelmax** [comment]
Most likely, because the mod was not installed on all clients.

**Comment by Dr3mmy** [comment]
It was on the server and client side for myself and at least one other person and neither of us could see the server be able to connect. 

I’ll try the next older version and see if that one works.
