### ISSUE TITLE
Dynamic Surroundings Sound Processing Support

### ISSUE THREAD

**Issue by Khodyn** [henkelmax/simple-voice-chat#327]
There's a [fully functional PR porting Dynamic Surroundings to 1.18.x here, which I actively use.](https://github.com/OreCruncher/DynamicSurroundingsFabric/pull/14) This mod doesn't seem to get the enhanced sound processing, presumably on the 1.17 version as well.

**Comment by henkelmax** [comment]
Simple Voice Chat only has support for sound physics.
