### ISSUE TITLE
Visual bug in groups interface

### ISSUE THREAD

**Issue by alejamt00** [henkelmax/simple-voice-chat#329]
**Bug description**
Idk why but when I'm on my server, groups members are not shown in the list:
Idk if I'm doing something wrong or what but the voice chat works fine, just this visual bug :s

**Steps to reproduce the issue**
1. Go multiplayer on a server with the mod installed and the port opened
2. Create a group
3. It works but the interface looks like this:
![image](https://user-images.githubusercontent.com/74151787/146099660-c41709ea-630e-466f-81f3-c3190a61fe82.png)

**Expected behavior**
When it should look like this:
![image](https://user-images.githubusercontent.com/74151787/146099815-18f3a6e7-9333-44cc-872b-5f93c84c9a37.png)
(In singleplayer looks fine)

**Versions**
- 1.18
- fabric-api-0.44.0+1.18
- voicechat-fabric-1.18-2.1.17

**Comment by henkelmax** [comment]
I need your logs.

**Comment by alejamt00** [comment]
Server log:
https://gist.github.com/alejamt00/e43acbde3df5e59d3d2b2c1603a7801e
My log:
https://gist.github.com/alejamt00/dcfe7a8767782b931946065ff0a470c8

**Comment by henkelmax** [comment]
Can you test if this happens without any other mods installed?

**Comment by alejamt00** [comment]
Ok, i will try that this afternoon :)

**Comment by alejamt00** [comment]
Em... I just tried it on a local server, just the voicechat mod and it looks fine. Then i tried a local server with the exact same mods i have on the other server and it looks fine too :s Maybe it is a server.pro bug? On server.pro the voice chat works fine but looks like the screenshot i posted before :ss 
Anyway, sorry for bothering you, ill try asking server.pro customer service :(

**Comment by ux92** [comment]
@alejamt00 Hi! Did you ever solve this issue? We're facing the same problem and we don't know where to look.

**Comment by henkelmax** [comment]
This seems to only happen for cracked (offline mode) servers (which we don't support).
If you are encountering this issue with an online mode server, let me know.

**Comment by henkelmax** [comment]
@alejamt00 @ux92 

It seems that this issue was also affecting some BungeeCord setups without offline mode, so we went ahead and fixed it.

You can find the new version in the `#beta-testing` channel of the Discord.
