### ISSUE TITLE
How do you open the voice chat port .

### ISSUE THREAD

**Issue by tr4e5uytdturdiyrdyitfuyru7yrfvt65ev6dev** [henkelmax/simple-voice-chat#33]
how do you open the voice chat port, me and my friends have been trying for bout an hour now.

**Comment by tr4e5uytdturdiyrdyitfuyru7yrfvt65ev6dev** [comment]
no

**Comment by henkelmax** [comment]
Cited from the FAQ:

> If you are hosting a server you should know that. I am not tech support. Ask your server hoster or use the internet to search for a solution.
