### ISSUE TITLE
Unavailable if no valid UUID

### ISSUE THREAD

**Issue by rex706** [henkelmax/simple-voice-chat#330]
**Bug description**
I run a server with custom database authentication that does not use Microsoft/Mojang auth (offline mode). Joining the server in this fashion does not allow voice chat to initialize and the plug with the red line through shows in the bottom left. If the server is joined with the normal Minecraft launcher with normal authentication the mod works as expected. This seems to be caused by an inability to process the player's UUID (see log below), which may not exist in this case.

Edit: running the custom launcher or Java process as Admin does not resolve the issue.

**Steps to reproduce the issue**
Launch Minecraft client without official Microsoft/Mojang authentication, join server running with property `online-mode=false` and notice Voice Chat does not initialize.

**Expected behavior**
Ideally, the mod should not need any official authentication info to work correctly as this was the case last time I used this mod in 1.16.5 earlier this year. 

**Log files**
Client Log when joining the server:
`[16:39:09] [VoiceChatConnectionThread/INFO]: Server acknowledged authentication`
`[16:39:09] [VoiceChatConnectionThread/ERROR]: Failed to process packet from server: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "p_130078_" is null`

**Versions**
- 1.18.1
- 39.0.5
- 2.1.22

**Comment by henkelmax** [comment]
Simple voice chat heavily relies on the players real UUID.
We do not support pirating the game in any way.
There will never be a fix for this, because it only affects people pirating the game.

**Comment by henkelmax** [comment]
We fixed another issue that was related with UUIDs. So this might also fix your issue. I'm still in no way supporting pirating the game, so if it didn't fix the issue I won't actively try to fix it.

You can find the new version in the `#beta-testing` channel of the Discord.
