### ISSUE TITLE
hearing your own voice playback

### ISSUE THREAD

**Issue by LittleEnvie** [henkelmax/simple-voice-chat#333]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
My friend hears his voice with 1s delay after he speaks based on my position and my player' rotation. I won't see him for 2 weeks so I can't really tell how to reproduce the issue and if it's something related to his laptop or smth. I just want to know if it's something that has been here already? I'm gonna create a new thread following this one when he gets back if the issue still exists. As far as we know he still could hear his voice when he quit discord and it was always based on caps lock.

**Steps to reproduce the issue**

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.18.1
- Forge/Fabric version  39.0.5
- Mod version 1.18.1-2.1.22

**Other mods**
In the screenshot if it was attached properly

**Screenshots (Optional)**
Screenshots of the issue.
![image](https://user-images.githubusercontent.com/96439606/146809525-e9f709c7-e3df-48d3-8735-be6d4520b8e8.png)

**Comment by henkelmax** [comment]
Please fill out the complete bug template including logs and steps to reproduce.
Also remove all other mods and check if it still happens.
Make sure to select the correct microphone in the settings.
If you are creating another bug report, please also include the list of audio devices of your PC.
