### ISSUE TITLE
Mic recognized but not producing sound

### ISSUE THREAD

**Issue by Embro674** [henkelmax/simple-voice-chat#339]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Im playing with the latest version of simple-voice-chat and whenever I talk with my mic, it cant hear me...like no sound it produced. The mic itself works, I use it for discord as I am typing this, and I know the mod itself works as I have another mic that works.

**Steps to reproduce the issue**
 1.join a configured server
 2.open the voice menu
 3.press the voice test button
 4.see that test hasn't worked

**Expected behavior**
Me to be able to hear my own voice when testing the mic in the menu

**Log files**
N/A

**Versions**
- 1.18.1
- 0.45.0+1.18 (Fabric)
- 1.18.1-2.1.28

**Other mods**
Fabric API

**Comment by henkelmax** [comment]
This is not a bug. Visit the discord if you need help.
