### ISSUE TITLE
Unavailable if main menu is skipped

### ISSUE THREAD

**Issue by rex706** [henkelmax/simple-voice-chat#34]
**Bug description**
Voice chat is unavailable when the main menu is skipped by launching client Minecraft jar with `--server <server>` and `--port <port>` arguments. Leaving the server and joining back then allows voice chat to work as expected.

**Steps to reproduce the issue**
1. Join server running Simple Voice Chat by skipping main menu with `--server <server>` and `--port <port>` client minecraft jar launch arguments.
2. Use any voice chat related button to view "Unavailable" message.
3. Leave server. (Can stay in server selection screen)
4. Join back to the same server joined previously and notice voice chat now works.

**Expected behavior**
Simple Voice Chat should initialize and work even if Minecraft main menu is skipped by utilizing `--server <server>` and `--port <port>` client jar launch arguments.

**Versions**
- 1.16.5, 1.16.4
- 1.16.5 - 36.0.1, 1.16.4 - 35.1.37
- 1.16.5-1.0.0, 1.16.4-1.1.3

Great work on this mod. Best proximity voice chat solution I've ever seen and used.

**Comment by henkelmax** [comment]
Let me know if it works for you.

**Comment by rex706** [comment]
Works perfectly. Thank you for the quick fix! Very much appreciated for this.

**Comment by henkelmax** [comment]
No problem!
