### ISSUE TITLE
Using UUID in commands is not possible

### ISSUE THREAD

**Issue by kruthers** [henkelmax/simple-voice-chat#340]
**Bug description**
Where the group management commands have been updated to use a uuid there is no way to get the uuid and the invite command, click compleation uses the name not the uuid.

There does not either seam to be a way to get the uuid of a group, it would be best if they used names to allow for easy use.

**Steps to reproduce the issue**
1. Create a group with any name
2. Get a 2nd person on the server
3. Run /voicechat invite <2nd user>
4. When the 2nd user trys to click on it to join it does not work

**Expected behavior**
When using the /group join command or clicking the link to be able to join groups

**Versions**
- Minecraft version: 1.18.1
- Forge/Fabric version: Fabric 0.12.11-1.18.1
- Mod version: 1.18.1-2.1.23

**Other mods**
Was tested with just the mod

**Comment by henkelmax** [comment]
UUIDs work now, but @ selectors will never work in bukkit.

**Comment by kruthers** [comment]
This has fixed the invite command but the join command still does not work as your not able to get a group name or use it in commands (it would be best if you could for automation in commands).

**Comment by henkelmax** [comment]
The join command is used exclusively to accept invites. There is only the UUID option for that command, since the group name is not unique.
