### ISSUE TITLE
Audio Device Name c

### ISSUE THREAD

**Issue by BowTieDaniels** [henkelmax/simple-voice-chat#341]
**Bug description**

When selecting the audio devices for the microphone and speakers, the full names of certain audio devices are not displayed. This does not appear to be an issue with name length since several of the impacted devices have a shorter name than others that do display correctly. For some reason the name have the beginning cut off and only the end is shown making it impossible to select the correct device in some situations.

**Steps to reproduce the issue**

1. Press 'V' to open Voice Chat menu.
2. Click on 'Settings' button.
3. Click on 'Select microphone' or 'Select speaker' button.
4. Use 'Previous' and 'Next' button to view available devices.
5.  Device names are cut off.

**Expected behavior**

When viewing device names, I would expect to see the full name, not the last word of it. At the very least I would expect to see the beginning of the name which would allow me to correctly identify the device I want to select.

**Versions**

- Minecraft version 1.18.1
- Fabric Loader 0.12.12
- Fabric API 0.45.0+1.18
- Simple Voice Chat 1.18.1-2.1.28

**Other mods**

Problem occurred with my full mod list as well as just the basics listed under Versions.

**Screenshots**

Microphone name getting cut off. Name should be `Chat Mic (TC-Helicon GoXLR)`  Length - 27 characters
![image](https://user-images.githubusercontent.com/36642261/147769858-ae452018-3e28-47e4-a9c6-4d593257877e.png)

Speaker name getting cut off. Name should be `Chat (TC-Helicon GoXLR)` Length - 23 characters
![image](https://user-images.githubusercontent.com/36642261/147769705-0e918399-1a48-472b-9884-34d86225e1b6.png)

Example showing this is not limited to the GoXLR devices. Name should be `GNV34DB (NVIDIA High Definition Audio)` Length - 38 characters
![image](https://user-images.githubusercontent.com/36642261/147771290-8af4eb94-53c6-4771-839b-2eedee6a1095.png)

Example of device with longer name displaying correctly Length - 41 characters
![image](https://user-images.githubusercontent.com/36642261/147771380-1bd3427c-3154-4ced-bdcd-7f86dca70c20.png)

**Comment by henkelmax** [comment]
Are the device names the same when selecting them in the vanilla minecraft audio settings?

**Comment by BowTieDaniels** [comment]
The full device names appear in the vanilla sound options. Screenshots for verification.

![image](https://user-images.githubusercontent.com/36642261/147774321-30755c27-5f47-4407-a727-fc75e645b4d8.png)

![image](https://user-images.githubusercontent.com/36642261/147774336-be52bc95-7a71-4f3f-958b-20d9805956ea.png)
