### ISSUE TITLE
There is no command guide on the wiki

### ISSUE THREAD

**Issue by rhystedstone** [henkelmax/simple-voice-chat#342]
## Bug description
There is no mention of commands on the wiki.

Related to #319

## Screenshots (Optional)
No mention in the Wiki
![image](https://user-images.githubusercontent.com/12123847/147788291-c7cf6e50-442a-46e5-aa7f-89e64e4665b3.png)

Or FAQ:
![image](https://user-images.githubusercontent.com/12123847/147788322-c0935389-014c-4fee-b984-8e7c2ffc06f8.png)

Original comment:
![image](https://user-images.githubusercontent.com/12123847/147788219-80694b31-3870-4d16-a272-4b0f6833fda3.png)

**Comment by henkelmax** [comment]
The only officialy documented command is the test command. It is documented in the wiki.
All other commands are not official/subject to change.

**Comment by henkelmax** [comment]
This bug tracker is also only meant for the mod itself and not the documentation.
