### ISSUE TITLE
Proxy Chat will not connect on BungeeCord Server

### ISSUE THREAD

**Issue by arizotaz** [henkelmax/simple-voice-chat#343]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
When running the plugin on a server connected by the bungeecord server proxy, I keep getting an error that the plugin could not read the clients traffic.  I saw that a reply on the spigotmc page stated that you need to pass the voice chat traffic through the proxy.  Though how could this be done?  I tried a few thing to no avail.

**Comment by henkelmax** [comment]
If you want help setting up voicechat, visit the discord.
You should also try the latest beta version in the #beta-testing channel.
