### ISSUE TITLE
Without UDP support.

### ISSUE THREAD

**Issue by SirObby** [henkelmax/simple-voice-chat#345]
**Is your feature request related to a problem? Please describe.**
I have a problem, I'm tunneling the server via ngrok, but it doesn't support tunneling UDP.

**Describe the solution you'd like**
A sort of backend server for simple-voice-chat or something, that has the voice server so no UDP port is required.

**Describe alternatives you've considered**
Finding another tunneling system.

**Additional context**
Yes, I know this would probably cost money to host the server, but you can probably take in donations.

**Comment by henkelmax** [comment]
You don't need a tunneling software. Just open the port in your network. There is really no reason to do that. There are also alternatives like playit.gg or hamachi.

**Comment by SirObby** [comment]
I don't have portforwarding on my router.

**Comment by henkelmax** [comment]
> There are also alternatives like playit.gg or hamachi.

**Comment by SirObby** [comment]
I don't think those alternatives work for me,
we're just gonna stick to Discord VC chats.

**Comment by thecoder08** [comment]
> There are also alternatives like playit.gg or hamachi.

playIt doesnt allow for forwarding arbitrary ports to the same address as the minecraft server.

Hamachi requires all clients to download a piece of software on their computer.
