### ISSUE TITLE
Unexpected error messages when restarting/stopping Paper server

### ISSUE THREAD

**Issue by SleepyCatten** [henkelmax/simple-voice-chat#346]
**Bug description**
The plugin seems to be encountering a bug on restarting/stopping a server.

**Steps to reproduce the issue**
1. Set up a Paper MC server (version 133 was used in this case).
2. Use voicechat-bukkit-1.18.1-2.2.1
3. Start up the server and let it fully load.
4. Restart or stop server, then check the log/console.

**Expected behavior**
No error messages.

**Log files**
Here is the relevant part of the log file. The issue occurs each time.
https://gist.github.com/SleepyCatten/96c01c2ad5cf01796d6eb5b4c7f05233

**Versions**
- Minecraft version: 1.18.1
- Paper version: 133
- Mod version: 2.2.1

**Other mods**
Plugins (18): AngelChest, ArmoredElytra, BestTools, ChestSort, CoreProtect, Drop2InventoryPlus, HolographicDisplays, LuckPerms, PetMaster, PluralKitMC, ProNouns, ProtocolLib, RoseStacker, StackableItems, UltimateTimber, Vault, ViewDistanceTweaks, voicechat
There are 21 data packs enabled: [vanilla (built-in)], [file/bukkit (world)], [file/anti enderman grief v1.1.2.zip (world)], [file/coordinates hud v1.2.2.zip (world)], [file/durability ping v1.1.2.zip (world)], [file/multiplayer sleep v2.6.2.zip (world)], [file/player head drops v1.1.2.zip (world)], [file/redstone rotation wrench v1.1.3.zip (world)], [file/silence mobs v1.1.2.zip (world)], [file/terracotta rotation wrench v1.1.3.zip (world)], [file/more mob heads v2.9.4.zip (world)], [file/dragon drops v1.3.2.zip (world)], [file/double shulker shells v1.3.2.zip (world)], [file/armor statues v2.8.3.zip (world)], [file/respawning-pets-e630.zip (world)], [file/unlock all recipes v2.0.3.zip (world)], [file/global-trades.zip (world)], [file/afk display v1.1.2.zip (world)], [file/nether portal coords v1.1.2.zip (world)], [file/track raw statistics v1.5.2.zip (world)], [file/track statistics v1.1.3.zip (world)]

**Screenshots (Optional)**
N/A

**Comment by henkelmax** [comment]
Please post the full logs.
Please also try if this happens without any other plugins.

**Comment by SleepyCatten** [comment]
Full log as requested. I'll see if the issue occurs without other plugins and post back.

https://gist.github.com/SleepyCatten/9595bd5fef697f45b80782f74eb6d91e

**Comment by henkelmax** [comment]
I tested running the voice chat plugin with Paper 133 and nothing happens, so it must be a combination with another plugin causing this.

**Comment by SleepyCatten** [comment]
In that case, please close this issue, as it won't be something your plugin is doing. Thank you kindly for the quick responses.

**Comment by henkelmax** [comment]
> In that case, please close this issue, as it won't be something your plugin is doing. Thank you kindly for the quick responses.

It might still be an issue with voicechat. Let me know if you find out which plugin causes it.

**Comment by SleepyCatten** [comment]
Hi. I found out which plugin is causing the issue, but I do not know why.
https://github.com/lucypoulton/ProNouns

If this plugin is enabled, it causes the error message each time on shutting the server down. It also causes a warning message with AngelChest.
https://github.com/JEFF-Media-GbR/issue-tracker

**Comment by henkelmax** [comment]
Can you send me the logs with just voicechat and pronouns?

**Comment by SleepyCatten** [comment]
Here you go. Thank you again for looking at this 💟
https://gist.github.com/SleepyCatten/eb6f733c6f6acec624fcc4af89fbd473

**Comment by lucyydotp** [comment]
turns out this is my fault. working on a fix for pronouns, should be out tomorrow

**Comment by henkelmax** [comment]
> turns out this is my fault. working on a fix for pronouns, should be out tomorrow

Thank you!
