### ISSUE TITLE
Crash when exiting to title screen with no audio device

### ISSUE THREAD

**Issue by MidGame1** [henkelmax/simple-voice-chat#347]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**
I read the relevant FAQ

**Bug description**
Crash when quitting to title if you do not have an audio device connected. I disabled every device other than my headphones, and had my headphones unplugged (hence no devices) when it crashed. Looks like it doesn't check to see if soundManager is null when closing. This occurs in Singleplayer or Multiplayer worlds.

**Steps to reproduce the issue**
1. Disable all audio devices - 
    a. Right click on audio in corner of desktop, open sound settings
    b. Click "Manage sound devices"
    c. Click on each device and select "Disable"
2. Open Minecraft and join a world (Singleplayer or Multiplayer)
3. Pause and click "Save and Quit to Title"
4. Crash to desktop

**Expected behavior**
Disabling all audio devices causes a crash to desktop upon quitting to title. Most likely due to no check on if soundManager is null before closing.

**Log files**
Log File - https://gist.github.com/MidGame1/9e41496fc5ad7750e15efc83dc3c57e7
Crash Report - https://gist.github.com/MidGame1/96a91f58ddcd2d803d6c8de9a7ec0b17

**Versions**
- Minecraft version: 1.18.1
- Forge/Fabric version: Fabric 0.12.12
- Mod version: 2.1.28

**Other mods**

NOTE - Tested it without any mods other than simple voice chat and the problem persisted

Logs have the following installed too:
Clear Skies
Clumps
Continuity
Fabric API
FerriteCore
Indium
Iris
LambDynamicLights
LazyDFU
Lithium
Mod Menu
OK Zoomer
Smoothboot
Sodium
Starlight
Worldedit

**Screenshots (Optional)**
Disabled Audio:
![image](https://user-images.githubusercontent.com/81443709/148811026-0fd8ca3f-ba5b-4c84-96c9-c2c78b66e22d.png)
Crash message:
![image](https://user-images.githubusercontent.com/81443709/148811267-eb465d2f-e572-4927-bddc-7cd5ff406844.png)

**Comment by henkelmax** [comment]
Thanks for reporting this issue. It will be fixed in the next version.
