### ISSUE TITLE
Release type is not being updated in Forge

### ISSUE THREAD

**Issue by shotah** [henkelmax/simple-voice-chat#351]
**Bug description**
Release to Forge are marked as Alpha

**Expected**
Release to CurseForge are marked as Release

**Impact**
Unable to filter files properly when implementing automatically pulling from the Forge API.

**Current Output***
```json
            ...
            "displayName": "[FORGE][1.18] Simple Voice Chat 1.18-2.1.18",
            "fileName": "voicechat-forge-1.18-2.1.18.jar",
            "releaseType": 3,
            ...
```

**Expected Output***
```json
            ...
            "displayName": "[FORGE][1.18] Simple Voice Chat 1.18-2.1.18",
            "fileName": "voicechat-forge-1.18-2.1.18.jar",
            "releaseType": 1,
            ...
```

*** Forge API Documentation ***
https://docs.curseforge.com/#tocS_FileReleaseType

**Comment by henkelmax** [comment]
I have no idea what you mean. No curseforge release has ever been marked as release. 

No Release on CurseForge at all:
![image](https://user-images.githubusercontent.com/13237524/149277229-e5771df8-fcca-44cf-8d3e-677f44c95c4c.png)

The file you mentioned is clearly alpha;
![image](https://user-images.githubusercontent.com/13237524/149277427-820dcf0a-4737-47b8-9811-a6c797922120.png)

What you mention as current output (3) is alpha:
![image](https://user-images.githubusercontent.com/13237524/149277567-bbf7b83b-08a2-4e66-b728-9e5fa56b4bf8.png)

**Comment by shotah** [comment]
Oh this is showing only Beta and Alpha. I was looking for the actual words somewhere. But yes your files are not marked as release. Here is an example from Fabric API.
![image](https://user-images.githubusercontent.com/8572809/149371568-6bf0e1b2-8c44-4d6d-8a1f-b78e4b475639.png)

Here is Voice Mod(Which is all B for beta):
![image](https://user-images.githubusercontent.com/8572809/149371700-92f0a04e-4d25-496c-aabe-e2bfecbc943c.png)

**Comment by henkelmax** [comment]
Yes, but where's the bug?

**Comment by shotah** [comment]
Wanted to say again that this is an awesome mod. It's why I'm here looking at it! :)

I was enabling user of itzg/minecraft-server to supply projectIds to have it pull mods, but I wasn't wanting to include Beta or Alpha. Which we yes can make as an option, but in reviewing this none of the mods are marked as release. 

Shell script to parse the files and return the Latest Release for the Version Queried. 
```
   PROJECT_FILE=$(jq -n "$project_files" | jq -jc '
      .data|=( map(select(.releaseType==1)) | sort_by(.id) | reverse) | .data[1]')
```

PR for the addition over at the itzg repo: https://github.com/itzg/docker-minecraft-server/pull/1275

**Comment by shotah** [comment]
Bug isn't in the mod, maybe that is the confusion. Or is this mod still in Beta and my confusion?

**Comment by henkelmax** [comment]
Yes this mod is still in beta.

**Comment by shotah** [comment]
Was able to get this implemented. Your mod was a great help in getting this fleshed out a bit further. :) https://github.com/itzg/docker-minecraft-server#forgeapi-usage-to-use-non-version-specific-projects
