### ISSUE TITLE
Backward/forward version support

### ISSUE THREAD

**Issue by srnyx** [henkelmax/simple-voice-chat#352]
Could it be possible for you to add backward/forward support? Mainly for the mod.
Currently, you have to be on the **same exact** version of the server. This makes it virtually impossible to update the plugin because if you do, the entire playerbase has to reinstall/update the mod on their client, which can be confusing for some people.
It would be amazing if a player using a mod version older than the plugin version could still use voice chat. Same with vice-versa, a player using a version newer than the plugin version can still use voice chat.

**Comment by henkelmax** [comment]
What you say is not true at all. Please read the wiki (Compatibility tab)
