### ISSUE TITLE
Leaving a group crashes the game (client)

### ISSUE THREAD

**Issue by SleepyCatten** [henkelmax/simple-voice-chat#353]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Leaving a group voice chat crashes the game (client).

**Steps to reproduce the issue**
1. Install a Paper server and use the plugin - version 1.18.1-2.2.4.
2. Connect via the client using the Fabric plugin - version 1.18.1-2.2.4.
3. Enter a group chat.
4. Get multiple people to join.
5. Ask the people to leave the group chat.
6. Watch their clients crash.

**Expected behavior**
No crash.

**Log files**
https://gist.github.com/SleepyCatten/0f9e9ec976f59f1950132dc645d270f3

**Versions**
- Minecraft version - 1.18.1
- Fabric version - loader-0.12.12
- Mod version - 2.2.4

**Other mods**
ArmoredElytra-3.0.1
borderless-mining-1.1.1+1.18
fabric-api-0.46.0+1.18
HideArmor-Fabric-1.18.1-2.5
infinitemusic-1.5.1-1.18.1-fabric
malilib-fabric-1.18.0-0.10.0-dev.26
minihud-fabric-1.18.0-0.19.0-dev.20211204.230657
optifabric-1.12.10
OptiFine_1.18.1_HD_U_H4
replaymod-1.18.1-2.6.3
Xaeros_Minimap_21.23.1_Fabric_1.18

**Comment by henkelmax** [comment]
Can you please send me the full logs?

**Comment by henkelmax** [comment]
Also please install the latest version of the mod and test if it still happens.

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/149674347-d196b27f-96be-4a18-bdb8-93ca5b99c06a.png)
It has already been fixed in 1.2.8
