### ISSUE TITLE
max/min_distance or max/min_voice_distance? 

### ISSUE THREAD

**Issue by yijiazz** [henkelmax/simple-voice-chat#355]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
There seems to be a discrepancy between the documented configuration keys and actually used keys for "max voice distance" and "min voice distance". Which pair should we use for server config? 

[Documented:](https://modrepo.de/minecraft/voicechat/wiki?t=configuration)
![image](https://user-images.githubusercontent.com/88701798/149873708-8a84f0b2-f4b2-4cf9-aec5-b7d97c449732.png)

[Used in code](https://github.com/henkelmax/simple-voice-chat/blob/f5cafa0b302f4cff7a47db85c892c802a9ad5d11/fabric/src/main/java/de/maxhenkel/voicechat/config/FabricServerConfig.java):

![image](https://user-images.githubusercontent.com/88701798/149873813-ea0bd105-34b9-4187-b599-7c4e64fc73bc.png)

**Steps to reproduce the issue**
1. Configured `max_distance` and `min_distance` in `voicechat-server.properties` for MC server (Fabric). 
2. Verify actual max/min distance in game. 

**Expected behavior**
Max/min distance NOT behaving as configured.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft: 1.18.1
- Fabric: 0.12.12
- Mod1.18.1

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Works perfectly fine. The sound fades in a sigmoid curve, so it is almost not hearable at 48 blocks.

**Comment by yijiazz** [comment]
> Works perfectly fine.

@henkelmax Could you please confirm if you have with `max_distance`/`min_distance` or with `max_voice_distance`/`min_voice_distance` in `voicechat-server.properties`?

**Comment by henkelmax** [comment]
Oh, I'm so sorry, I thought you were actually talking about the values not doing anything.
I will fix that.

Next time please report errors of the wiki to https://github.com/henkelmax/modrepo
