### ISSUE TITLE
translation.yml not working

### ISSUE THREAD

**Issue by kakigorimochi** [henkelmax/simple-voice-chat#356]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
I tried modifying the translation.yml file and the changes applied doesn't seem to be working

**Steps to reproduce the issue**
1. Go to '/plugins/voichat/translation.yml' with voicechat (2.2.8)
2. Edit the not compatible message and check if my yml is valid on yamllint.com, save changes
3. Fire up the server and login with an old voice chat version (2.1.28)

**Expected behavior**
I expected my custom message to appear.

**Log files**
No logs available as voice chat seem to say it loaded the translation.

**Versions**
- 1.18.1
- Forge 39.0.5
- 2.2.8

**Other mods**
n/a

**Screenshots (Optional)**
n/a

**Comment by henkelmax** [comment]
The custom message will only appear if there is no matching translation on the client.

https://github.com/henkelmax/simple-voice-chat/blob/dfc7ea2e363c7e27185d47b5bb4cb96bf403d6c0/bukkit/src/main/java/de/maxhenkel/voicechat/voice/server/ServerVoiceEvents.java#L64-L66
