### ISSUE TITLE
Mute command for staff

### ISSUE THREAD

**Issue by srnyx** [henkelmax/simple-voice-chat#357]
**Is your feature request related to a problem? Please describe.**
Swearing isn't allowed on my server. When someone is muted for swearing, they can just use voice chat to scream their lungs off.

**Describe the solution you'd like**
A `/voicechat mute <player> [duration] [reason]` command that will mute the user's voice for everyone on the server.

**Describe alternatives you've considered**
Banning the user

**Comment by henkelmax** [comment]
Muting is completely client side.
You can revoke the talk permission from a player with the bukkit plugin.

**Comment by srnyx** [comment]
> Muting is completely client side. You can revoke the talk permission from a player with the bukkit plugin.

How can I do that? Can't find a command for it.

**Comment by srnyx** [comment]
Ohhhhh, permission, gotcha.
