### ISSUE TITLE
Mac issues

### ISSUE THREAD

**Issue by ceiri** [henkelmax/simple-voice-chat#358]
**Bug description**
I know many have reported this same issue, but I just can't get the microphone to work with Voice Chat. I've tried the built-in Launcher patcher but the only thing that did was change the icon to a folder, and make tens of annoying authentication pop-ups show up.

**Steps to reproduce the issue**
1. Open a Fabric installation of Minecraft (1.18.1) with Simple Voice Chat - on MacOS Monterey
2. Follow the prompts from the patcher
3. Restart the Launcher and the java instance

**Expected behavior**
Not only will many authentication promps pop up but the microphone will still not work with the launcher/mod

**Log files**
[2022-01-24-7.log.gz](https://github.com/henkelmax/simple-voice-chat/files/7928284/2022-01-24-7.log.gz)

**Versions**
- 1.18.1
- 1.18.1 Fabric
- 2.2.11

**Other mods**
It's obvious that it's most likely not because of my installed mods, but they are:
- eating-animation
- fabric-api
- farsight
- malilib
- minihud
- modmenu
- optifabric
- optifine
- replay mod
- sound physics remastered
- tweakeroo
- simple voice chat

**Screenshots (Optional)**
![2022-01-24_19 29 52](https://user-images.githubusercontent.com/57523771/150851033-95518936-104b-4db6-b06e-ae8c1b5e92d3.png)

**Comment by henkelmax** [comment]
The crash you are getting is not from voice chat.

If you need help patching your launcher visit the discord.
