### ISSUE TITLE
Make voice chat louder

### ISSUE THREAD

**Issue by ChristianKilduff** [henkelmax/simple-voice-chat#359]
make the master volume go higher than 200% because even with 200% + 300% individual volume and my computer volume max some people are nearly impossible to hear while others r just quiet

**Comment by henkelmax** [comment]
If you need to crank up your volume that much I would advise you to look into the audio level of the OS.
Making it even louder through the mod would result in audio clipping.

**Comment by notdev27** [comment]
> If you need to crank up your volume that much I would advise you to look into the audio level of the OS.
> Making it even louder through the mod would result in audio clipping.

fair enough i just get much much louder sound out of discord without issue while prox I have my volume at max and even turn down discord master in settings to like 15-30% just so I dont blasted when entering vc, I just find that the sound does not get that loud and many ppl on my server have mentioned similar issues.

Didnt mean to be on two accounts this browser was just logged in different and i didnt bother to check so same person as above
