### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by skyisnotcool** [henkelmax/simple-voice-chat#36]
I am trying to put the mod on my server on Pebblehost. I set it all up and got a little green checkmark on minecraft but when I launch it, it still says voice chat unavailable. I could not test anything as it will not let me use it even though it is supposedly running fine. I read the wiki but am unfamiliar with coding. I have attempted to resolve this for hours and it will not work. I would use a different voice chat but none are up to date with minecraft. Please help
Also, it's not just the server that this mod doesn't work in. It's my game in general. No matter which server I use.
The v command to open the settings does not work either. It also just says voice chat unavailable

**Comment by henkelmax** [comment]
Have you opened the voice chat port?

**Comment by FamishedYeti** [comment]
To set it up with pebble host you will need to change the port. You're going to have to use something such as FileZilla to get FTP file access, there are many tutorials specifically on pebblehost on how to do that. 
You'll need to change the port to whatever port your server is being hosted on, and to get that you just need to go to the dashboard on pebblehost and look where the IP is. the host is seperated from the ip by a colon (for example x.x.x.x:wwwww, the w's are the port.) just put the port into the server config (located in world\serverconfig\voicechat-server.toml) and when you load up the world it should work.
![image](https://user-images.githubusercontent.com/29389443/105794679-7c798980-5f59-11eb-9b2d-36daf00665fc.png)
