### ISSUE TITLE
Quark adjustable chat option conflict with mod UI.

### ISSUE THREAD

**Issue by KKotik** [henkelmax/simple-voice-chat#361]
**Bug description**
Quark have option to adjust chat position, when position adjusted microphone icon seems to be duplicated.

**Steps to reproduce the issue**
1. Go to Quark config.
2. Find adjustable chat option.
3. Set vertical shift to -20 for example.
4. Turn on UI icons in Voice chat mod and see the issue.

**Versions**
- Minecraft 1.18.1
- Forge version
- 2.2.13

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/45950781/151195960-404460ba-a5ca-47c1-afa3-8e43fbc4dbf5.png)

**Comment by henkelmax** [comment]
Thanks for reporting this issue

**Comment by KKotik** [comment]
Still exist with latest alpha versions as well.

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/151435762-18984afc-176d-4f4b-a9ee-e39b76567649.png)

Works perfectly fine.
