### ISSUE TITLE
Can't hear my friend on Linux

### ISSUE THREAD

**Issue by arch-user-france1** [henkelmax/simple-voice-chat#363]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
He is able to hear me (he's on Windows) but I'm not able to hear him (connection works, and I can see that he is talking, his mic isn't the problem.

**Steps to reproduce the issue**

**Expected behavior**
It works

**Log files**
Nothing on the server log, can I find a client log?

**Versions**
- 1.16.5
- newest 1.16.5 (on both computers)
- .minecraft/mods/voicechat-forge-1.16.5-1.8.0.jar

**Other mods**
I guess this wont be a problem.

**Comment by henkelmax** [comment]
1.16.5 is not actively developed anymore. These issues are fixed in later versions.

**Comment by arch-user-france1** [comment]
Is it possible to simply change the version from 1.17/18 but install it or would it not work?

**Comment by henkelmax** [comment]
Nope, that's not how mods work.
It will only work for the MC version the mod is for.

**Comment by arch-user-france1** [comment]
Do you at least know what the issue is?

**Comment by henkelmax** [comment]
Yes, it has been fixed in later versions, as already stated.

**Comment by arch-user-france1** [comment]
Can I fix it by myself?

**Comment by henkelmax** [comment]
There might be other workarounds, but please visit the discord for that.
