### ISSUE TITLE
Problem with proximity voicechat

### ISSUE THREAD

**Issue by NotKapani** [henkelmax/simple-voice-chat#364]
The sound doesn't move or change volume as other players move away or around me (this is the situation for all of us), is there any setting or option I'm missing?

The mod should work as proximity voicechat does, voices moving along with the players

Minecraft Fabric 1.18.1 voicechat version 2.2.8

(mods being used at the same time)
Origins, Origins Classes, Advanced Netherite

**Comment by henkelmax** [comment]
Please visit the Discord if you need help. I'm pretty sure this is not a bug.
