### ISSUE TITLE
MacOS Microphone Permission Doesn't actually patch launcher

### ISSUE THREAD

**Issue by hens50** [henkelmax/simple-voice-chat#367]
**Bug description**
When I installed simple voice chat, i launched forge with it and it showed the popup window "Simple Voice Chat MacOS Microphone Permission" (pictured below) where it asked me to drag my launcher into the box below. I did so, and it asked if I was sure to patch my launcher, and I accepted. I relaunched and the same popup shows. This keeps happening over and over. 

**Steps to reproduce the issue**
1. Install simple voice chat onto a forge installation
2. Launch using vanilla launcher
3. While red mojang logo window loads, a java popup shows asking to patch launcher (pictured below)
4. I drag Minecraft from the applications folder and confirm with a "Are you sure" yes/no/cancel popup

**Expected behavior**
Me to be able to drag in the launcher application into the popup and relaunch the game for simple voice chat to work

**Log files**
None

**Versions**
-MC: 1.18.1
-Forge: 39.0.9
- Mod version: 2.1.23

**Other mods**
None, only simple voice chat

**Screenshots (Optional)**
<img width="899" alt="Screen Shot 2022-02-05 at 5 47 55 PM" src="https://user-images.githubusercontent.com/96390278/152661525-0078d1c4-a381-4cd2-902e-498c81dd4d59.png">

**Comment by henkelmax** [comment]
Sometimes the setup requires a little more for it to work, but this completely depends on your system. Please visit the Discord, so we can help you with that.
