### ISSUE TITLE
Unsupported API version 1.18

### ISSUE THREAD

**Issue by TheCiROMG** [henkelmax/simple-voice-chat#368]
**Bug description**
Unsupported API version 1.18 (https://paste.gg/p/anonymous/0070c8b4a9b54f30bffcbed1ebf6962c)

**Steps to reproduce the issue**
1. Put the latest version of the plugin (curseforge) in the plugins folder and open the server

**Log files**
https://paste.gg/p/anonymous/0070c8b4a9b54f30bffcbed1ebf6962c

**Versions**
- Minecraft version : 1.18.1
- Purpur version : 1.18.1
- Mod version : 2.2.21

**Other mods**
Only Optifine

**Comment by mjwells2002** [comment]
Your server is version 1.17.1 use the 1.17.1 plugin version
