### ISSUE TITLE
Players with invisibility can be seen.

### ISSUE THREAD

**Issue by SzczurekYT** [henkelmax/simple-voice-chat#371]
**Bug description**
When player is invisible the mute / microfophone icon near nametag is visible, revealing him.

**Steps to reproduce the issue**
1. Drink invisibility potion.
2. Other players can see you icon near nametag.

**Expected behavior**
The micorphone / mute icon near nametag shoud be hidde so invisibility makes sense.

**Log files**
It's not really bug, but a lack of feature so there is no log. I marked this as issue because this mod makes invisibility a bit useless, so it's a feature that's needed for mod to work properly.

**Versions**
- Minecraft version: 1.18.1
- Forge version: 29
- Mod version

**Other mods**
Around 100 but I don't think they affect this. I needed I can provide entire list.

**Screenshots**
![image](https://user-images.githubusercontent.com/67533827/154482274-579da3fe-e102-419e-be74-76c0ca792f5a.png)

**Comment by henkelmax** [comment]
Please test if it happens with just the voice chat installed.

EDIT: Tested it and it also happens without any other mods.

**Comment by SzczurekYT** [comment]
Yeah it's just a simple thing no one thinked of. Not sure but I think there should be some kind of check in https://github.com/henkelmax/simple-voice-chat/blob/1.18.1/forge/src/main/java/de/maxhenkel/voicechat/intercompatibility/ForgeClientCompatibilityManager.java around line 63

Edit: Wrong word, grammar fix

**Comment by henkelmax** [comment]
Yeah, I know the cause, the issue is already fixed. I'm just testing a couple of things.

It's just weird that Forge fires the render nameplate event, even if it isn't even rendered...

**Comment by SzczurekYT** [comment]
> It's just weird that Forge fires the render nameplate event, even if it isn't even rendered...
 
When I was reading the code I tought so too.
In programming it's pretty common that there's something you don't expect and than you have some weird behavior.

> Yeah, I know the cause, the issue is already fixed.

Cool, thanks for your work. I was looking for proximity voice chat for few years ( especially for spigot), and there was nothig for long time. While now I have forge server the best thing is that your mod also works on spigot.

Thanks
