### ISSUE TITLE
Version 2.2.21 is non downloadable

### ISSUE THREAD

**Issue by Hozq** [henkelmax/simple-voice-chat#372]
Really have no idea when it was released but the curseforge app downloads the version 2.2.21, so does Aternos but its not possible to download it manually so I have players that can't join my server because the version required for this mod is unavailable.

**Comment by henkelmax** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/3638504

https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/3638505

**Comment by Hozq** [comment]
Oh okay weird, I can't see those in the file list
