### ISSUE TITLE
Crash when adjusting volume

### ISSUE THREAD

**Issue by roomfullofcommits** [henkelmax/simple-voice-chat#373]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
The game crashes when adjusting the voice chat volume.
I didn't really see a pattern in the behaviour, sometimes it takes a few seconds of quickly adjusting the volume.
I also noticed that it didn't happen on Auto GUI scale, I tried for over 30 seconds. I changed to GUI scale 3 and it happened within a few seconds.

**Steps to reproduce the issue**
1. Press "v" to get to the voice chat settings
2. Adjust the volume (quickly?)
3. Crash

**Expected behavior**
The volume gets adjusted without the game crashing

**Log files**
Log: https://pastebin.com/iQHMDKaE
Before 23:13:23 the GUI scale was set to Auto, after it was set to 3.
Crash log: https://pastebin.com/J7T3RGWF
Crash message: https://imgur.com/a/UuV83A7

**Versions**
- Minecraft version: 1.18.1
- Forge version: 39.0.75
- Mod version: 2.2.21

**Other mods**
None

**Comment by roomfullofcommits** [comment]
So that's weird. I tried updating Forge to 39.0.79 just to check if it was the Forge beta and couldn't recreate it. When I changed back to a profile with Forge 39.0.75, the exact one where the log is from that I never updated, I couldn't recreate it either. On any GUI scale.

**Comment by roomfullofcommits** [comment]
I think I wasn't very clear with my comment. What I meant to convey was that the issue seems to be kind of random. It happened multiple times with and without other mods, on different days, with restarts of my PC in between. I think my comment made it seem like it isn't an issue anymore, it definitly is. 
I just tried it again it crashed pretty much instantly after adjusting the volume. I think I was on GUI scale 2 this time, so I'm not even sure GUI scale is related at all.

I don't know the reason why this thread was closed. I'm just assuming I made it seem like it fixed itself, which it did not.

**Comment by henkelmax** [comment]
Oh, sorry I misunderstood you

**Comment by henkelmax** [comment]
> Log files
Log: https://pastebin.com/iQHMDKaE

Can you please send me the crash logs. The logs you sent don't contain any crash.

**Comment by roomfullofcommits** [comment]
Of course, sorry. I sent the completely wrong thing. I updated the original comment.
