### ISSUE TITLE
[1.16.5- 2.x backport regression] JNA version too new, crashes Vivecraft.

### ISSUE THREAD

**Issue by Colin-J-Wood** [henkelmax/simple-voice-chat#374]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
when the game launches vivecraft on the newest version of voice chat mod, it will crash whilst loading libraries.

**Steps to reproduce the issue**
1. Install vivecraft (headset not required to reproduce the crash)
2. Install simple voice chat mod in the mods folder
3. launch and crash.

**Expected behavior**
Don't use JNA 5.  Vivecraft is using 4.2.1 and mojang uses 4.4.0 in 1.16.5.  I assume the json of libraries when backported from 1.18 did not consider that 1.16 uses jna4 and not jna5

**Log files**
https://pastebin.com/6pLkWuM9

**Versions**
- Minecraft version 1.16.5
- Forge/Fabric version 36.2.20
- Mod version 2.2.22

**Other mods**
Vivecraft 1.16.5-8b

**Comment by henkelmax** [comment]
Thanks for reporting this issue. It should be fixed in the latest version.
