### ISSUE TITLE
Microphone Not Working On macOS

### ISSUE THREAD

**Issue by B0spammed** [henkelmax/simple-voice-chat#375]
**Bug description**
Whenever I try to make the start up window of Simple Voice Chat scan MultiMC and allow microphone access to MultiMC it gives me an error.

**Steps to reproduce the issue**
1. Launch an MultiMC Instance
2. Drag the MultiMC in Applications into the window
3. Click Yes
4. See the error

**Expected behavior**
I expected the window to scan MultiMC and automatically close the window, and simple voice chat would work.

**Log files**
script src=https://gist.github.com/B0spammed/74b9ad83f8944bb7ecfc073f2f43956c.js

**Versions**
- 1.18.1
- Fabric
- 2.2.11
- MacOS Mojave 10.14.6

**Other mods**
None

**Comment by henkelmax** [comment]
This is not a bug. Please visit the Discord if you need help.

**Comment by B0spammed** [comment]
> This is not a bug. Please visit the Discord if you need help.

Where is the patch of this glitch? Thanks
