### ISSUE TITLE
[Feature Request] Voice activation permission

### ISSUE THREAD

**Issue by ilfarpro** [henkelmax/simple-voice-chat#376]
**Is your feature request related to a problem? Please describe.**
Unfortanetly in my server a large amount of people with poor quality cheap microphones and they prefer to use voice activation instead of Push to Talk. And as a server owner and as a streamer I want to prevent them from using voice activation option. 
It would be great to have permission to do that. Also if it possible, I really need permission for other setting such as noise suppression. 

**Describe the solution you'd like**
Please add permission for using voice activation to prevent people from broadcasting their strong microphone noise. How it will work: I'm setting permission voicechat.voiceactivation to false for default permission group. And players within this permission group can't use voice activation. Only Push to Talk.
Also, please add permission for controlling user's settings. For example, as a server owner I want to set permission voicechat.noisesuppression true for default permission group. As a result all players will speak with noise suppression enabled.  

**Describe alternatives you've considered**
Maybe enabling noise suppression by default in newer version of Simple Voice Chat will partially fix this. Also I think this can't make any negative impact, unless the case when end user has very-very silent mic without any amplification.

**Comment by henkelmax** [comment]
There already is a permission for generally sending audio.

https://modrepo.de/minecraft/voicechat/wiki?t=permissions

But differentiating between the activation types is definitely not possible, since it is purely client side.
