### ISSUE TITLE
[1.16.5]Server crash on startup

### ISSUE THREAD

**Issue by SkullDiamond** [henkelmax/simple-voice-chat#377]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
server crash on start up

**Steps to reproduce the issue**
1. use the last version of the mod (2.2.23) and start the server

**Expected behavior**

**Log files**
crash.log: https://pastebin.com/NbGVyrG1

**Versions**
- Minecraft version: 1.16.5
- Forge/Fabric version: Forge
- Mod version: 2.2.23

**Other mods**
you can see the list on the crash

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by SkullDiamond** [comment]
is fix on the last update?

**Comment by henkelmax** [comment]
No it hasn't been released yet.
