### ISSUE TITLE
Using QuestCraft I Get A Microphone Unavailable Message

### ISSUE THREAD

**Issue by ghost** [henkelmax/simple-voice-chat#379]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
My Server does have the Simple Voice Chat Plugin But When I Join Using Questcraft (Minecraft Vr On Oculus Quest Standalone) It Says Microphone Unavailable

**Steps to reproduce the issue**
1. Go to Youtube And Find A Tutorial on how to get QuestCraft
2. Then Launch The fabric-loader-0.12.12-1.18.1 version
3. Join A Server With THe Simple Voice Chat Mod Installed

**Expected behavior**
I Expect To Be Able to Talk With My Friends While Using QuestCraft

**Log files**
https://gist.github.com/Foxxy-01/11d651d7abb292ae5afa690a7afc973a

**Versions**
- 1.18.1
- fabric-loader-0.12.12-1.18.1
- voicechat-fabric-1.18.1-2.2.16.jar

**Other mods**
titleworlds-0.0.1.jar
voicechat-fabric-1.18.1-2.2.16.jar
starlight-1.0.0+fabric.d0a3220.jar
mcxr-core-0.1.1+build.6.jar
mcxr-play-0.1.3null.jar
fabric-api-0.45.0+1.18.jar
lazydfu-0.1.2.jar

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
This mod only supports the platforms that Mojang also officially supports.
We already contacted the devs of the Pojav launcher, but they were not interested in a fix.
