### ISSUE TITLE
Others can hear me, but I cannot hear them.

### ISSUE THREAD

**Issue by GitHababi** [henkelmax/simple-voice-chat#38]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
According to my logs, I am fully connected to the server, others can hear me, but I cannot hear them.
From what I could gather, the only line that is of relevance to this bug is simple:
- My client isn't recognized as having the mod & incoming packets are for some reason not identified.
Check lines 215 & 222 of my logs.

**Steps to reproduce the issue**
I do not know.

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [Logs](https://cdn.discordapp.com/attachments/780682764756058132/803333804587745280/latest.log).

**Versions**
- Minecraft version 1.16.4
- Forge version forge 35.1.4
- Mod version 1.1.3 (1.16.4)

**Other mods**
None.

**Screenshots (Optional)**
Not relevant, but others

**Comment by GitHababi** [comment]
Oh, and something I forgot to note, I made sure that the audio output device worked, I could minecraft's audio and in the voice chat menu my headphones were selected.

**Comment by henkelmax** [comment]
It sometimes takes a minute until the voice chat works. Can you try it for a longer amount of time? Please also try the test command and send me the logs of both client and server.

**Comment by rotigod** [comment]
Having this same issue occur with one of my players. Is there any fix for it?

**Comment by henkelmax** [comment]
Have you tried everything in the wiki?

**Comment by henkelmax** [comment]
I'm closing this issue, since it is basically the same as #23
