### ISSUE TITLE
Voicechat server crashing

### ISSUE THREAD

**Issue by TVince0** [henkelmax/simple-voice-chat#380]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Hi! I made a server on fabric using bukkit and only added the voicechat mod (+ the fabric api). My server crashed with an error what I think is related to this mod.

**Log files**
https://gist.github.com/TVince0/6a5c774f952a7152d77fbfdc7ae57a3f

**Versions**
- 1.18.1
- 0.13.3
- 2.2.16

**Comment by henkelmax** [comment]
This crash is not caused by the voice chat mod.
I also don't know what you mean with "server with fabric using bukkit".
