### ISSUE TITLE
Doc update: MacOS Microphone

### ISSUE THREAD

**Issue by drewburr** [henkelmax/simple-voice-chat#382]
Relates to the [MacOS Microphone Permission Hack](https://github.com/henkelmax/simple-voice-chat/tree/1.18.2/macos#macos-microphone-permission-hack) documentation/process.

Today I helped someone patch their Minecraft launcher on MacOS and I wanted to provide some feedback since it seems that historically this has been a pain point for you guys (Looking at you, #24).

**Additional context**
MacOS Monterey (12.2.1) Intel CPU
Minecraft 1.18.2, launched via CurseForge
Mod version [2.2.26 for Fabric](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/3670736).

**Feedback**

After installing the mod, we did get the new pop-up for patching the Minecraft installation. We were able to do this once locating the CurseForge-specific launcher (~/Documents/curseforge/Installation/Minecraft.app), but we were not able to get the microphone working still. When joining a world, we got a message asking for permissions to be granted via the Security & Privacy section. Minecraft didn't show up under microphone permissions, so we pulled up the above-linked docs and noticed the **codesign** commands. We attempted to sign the launcher application, but ended up running into the errors described in this [Apple Developers Q&A](https://developer.apple.com/library/archive/qa/qa1940/_index.html). 

> resource fork, Finder information, or similar detritus not allowed.

We were able to get around this by executing:

`xattr -cr ~/Documents/curseforge/Installation/Minecraft.app`

Which allowed the codesign command to work without issue. The Microphone permission popped up during the Minecraft startup sequence, and we were able to get running with no problems.

I guess my suggestion here is to consider either including both the xattr and codesign commands in the workaround process, or add this additional bit of information to the documentation.

Lastly, we also noticed that after the currently-automated patching process, every time we load the game we get 7-8 pop-ups for reading values from the Keychain. For the sake of time, we did not look into fixing this, but I wonder if there's a workaround we could find there? It's really not that bad, it's just annoying to type in a password 7-8 times every time we launch the game.

Hopefully this is helpful to you all. This plugin is awesome, thank you for supporting it!

**Comment by drewburr** [comment]
![Screen Shot 2021-11-23 at 7 36 08 AM](https://user-images.githubusercontent.com/29960267/157062931-83c724b2-772e-47a6-9b8a-7c716abfb33d.png)

**Comment by drewburr** [comment]
![2022-03-07_09-23-27](https://user-images.githubusercontent.com/29960267/157063476-0eaa8d7a-7710-433f-ae53-ce9d0218a916.png)

**Comment by henkelmax** [comment]
Thank you for letting us know. We will try this command if people have issues with the patcher. If it works for them, we'll add it to the patcher.

**Comment by Devnol** [comment]
Hello, Monterey user here too, running MultiMC. Tried the xattr suggestion above and then running the patcher (with Java 18) but it didn't seem to work. Anything else I can try?
(I'm using the plasmo-voice mod which points to your patcher for use too). Running the launcher from the terminal which has mic perms and then the game works but that's far from ideal.

**Comment by Devnol** [comment]
Tried it with simple-voice-chat as well, the NSMicrophoneUsageDescription permission does get added in MultiMC's info.plist but I never get a prompt to allow access to the microphone, not even after clicking on Enable microphone testing. What else can I try?

**Comment by henkelmax** [comment]
@drewburr unfortunately, this command didn't work for the people having issues with the patcher.

**Comment by drewburr** [comment]
Thanks for the heads up @henkelmax. I think it might be worth working with @Devnol rather than deleting their messages every time feedback is left :)

**Comment by henkelmax** [comment]
I marked these messages as off topic since their messages are support related and didn't add to the actual topic.
GitHub is only for bugs and enhancements, not for getting support.
It was also not feedback it was just a support request.

**Comment by Devnol** [comment]
Hi, I'm not trying to provide support, I'm reporting my findings as I do not know how to fix it myself because I find that it might be of help to someone who does

Edit: Ah yes that "what else can I try" does seem like asking for support, yeah that makes sense but still I find that the feedback could be of help to developers

**Comment by benjirocker** [comment]
Hello all, I know I'm late, im just trying to help: I found a fix that worked for me (m2 mac): I do not own this document and none of the work is mine: [https://docs.google.com/document/d/1DvRBN11Dl-ClJ7T-fpYyPBfk39TYott33biHYsLXaTM/edit](url)
instructions are in the document. hope this helps. p.s i know its tedious but it works.
