### ISSUE TITLE
Patching SKlauncher macOS microphone permissions

### ISSUE THREAD

**Issue by gitnixpie** [henkelmax/simple-voice-chat#384]
I get the message about microphone permission when joining a world, but the patch GUI does not open, even if I open via terminal. 

I downloaded the [standalone version](https://github.com/henkelmax/simple-voice-chat/tree/1.18.1/macos#standalone-version) of the workaround. When I try to patch SKlauncher 3-beta.20.jar it tells me it's not an app. There is no .app with this launcher, so can it be patched some other way?

**Versions**
- SKlauncher 3-beta.20
- Forge 1.18.1 (39.1.2)
- voicechat-forge-1.18.1-2.2.27
- macOS Monterey 12.2.1

**Comment by henkelmax** [comment]
We only support the launchers that are documented on this page: 
https://github.com/henkelmax/simple-voice-chat/tree/1.18.2/macos

We also won't ever support cracked launchers.
