### ISSUE TITLE
I cant connect to the voice mod server but others can

### ISSUE THREAD

**Issue by LuckyNova44** [henkelmax/simple-voice-chat#386]
This is a help wanted post but it didn't give me an option to do that...

This is the first time downloaded and used fabric on my computer. I downloaded everything and I set up voice mod on the server right and others can connect and talk to each other on it. but whenever I join I just get the plug with a cross? I have tried changing the server port to a better one. I have tried changing the config files around too that didn't work. and I have deleted everything and redownloaded everything and that also didn't work.

mod version: Fabric

mod list:
Adorn
Fabric API
Fabric Language Kotlin
Voicechat Fabric

**Comment by henkelmax** [comment]
you want help, visit the discord.
