### ISSUE TITLE
client not connected

### ISSUE THREAD

**Issue by xanders0907** [henkelmax/simple-voice-chat#387]
**Bug description**
I have a smp with my friends on pebble host.
but al my friends including me have a issue with the mod.
it says the the client issent connected when we talk.
pebble host dit the setup for the mod and plugin but i still dident work.

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
i was expecting that i could just talk to my friends with proximity chat.
with out any problems

**Log files**
there is nothing in there.
we just have the emoji in the right under side of the screen.
that says client not connected.
but in the logs it says when someons joins client connected.

**Versions**
- 1.18.2
- paper
- newest

**Other mods**
we have a vieuw other plugins like /tpa /home and other general stuff

**Screenshots (Optional)**
Screenshots of the issue.

greetings,

Xander Schenkel

**Comment by henkelmax** [comment]
If you need help, visit the discord.
