### ISSUE TITLE
Discord bot link

### ISSUE THREAD

**Issue by MidyGamy** [henkelmax/simple-voice-chat#388]
Hi.
Is it possible to implement a functionality to link a public group to a discord bot, to voice chat with Discord users whithout them to launch Minecraft
It will be great, and we already did that with text chat, why not voice ?

**Comment by henkelmax** [comment]
It is possible with the [Plugin API](https://github.com/henkelmax/simple-voice-chat/blob/1.18.2/api/readme.md). But you would need to implement it yourself.
