### ISSUE TITLE
Volume Adjustment settings not working correctly

### ISSUE THREAD

**Issue by ravenmoon312** [henkelmax/simple-voice-chat#389]
**Bug description**

When player volumes are adjusted (client side) they have no effect when talking in a group chat. Once players are in proximity of each other, the volume settings then take effect correctly. 

Eg. I can mute someone and I will still hear them talking when in a group chat. However, when I am next to them in game, they are muted, even if the group chat is still active. 

**Versions**
- Minecraft version 1.18.2
- Fabric
- Mod/Plugin version - voicechat-fabric-1.18.2-2.2.26.jar

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
