### ISSUE TITLE
Use voicechat-server.properties settings when running as /publish or "open to lan"

### ISSUE THREAD

**Issue by MikeMM70** [henkelmax/simple-voice-chat#390]
Hi Henkelmax,
   If I'm playing Minecraft single player and I "Open to LAN" from settings, or I "/publish <port>" my game to get a static port number, Simple-Voice-Chat picks a random port # to open for its server service. I haven't really tried your mod yet because of this, though the general settings look easy to understand. I like the idea that it works with SoundPhysicsRemastered, and that it has positional audio, so I look forward to trying it out.

Thank you for your efforts on this mod.
Mike

**Comment by henkelmax** [comment]
This was done on purpose, since Minecraft also does not use its server port for LAN worlds.
