### ISSUE TITLE
Issue in the serverconsole.

### ISSUE THREAD

**Issue by Taknax** [henkelmax/simple-voice-chat#391]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Issue in the serverconsole

**Steps to reproduce the issue**
1. Install voicechat-forge-1.16.5-2.2.31.jar on a server with the Forge 36.2.33
2. Run the server
3. After the world is loadet the issue occure in the server console.

**Expected behavior**
If this issue doesnt have negative effect on the server then it coud be get ignored.

**Log files**
[https://pastebin.com/pAuidD0K]() 

**Versions**
- Minecraft version 1.16.5
- Forge/Fabric/Bukkit/Spigot/Paper version Forge 36.2.33
- Mod/Plugin version 2.2.31

**Other mods**
A list of the other mods/plugins that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod/plugin is installed.
If not, please narrow down the mod(s)/plugin(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
This error is not related to the voice chat mod itself.

**Comment by henkelmax** [comment]
Also please don't open bug reports, just because you don't want to fill out the support template on the discord.
