### ISSUE TITLE
Crash when muting another player in a group (also unable to hear other player(s) in the group)

### ISSUE THREAD

**Issue by SirOMGitsYOU** [henkelmax/simple-voice-chat#395]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
When pressing the mute sound button the game client produced a crash, the person involved in the crash was unable to hear the other party in the group prior to pressing mute

**Steps to reproduce the issue**
1. Invite someone to party
2. press mute button

**Expected behavior**
Mute the other person

**Log files**
Crash report - https://paste.vcnet.work/CJ3C4k7uH5

**Versions**
- Minecraft version 1.16.5
- Forge/Fabric/Bukkit/Spigot/Paper version 36.2.33
- Mod/Plugin version 2.2.32

**Other mods**
Part of my modpack - https://www.modpackindex.com/modpacks/compare?modpacks=6279

**Screenshots (Optional)**
n/a

**Comment by henkelmax** [comment]
> Crash report - https://paste.vcnet.work/CJ3C4k7uH5

Please send me the full logs

**Comment by henkelmax** [comment]
Also this works perfectly fine for me.
![image](https://user-images.githubusercontent.com/13237524/162265806-523ff84e-c3df-4f50-baff-69bf49c657f9.png)
![image](https://user-images.githubusercontent.com/13237524/162266263-d43d25a1-1c62-4f23-b623-1a4aac1ba27d.png)

Please check if this happens for you without any other mods.

**Comment by SirOMGitsYOU** [comment]
> > Crash report - https://paste.vcnet.work/CJ3C4k7uH5
> 
> Please send me the full logs
https://transfer.sh/SkXy5S/latest.log

I will test on my end with no mods as this was submitted by another user

EDIT: I have checked on my end with no mods and it works fine so it may be a combination of a mod conflicting somewhere hopefully the latestlogs can help

**Comment by henkelmax** [comment]
> https://transfer.sh/SkXy5S/latest.log

This file is 50MB. Please restart the game and get fresh logs that are shorter.

> I will test on my end with no mods as this was submitted by another user

Thanks

**Comment by SirOMGitsYOU** [comment]
> > https://transfer.sh/SkXy5S/latest.log
> > This file is 50MB. Please restart the game and get fresh logs that are shorter.

I'll request them to send a new log that's smaller 

> > I will test on my end with no mods as this was submitted by another user
> Thanks

Tested on my end with no mods can't reproduce so waiting on the new logs

**Comment by SirOMGitsYOU** [comment]
Here's another crash report they sent through - https://crashy.net/0faejwf5tzBRt9pJ2uRy.

They've just tried it again and it's working again so it seems like it's potentially an issue that only occurs after long game play or a one-off issue. Sorry to bother you in this, I'll leave the crash reports above etc and if we get any further updates on this issue and can re-produce with a smaller log file then will update the ticket :)

**Comment by henkelmax** [comment]
> Here's another crash report they sent through - https://crashy.net/0faejwf5tzBRt9pJ2uRy.

That's not a log. Please send me the actual log.

**Comment by SirOMGitsYOU** [comment]
> > Here's another crash report they sent through - https://crashy.net/0faejwf5tzBRt9pJ2uRy.
> 
> That's not a log. Please send me the actual log.

They weren't able to have it crash again after restarting the game so it was likely a one-off issue thus they weren't able to send the log through. I will update the issue if it happens again with a new log

**Comment by henkelmax** [comment]
Alright, I will close the issue for now. Please feel free to reopen it once it happens again.

**Comment by henkelmax** [comment]
I just experienced the same issue. This happens when you are replacing the mod jar file while the game is running.
https://gist.github.com/henkelmax/12c657a2b9e37335443c22fa228bc74d

**Comment by woutwoot** [comment]
For us it does not have to do with replacing the jar.

I had my friend over yesterday and was planning to try again so I could get you the proper logs etc... Suddenly we did not have any issues and group chat worked. Because of that, I'm not sure what the actual cause was, but we will try again. 

Difference between yesterday and before is that my friend was now in the same network the server is hosted on (like me). We will test again remotely later, will report if the issue persists then. (so it's ok this is closed for now)
