### ISSUE TITLE
Brazilian Portuguese (Full Translation)

### ISSUE THREAD

**Issue by Sanadriell** [henkelmax/simple-voice-chat#399]
pt_br

[Translation](https://gist.github.com/Sanadriell/da9d872ba875157da32e803abe70351e)

**Comment by henkelmax** [comment]
You are missing  `message.voicechat.other_volume`, `message.voicechat.other_volume.description` and I think one other translation.

**Comment by Sanadriell** [comment]
> You are missing `message.voicechat.other_volume`, `message.voicechat.other_volume.description` and I think one other translation.

It's done.
I had used some old version of this file and that's why I was missing these ones.
The other translation I was also missing `message.voicechat.invite_player´.
And I've fixed some part where I made a mistake.
Thank you for letting me now!

**Comment by henkelmax** [comment]
Thank you!
