### ISSUE TITLE
Updated Translation

### ISSUE THREAD

**Issue by Sanadriell** [henkelmax/simple-voice-chat#401]
pt_br

https://gist.github.com/Sanadriell/a09d7dd1016540e3afb404cd5fa115bd
I've made some adjustments.

And I'd like to ask if it's possible to remove the fork I unintentionally created

**Comment by henkelmax** [comment]
I hope this is the last time updating the translation.
Please double check your translations before submitting them, next time.

Anyways. Thank you for your contribution.

**Comment by Sanadriell** [comment]
> I hope this is the last time updating the translation. Please double check your translations before submitting them, next time.
> 
> Anyways. Thank you for your contribution.

Sure
I'll pay more and more attention to this

Thank you for your comprehension
