### ISSUE TITLE
Audio Playing Bot

### ISSUE THREAD

**Issue by EltoCode** [henkelmax/simple-voice-chat#402]
A way to stream music from the local machine/streaming service for everybody in a group is something that would be useful.

I'm aware of the companion mod that lets you add music one at a time to minecraft. But that's mainly for adding music that's likely to be constantly used. Not for having a quick listen, or for playing many songs back to back, quickly. 

Perhaps there could be an option to add a bot to a group with a url for a playlist or some such.

**Comment by henkelmax** [comment]
Such things won't be added to this mod. There is an API that is capable of doing that.
If you want such a feature, you can implementit yourself as an addon to the mod.
