### ISSUE TITLE
You need Simple Voice Chat to play on this server

### ISSUE THREAD

**Issue by TheButterbrotMan** [henkelmax/simple-voice-chat#407]
**Bug description**
Simple Voice Chat does not work on server. ![Screenshot](https://user-images.githubusercontent.com/64548098/170386960-971eb03c-ecf5-4d34-b028-3c1eb31bc748.png)

**Steps to reproduce the issue**
1. Download https://www.curseforge.com/minecraft/modpacks/deathdusk (2.0.5 & 2.0.6)
2. Make a server
3. Try to join

**Expected behavior**
I want to connect without problems

**Versions**
- Minecraft version 1.18.2
- Fabric 0.14.6
- Mod/Plugin version: 1.18.2-2.2.44

https://bytebin.lucko.me/JZClT9p2R1

**Comment by TheButterbrotMan** [comment]
Also when i disable forceVoicechat, it doesnt work on server. When i type in commands i get
![image](https://user-images.githubusercontent.com/64548098/170387105-b52e9903-4559-4c48-ade8-eb90def13853.png)

**Comment by TheButterbrotMan** [comment]
The mod is 100% installed on the server and i dont know why it dont work.

**Comment by henkelmax** [comment]
Please visit the discord if you have issues setting up the mod.
This is not a bug.

**Comment by TheButterbrotMan** [comment]
I dont think its a setup problem, because it was working and just stopped working without a update or any changes directly to it.
