### ISSUE TITLE
Random crash while talking to players

### ISSUE THREAD

**Issue by Lapiukas6** [henkelmax/simple-voice-chat#408]
**Bug description**
Randomly appears when someone joins or you join a group, you cant hear anyone. If you press the settings the game crashes also dont know if this is related to the issue but all textures from Simple Voice Chat are corrupted textures

**Steps to reproduce the issue**
1. Make someone join or join (you) a group
2. If you cant hear anyone it worked
3. Go into the settings tab
4. And you crash

**Expected behavior**
1. Expected to hear my friends
2. Expected it to not crash

**Log files**
[crash-2022-05-27_14.50.25-client.txt](https://github.com/henkelmax/simple-voice-chat/files/8786470/crash-2022-05-27_14.50.25-client.txt)

**Versions**
- 1.18.1
- forge-1.18.1-39.0.88-universal
- voicechat-forge-1.18.1-2.2.36

**Other mods**
According to Not Enough Crashes:

Suspected Mods: 
- Simple Voice Chat (voicechat)
- Minecraft (minecraft)

**Mod list:**

- Tinkers' Construct
- Compact Machines 4
- Simple Voice Chat
- Not Enough Crashes
- Flywheel
- Mantle
- Create
- CC: Tweaked
- Storage Drawers
- JEI (Just Enough Items)

**Screenshots (Optional)**
None.

**Comment by henkelmax** [comment]
Please update the mod to the latest version and send me the latest.log and not the crash report.

**Comment by henkelmax** [comment]
Closed due to inactivity
