### ISSUE TITLE
Possible geyser support

### ISSUE THREAD

**Issue by amsam0** [henkelmax/simple-voice-chat#409]
**Is your feature request related to a problem? Please describe.**

Currently players connected via GeyserMC behave like vanilla Java clients and the voice chat is not supported for them.

**Describe the solution you'd like**

Allow geyser players to connect and speak. One idea is a discord bot that would 1. stream the audio for the Geyser player into a voice channel and 2. get the audio for the player speaking and emulate the voice chat for them.

This has a major downside of only allowing one Geyser player to connect but this may be able to be avoided by calling the user via DM, if that’s possible with bots.

I believe this may be out of the context of this mod so this could be implemented as a plugin. I am happy to help with making this but I might need some help with the simple voice chat API.

**Comment by henkelmax** [comment]
This could be done with a plugin, but we won't implement that. The API is completely public and pretty well documented.
