### ISSUE TITLE
Server shuts down when I have both GeyserMC and Simple Voice Chat

### ISSUE THREAD

**Issue by WowWhatAName** [henkelmax/simple-voice-chat#410]
**Bug description**
When I run my small Paper 1.18.2 (Shockbyte Hosting) server it shuts down. The errors say "Failed to run voice chat at UDP port, make sure no other application is running at that port" and "Voice chat server error Address already in use"

I was wondering if theres a way to fix this, or if it's just not compatable with Geyser.

**Steps to reproduce the issue**
1. Run GeyserMC and Simple Voice Chat

**Expected behavior**
Run the server correctly.

**Log files**
[Logs.zip](https://github.com/henkelmax/simple-voice-chat/files/8801736/Logs.zip)

**Versions**
- 1.18.2

- PaperMC/Spigot/Bukkit 1.18.2

- voicechat-bukkit-1.18.2-2.2.33

**Other mods**
-GeyserMC
-Floodgate
-ProtocolLib

![Screenshot (6)](https://user-images.githubusercontent.com/106569977/171086365-ebeddb63-cec3-4292-9219-70762195b486.png)

**Comment by henkelmax** [comment]
This is completely intended and not a bug. If you need help setting up the mod, visit the discord.
