### ISSUE TITLE
Cannot get this to work (MacOS Microphone Permission Hack) - MacOS Monterey vers 12.4

### ISSUE THREAD

**Issue by liebl00m** [henkelmax/simple-voice-chat#411]
I've been trying to load this mod for a minecraft server I just joined, but have been completely unsuccessful for hours now. 

The guide I've been referring to is [this one ](https://github.com/henkelmax/simple-voice-chat/tree/1.18.2/macos)

I started by installing it through Curseforge, got to the drag-n-drop microphone perm GUI, dragged my curseforge launcher instillation (as per the guide). Closed the GUI, the game basically launched automatically. If I tried to quit it (so as to "restart the launcher", as the GUI says I should, it'd just send me in the same cycle.

Once I opened the game, the mod has loaded fine, but when I opened the in-game chat, it had the message 
[Simple Voice Chat] No microphone permission. Please Check Security & Privacy Settings
with no apparent output when I attempted a mic test.

I went round in that circle a few times, then encountered the "Minecraft wants to use your confidential information stored in "mojangTokenService" in your keychain" pop-up bug, where I wasn't able to grant minecraft the permission (even went through every mojang keychain entry and manually updated the perms), and minecraft would end up logged out. 

I gave up, uninstalled all the mods, ditched curseforge. I downloaded the fabric installer, fabric api and the voice chat mod from the curseforge website, ran it all. Ended up in the same cycle as mentioned above (running the game, dragging the launcher to the GUI, launching the game, getting the 'no microphone permission' message).

I've tried launching the game in the terminal w the "open -a Minecraft" command (I don't know how else to do so), just opened the launcher without a mic permission request popup. If there is a different way to "run the launcher in the terminal", please let me know. I am no coder, all my knowledge is from google searches and wikihow. 

Finally, I tried the standalone vers. I wasn't really sure what to do differently with this, I installed java 17 as per recommended, and then I tried launching the game with it in the mod folder, and both voice chat files in the mod folder: nothing. If the standalone file is in the mod folder by itself (with fabric api ofc), then the mod doesn't even come up.

Sorry for the wall of text. I'm not a computer person, and it's possible that I'm just misinterpreting a simple instruction here. If this is the case, please let me know, I just wanna be able to use proximity chat on this random minecraft server and get to know some people ;-; If you need screenshots of anything, please let me know.

**Comment by henkelmax** [comment]
Please join the discord if you need help with the patcher
