### ISSUE TITLE
Can't get launcher to gain Mic permissions (macOS Monterery)

### ISSUE THREAD

**Issue by liebl00m** [henkelmax/simple-voice-chat#412]
Referring to [this guide](https://github.com/henkelmax/simple-voice-chat/tree/1.18.2/macos), I've been unable to allocate my minecraft launcher the necessary microphone permissions for the simple voice chat mod. I'd like to preface this by saying that I'm not a computer person in any way, all my knowledge about this is gained from google searches and wikihow. 

After following the instructions in the MacOS Microphone Permission Hack, I installed the mod (using first curseforge, then just using the fabric installer, api and mod files in my normal launcher). I was able to get up the Mic perm GUI, but after dragging and dropping the relevant minecraft launcher (as per the guide's instructions), the launchers remained unchanged and, when loading in a multiplayer server, I got this message when I opened chat:

[Simple Voice Chat] No Microphone Permission. Please check Security & Privacy settings

The mic didn't seem to be picking up anything when I attempted a mic test; I got no change or indication if of sound input.

**The issue here seems to be that the launcher is not receiving the needed mic permissions. I am having no issue with any other element of the mod.** 

**Steps to reproduce the issue**
- download fabric launcher, fabric api, simple voice chat mod
- open launcher, select fabric launcher game version
- add the api and the simple voice chat jar files to the mod folder
- launch the game
- macOS microphone permissions GUI pops up, drag the minecraft launcher from application folder
- accept the pop-up asking if I want to continue
- close the GUI, game launches automatically
- If I quit and relaunch the game (as per the instructions), it takes me back to the "no mic perms" GUI. rinse and repeat
- game loads in modded version, mod appears functional
- enter multiplayer server (w all mods installed and running). All aspects of the Voice Chat mod seem to be fine
- Open chat, see the "No Microphone Permission" message

I haven't seen the expected request for microphone permission pop-up at any point in the process via the launcher, despite attempting the process many times, via the launcher, through curseforge etc. Even encountered the "mojangTokenService" keychain bug and uninstalled and reinstalled at that point (as well as switching from curseforge to the mod folder & fabric installer).

**Log files**
I'm willing to provide any log files if someone can show me how, re: not a computer person. I don't even know what you'd need or how I would get it. 

**Versions**
- Minecraft version 1.18.2
- Fabric Loader 1.18.2
- Simple Voice Chat mod vers 1.18.2

**Other mods**
I had Fabric API and the voice chat mod in the mods folder. At a time, I included the standalone version (with the original verison still in the mod folder, and then without).

I literally made a github account so I could report this.. If anyone else needs more information/screenshots/anything I haven't provided, please let me know, and so sorry if the formatting is terrible, I have no idea what I'm doing ;-;

**Comment by henkelmax** [comment]
As already said. If you need help patching the launcher, visit the discord.
