### ISSUE TITLE
Reconecting Voice chat to player

### ISSUE THREAD

**Issue by TheHackerYTB** [henkelmax/simple-voice-chat#413]
Trying to solve the reconecting issue and client not connected 
I switched the port like my host telled me and was good and now this
Yesterday it worked but now not
And i get rendomly get kicked of server with disconected

1.16.5
Forge
2.2.44

**Other mods**
Useful backpacks 
Camera Mod
Never Enough Curency 2
MrCrayFish Furniture/Car mod 
SecurityCraft 
JEI
Sit

**Comment by henkelmax** [comment]
If you need help setting up the mod, please visit the discord.
