### ISSUE TITLE
Client microphones cannot connect to server

### ISSUE THREAD

**Issue by peeruzxe** [henkelmax/simple-voice-chat#416]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Apparently not connected to server but everything is set up correctly. Opened this ticket yesterday and today I saw for some reason it was deleted without notifying me.

**Expected behavior**
Client microphone connecting to server and working

**Versions**
- Minecraft version 1.18.2 Better minecraft v7
- Forge 40.0.54
- Mod/Plugin version 2.2.44

**Other mods**
simple cars, exlines furniture, mrcrayfish furniture, mrcrayfish guns, create, flywheel, security craft, create chunkloading, framework, mc paint (and all the mods from better minercaft v7)

**Comment by henkelmax** [comment]
Please explain your issue properly, fill out the bug template and make sure to include logs.

**Comment by peeruzxe** [comment]
> Please explain your issue properly, fill out the bug template and make sure to include logs.

what logs? i'm filing this with all the info that should be needed

**Comment by henkelmax** [comment]
We always need logs.
Also you described your issue very poorly, so I don't even know what your issue is.

**Comment by peeruzxe** [comment]
> We always need logs. Also you described your issue very poorly, so I don't even know what your issue is.

on my server me and my friends get an error every time we try to speak with the mod. when we do try, we get the "cannot connect error" and i've set everything up properly. where am i supposed to get the logs?

**Comment by henkelmax** [comment]
This is not a bug. Your server is just set up incorrectly. For support, join the discord server. GitHub is the wrong place for that.
