### ISSUE TITLE
[API] connection.setGroup(null) doesn't work (see screenshot)

### ISSUE THREAD

**Issue by Mimexe** [henkelmax/simple-voice-chat#417]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
connection.setGroup(null) doesn't work it's remove the hud but i can hear players

**Steps to reproduce the issue**
1. use connection.setGroup(Group)
2. and set to null
3. Speak, you can hear/speak to the player
4. And the mod make the group is left but speaking/hearing work

**Log files**
No error

**Versions**
- 1.16.5
- Forge
- 2.2.45

**Other mods**

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/74558118/173886014-1e4feca0-cba8-4058-a489-b34eb39b0e65.png)

**Comment by henkelmax** [comment]
Can you please explain the issue in proper english?

**Comment by henkelmax** [comment]
Nevermind. I found the issue, you were describing. Thanks for reporting this!
