### ISSUE TITLE
sculk activates with your voice with the mod instaled server side

### ISSUE THREAD

**Issue by 4567gio** [henkelmax/simple-voice-chat#422]
feature requested
i would like that when you talk close to a sculk sensor or warden it activates (it's not a problem)

enchancement
when you talk the sculk sensor or the warden activates/hears your voice

alteratives
a command that detects when someone talks so you can make diferent things with the command

**Comment by henkelmax** [comment]
https://github.com/henkelmax/voicechat-interaction
