### ISSUE TITLE
Invite to Group via Social Interactions Menu

### ISSUE THREAD

**Issue by braxtonhall** [henkelmax/simple-voice-chat#423]
**Is your feature request related to a problem? Please describe.**
I think the process of having a friend join your current group could be made a little bit more accessible than asking them via chat to open the group menu and select your group.

**Describe the solution you'd like**
For players in the Social Interactions Menu (accessed via <kbd>P</kbd> in vanilla), each player could have an invite to group button. If the inviter is already in a group, the invitee is invited to the current group. If the inviter is not yet in a group, they are prompted to create one.

On the invitee's side, they are prompted to join the group.

**Comment by henkelmax** [comment]
All of this is already a thing. On fabric and quilt you can invite players from the social interactions menu. And generally, you can use the /voicechat invite command.
