### ISSUE TITLE
voice chat not working on server( but it works in single player?)

### ISSUE THREAD

**Issue by Kaicidify** [henkelmax/simple-voice-chat#424]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
1. Go to 'bottom left side'
2. Click on 'nothing'
3. Scroll down to 'nothing'

**Expected behavior**
just the voice chat not working and saying it isnt connected when i use aternos mc server
**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.19
- Fabric
- Mod/Plugin version voicechat-fabric-1.19-2.2.45.jar

**Other mods**
A list of the other mods/plugins that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod/plugin is installed.
If not, please narrow down the mod(s)/plugin(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.
![image](https://user-images.githubusercontent.com/108632312/177056890-1387b6e4-b165-4c87-bd77-eb3f3f87c3af.png)

**Comment by henkelmax** [comment]
Visit the discord for help
