### ISSUE TITLE
Voicechat 1.19-2.2.45 crashes MC Java on Mac

### ISSUE THREAD

**Issue by iamsausage** [henkelmax/simple-voice-chat#425]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Minecraft starts fine under Fabric loader 0.14.8-1.19. Terrain loads, and 5-10 seconds later, game crashes with Error Code 6.

**Steps to reproduce the issue**
1. Launch Minecraft Fabricloader 014.8-1.19
2. Wait 5-10 seconds.
3. Game crashes, Error Code 6.

**Log files**
[Log](https://drive.google.com/file/d/1h5LJjZL_trancSGBefpOew1bz2j2aYT4/view?usp=sharing)

**Versions**
- Minecraft version 1.19
- Fabric 0.14.8-1.19
- Voicechat 1.19-2.2.45

**Other mods**
custom-portals-3.1.0
exlinefurniture-fabric-1.19-v2.2.0
fabric-api-0.57.0+1.19
Mo-Glass-1.6.1-MC1.19
modmenu-4.0.0
optifabric-1.13.4
preview_OptiFine_1.19_HD_U_H8_pre2
starlight-1.1.1+fabric.ae22326
vanilla-essence-3.2.0-1.19

Eliminated each mod in turn, and crash persisted until voicechat was removed.

**Comment by henkelmax** [comment]
Are you on macos 10.15 or lower?

**Comment by iamsausage** [comment]
Yes, 10.13.5.

**Comment by henkelmax** [comment]
Voice chat requires MacOS 10.16 or newer.

**Comment by iamsausage** [comment]
OK. Odd that it’s been working fine up until now.

Thanks anyway.
