### ISSUE TITLE
server connection problem

### ISSUE THREAD

**Issue by Stu-C15** [henkelmax/simple-voice-chat#426]
**Bug description**
i don't know for sure but it looks like the mod is not connecting to the server, i'm playing in a Aternos serve with some other mods but the voice chat is not connecting it keeps showing a plug with a red simbol on it 
![20220705_105535](https://user-images.githubusercontent.com/108741171/177346659-93edb353-9cd3-440c-983e-8d556843226e.jpg)

**Steps to reproduce the issue**
1. just install de mod on a Aternos server using fabric and it should happen 

**Expected behavior**
i expected it to work properly since the start

**Log files**
i don't know how to provide it, it dosen't show in the error logs 

Versions
- Minecraft java edition version 1.18.2
- Fabric 0.14.8
- 2.2.45

**Other mods**
appleskin-fabric-mc1.18.2-2.4.0.jar
cardinal-components-api-4.1.4.jar
cloth-config-fabric-6.2.62.jar
EnvironmentalArmor-1.18.2-1.4.4.jar
fabric-api-0.57.0+1.18.2.jar
farmers-delight-fabric-0.2.1.jar
flytre_lib-1.18.2-1.8.2-fabric.jar
hookshot-r25.jar
IronChests-1.7.2.jar
jam-lib-0.0.5.jar
jei-1.18.2-fabric-10.1.0.208.jar
journeymap-1.18.2-5.8.5-fabric.jar
lithium-fabric-mc1.18.2-0.7.10.jar
lovely_snails-1.0.4+1.18.jar
mavm-mc1.19-fabric-1.0.8a.jar
Origins-1.18.2-1.4.1.jar
Origins-Classes-1.18.2-1.3.0.jar
pipe-1.18.2-1.7.1-fabric.jar
rightclickharvest-2.1.1.jar
Strawgolem-fabric-1.18.2-2.0.0b1.jar
travelers-backpack-1.18.2-7.1.2.jar
Twerk_Mod-fabric-1.0.jar
voicechat-fabric-1.18.2-2.2.45.jar

**Comment by henkelmax** [comment]
Visit the discord for help
