### ISSUE TITLE
voice chat unavailable error

### ISSUE THREAD

**Issue by phivumop** [henkelmax/simple-voice-chat#427]
can you guys help me ? i have the voice chat unavailable error too. i play singleplayer connect radmin with my friend. Thanks

**Comment by henkelmax** [comment]
Visit the discord if you want help. This is not a bug!

**Comment by phivumop** [comment]
ok
but where is the discord link ?

**Comment by henkelmax** [comment]
Read the mod description. You literally can't miss it!

**Comment by phivumop** [comment]
ok
