### ISSUE TITLE
Works, but people keep cutting in and out

### ISSUE THREAD

**Issue by fayces** [henkelmax/simple-voice-chat#43]
I have lowered the audio bitrate down to 10k, but people are cutting out so much that it's impossible to hear anyone.

I'm playing on a pebblehost server with ~36 mods, and I just used the port that the server came with.

**Comment by fayces** [comment]
Also if it helps- whenever I do /voicechat test the requests time out unless its to myself

**Comment by henkelmax** [comment]
Have your read the wiki?

**Comment by fayces** [comment]
> Have your read the wiki?

Yeah- I don’t think it says anything about the issue anywhere there

**Comment by henkelmax** [comment]
Did you restart the server after lowering the bitrate?
Maybe you have packet loss.

**Comment by fayces** [comment]
> Did you restart the server after lowering the bitrate?
> Maybe you have packet loss.

Yeah I’ve restarted the server a bunch and even upgraded it. I’m pretty sure it is packet loss or something. The voice chat works alright when there’s only 2 people online. However, when there’s more than that it gets super choppy so everyone ends up using discord.

The server specs are good enough that I don’t think it’s a CPU/memory issue. (Intel i9-9900K / Xeon E-2288G @ 5Ghz @ 7GB DDR4 2666MHz Memory)

**Comment by henkelmax** [comment]
What's the network speed of your server?

**Comment by fayces** [comment]
> What's the network speed of your server?

If my ping is what you're talking about, it's around 90ms and is similar for everyone else

**Comment by henkelmax** [comment]
I mean the download and upload.
But the problem you described sounds like packet loss.
You could test this with for example [WinMTR](https://sourceforge.net/projects/winmtr/).

**Comment by PoggersNation** [comment]
I’m having the same issue, tested people and server for packet loss and upload/download speed and there were no issues, download/upload above 80 for everyone and no packet loss, tried setting output buffer to 16, made no noticeable difference. However, everyone has no issues with /voicechat test. Is there anything else I can try?

**Comment by henkelmax** [comment]
Does this only happen if the bitrate is set to 10.000?

**Comment by PoggersNation** [comment]
That was one thing I was confused on, what bitrate are you referring to, and where I would be able to change said setting.

**Comment by henkelmax** [comment]
In the server config. It's the audio bitrate. Higher values mean better sound quality.

**Comment by PoggersNation** [comment]
What exactly do you define as the server config, because I'm looking in server properties and don't see a variable named that, and in the config folder I don't see a voicechat config file either. Unless is it a variable that you have to add to the server properties file?

**Comment by fayces** [comment]
> I mean the download and upload.
> But the problem you described sounds like packet loss.
> You could test this with for example [WinMTR](https://sourceforge.net/projects/winmtr/).

Here's that MTR test. https://i.gyazo.com/cfd74435d4c610ee1280b6183842c93b.mp4

**Comment by PoggersNation** [comment]
Nvm just read the wiki, I understand now

**Comment by PoggersNation** [comment]
Yeah, so bringing it to 10 kbps makes the cutting out stop completely, the only problem being that it sounds like we are in a 2012 cod lobby. Any ideas how to do it at a higher bitrate? Or is that just not possible.

**Comment by henkelmax** [comment]
> > I mean the download and upload.
> > But the problem you described sounds like packet loss.
> > You could test this with for example [WinMTR](https://sourceforge.net/projects/winmtr/).
> 
> Here's that MTR test. https://i.gyazo.com/cfd74435d4c610ee1280b6183842c93b.mp4

You cut of the most important part: the loss in %

**Comment by henkelmax** [comment]
> Yeah, so bringing it to 10 kbps makes the cutting out stop completely, the only problem being that it sounds like we are in a 2012 cod lobby. Any ideas how to do it at a higher bitrate? Or is that just not possible.

Then just set it back to 16k.

**Comment by fayces** [comment]
I decided to just downgrade my server and use Glibys Voice Chat

**Comment by Rhyguy1** [comment]
same thing is happening for me on my own server, any new solution or fix?
