### ISSUE TITLE
Support Adjusting Client Ports

### ISSUE THREAD

**Issue by sfxworks** [henkelmax/simple-voice-chat#430]
**Is your feature request related to a problem? Please describe.**

Hello, we are a host that does port mapping for clients. All containers get assigned an internal IP address and have your port `24454` open. In order to save IPv4 space, we port forward to a random port on a smaller number of external IP addresses. 

For example, when we have a server named play-0 with port `24454` requested to be open, we would open `30950` on an external address and map it to that internal IP/Port. 

However, as it appears there is no way to adjust the client connecting port, we have to resort to alternatives to get it working for clients.

**Describe the solution you'd like**
I want the ability to have the client specify the port in their config file.

**Describe alternatives you've considered**
We have considered assigning all servers that use your mod an IPv4 address. However, we believe this is wasteful due to the [current shortage](https://www.arin.net/resources/guide/ipv4/).

We have considered IPv6, though this would require quite the overall that not all clients would support [yet](https://www.google.com/intl/en/ipv6/statistics.html).

**Comment by henkelmax** [comment]
You can already do that. Just set `voice_host` on your server to the IP and port, the voice chat should connect to.

**Comment by sfxworks** [comment]
Thanks! Noted.
