### ISSUE TITLE
Error occurs during loading of mod

### ISSUE THREAD

**Issue by DeviUserYT2** [henkelmax/simple-voice-chat#432]
Whenever the game opens with Simple Voice Chat mod an error occurs and it states that it encountered an error during the sided_setup event phase

**Steps to reproduce the issue**
1. Open Minecraft
2. Set installation to Forge 1.19 ver. 41.0.100
3. Press play

**Expected behavior**
The game should open and load the mod normally with no issue

**Log files**
https://gist.github.com/DeviUserYT2/0e4b8302787b536e0c0d3a20ab62b5a3
https://gist.github.com/DeviUserYT2/e8f49ab09c66561d5291f5a1088f8d3e

**Versions**
- Minecraft version : 1.19
- Forge version : 41.0.100
- Mod version : 2.2.45

**Other mods**
Optifine
Chat Heads
Cloth Config
Sound Physics Remastered

**Screenshots (Optional)**
**When alone**
![image](https://user-images.githubusercontent.com/62062337/179942623-b93df7ea-05bd-46bb-9b9d-1cb32df3507b.png)

**With any other mod**
![image](https://user-images.githubusercontent.com/62062337/179942273-8d366228-f592-43d6-8a1d-e9c072a73b80.png)

**Comment by henkelmax** [comment]
You are using a version of the mod thats built for an older Forge version.
Forge had a breaking change in 41.0.94, so you need to update to the latest voice chat version.
