### ISSUE TITLE
Pehkui integration for pitch

### ISSUE THREAD

**Issue by andersmmg** [henkelmax/simple-voice-chat#434]
**Is your feature request related to a problem? Please describe.**
Not really a problem

**Describe the solution you'd like**
It would be cool if pitch and volume could scale with the player scale, so like high pitched when tiny

**Describe alternatives you've considered**
None that I can find, it doesn't seem like manual pitch scaling is even available currently

**Additional context**
https://github.com/Virtuoel/Pehkui

**Comment by henkelmax** [comment]
You can do that with the voice chat API.

**Comment by henkelmax** [comment]
See https://github.com/henkelmax/replay-voice-chat for reference
