### ISSUE TITLE
1.19 Forge Crash 

### ISSUE THREAD

**Issue by wmiltp** [henkelmax/simple-voice-chat#435]
**Steps to reproduce the issue**
1. Launched Minecraft 1.19 Forge with installed Voice Chat modification 2.2.45
2. Saw crash

**Expected behavior**
I just installed this modification and 1.19 Forge crashes

**Log files**
https://gist.github.com/wmiltp/ef7eae382feb1e2547f76aacfd13c9c6

**Versions**
- Minecraft 1.19 
- Forge
- Simple Voice Chat 2.2.45

**Comment by henkelmax** [comment]
You are using a version of voice chat thats outdated. It was built for Forge 41.0.93 and lower. Either use an older forge version or update the mod to the latest version.
