### ISSUE TITLE
mojangTokenService popup will not stop appearing even after restarting (Mac)

### ISSUE THREAD

**Issue by NoviOnGitHub** [henkelmax/simple-voice-chat#437]
Bug description:
Before all of this, I dragged the Minecraft application into the area where it told me to. 
When you load up Minecraft Launcher the mojangTokenService keychain popup will appear immediately, which is normal. When I type my password into the area and then click always allow, it pops up again instantly, which is also normal. But after I restart my mac, it will still pop up and have the same issues. I don't need the mod right now, so I click deny and then click play on the launcher, which will load for a bit and then crash (exit code: 1). I load up Minecraft launcher again after that and the popup still appears. **So basically the mojangTokenService keychain popup will not go away no matter what.**  

Steps:
1. Click on Minecraft
2. Popup appears
3. Type in password and click 'always allow'
4. Popup appears again
5. Restart mac
6. Click on Minecraft again, pop up appears once more
7. Click deny
8. Click play on the launcher
9. Game crashes (exit code: 1) 
10. Close the launcher
11. Open the launcher again 
12. Popup still appears

Expected behavior:
Clicking always allow then playing like normal, or restarting my mac and then clicking always allow to then have it work.

Log files: Unable to do so

Versions: 
- This happens when I try to load up any version in the vanilla launcher
- Started after downloading the Fabric simple voice chat mod and dragging Minecraft into the area where it told me to
- Simple voice chat 1.17.1

Other mods:
I had other mods downloaded from a friend's Minecraft boat racing mod pack (boat cam, timer, etc) but the problems didn't start happening until I dragged Minecraft into the area where it told me to. Plus all the problems are specific and relate to things with this mod, like mojangTokenSerive keychain popup.

Screenshots: 
https://user-images.githubusercontent.com/109996861/180889843-8285a0c0-4ad4-45aa-8cbf-a024cdb1d344.png
https://user-images.githubusercontent.com/109996861/180889987-719b205c-fac1-444e-a652-c347203ab5a8.png

Extra:
Thanks for helping!

**Comment by henkelmax** [comment]
Theres basically nothing we can do about that.
This just happens for some people sometimes.

**Comment by georgewesley** [comment]
There is a fix for this actually. I had the exact same issue. Turns out if you have your curseforge or minecraft folder in an area that uploads to icloud such as documents it will not work. As soon as I moved the folder to downloads instead it worked as intended.

**Comment by ChillBrian** [comment]
Has there been any other fixes? cause this didn't work for my friend
