### ISSUE TITLE
MC Crash when i try to talk

### ISSUE THREAD

**Issue by symsym-1629** [henkelmax/simple-voice-chat#439]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**

**Steps to reproduce the issue**
1. go to your world
2. Tap "caps lock" or disable PTT
3. MC crash 

**Expected behavior**
The little "talking" icon shows up

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
https://pastebin.com/pHGKUGU1

**Versions**
- Minecraft crack version
- Forge version
- Mod version

**Other mods**
 - TLauncher skin cape

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by symsym-1629** [comment]
oh and im on mac

**Comment by henkelmax** [comment]
We don't provide support for pirated Minecraft.
