### ISSUE TITLE
Server Crash when I upload the mod

### ISSUE THREAD

**Issue by piodotcom** [henkelmax/simple-voice-chat#44]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
When I upload the plugin on my server and I try to start it, the server crashes

**Steps to reproduce the issue**
1. Upload the 1.16.4-1.1.5 version of the mod on the server folder "mods"
2. Try to start the server

**Expected behavior**
I expected the server to start without problems, but only when I load this mod, it crashes

**Log files**
https://gist.github.com/piodotcom/a401bd6d78ca9dd4de05d8647adaa6ac

**Versions**
- Minecraft version 1.16.4
- Forge version 1.16.4-35.1.37
- Mod version 1.16.4-1.1.5

**Other mods**
Waystones, Coins, Bookshelf

**Comment by henkelmax** [comment]
> Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid value: 24454/udp

The port is a number. You can't change the protocol.
