### ISSUE TITLE
[Simple Voice Chat] No microphone permission. Please check Security & Frivacy sening

### ISSUE THREAD

**Issue by ROCK172009** [henkelmax/simple-voice-chat#446]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ROCK172009** [comment]
[Simple Voice Chat] No microphone permission. Please check Security & Frivacy sening[Simple Voice Chat] No microphone permission. Please check Security & Frivacy sening[Simple Voice Chat] No microphone permission. Please check Security & Frivacy sening[Simple Voice Chat] No microphone permission. Please check Security & Frivacy sening[Simple Voice Chat] No microphone permission. Please check Security & Frivacy sening[Simple Voice Chat] No microphone permission. Please check Security & Frivacy sening

**Comment by ROCK172009** [comment]
[Simple Voice Chat] No microphone permission. Please check Security & Frivacy sening

**Comment by henkelmax** [comment]
Please visit the discord for help
