### ISSUE TITLE
Restarting PipeWire on Linux causes a crash when selecting a microphone

### ISSUE THREAD

**Issue by coolpx** [henkelmax/simple-voice-chat#447]
**Bug description**
Restarting PipeWire 0.3.56 on Linux and then attempting to select a microphone crashes minecraft

**Steps to reproduce the issue**
1. Go to the voice chat GUI
2. Select a microphone
3. Restart PipeWire, I ran `systemctl restart pipewire --user`
4. Select a microphone

**Expected behavior**
I expected selecting a microphone to work as normal after restarting 

**Log files**
https://gist.github.com/coolpx/37f7984c28ec64baf5d7349722f8a8ae # Original crash
https://gist.github.com/coolpx/b71f0955942690c2df615861d5fcdffa # Recreation with no other mods

**Versions**
- 1.19.2
- Fabric 1.19.2, Paper git-Paper-112 1.19.2
- 1.19.2-2.3.2

**Other mods**
AppleSkin, Sodium, Iris, Mod Menu, and Fabric API.

**Comment by henkelmax** [comment]
Please send me the crash report.

**Comment by coolpx** [comment]
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/9280169/latest.log)

**Comment by henkelmax** [comment]
Thats just the logs. I need the crash report.

**Comment by coolpx** [comment]
I don't have a crash report because when this issue happens the game freezes and I need to kill the process.

**Comment by henkelmax** [comment]
Does that also happen without any mods installed?

**Comment by coolpx** [comment]
Yes.

**Comment by henkelmax** [comment]
> Yes.

Then this isn't an issue with the voice chat mod. I would suggest reporting this to the Minecraft bug tracker.

**Comment by coolpx** [comment]
Sorry, I thought you meant without any mods other than the voice chat mod. No, this does not happen without any mods installed.

**Comment by henkelmax** [comment]
Then I need crash logs to fix it. I can't fix it blindly, since I'm not on linux.

**Comment by coolpx** [comment]
I'll close this issue then, because it's impossible for me to get crash logs, and this is a very minor bug that nobody else will probably ever encounter.

**Comment by henkelmax** [comment]
Alright, sorry for that... I'll try to investigate the issue further and keep you up to date if I found something.
