### ISSUE TITLE
Y-Axis Control

### ISSUE THREAD

**Issue by printsammy** [henkelmax/simple-voice-chat#448]
**Is your feature request related to a problem? Please describe.**
Players are able to be heard from a Y-Axis range that shouldn't normally be heard from that range.

**Describe the solution you'd like**
A feature where you can edit specifically the Y-Axis to avoid conflicting audio from where you cannot hear it normally.

**Describe alternatives you've considered**
Using Sound Physics seems to cover that issue, but should be a feature on its own in Simple Voice Chat.

**Additional context**
Version 1.17.1

**Comment by henkelmax** [comment]
I just tested it and the audible range is exactly the same, no matter which axis.
