### ISSUE TITLE
Logging "Trying to authenticate voice connection"

### ISSUE THREAD

**Issue by mrmelon54** [henkelmax/simple-voice-chat#449]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**

It logs "Trying to authenticate voice connection" every second if it is unable to connect to the voice chat server.

**Steps to reproduce the issue**
1. Start a server with simple voice chat.
2. Start a client with simple voice chat.
3. If the client fails to connect to the voice chat server (packet blocking or not port forwarding it).
4. VoiceChatAuthentication error message..
5. Produces a really long log 

**Expected behavior**
It just doesn't do this cuz it's dumb...

**Log files**
```
[19:41:59] [VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection
```

**Versions**
- Minecraft/1.19.2
- Fabric/0.14.9

**Other mods**
I believe it's just this mod with the issue

**Comment by henkelmax** [comment]
Please visit the discord if you need help setting up voice chat. This is not a bug.

**Comment by mrmelon54** [comment]
The bug is not the fact that it logs.. the bug is that is logs every single second to destroy my log file.. for servers that don't connect..

**Comment by henkelmax** [comment]
Yes, thats completely normal if the server isn't set up correctly.

**Comment by mrmelon54** [comment]
So just log that the server is not setup correctly and don't continually log and create a massive log file

**Comment by henkelmax** [comment]
This is needed for debugging. Usually this could happen if there is a lot of packet loss. A message about that wouldn't help much there.
