### ISSUE TITLE
Distance based voice chat?

### ISSUE THREAD

**Issue by Demonic** [henkelmax/simple-voice-chat#45]
Verified this hasn't been answered in FAQ, and looked through a lot of the comments on curseforge.

Does this have distance based voice chat? As in, if someone is 5 meters away it sounds like they are 5 meters away vs someone who is 1 meter away who sounds louder? If not, I feel this could be a simple and wonderful addition to the mod.

**Comment by henkelmax** [comment]
Read the description of the mod.
