### ISSUE TITLE
My friend is on macos and the noise suppression is force disabled, so I have trouble talking to him.

### ISSUE THREAD

**Issue by stritzs** [henkelmax/simple-voice-chat#450]
**Bug description**
My friend is on macos, and on the newest version of 1.19 voice chat, and he can't enable noise suppresion. The option is grayed out, as if there's a barrier that got in the way.

**Expected behavior**
The expected behavior is for the button to not be grayed out, and to be able to use the feature.

**Log files**
There was no crash report, as there was no crash.
**Versions**
-1.19
- Fabric
- FO, MMC

**Comment by henkelmax** [comment]
The denoiser is not available for all platforms and architectures.
