### ISSUE TITLE
One Player Crashes upon interacting with the voice chat 

### ISSUE THREAD

**Issue by LiquidCreativity** [henkelmax/simple-voice-chat#452]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**
I have a server running with this mod installed, I have one specific player (she goes from a mac) who once anyone goes near her and speaks, she crashes, and it gives her -Error Code 6-. She disabled the voice chat and is able to work on the server just fine, so I'm halfway certain its the voice chat mod. I'm not sure what to do about it, so I was hoping you might have some kind of idea or direction to point me.

**Steps to reproduce the issue**
1.  player joins game
2.  speak near the player
3. player crashes 
4. error code 6

**Expected behavior**
I was hoping I could get said player to be able to interact with the voice chat mod while being in game.

**Log files**
I can't access her crash files, and she doesn't know how to do it sense she is on a mac.

**Versions**
- 1.19.2
- Fabric
-1.19.2-2.3.5

**Other mods**
voicechat
wthit
wraith
techreborn
sound physics 
reborncore
quartz-elveator
-megane
mcw lights/mcw doors
rouhglyenoughitems
modmenu
ironchests
DungeonsArise
Croptopia
cloth
Culinaire
dawn
blockus
trinkets
floral enchantments
pal
patchouli
emerald tools

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Which macos version is this?
The mod generally doesn't work for macos versions older than 10.15

**Comment by LiquidCreativity** [comment]
ah, I just checked with her and it is indeed older than that. thank you for your time =)
