### ISSUE TITLE
simple voice chat mod keeps crashing and I don't know why so I believe its something to do with the mod its self 

### ISSUE THREAD

**Issue by dynamicnightmare** [henkelmax/simple-voice-chat#455]
it just happens when I try to start Minecraft and it says that the error occurred at 

org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar%2391!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}

**Comment by henkelmax** [comment]
Please fill out the bug template
