### ISSUE TITLE
[Request] Configurable X and Y offset for group chat overlay.

### ISSUE THREAD

**Issue by murao-kun** [henkelmax/simple-voice-chat#458]
**Is your feature request related to a problem? Please describe.**
I am developing modpack which adding different UI elemets, and some of them are being conflicting with Voice Chat mod. For example bedrock-like paperdoll character on top left of the screen.

**Describe the solution you'd like**
I am suggest to add X and Y offset to group chat overlay, that will make me able to move it to another possition.

**Describe alternatives you've considered**
There is no other alternatives.

**Additional context**
Will provide if it's will be need.

**Comment by henkelmax** [comment]
Thats already in the mod. Read the configuration section of the wiki.
