### ISSUE TITLE
Option to mute new players by default

### ISSUE THREAD

**Issue by Yahm0n** [henkelmax/simple-voice-chat#461]
When livestreaming, I want to be able to reliably control who can talk to me.  Per player volume control is somewhat useful for this, but new people popping into the server will be audible until I manually disable them, putting me at risk for forgetting or not catching it in time.

I would like a checkbox which, if checked, would cause new players to be automatically muted until I manually change their volume.

**Comment by henkelmax** [comment]
This won't be a feature of the mod. You can do that with the voice chat API.
Alternatively you can use permission nodes.
