### ISSUE TITLE
Voice chat not connected.

### ISSUE THREAD

**Issue by AspenHD** [henkelmax/simple-voice-chat#462]
**Bug description**
When I try to talk I get the error.

**Steps to reproduce the issue**
1. Go to the game
2. Click on any voice chat key.
3. See error

**Expected behavior**
Open a voice chat menú or just talk.

**Log files**
[<script src="https://gist.github.com/AspenHD/38495e2d7a9b383cb91fae2b9c19a8e9.js"></script>](https://gist.github.com/AspenHD/38495e2d7a9b383cb91fae2b9c19a8e9)

**Versions**
- 1.18.2
- Forge 40.1.76
- 2.3.8

**Other mods**
- Blood Magic
- Comforts
- Corpse
- Cosmetic Armor Reworked
- Create
- CreativeCore
- Farmer's Delight
- Flywheel
- JEI
- Mantle
- MrCrayfish's Furniture Mod
- Patchouli
- PlayerRevive
- Security Craft
- Simple Shops
- Simple Voice Chat
- Xaero's Minimap (Fair-play Edition)
- Xaero's World Map
- YUNG's API
- YUNG's Better Desert Temples
- YUNG's Better Dungeons
- YUNG's Better Mineshafts

**Screenshots (Optional)**
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/113128132/189181598-6f3b771f-486b-4e6f-bb6e-6cfeb3bbc35c.png">

**Comment by henkelmax** [comment]
If you need help setting up the voice chat visit the discord, but this is not a bug.
