### ISSUE TITLE
Mod crashes client and server on start-up.

### ISSUE THREAD

**Issue by ccessarr** [henkelmax/simple-voice-chat#463]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Whenever I try to start my server or try to play, it gets to a point that it crashes saying:
`Simple Voice Chat (voicechat) encountered an error during the common_setup event phase`

**Steps to reproduce the issue**
Client:
1. Launch the Minecraft installation.
2. Loading screen shows up.
3. See error
Server:
1. Start the server.
2. Console loading everything.
3. See error

**Expected behavior**
Load to the main menu and get my server running.

**Log files**
[crash-2022-09-11_19.38.12-fml.txt](https://github.com/henkelmax/simple-voice-chat/files/9543187/crash-2022-09-11_19.38.12-fml.txt)

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.2.39
- Mod version: 2.3.9

**Other mods**
List is inside the crash log, starting at line 149.

**Screenshots (Optional)**
![imagen](https://user-images.githubusercontent.com/83140452/189541419-78057f88-da24-4f5e-9bc6-9c6ef12fcb80.png)

**Comment by henkelmax** [comment]
This error seems to be caused by RandomPatches. I'm not able to reproduce it. Please confirm to me if this happens without any other mods installed.

**Comment by ccessarr** [comment]
Dang it. 
Anyways it doesn't happen without another mod.

**Comment by ccessarr** [comment]
Isn't there any other way I can have RandomPatches and Simple Voice Chat in the same thing? Like downloading other version of one mod or another.

**Comment by henkelmax** [comment]
I tried it with both mods and for me it works fine.

**Comment by ccessarr** [comment]
Hmm, then it must be another mod causing it or something.

**Comment by henkelmax** [comment]
You need to check which mod is causing it.

**Comment by ccessarr** [comment]
Without RandomPatches it just doesn't finish up loading. I guess it's because of my components.

**Comment by ccessarr** [comment]
Did you use an older version of it or am I outdated? I got version 2.4.4

**Comment by henkelmax** [comment]
Thats the version I used too.

**Comment by ccessarr** [comment]
I went away for a bit and now I'm back, I tried it with only these mods:
![imagen](https://user-images.githubusercontent.com/83140452/189550941-5df7e39c-6119-4f16-b722-846ef7b29416.png)
And same error happend, then without RandomPatches and it was fine. So I don't know if there's something wrong with any file or you did something different.

**Comment by henkelmax** [comment]
You need to find out which mod causes it, I can't help you otherwise.

**Comment by ccessarr** [comment]
Found the problem.
Turns out connectivity-2.4-1.16.5 has some overlap with RandomPatches and that's what causes it to crash.
Thanks for helping me.
