### ISSUE TITLE
Voicechat Status Placeholder

### ISSUE THREAD

**Issue by Gabo6480** [henkelmax/simple-voice-chat#464]
Is is it possible to add a placeholder for the voicechat icons that should appear beside a player's name tag?
![image](https://user-images.githubusercontent.com/60194781/183222337-ac374ea1-e6a1-44e4-bf41-4daa9a72de3d.png)
I'm using the TAB plugin, and the "unlimited-nametag-mode" overrides the player's name tag, which effectively hides the icon.

A placeholder like `%voicechat_status%` that will render a player's icon in a client with voicechat.
Or, at least, a placeholder to access a value that represents the current icon that would have to be displayed, and another one that returns whether or not a player has voicechat installed.

**Comment by henkelmax** [comment]
There are already placeholders for the placeholder API. I don't plan on adding any other placeholders.

**Comment by Gabo6480** [comment]
Is there documentation on them? Exactly what value do they give?
voicechat_prefix_uses_voicechat
voicechat_prefix_no_voicechat
voicechat_prefix_disabled

**Comment by henkelmax** [comment]
You can change the values in the translations.yml
By default they are color codes.

**Comment by Gabo6480** [comment]
So:
voicechat_prefix_uses_voicechat -> Whether or not they have voicechat installed in their client
voicechat_prefix_no_voicechat -> ?
voicechat_prefix_disabled -> Muted?

**Comment by henkelmax** [comment]
voicechat_prefix_uses_voicechat -> Whether or not they have voicechat installed in their client
voicechat_prefix_no_voicechat -> Just the opposite of the above
voicechat_prefix_disabled -> Not muted. Disabled.

**Comment by Gabo6480** [comment]
"voicechat_prefix_disabled -> Not muted. Disabled."
So this means that they have voicechat installed but they have it disabled, thus, are unable to speak or hear anything?

**Comment by henkelmax** [comment]
Exactly.
