### ISSUE TITLE
1.12.2 version

### ISSUE THREAD

**Issue by SashaShtal** [henkelmax/simple-voice-chat#465]
**Is your feature request related to a problem? Please describe.**
There are no stable working voice chat mods on 1.12.2

**Describe alternatives you've considered**
I've considered Gliby's Voice Chat Reloaded, some other it's versions and forks, but no one of them works correctly (sometimes chat stop working without any errors in the console)

**Comment by henkelmax** [comment]
There are no plans on porting Simple Voice Chat to 1.12.2
