### ISSUE TITLE
add an icon next to players on the tab menu

### ISSUE THREAD

**Issue by ghost** [henkelmax/simple-voice-chat#466]
**Is your feature request related to a problem? Please describe.**
on servers where you don't _need_ the mod, its hard to tell who is actually using it unless you find them.

**Describe the solution you'd like**
I would like the microphone/no input icon next to players names to identify if they can/cannot talk.

**Comment by henkelmax** [comment]
There is placeholder API support. If that isn't enough, you can code something with the voice chat API.
