### ISSUE TITLE
walkie talkie integration

### ISSUE THREAD

**Issue by lostopkk** [henkelmax/simple-voice-chat#469]
**Is your feature request related to a problem? Please describe.**
well I had a problem because my friends from far away want to talk to me up close but the mod is only available close by,

**Describe the solution you'd like**
it would be interesting to have an item that makes you talk far away from each other

**Comment by henkelmax** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-radio

**Comment by lostopkk** [comment]
> https://www.curseforge.com/minecraft/mc-mods/simple-radio

have a 1.19.2 version?

**Comment by henkelmax** [comment]
This mod is not by me. You'll have to ask the author
