### ISSUE TITLE
[1.16.5] Crash when exiting group menu that was gotten to via GUI menu.

### ISSUE THREAD

**Issue by NighthowlerStudios** [henkelmax/simple-voice-chat#471]
**Bug description**
The game crashes as the mod cannot find a class to erase the al context of the menu when it's a menu nested inside a menu.

**Steps to reproduce the issue**
1. Open Voice Chat GUI (not settings etc)
2. Use the GUI to open the Group menu
3. Hit Esc to close the menu immediately, crashing the game.

**Expected behavior**
The mod should be able to erase the context cleanly.  

**Log files**
https://pastebin.com/ncXqqe0g

**Versions**
- Minecraft version 1.16.5
- Forge/Fabric/Bukkit/Spigot/Paper version 36.2.39
- Mod/Plugin version 2.3.9

**Other mods**
Vivecraft (which includes Optifine).
Was on a multiplayer server instance in VR of Kaleidio's Battle Pack.  Unsure if the crash can occur on Desktop, but it is likely, and will be tested.
Crash does not occur on previous versions of the mod.  I am still working to pick out exact version numbers.  I was unable to update to latest due to a mixin crash which I will explain in another issue.

**Comment by NighthowlerStudios** [comment]
the crash seems to indicate that the event listening class DestroyOpenALContextEvent (api/events) was missing, but opening the jar and finding the compiled file shows that is not the case.  upon further inspection of the code, however, seems to indicate it's not a class, but rather an Interface.  This could mean something happened where something in the code is attempting to instantiate it somehow.  I am therefore unsure if this is a result of a mod collision with Immersive MC or not since they have significant modification to the OpenAL context as well as Optifine and your mod.

**Comment by henkelmax** [comment]
Is this reproducible or did it just happen once?

Please check if this also happens without any other mods.
This exact issue usually only happens if the mod jar is already used or modified by another program.


> This could mean something happened where something in the code is attempting to instantiate it somehow. I am therefore unsure if this is a result of a mod collision with Immersive MC or not since they have significant modification to the OpenAL context as well as Optifine and your mod.


No. This is as intended. This error happens if the class can't be loaded. For example if it was removed while the game is running or you replaced it while it was running. 

As far as I know Optifine does not change any OpenAL audio stuff. Its only visuals. Despite this, that event is only internally used in the voice chat mods and other mods that use the voice chat API.

**Comment by NighthowlerStudios** [comment]
I do know that Vivecraft does have OpenAL overrides.  They create a context that has its own HRTF. I cannot get the issue to reproduce outside of VR mode.  Because Vivecraft is a jar mod consisting entirely of patches, that would explain why the issue only occurs during "modification" even though I have not modified absolutely any jar.  I only used 7 zip to check the class was there and checked your git.

Their repository is public.  There is a lot of patch code there.  Maybe you could give it a check to investigate?

**Comment by henkelmax** [comment]
The OpenAL class loading failing does not have anything to do with actual OpenAL stuff.
It seems that another mod is causing this weird class loading behavior. Please check which exact mod is causing this issue and try to report it on their issue tracker. But I'm fairly sure that the voice chat mod is not the cause of the issue. It just manifests there.

If you find out anything that it actually does come from the voice chat mod, feel free to reopen this issue.

**Comment by NighthowlerStudios** [comment]
I don't understand why I have to clarify, but again, the mod conflict is Vivecraft.  I can get it to reproduce with that mod's VR mode only, and I have HRTF enabled in their config.  However, 1.16.5 support was recently dropped by the devs.  so the only hope I have in this mod getting fixed would be on you.  I can stay downgraded if I must, I just felt the new features appealing.

**Comment by henkelmax** [comment]
I'm sorry but I won't fix issues of other mods.

**Comment by NighthowlerStudios** [comment]
alright
