### ISSUE TITLE
voice chat authentication fails if player is far away from spawn

### ISSUE THREAD

**Issue by MedievalApple** [henkelmax/simple-voice-chat#473]
**Bug description**
The client fails to authenticate voice chat with the server if the player is hundreds of blocks away from spawn in the latest paper 1.19.2 version

**Steps to reproduce the issue**
Start a server with the latest version of paper 1.19.2
Then teleport about 800 blocks away from spawn
Logout and log back in and it should fail to authenticate voice chat

Note: it does work every once in a while when you log in but 98% of the time it fails to authenticate

**Expected behavior**
It should authenticate voice chat with the server

**Log files**
https://gist.github.com/MedievalApple/dda99691477f7ab576b647c41828f807

**Versions**
Fabric 1.19.2
Paper 1.19.2-211 (The Issue appears to have started on Paper 1.19.2-174)
Server : Voicechat Bukkit 1.19.2 2.3.10
Client : Voicechat Fabric 1.19.2 2.3.10

**Other mods**
There were no other plugins on the server

The Client had sodium fabric 1.19.2-0.4.4+build.18

**Comment by henkelmax** [comment]
There are no logs about anything failing on your server. Can you also send me the client logs?

**Comment by MedievalApple** [comment]
Here's the client-side fabric log. --> https://gist.github.com/MedievalApple/2442384bd79d2409a56a1852ef4e8656

**Comment by henkelmax** [comment]
The issue is that your microphone is not compatible with the mod. You can try setting `java_microphone_implementation` to `true` in the client config. But if that also doesn't work, its just not compatible.

**Comment by MedievalApple** [comment]
I did some tests with a different mic, and the same issue happened. Where voice chat works fine around 0,0 but if I go out a few 100 blocks in the server and log back in it fails. Giving me a voice chat not connected error however, every once in a while when you log on it will work fine. But if I go back to paper version 1.19.2-173 using the same client version and the same version of the voice chat plugin everything works fine every time you log on.

**Comment by henkelmax** [comment]
The only errors that were in the logs you sent were these about your microphone. There is no disconnection or failing to authenticate in the logs.

But if you say this happens only in a specific paper versions, I guess this is a paper bug.

**Comment by MedievalApple** [comment]
Thats whats was really weird about this issue. When its happens nothing about it seems to get logged. It only started happening after paper did this rewrite of the server chunk system ---> https://github.com/PaperMC/Paper/pull/8177

**Comment by henkelmax** [comment]
Yeah this seems like a really big change. I guess they messed something up there...

**Comment by henkelmax** [comment]
I tested it with the latest voice chat and paper version (build 212) and it works completely fine for me.

**Comment by MedievalApple** [comment]
I just downloaded paper version (build 212) and it still seems to be happening for me. But I've noticed that it only happens if I load a big area with a bunch of new chunks. so I think the issue just has to do with my hardware not keeping up with the new chunk-loading system and lagging the player a bit on join causing the voice authentication not to go through. Out of curiosity Is there any way to have the plugin wait till after the player has fully joined to start the voice connection and or possibly retry the connection if it fails?

**Comment by henkelmax** [comment]
Unless paper drops network packets, the mod always retries to connect every second.

**Comment by MedievalApple** [comment]
Will it still try to reconnect if the client never receives the secret from the server?

(In these logs I think it's not receiving the secret)
(Server)
[17:15:02 INFO]: UUID of player jonnyapple97 is 6272e1a2-0880-47fa-92b6-5ccac22fe3e0
[17:15:02 INFO]: [voicechat] Received secret request of jonnyapple97 (15)
[17:15:02 INFO]: [voicechat] Sent secret to jonnyapple97
[17:15:02 INFO]: jonnyapple97 joined the game
[17:15:02 INFO]: jonnyapple97[/127.0.0.1:49639] logged in with entity id 4935 at ([world]371.61700203986345, 143.84557504303058, 299.1032989220625)

(Client)
[17:15:02] [Render thread/INFO]: Connecting to localhost, 25565
[17:15:02] [Render thread/INFO]: Started 4 worker threads
[17:15:02] [Render thread/INFO]: Sending secret request to the server
[17:15:03] [Render thread/INFO]: [System] [CHAT] jonnyapple97 joined the game
[17:15:03] [Render thread/INFO]: Loaded 158 advancements

**Comment by henkelmax** [comment]
Thats what I said. The mod only works if minecraft packets actually get through. Unless paper messes with it there is no possibility it gets lost.

**Comment by MedievalApple** [comment]
Ok, thanks for helping me out with this :)  I'll see if it's something with my network setup if not I just wait and see if a future paper update solves it.
