### ISSUE TITLE
Some Sort of Web Intergration.

### ISSUE THREAD

**Issue by agmass** [henkelmax/simple-voice-chat#476]
**Is your feature request related to a problem? Please describe.**
This mod is absolutely amazing, but the main factor that holds it back is that it REQUIRES a fabric mod, which blocks all type of geyser/unmodded support.

**Describe the solution you'd like**
A simple web-page which would ask you to link your browser to your account - with some sort of passcode shown in big text on the webpage you would use in chat with a command such as

/weblink [code]

You could then have some sort of UI on the webpage to handle groups, mutes, deafens, etc.

**Additional context**
![image](https://user-images.githubusercontent.com/56167347/196036694-b58f5d92-b928-4715-a84e-4b4385a9506c.png)
Image on how i think the website world look like.

**Comment by agmass** [comment]
After reading a few more duplicate issues, i see that the common answer to this is just "Use the API to make it yourself", but some official support would be great

**Comment by henkelmax** [comment]
This might come as an addon mod in the future, but not integrated into the voice chat mod.
It will also be made by someone else.
