### ISSUE TITLE
Got a crash when using 'Simple Voice Chat' on MacOS

### ISSUE THREAD

**Issue by stantios** [henkelmax/simple-voice-chat#477]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
When I try and talk, my game crashes.

**Steps to reproduce the issue**
1. Open Minecraft with Simple Voice Chat.
2. Load into a server.
3. Talk or hold the keybind you use to talk with.
4. You've found the bug!

**Expected behavior**

**Log files**
https://mclo.gs/NTdbQ8b

**Versions**
- Minecraft version - 1.19.2
- Forge/Fabric/Bukkit/Spigot/Paper version - Fabric Version 0.14.9
- Mod/Plugin version - Mod Version 2.3.10

**Other mods**
I was using the Fabulously Optimised Moodpack which had these [mods](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/INCLUDED-MODS.md) and then only added 'Simple Voice Chat'.

**Screenshots (Optional)**
![Screen Shot 2022-10-16 at 14 11 36](https://user-images.githubusercontent.com/98621617/196037326-fb969a40-25fa-4df4-adcc-70ac16ad351d.png)

**Comment by henkelmax** [comment]
As you can read in the logs:

> Your MacOS version is incompatible with Simple Voice Chat


MacOS 10.15 and lower is not compatible with voice chat.
