### ISSUE TITLE
Updated Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by Sanadriell** [henkelmax/simple-voice-chat#479]
pt_br

https://gist.github.com/Sanadriell/ac7fe7afd90c75d3d786975d35559f67

**Comment by lhardt** [comment]
Hello! Is there somebody working on this? I could do it quiclky, being a native speaker

**Comment by Sanadriell** [comment]
> Hello! Is there somebody working on this? I could do it quiclky, being a native speaker

I already updated that. I'm a native speaker.

**Comment by henkelmax** [comment]
Thank you!
