### ISSUE TITLE
It won't work

### ISSUE THREAD

**Issue by Samsonite429** [henkelmax/simple-voice-chat#48]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**
I am trying to install the mod and it keeps saying voice chat not available. I have changed the port in the server config and I changed it to the minecraft port since the port is open in my network and it still didn't work. Then I used Netcat to try to fix it and it still isn't working. So what am I doing wrong?

**Comment by henkelmax** [comment]
Did netcat work?

**Comment by bernatroller** [comment]
I want to make a server with voice chat, have u make it work? I need help xd

**Comment by henkelmax** [comment]
Cited from the FAQ:

> If you are hosting a server you should know that. I am not tech support. Ask your server hoster or use the internet to search for a solution.
