### ISSUE TITLE
Incompatible with BuildGuide > 1.19.2

### ISSUE THREAD

**Issue by TheUnknownCod3r** [henkelmax/simple-voice-chat#480]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
When loading Simple Voice Chat along with Fabric API, and Build Guide connecting to a server with Simple VC causes a client mismatch error, stating client version is incorrect. Works normally again without. Ive updated the creator of said mod, but thought i'd add here too so you can also check.

**Steps to reproduce the issue**
1. Create a new curseforge instance with just Fabric 0.14.10, Fabric API, Simple VC and Build guide
2. load up the game, connect to a server with Simple Voice chat
3. open messages, and you should see a similar message to "Voice chat version incompatible with server, please install 1.19.2-2.3.xx of Simple Voice chat. Server logs the error Client Version Mismatch(Server=15, client=-1)

**Expected behavior**
Server Authenticates voice chat as usual, connects and can be used.

**Log files**
https://pastebin.com/ZNXK2L99 - Client Log
Server log is full of Dynmap spam, but the error the server logs is https://pastebin.com/BxzC9xSk

**Versions**
- Minecraft version: 1.19.2
- Forge/Fabric/Bukkit/Spigot/Paper version: Fabric 0.14.10 1.19.2
- Mod/Plugin version 2.3.10, tried 2.3.11 too.

**Other mods**
Audioplayer, Fabric API, VC Integration, No Chat Reports, Build Guide (The Issue)

**Screenshots (Optional)**
Not adding a screenshot as its just a message on connection saying the server is incompatible. Removing Build Guide fixes, not sure what the incompatibility is, so notifying both.

**Comment by henkelmax** [comment]
https://www.curseforge.com/minecraft/mc-mods/build-guide/issues/4
