### ISSUE TITLE
Issue with vc connection after reconnecting to servers

### ISSUE THREAD

**Issue by MrPresidentWhite** [henkelmax/simple-voice-chat#481]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
When I'm disconnecting from an server and reconnecting to the same server, the plugin doesn't connect to the Voice Chat Server. I have to completely restart my game, that this wil work again.

**Steps to reproduce the issue**
Idk how to reproduce this error. I'm disconnecting from my server and then reconnecting and then this issue occoures 

**Expected behavior**
Normal establishing of a vc connection to the server without restarting the whole game

**Log files**
server logs*, **:
![DdErz5NMSv](https://user-images.githubusercontent.com/38688739/199598425-044b9b69-667b-4c59-8ed5-ca4ee19d6942.png)
*: somehow after reconnecting to the server the client can't authenticate with the secret sent by the server to connecting to the vc server.
**: blured things are usernames, UUIDs and IP adresses

[client log while this error occures (github gist)](https://gist.github.com/MrPresidentWhite/f5a2d47bee749fd2c56c61e22c7759bf)

**Versions**
- Server: Debian 11 bullseye
- Paper Version: 1.19.2
- Simple VC Version: 1.19.2 | 2-2.3.10
- Java Version: 17.0.4 (Server)
- Java Version: 17.0.2 (Client)
- Client: Fabric 1.19.2 (via MultiMC 0.6.16 - The Modpack Apocalypse)

**Other mods**
client mods:
![image](https://user-images.githubusercontent.com/38688739/199595348-28b91731-fbd7-473c-8e3b-32d3ad2f1569.png)

server plugins:
![Ym8GQrWPe2](https://user-images.githubusercontent.com/38688739/199599681-8c696d7c-8ca1-424b-bfb3-9a4c20c73fa3.png)

**Screenshots (Optional)**
i could post a screenshot of the indicator icon that the client isn't connected to the server, but that wouldn't really help much.

**Comment by henkelmax** [comment]
I am not able to recreate this issue with the latest paper version and the latest voice chat version.
Please try installing SVC version `2.3.12` on your client and Paper `1.19.2-256` on your server.
I also need the full server logs in text form.

When trying this, please make sure you have no other plugins and mods installed on your client and server.

**Comment by henkelmax** [comment]
Closed due to inactivity
