### ISSUE TITLE
Voice Chat icon resource pack keeps disabling itself after turning off Minecraft

### ISSUE THREAD

**Issue by VeggeieDude** [henkelmax/simple-voice-chat#485]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Whenever I turn off minecraft, the Simple Voice Chat Icon resource pack disables itself from the active resource packs list, and I have to reenable it every time. I tried with all three and they all do the same thing.

**Steps to reproduce the issue**
1. Enable one of the icons in the resource packs option.
2. Turn off Minecraft.
3. Start up Minecraft.
4. Go to resource packs options again, and for me the icon will always be disabled.

**Expected behavior**
The icon resource pack not disabling itself unless I take it of manually.

**Log files**
N/A

**Versions**
- 1.19.2
- Fabric
- 2.3.13

**Other mods**
Sodium, Indium, Iris, Lithium, Starlight, Krypton, Audio Player, Colormatic, Enhanced Block Entities, Exordium, Feytweaks, More Culling, CEM, CIT-Resewn

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by DmanMC** [comment]
not sure why this is closed, its still a problem

**Comment by slushieuwu** [comment]
was this fixed? its still an issue for me

**Comment by henkelmax** [comment]
Can confirm it happening in 1.19.2-2.3.13

**Comment by henkelmax** [comment]
Alright, @DmanMC  it will be fixed in 2.3.14

**Comment by slushieuwu** [comment]
> Alright, @DmanMC it will be fixed in 2.3.14

thanks!
