### ISSUE TITLE
Rename the icon resource packs so they are ordered correctly

### ISSUE THREAD

**Issue by Foozey** [henkelmax/simple-voice-chat#486]
**Is your feature request related to a problem? Please describe.**
Yes (in my opinion). Currently the icon resource packs are jumbled up with any other resource packs installed.

**Describe the solution you'd like**
This problem can be solved by renaming the resource packs in a format like this: "Simple Voice Chat - Black Icons", "Simple Voice Chat - White Icons", "Simple Voice Chat - Classic Icons".

**Describe alternatives you've considered**
Naming convention is up to you, but just start each icon pack with the same word or phrase so they are all ordered neatly together.

**Comment by henkelmax** [comment]
It does not seem to be possible to modify the order of builtin resource packs from their display name or ID:

![](https://user-images.githubusercontent.com/13237524/203255252-ce5ab536-3327-4254-8421-346c07d85b0a.png)
