### ISSUE TITLE
Log spammed if a device is not available

### ISSUE THREAD

**Issue by Martmists-GH** [henkelmax/simple-voice-chat#490]
**Bug description**
The log seems to get spammed when my microphone is unavailable as it was not connected when I launched the game. Even after changing the microphone in-game, it still sems to try to connect to the same microphone.
Because these actions seem to be linked to the render thread, it becomes difficult to do anything as the game updates at one frame per 30 seconds

**Steps to reproduce the issue**
1. Connect to a server
2. Watch the minecraft log

**Expected behavior**
The mod logs a warning once or maybe periodically

**Log files**
[pastebin](https://pastebin.com/fBNsLGvj)

**Versions**
- Minecraft version: 1.18.2
- Fabric version: 0.59.1
- Mod version: 2.3.11

**Other mods**
None that should interfere with this issue.

**Comment by henkelmax** [comment]
Your logs are incomplete. Please send the full `latest.log`.
Is this reproducible?
Does this also happen in the latest version of the mod?

**Comment by henkelmax** [comment]
Fixed with 09b3a7a182aeaf3d4477ea09bb355742befb4f6e

**Comment by Martmists-GH** [comment]
Will this fix be backported to 1.18.2?

**Comment by henkelmax** [comment]
Of course, it already is.
