### ISSUE TITLE
Reloading on bukkit/spigot disconnect client voice chat with Fabric

### ISSUE THREAD

**Issue by buuugle** [henkelmax/simple-voice-chat#493]
**Bug description**
When I use the /reload command on bukkit/spigot, the voice chat is marked as "not connected" (there is the specific icon in the bottom left corner of the screen). I can still quit and rejoin the server to solve the problem.

**Steps to reproduce the issue**
1. Start a Spigot server with this plugin
2. Connect to the server with the mod installed on Fabric (I didn't try with Forge)
3. Use the /reload command
4. The problem occurs
5. Quit and rejoin the server to solve it

**Expected behavior**
I've used Simple Voice Chat on a Fabric server and the /reload command didn't cause this problem.

**Log files**
https://gist.github.com/Buuugle/9cb85df3073878b0e7ac2f5d885789dd

**Versions**
- Fabric Loader 1.19.2 1.14.10 (with Fabric API 1.19.2 0.67.1)
- Spigot 1.19.2 R0.1 SNAPSHOT
- Simple Voice Chat 1.19.2 2.3.16

**Other mods**
None

**Screenshots (Optional)**
None

**Comment by henkelmax** [comment]
> [18:51:00] [Server thread/ERROR]: Simple Voice Chat does not support reloads! Expect that things will break!
