### ISSUE TITLE
No Config file (1.19 Forge)

### ISSUE THREAD

**Issue by TheGamingDogYT7** [henkelmax/simple-voice-chat#496]
Hello, I was testing this mod out and all the other mods I tested (with this one) all had a config file, simple voice was the only one that didnt have one.

**Steps to reproduce the issue**
1. Install simple voice for 1.19.2 forge
2. Drag it onto the server mods 1.19.2
3. Click start server
4. Go to config and its not there

The expected result is It will be there and showing up

**Log files**
https://mclo.gs/R6AWSaQ (wouldnt allow me to download)

**Versions**
- Minecraft version - 1.19.2
- Forge
- Mod

**Other mods**
- Create Mod
- JEI

**Screenshots (Optional)**
Screenshots of the issue.
![image](https://user-images.githubusercontent.com/77247053/205169908-ba169f9e-44c4-42ee-9220-d3d53828b424.png)
![image](https://user-images.githubusercontent.com/77247053/205170013-5da42031-6ed1-4204-a6c4-bb2ff33f674b.png)

**Comment by henkelmax** [comment]
Read the wiki for the config location.
