### ISSUE TITLE
We can't hear each other

### ISSUE THREAD

**Issue by Niklaskerl200l** [henkelmax/simple-voice-chat#5]
**Bug description**
The mod is installed and running. But we can't hear each other. You can only hear clicks sound.

**Log files**
Client Debug Log: https://gist.github.com/Niklaskerl200l/6c9a4c230e21b188368ce17595149978
Server Debug Log: https://gist.github.com/Niklaskerl200l/2a5e141ca9bbb7de6b7e95aa3576198b

**Versions**
- 1.16.4
- Forge 35.1.0
- Simple Voice Chat 1.16.4-1.0.1

Server Hoster
mine-hoster.de

**Other mods**
chiselsandbits-0.2.7-RELEASE
eternalwinter-1.3
fairylights-4.0.3-1.16.4
jei-1.16.4-7.6.0.58
Kiwi-1.16.3-3.4.1
OptiFine_1.16.4_HD_U_G5
SnowRealMagic-1.16.3-2.2.2
Xaeros_Minimap_20.28.2_Forge_1.16.4
XaerosWorldMap_1.11.4_Forge_1.16.4

**Screenshots (Optional)**
Mod Config: https://prnt.sc/w02e4k
Video: https://www.youtube.com/watch?v=rMYO_QrRSwA&feature=youtu.be
at 0:17 you can hear what other players hear
server properties: https://gist.github.com/Niklaskerl200l/f94febe2e102a3f8f36e72e8c628aaa8

**Comment by henkelmax** [comment]
From what I can see from your configs and logs, it seems to be set up correctly. The voice chat is successfully connected to the server and since the microphone testing works correctly it can't be your microphone...

Can you test if it works with just the voice chat mod installed on the client and the server?

**Comment by Niklaskerl200l** [comment]
I have only tried with the voicemod, it still doesn't work.


[Server debug.log](https://github.com/henkelmax/simple-voice-chat/files/5681191/Server.debug.log)
[BaumTeddi debug.log](https://github.com/henkelmax/simple-voice-chat/files/5681192/BaumTeddi.debug.log)
[Niklas debug.log](https://github.com/henkelmax/simple-voice-chat/files/5681193/Niklas.debug.log)

**Comment by henkelmax** [comment]
I'm sorry, but I can't find anything that's wrong. Maybe you muted the other player in the `Adjust player volumes` section, but that seems very unlikely.

**Comment by afishofsorts** [comment]
I'm now having the same issue, but only after getting it to work once. After the first successful setup, we could hear each other and everything, we later restarted the server, but the exact same problem as above occurred. Not sure if this helps at all but the server's console had zero differences between the two:

Successful: https://gist.github.com/afishofsorts/cebd5c288c7c43606965795569308745
Unsuccessful: https://gist.github.com/afishofsorts/bb39672c8ef806522d8e1171cf46c13b

Multiple restarts as well as a complete purge and second identical setup have done nothing to mitigate this. Our mic settings were unchanged between the two and the player's aren't muted by accident. Not sure what changed, but hopefully we can get this issue resolved!

**Comment by henkelmax** [comment]
There isn't even a player logging in in your logs.
I need the server logs including a player logging in and also the client logs,

**Comment by henkelmax** [comment]
@Niklaskerl200l @afishofsorts Is it still not working with the latest version?

**Comment by JJK96** [comment]
We seem to have the same problem here, we see an indicator when the other talks, but we don't hear anything.
Locally, for each of us voice activation and microphone testing works.

**Comment by henkelmax** [comment]
Please provide the logs of your server and the clients

**Comment by JJK96** [comment]
https://gist.github.com/JJK96/7d214a4227581e085cb79caf1fdf62a5

You can see that the error is due to reading the TOML config file, before the error it was working for a while (one-way, I could hear the other player).

There is no relevant data in the server log during the moment where it stops working.

**Comment by henkelmax** [comment]
Please send me the logs of your server. You don't know what's relevant to me.
Please also fix your client config and send me logs of your client.

**Comment by JJK96** [comment]
The server logs are included in the same gist.

The client config file consists of:

```
microphone_amplification = 1.018181818181818
voice_activation_threshold = -42.14090909090909
microphone_activation_type = "VOICE"
```

I don't see why it complains about microphone_amplification defined twice.
Any ideas on how to "fix the client config"?

**Comment by henkelmax** [comment]
Sorry, I didn't see the server logs.
You can "fix" it by deleting it. But that will reset your settings. As far as I can see it looks fine, but you should try it anyways.

**Comment by JJK96** [comment]
Haven't tried that, I will consider it next time I test with this.

**Comment by afishofsorts** [comment]
> @Niklaskerl200l @afishofsorts Is it still not working with the latest version?

Yes! The latest update seems to work flawlessly now. Thanks for the hard work!

**Comment by henkelmax** [comment]
Great!
