### ISSUE TITLE
There is no voice_chat.port file in config folder.

### ISSUE THREAD

**Issue by technomaniak** [henkelmax/simple-voice-chat#50]
Bug description
There is no voice_chat.port file in config folder.

Versions
- 1.16.4
- 35.1.37
- 1.1.5
[latest (1).log](https://github.com/henkelmax/simple-voice-chat/files/5964999/latest.1.log)
[debug (1).log](https://github.com/henkelmax/simple-voice-chat/files/5965000/debug.1.log)

![image](https://user-images.githubusercontent.com/49454508/107633304-1171c780-6c68-11eb-86af-3c55b0f63a41.png)

**Comment by henkelmax** [comment]
`voice_chat.port` is the key of the config setting in the server config. Read the FAQ for more information to the server config.
