### ISSUE TITLE
1.12.2 Singleplayer worlds compatibility instead of just multiplayer worlds where a plugin is needed

### ISSUE THREAD

**Issue by Titoo8899** [henkelmax/simple-voice-chat#502]
My problem is that I would also like to use or test this mod in the single player area than just on a server where I need a plugin.

I would wish that there was an extra version or something of the 1.12.2 that can also be played in the single player area and does not require plugins or servers if that is possible.

Otherwise, I have nothing to do with the other 2 points for alternatives that I would consider or further context.

I hope it help

MFG
Mirko

**Comment by henkelmax** [comment]
The plugin is not needed it also supports Forge on the server
