### ISSUE TITLE
[FORGE][1.12.2] Simple Voice Chat 1.12.2-2.3.22 Crash by Start of Loading

### ISSUE THREAD

**Issue by Titoo8899** [henkelmax/simple-voice-chat#504]
I have read the Wiki and I have only the Forge Version in the Mod Folder

**Bug description**
My problem is that with the latest version of the mod for 1.12.2 the game stops after 2 seconds where it begins to load and a crash report appears

**Steps to reproduce the issue**
1. Download your Mod for 1.12.2-2.3.22 Version
2. Put the Mod to your Mods Folder
3. Start Minecraft Launcher
4. Click the Icon vor the Minecraft Forge 1.12.2 Version
5.  Start now the game
6.  2 seconds later the game crash

**Expected behavior**
I was hoping after the last update version 2.3.21 that everything that comes after it would work because they had fixed the build for 1.12.2 as well

**Log files**
https://gist.github.com/Titoo8899/65e4fc2492f29c63e7b049ec929b9c6f

**Versions**
- Minecraft version: 1.12.2
- Forge: 1.12.2 - 14.23.5.2860
- Mod: [FORGE][1.12.2] Simple Voice Chat 1.12.2-2.3.22

**Other mods**
no other Mods

**Comment by henkelmax** [comment]
Sorry, version 2.3.22 wasn't meant to be uploaded for 1.12.2. Please use 2.3.21
