### ISSUE TITLE
Unsuccessful authorization (probably due to the datapack) (!)

### ISSUE THREAD

**Issue by zentixua** [henkelmax/simple-voice-chat#508]
**Bug description**
With a certain combination of datapacks (or with one of them, I don’t know), it’s not the first time I manage to connect to the voice chat!
- I asked the hosting to add the ports that I use to exceptions - it did not help.
- Everything works fine on a clean server.
- 

**Steps to reproduce the issue**
1. Install PlasmoVoice (voicechat-bukkit-1.19.2-2.3.17)
2. Install these datapacks: 
![image](https://user-images.githubusercontent.com/65168490/207373994-b2e42bbd-2545-4e75-ae7c-8468b87c7e3d.png) OR install my copy of server floders: 
https://drive.google.com/file/d/1NkRHcw1MQj2PwEC8VaqHFDYJxZhcEcan/view?usp=share_link (velocity)
https://drive.google.com/file/d/1OUfOcauJB3akBXgtfxRwpAEh-jnSz3Kn/view?usp=share_link (purpur server)

3. Maybe not the first time, but you won't see "Successfully authenticated player" (from time to time, like it's random. it works)

**Expected behavior**
I go to the server and the voice chat connects the first time

**Log files**
https://pastebin.com/M9FPWhda (server log)
https://pastebin.com/tcGn7S4Z (client log)

**Versions**
- 1.19.2 (same on 1.19.3)
- Paper (Purpur), Velocity proxy (so offline mode)
- Plugin - 1.19.2-2.3.17, Fabric mod: 1.19.2-2.3.19

**Other mods**
LazyDFU, ModMenu, OptiFabric, Simple Voice Chat, Xaero's Minimap

[17:45:07 INFO]: Plugins (2): spark, voicechat (server plugins)

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/65168490/207379206-a70e5c74-c474-4104-9d99-8669fcc6531e.png)

**Comment by zentixua** [comment]
I have the same problem ON MY LOCAL PC..
I noticed this feature:
This problem is not easy to reproduce. But for it to be almost always - you need to make a clean server, fly around its world (generate chunks), restart the server and you will receive unsuccessful authentication when you enter the server. If you log in from another nickname and spawn at spawn, this player may not have a problem, but the one who loaded the chunks has.

**Comment by henkelmax** [comment]
> Install PlasmoVoice
This is not plasmo voice.

**Comment by zentixua** [comment]
I'm sorry I was very wrong.. lel

**Comment by zentixua** [comment]
looool

**Comment by zentixua** [comment]
pls do not close

**Comment by zentixua** [comment]
I meant simple voice

**Comment by zentixua** [comment]
Also this problem does not depend on datapacks, i figured it out during testing now. It happens even on a CLEAN server.

**Comment by henkelmax** [comment]
If you are having issues connecting to voice chat, visit the discord.

**Comment by zentixua** [comment]
I opened a ticket and they didn't answer me for more than 15 days

**Comment by zentixua** [comment]
and by all indications this is a bug, I think so

**Comment by henkelmax** [comment]
What's your discord name?

**Comment by zentixua** [comment]
Genife#8657

**Comment by henkelmax** [comment]
You never pressed confirm in your support thread.
