### ISSUE TITLE
Client crash when creating group

### ISSUE THREAD

**Issue by Tschipp** [henkelmax/simple-voice-chat#509]
**Bug description**
When trying to create a group on a server, the client crashes

**Steps to reproduce the issue**
1. Press V
2. Try to create a group
3. Crash

**Expected behavior**
No Crash

**Log files**
https://pastebin.com/qarSCQqL

**Versions**
- 1.12.2
- Forge 14.23.5.2838
- Mod version 1.12.2-2.3.23

**Other mods**
Listed in the crash report, but I doubt there is a conflict

**Comment by Tschipp** [comment]
Weirdly enough, I just tried it again twice and the third time it worked... might still be worth checking this out though.

**Comment by henkelmax** [comment]
Please make sure this issue is reproducible and try if this also happens without any other mods.

**Comment by henkelmax** [comment]
Closed due to inactivity.
