### ISSUE TITLE
Crashing instantly after start

### ISSUE THREAD

**Issue by SikiciBebek** [henkelmax/simple-voice-chat#513]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Game crashes if i add "voicechat-mod" after starting the game

Install ATM8
Put Simple-Voicechat-Mod in
Start the game
You recive your crash-report (if it starts, sometimes its just a blackscreen)

**Expected behavior**
Everytime i press Start, Minecraft crashes right after a few seconds.

**Log 
[crash-2022-12-18_18.53.16-client.txt](https://github.com/henkelmax/simple-voice-chat/files/10254423/crash-2022-12-18_18.53.16-client.txt)
files**

**Versions**
-1.19.2
- Forge 43.1.55
- 1.19.2-2.3.23

**Other mods**
All mods from "all the mods8"

**Comment by henkelmax** [comment]
> [crash-2022-12-18_18.53.16-client.txt](https://github.com/henkelmax/simple-voice-chat/files/10254423/crash-2022-12-18_18.53.16-client.txt)

This crash is not caused by the voice chat mod. It seems to be caused by one of the Thermal series mods.

**Comment by SikiciBebek** [comment]
but without the voice-chat mod its starts without any problems
u can try it out if u want to

**Comment by henkelmax** [comment]
There is no mention of the voice chat mod whatsoever in your crash log.
You can try if the voice chat mod crashes without any other mods installed.

**Comment by SikiciBebek** [comment]
i tried it out a few times now
it starts without the voicechat mod
if i add the mod it starts too but only a black screen appears and nothing happens
i waited for like 30-40 min
maybe u know why this happens :D
like i said we playing all the mods 8

**Comment by SikiciBebek** [comment]
nvm
i reinstalled the modpack
it works
Sry for taking your time
TY! 
have a great day
