### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by mrksbgg** [henkelmax/simple-voice-chat#514]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
player times out

**Steps to reproduce the issue**
1. just join server
2. open console
3. See error

**Expected behavior**
everything will be working

**Log files**
https://gist.github.com/mrksbgg/26bb8448f21ce5bcd57511ff5cdb0db2

**Versions**
- 1.19.2 Fabric
-  Pufferfish version git-Pufferfish-47 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 9b8cdc7 on HEAD)
- plugin is 1.19.2-2.3.24

**Other mods**
its all players bug 

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/101137197/209088881-47a4eb93-f087-4d9d-9f44-e2de5e9e4f54.png)
![image](https://user-images.githubusercontent.com/101137197/209088785-914f8bd5-248f-40b1-b5f3-a48d8f6bd2a5.png)

**Comment by henkelmax** [comment]
Please visit the discord if you need help setting up the mod.
