### ISSUE TITLE
crash (no crash report created) mac and fabric

### ISSUE THREAD

**Issue by superon** [henkelmax/simple-voice-chat#515]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**
.. running on mac osx 10.13.6

**Bug description**
attempting to activate the mic via toggling VOICE or PTT crashes with exit code 6 on cf launcher

**Steps to reproduce the issue**
try to activate mic on multiplayer or single player

**Expected behavior**
i expect to be able to progress to voice chatting

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
You can use [https://gist.github.com/](https://gist.github.com/).
https://pastebin.com/FCip6b5D

**Versions**
- Minecraft version: 1.19.2
- Fabric version fabric-api-0.69.0+1.19.2
- Mod/Plugin version voicechat-fabric-1.19.2-2.3.24

**Other mods**
fabric-api-0.69.0+1.19.2

**Screenshots (Optional)**
Screenshots of the issue.
![Screen Shot 2022-12-22 at 23 45 19](https://user-images.githubusercontent.com/5957924/209243707-16294c7b-5a8f-4cb3-9e9e-dea5e008d0d5.png)

**Comment by henkelmax** [comment]
> [23:37:37] [Render thread/WARN]: Your MacOS version is incompatible with Simple Voice Chat

You are using an unsupported macos version. We only support macos 10.15 and newer.
