### ISSUE TITLE
Velocity dose not seem to forward the Simple Voice Chat packets

### ISSUE THREAD

**Issue by samuelh2005** [henkelmax/simple-voice-chat#518]
**Bug description**
The voice chat server never receives the packets from the server when behind a velocity proxy. 

**Steps to reproduce the issue**
1. Set up a Fabric server with Simple Voice Chat and a velocity proxy 
which successfully forwards the player to the server (Use [Fabric Proxy-Lite](https://modrinth.com/mod/fabricproxy-lite)?)
2. Make the Minecraft server use a port e.g. (30067). Use this port for Velocity too :
```toml
[servers]
create_pack_1 = "127.0.0.1:30067" # <-- Like this
```
3. Make this mod use same port.
4. Connect with this mod.
5. The voice chat will be unable to connect.

**Expected behaviour**
A successful voice chat connection will happen.

**Log files**
The only applicable logs I have is this \/ on the client, a few times.
```
Trying to authenticate voice connection
```

**Versions**
- Minecraft version : 1.19.2
- Forge/Fabric/Bukkit/Spigot/Paper version
* Velocity : `velocity-3.1.2-SNAPSHOT-201`
* Fabric Loader: `0.14.10`
- Mod/Plugin version : voicechat-fabric-1.19.2-2.3.11

**Other mods**
Not sure if its applicable.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
https://modrepo.de/minecraft/voicechat/wiki/setup#setting-it-up-with-a-proxy

**Comment by samuelh2005** [comment]
I've read that, but it doesn't seem to work.

* Velocity and the Fabric server are on the same machine.
* Simple Voice Chat and the fabric server use the same port. (This worked before I started to use velocity)
* On the voice chat config the bind address is '0.0.0.0'. 
* Even tried to set the voice host to the domain of the server (which players use to connect)

**Comment by henkelmax** [comment]
1. Voice chat packets are never routed through the proxy
2. If you need help setting it up, visit the discord.
