### ISSUE TITLE
Failed to load native Opus codec

### ISSUE THREAD

**Issue by jackaboy216** [henkelmax/simple-voice-chat#520]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
me and my friends keep getting disconnected because of "Failed to load native Opus codec"

**Steps to reproduce the issue**
1. installed simple voice chat
2. tried connecting
3. I got disconnected

**Expected behavior**
I expected it to not disconnect me and my friends

**Log files**
[<script src="https://gist.github.com/jackaboy216/18c3317ed5062d09bdba440ee54252a9.js"></script>](https://gist.github.com/jackaboy216/18c3317ed5062d09bdba440ee54252a9)

**Versions**
- Minecraft version: 1.19.2
- Fabric version: fabric - 0.14.10
- Mod version: voicechat-fabric-1.19.2-2.3.26.jar

**Other mods**
The problem still occures even without the other mods
![image](https://user-images.githubusercontent.com/63114920/210282459-8237a5be-3f76-453b-8876-f3713f801103.png)

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/63114920/210282396-df06a814-4e22-4bb8-9b7b-b9341d652c62.png)

**Comment by henkelmax** [comment]
This message is just a warning. There is a fallback to a pure Java Opus implementation.

This is not a reason for getting disconnected.

**Comment by jackaboy216** [comment]
When i remove the voice chat mod, the problem is fixed so i don't get why it keeps disconnecting me and my friends

**Comment by henkelmax** [comment]
All I can tell you is that it is not caused by the opus codec.

If you need help setting up the mod, visit the discord.

**Comment by jackaboy216** [comment]
okay, thanks for the help

**Comment by jackaboy216** [comment]
I think i found the problem, i was also using vc interactions and it turns out this caused the problem
