### ISSUE TITLE
Incompatible mod set with latest version of voicechat & audioplayer

### ISSUE THREAD

**Issue by ComputerJock** [henkelmax/simple-voice-chat#522]
**Bug description**
I was getting my 1.19.2 installation updated to the latest audio mods:
  voicechat-fabric-1.19.2-2.3.26.jar
  audioplayer-1.19.2-1.4.5.jar

I now get this message:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!

A potential solution has been determined:
	 - Install voicechat, version 1.19.2-2.3.3 or later.
Unmet dependency listing:
	 - Mod 'AudioPlayer' (audioplayer) 1.19.2-1.4.5 requires version 1.19.2-2.3.3 or later of voicechat, which is missing!

**Steps to reproduce the issue**
Install the above two mods in a 1.19.2 fabric installation.

**Expected behavior**
No error message.

**Log files**
https://gist.github.com/ComputerJock/54ebbf52748b353d805447dea4f76322

**Versions**
- Minecraft version 1.19.2
- Fabric version
- Mod/Plugin version: listed above

**Other mods**
List is in the log file above.

I removed all mods except for fabric-api and these two audio mods. Got the same error message.

**Comment by ComputerJock** [comment]
Reinstalling voicechat-fabric-1.19.2-2.3.18.jar eliminates the error message and the game starts successfully.

**Comment by henkelmax** [comment]
Thats not an issue with the voice chat mod. please report that issue to https://github.com/henkelmax/audio-player
