### ISSUE TITLE
Plugin is not initializing

### ISSUE THREAD

**Issue by vitiacat** [henkelmax/simple-voice-chat#523]
**Bug description**
I'm registering plugin using BukkitVoicechatService, but Simple Voice Chat doesnt loading my plugin

**Steps to reproduce the issue**
1. Write bukkit plugin (using docs)
2. Start server with this plugin
3. See that plugin is not initialized and loaded

**Expected behavior**

**Log files**
[15:56:46 INFO]: [VCTestPlugin] Enabling VCTestPlugin v1.0-SNAPSHOT
[15:56:47 INFO]: Time elapsed: 302 ms
[15:56:47 INFO]: Running delayed init tasks
[15:56:47 INFO]: [voicechat] Loading plugins
[15:56:47 INFO]: [voicechat] Loaded 0 plugin(s)
[15:56:47 INFO]: [voicechat] Initializing plugins
[15:56:47 INFO]: [voicechat] Initialized 0 plugin(s)

**Versions**
- MC 1.19.3
- Patina (Paper) 1.19.3
- Plugin version 2.3.24

**Other mods**
Nothing

**Comment by vitiacat** [comment]
I found that BukkitVoicechatService is null
But i dont know why

**Comment by VitiaCatDragon** [comment]
BukkitVoicechatService is null, but i dont know why

**Comment by henkelmax** [comment]
Please visit the discord for help with voice chat API development.

**Comment by VitiaCatDragon** [comment]
Спасибо папаша, но ты мою проблему не решил, пошел рубиться к кс-го и дал мне мут на 1 минуту за пинг

**Comment by RXJpaw** [comment]
If you haven't found a fix for your issue yet.
You have to load your plugin "POSTWORLD" in your `plugin.yml`.
