### ISSUE TITLE
Mic Issues

### ISSUE THREAD

**Issue by Luth3L00s3r** [henkelmax/simple-voice-chat#527]
We have been having issues on a modded server. Some of us cannot use our mics at all. The mod doesn't send out a request to use the computers mic, at least on my end. This has been causing some problems. We are on a Fabric 1.19.2 server and have used the correct version of the mod

**Comment by henkelmax** [comment]
If you need help setting up the mod, visit the discord. If you want to report a bug, fill out the template.
