### ISSUE TITLE
Config port=-1 doesn't work correctly

### ISSUE THREAD

**Issue by LuckCrafter** [henkelmax/simple-voice-chat#528]
**Bug description**
The port of Simple Voice Chat is not correctly transmitted to the client if it is set to -1.
Instead of the port, which is also valid for the server, the -1 is transmitted.

**Steps to reproduce the issue**
1. Open to 'plugins/voicechat/voicechat-server.properties'
2. Set port to 'port=-1'
3. Start the Server and join them
4. See error (doesn't connected)

**Expected behavior**
The server port is transferred but not to the client.
The voice chat server starts on the correct port, but passes -1 to the client.
The correct port should be transmitted.

**Log files**
[https://gist.github.com/LuckCrafter/d2576a8755a4bdbcf403f841f589ba40](https://gist.github.com/LuckCrafter/d2576a8755a4bdbcf403f841f589ba40).

**Versions**
- Client:
- - Minecraft version: 1.19
- - Fabric: 0.14.10
- - Mod: 2.3.15
- Server:
- - Paper version: 1.19-81
- - Plugin version: bukkit-2.3.24

Edit: I know there is a workaround with the SVCPortChanger that sets the port on startup, but shouldn't it work that way too? After all, that is the idea behind "port=-1".

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
