### ISSUE TITLE
Add a Compressor to reduce loud volumes and increase quiet volumes.

### ISSUE THREAD

**Issue by TheAyes** [henkelmax/simple-voice-chat#533]
**Is your feature request related to a problem? Please describe.**
The clipping that is being produces when people talk a tiny bit louder ist very hurtful and unpleasent to listen to. While this doesn't apply to all people it's very disturbing for me.

**Describe the solution you'd like**
The easiest solution to prevent sound from clipping is using a limiter and/or a compressor

**Comment by henkelmax** [comment]
Microphone clipping is only caused by not setting up the microphone amplification and volume correctly.

There is already a builtin compressor, but if your microphone clips, this means you've not configured it correctly.

**Comment by TheAyes** [comment]
Then some guidance about how to configure it correctly would be nice, since people are either quiet or clipping. So I would like to be able to control thresholds and limits myself.

**Comment by henkelmax** [comment]
Visit the discord for help.
