### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ghost** [henkelmax/simple-voice-chat#536]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Crashes On Start up

**Steps to reproduce the issue**
start minecraft

**Expected behavior**
for minecraft to start properly

**Log files**
[Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
You can use [https://gist.github.com/](https://gist.github.com/).](https://mclo.gs/bk36Ewc)

**Versions**
1.12.2
14.23.5.3860 forge
2.3.26

**Other mods**
![image](https://user-images.githubusercontent.com/103887312/214559468-416e3a23-a795-4775-8fe2-9c5e01bc876e.png)

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
> Mixin config voicechat.mixins.json requires mixin subsystem version 0.8 but 0.7.11 was found. The mixin config will not be applied.

One of the mods you are using ships with an outdated mixin version. Either remove voice chat mod or the mod with the old mixin version.
