### ISSUE TITLE
Game crashes when opening config menu

### ISSUE THREAD

**Issue by lgc2333** [henkelmax/simple-voice-chat#538]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
title

**Steps to reproduce the issue**
1. open mod menu
2. click mod's config button
3. game crashed

**Expected behavior**
config menu open and game do not crash

**Log files**
https://gist.github.com/lgc2333/e8edb8a01a452c679376c2e43f2a5840

**Versions**
- Minecraft version 1.18.2
- Mod/Plugin version 2.3.27 with Quilt 0.17.8

**Other mods**
view log

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
This crash is caused by cloth config.
