### ISSUE TITLE
Won't let you connect to the server

### ISSUE THREAD

**Issue by wcordstudio** [henkelmax/simple-voice-chat#539]
**Bug description**
I have the plugin installed on the server, and the forge on the client. In idea, it should work according to the Wiki.

**Expected behavior**
I use the Magma engine, for plugins and mods. I have added VoiceChat-Bukkit in plugins and VoiceChat-Forge in mods. But when accessing the server, I get an error, that the server does not have it. Shouldn't it work?

**Log files**
Minecraft Client Log: [Here](https://gist.github.com/idorrd/e26279a267c1ab3de04b117188d68ab9)
Minecraft Server Log: [Here](https://gist.github.com/idorrd/db672cfae623fd8372d0450ceabda1e8)

**Versions**
- Minecraft version: 1.18.2
- Forge and Magma(SpigotMC)
- voicechat-forge-1.18.2-2.3.27 
- voicechat-bukkit-1.18.2-2.3.24

**Screenshots**
![image](https://user-images.githubusercontent.com/67788634/215268451-6b5e2c46-ffb7-423c-900e-252a90d4d4a7.png)

**Comment by henkelmax** [comment]
We don't support hybrid servers.
