### ISSUE TITLE
Game Crashes with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jtuller** [henkelmax/simple-voice-chat#542]
**Bug description**
Midgame crash with the following exceptions:
Internal Exception: io.netty.handler.codec.DecoderException:
java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 15

**Steps to reproduce the issue**
Unclear how to reproduce this exception, gameplay functions properly for several minutes before crashing.

**Log files**
https://gist.github.com/jtuller/093d971c309f6a23e75c9007066626f0

**Versions**
- Minecraft version: 1.19.3
- Forge/Fabric/Bukkit/Spigot/Paper version 44.1.5
- Mod/Plugin version 1.19.3-2.3.27

**Other mods**
No other mods installed

**Screenshots (Optional)**
![mc-svc-crash-image](https://user-images.githubusercontent.com/17995018/217985971-8a54b351-0904-4a9b-9e6c-4e22e7a58ab5.png)

**Comment by henkelmax** [comment]
I can't find any error in your logs. Please send me your client **and** server logs of the actual crash.

**Comment by jtuller** [comment]
My fault - I sent the wrong log... Here's the _latest_ log from when the crash occurred. Although there are no error messages in this log either!
https://gist.github.com/jtuller/5451fd117614af051accfb62389b031e

I'll have to ask my son's friend for the server logs.

Thanks for your time.

**Comment by henkelmax** [comment]
I'm gonna close this for now, please feel free to reopen if you get the logs.
