### ISSUE TITLE
Switch between group chat(s) and local chat

### ISSUE THREAD

**Issue by Fnige** [henkelmax/simple-voice-chat#543]
**Is your feature request related to a problem? Please describe.**
Sometimes you are in a group chat and then you end up with someone else you want to talk to that is not in said group chat, you could leave the group chat but then come back later but that isnt convenient and it justs feels like a solution is missing

**Describe the solution you'd like**
Via a keybind or within the GUI method, a way to switch between group chats would be best. As added functionality, being able to lower the volume of chats you arent in would be great too

**Describe alternatives you've considered**
Not that I can think of, I guess you could just leave and rejoin the group chat but eh

**Additional context**
(Honestly surprised I couldnt find another person suggesting this)

**Comment by henkelmax** [comment]
Use the `open_groups` config option.

**Comment by Fnige** [comment]
Does that let you talk to only people local to you or people within your group?

**Comment by henkelmax** [comment]
Both
