### ISSUE TITLE
Other Players Can't Hear Me

### ISSUE THREAD

**Issue by XmasPrincess** [henkelmax/simple-voice-chat#544]
**Bug description**
Other people can't hear me on my server. Everyone else can hear each other but I am constantly cutting in and out (I can hear other people). My internet speeds are completely okay. I'm not lagging in Minecraft, and I can hear myself when I do microphone testing. I've reinstalled the mod more than once. 

**Steps to reproduce the issue**
Can't reproduce the issue.

**Log files**
https://gist.github.com/XmasPrincess/c1123b5c244a8a717ab3c7e6cf3f45f0

**Versions**
Minecraft version 1.19.2
Fabric version 0.14.14
Mod/Plugin version 2.3.15

**Other mods**
- Fabric API
- Origins
- Extra Origins
- Mob Origins
- Medieval Origins
- Litematica
- Malilib
- Optifabric / Optifine
- Pehkui
- Phosphor
- Replaymod
- TheSkulker (origins mod)
- Worldedit
I can't currently test what mods if any are messing with the mod.

**Comment by henkelmax** [comment]
Your server is not set up correctly. Please visit the Discord for help. This is not a bug.
