### ISSUE TITLE
Simple chat for 1.16.5 in fabric 

### ISSUE THREAD

**Issue by sadjoyman** [henkelmax/simple-voice-chat#545]
**Is your feature request related to a problem? Please describe.**
A  need frabic simple voice chat for 1.16.5

**Describe the solution you'd like**
Make it so fabric users of 1.16.5 players can play

**Describe alternatives you've considered**
Pls make ....

**Comment by henkelmax** [comment]
How about you look if this version exists before asking for it?
https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/3459638
