### ISSUE TITLE
French translation overflows some buttons

### ISSUE THREAD

**Issue by sylv256** [henkelmax/simple-voice-chat#546]
**Bug description**
Pardon my French <sub>~~haha get it?~~</sub>, but buttons with longer translations generally don't expand. This causes issues.
I partially blame French for this issue.

**Steps to reproduce the issue**
1. Set Language to French or French (Canadian)
2. Open Voice Chat GUI
3. Click "Settings" (untranslated for some reason)
4. Look at the two buttons at the bottom of the GUI.
5. :crab: 

**Expected behavior**
Buttons and containing GUIs expand to accommodate translation size.

**Log files**
[logs](https://mclo.gs/UMm7f5Z)

**Versions**
- **Minecraft** `1.19.3`
- **Quilt** `0.18.1-beta.30`
- **Simple Voice Chat** `1.19.3-2.3.28`

**Other mods**
*(check log)*

**Screenshots (Optional)**
![The bottom part of the SVC Settings. Two buttons' text collide with each other, overlapping.](https://user-images.githubusercontent.com/18603248/221392063-cc30150d-6b49-465c-9045-7744d42209ee.png)

**Comment by henkelmax** [comment]
I'm assuming you are french. Do you have any suggestions for a shorter text that would fit on the buttons?

**Comment by sylv256** [comment]
I'm not french, I just switched the language, and my french isn't great; so I'm not one to ask for translations. But, maybe it could be "Choisir le microphone"/"Choisir l'enceinte" (choose)? Again, you should probably ask someone who speaks it better than me :stuck_out_tongue_closed_eyes:.

**Comment by henkelmax** [comment]
Alright, thanks for letting me know. For now I'll keep it like that until someone decides to update the translation.
