### ISSUE TITLE
[1.12.2] Crash when creating a group

### ISSUE THREAD

**Issue by SpokenWig620933** [henkelmax/simple-voice-chat#548]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
When I create a group in my modpack the client crashes.
It seems to mostly happen, occasicanally it randomly works.

I am doing this on a dedicated server.
This only really started to occur after I installed the Redstone++ and KleeSlabs mods.

I know there was already another ticket...
I created a new one so I could go through the template...

**Steps to reproduce the issue**
1. Create group.

**Expected behavior**
Not to crash for this wierd reason

**Log files**
[crash-2023-03-10_13.25.58-client.txt](https://github.com/henkelmax/simple-voice-chat/files/10945039/crash-2023-03-10_13.25.58-client.txt)
[crash-2023-03-10_13.43.10-client.txt](https://github.com/henkelmax/simple-voice-chat/files/10945040/crash-2023-03-10_13.43.10-client.txt)
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/10945041/latest.log)

**Versions**
- 1.12.2
- Forge - 2860
- 2.3.28

**Other mods**
As I said above this only actually started occuring after I add the Redstone++ and KleeSlabs mods. I don't understand why...

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
This has already been fixed. The fixed version is available in #beta-testing on the discord.
