### ISSUE TITLE
group gui doesn't appear on paper

### ISSUE THREAD

**Issue by rebarakuk** [henkelmax/simple-voice-chat#550]
**Bug description**
On paper server, I created group and invited someone. And when I click G, there was no group. Then I quit and rejoin the server, I can't even invite and there's no group.
(is it normal to kick a player if he quit the server?)

**Steps to reproduce the issue**
1. click G
2. Click Create Group button
3. set the name and click create button
4. Nothing changes. Screenshot below doesn't appear and just nothing.
5. But I can invite someone

**Expected behavior**
4. screenshot below appear

**Versions**
- Minecraft version 1.12.2
- Paper Version 1620
- both of them are 2.4.0 pre 3

Also, I did port forwarding on UDP 24454 and set firewall inbound rule

**Comment by henkelmax** [comment]
Please don't report bugs of pre release versions here. All feedback to that version should be in #beta-testing-feedback
