### ISSUE TITLE
MCProtocollib Definitions

### ISSUE THREAD

**Issue by mirkokral** [henkelmax/simple-voice-chat#552]
**Is your feature request related to a problem? Please describe.**
No i don't have any problem with that

**Describe the solution you'd like**
A packet definition for the java module MCProtocolLib and probably some helper functions

**Describe alternatives you've considered**
Creating my own definition. But i didn't succeed because i didn't have time and i didn't really know how to create custom packets.

**Comment by henkelmax** [comment]
I don't really see the why this would be useful.
