### ISSUE TITLE
Voicechat sound manager ALC error

### ISSUE THREAD

**Issue by TheDoctor1977** [henkelmax/simple-voice-chat#553]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Receiving this error and crash upon joining a server in a particularly laggy area, nobody else running the same modpack is getting this.

**Steps to reproduce the issue**
Enter an area with a large amount of lag (in this case, Create contraptions and mobs were the main lag generator)

**Expected behavior**
The game would run normally

**Log files**
https://mclo.gs/4uuXfcj

**Versions**
MC: 1.18.2
Forge: 40.1.92
Mod: 2.3.28 (latest)

**Other mods**
We are unsure what specifically could be causing this, but here is the modlist.html file generated by Curseforge. 
https://drive.google.com/file/d/1SCwD7oBtbgVo7RibEo9e-G5KSsJ2JPLJ/view?usp=sharing

**Comment by henkelmax** [comment]
Please send me your crash report.

Try setting `java_microphone_implementation` to `true`.

**Comment by henkelmax** [comment]
Closed due to inactivity
