### ISSUE TITLE
Add Folia support

### ISSUE THREAD

**Issue by sofianedjerbi** [henkelmax/simple-voice-chat#558]
**Is your feature request related to a problem? Please describe.**

Simple Voice Chat is not compatible with [Folia](https://github.com/PaperMC/Folia)

**Describe the solution you'd like**

Use Folia API to make it compatible with Folia. Might not be that hard,  
I did the compatibility by turning `Bukkit#runSyncDelayedTask` into `Bukkit.getGlobalRegionScheduler()#run` (same with every schedule call) and adding `folia-supported:true` to plugin.yml.

**Comment by henkelmax** [comment]
I'm sorry, but I won't add dependencies other than the Bukkit dependency to the project, to keep compatibility and not needing to wait until all dependencies have updated to a newer version.
`Bukkit.getGlobalRegionScheduler()` does not seem to exist in the Bukkit API.

I might reconsider adding support at some time in the future. But I think this is too unstable currently.

**Comment by henkelmax** [comment]
Update: I added multi Minecraft version support to Bukkit, and I decided to add Folia support to that aswell, since my changes allowed calling non-standard Bukkit API access.
