### ISSUE TITLE
ServerConfig file missing on BisectHosting sever  

### ISSUE THREAD

**Issue by MastaYesevil** [henkelmax/simple-voice-chat#56]
Hello!

I am trying to install this mod on a BisectHosting rented server. I am working with their tech support, who confirmed that port 24454 should always be open but I am getting the fabled "Voice chat unavailable" error. We went to find the serverconfig file to try and do a IP specific configuration as your FAQ recommends but we cannot it. Do you know where it could be? I've tried to attach a screenshot of their folder structure below for reference.

![BisectHosting](https://user-images.githubusercontent.com/79207536/108292438-164fe300-7162-11eb-8cc5-29ce9db27fba.jpg)

Regards,
Jason

**Comment by kgrubb** [comment]
it's in the world's directory. so for example, you should be able to go into the `world` directory and then see a directory called "serverconfig"

**Comment by MastaYesevil** [comment]
That did it! They were able to locate the file and set the IP and the mod worked right away. All came in nice and clear and no config changes were needed with the client configs. Thank you much! Great mod.
