### ISSUE TITLE
LabyMod Addon

### ISSUE THREAD

**Issue by strich3** [henkelmax/simple-voice-chat#561]
**Is your feature request related to a problem? Please describe.**
So I'm using labymod4 for a while and i really miss simple voice chat. 

**Describe the solution you'd like**
A LabyMod Port (If that's possible)

**Describe alternatives you've considered**
There are no alternatives (Only labymod standart voice chat, but it's not that good)

**Comment by henkelmax** [comment]
Sorry won't happen
