### ISSUE TITLE
Linux: Setted up all the port-fowarding for 24454 in router and in the computer, still not working. (Forge 1.16.5)

### ISSUE THREAD

**Issue by HTMLDevelopment** [henkelmax/simple-voice-chat#563]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
I've made all the port fowarding in the router and computer (using GUFW) for the mod, but in the server, for everyone, even me, it's not working, it says that "client is not connected"

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
For it to work. Since I also had this problem before, but when I went to GUFW and enabled entry for all ports, it worked, but it's broken now, after starting the server up a long time later.
I did the same things I did to make it work again like I did last time: Re-did the port-fowarding on router, enabled entry and exit for 24454 in computer, except that now it won't work. I'm not sure if this is a conflict issue, probably, but I don't have a single clue to how to discover it.

**Important Note (not sure)**
I did this in a dedicated minecraft server, that is in my own house, but not in the same computer as i'm using now.

**Log files**
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/11186454/latest.log)

**Versions**
- 1.16.5
- Forge version
- Mod Version 2.4.3

**Other mods**
1. Create (Dependencies: Flywheel)
2. Chisel (Dependencies: Connected Textures Mod)
3. Tinkers Construct (Dependencies: Mantle)
5. Constructs Armory (Dependencies: Mantle, Tinkers Construct)
6. Corpse 
7. Simple Voice Chat
8. FTB Library (Dependencies: Architectury API)
9. FTB Ranks 
10. FTB Teams
11. Simply Improved Terrain
12. Custom Skin Loader
13. Ars Nouveau
14. Mana and Artifice
15. Waystones
16. Lightman's Currency
17. Materialis
18. Relics
19. Farmer's Respite
20. Farmer's Delight
21. Oh The Biomes You'll Go
22. Tom's Simple Storage
23. Iron Chests
24. Ore Excavation
25. Just Enough Items

**Screenshots (Optional)**
![Router Port Fowarding](https://user-images.githubusercontent.com/82397029/230799785-aebbd2ad-fb85-44a0-b4f7-d021c804e505.png)
![Computer Port Fowarding, made on GUFW](https://user-images.githubusercontent.com/82397029/230799820-93beb3e8-9a48-4c40-bffb-1bdb24854ef3.png)

**Comment by henkelmax** [comment]
For help, visit the discord. This is the wrong place
