### ISSUE TITLE
Mod Menu Config Screen Not Able To Load

### ISSUE THREAD

**Issue by cookie-GHUB** [henkelmax/simple-voice-chat#564]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
The title kind of says it all, the config screen on mod menu says it's not able to load

**Steps to reproduce the issue**
1. Download and install 'Simple Voice Chat (FABRIC) 1.19.4, and Mod Menu 1.19.4'
2. Open Minecraft
3. Click on 'Mods in the MC main menu'
4. Scroll down to 'Simple Voice Chat'
5. Hover over the icon image
6. See error

**Expected behavior**
What I expected to happen was that the config menu would be able to load :/

**Log files**
Well, there isn't any files, just the thing it said in the Mod Menu: java.lang.NoSuchMethodError:'void net.minecraft.class_2588.<init>(java.lang.String)'

**Versions**
- 1.19.4
- Fabric 0.14.9
- Mod Version 2.4.3

**Other mods**
Advancement Info
BetterPvP
Dropz
Iris
Lithium
Sodium
Phosphor
MiniHUD
Mod Menu (Of Course)
Rayon
Replay Mod
Replay Voice Chat
Smooth Swapping
Sound Physics Remastered
WI Zoom
Xaero's World Map

**Comment by henkelmax** [comment]
Works perfectly fine with voice chat 2.4.3 and the latest modmenu version.
I also can't further investigate your issue if you don't provide any logs like stated in the template.
