### ISSUE TITLE
Graphic glitch with groupscreen if BedrockIfy mod is active

### ISSUE THREAD

**Issue by Cape-City** [henkelmax/simple-voice-chat#565]
**Bug description**
With active BedrockIfy mod this glitch happens, when joining a group:

![grafik](https://user-images.githubusercontent.com/122229367/231534793-ac12942f-52c2-4392-82e7-a8559dc1f6e6.png)

Without BedrockIfy installed and then joined a group it looks normal:

![grafik](https://user-images.githubusercontent.com/122229367/231535464-0eb2b625-f140-4ddf-bd53-510ed937db28.png)

**Expected behavior**
Not such glitch with BedrockIfy Mod active ;)

**Versions**
- Minecraft version 1.19.3
- Fabric 0.14.19
- Mod/Plugin version voicechat-fabric-1.19.3-2.4.4.jar / bedrockify-1.6.1+mc1.19.3.jar

**Other mods**
I created a new profile which only had the voice chat and the bedrockify mod active - no shader, no texturepack.

https://www.curseforge.com/minecraft/mc-mods/bedrockify

**Comment by henkelmax** [comment]
Can you post your logs?

**Comment by Cape-City** [comment]
Sorry, forgotten :/

[latest.log](https://github.com/henkelmax/simple-voice-chat/files/11214260/latest.log)

**Comment by Cape-City** [comment]
Found the setting within BedrockIfy - he has an option which enables the panorma screen on all screens and not only in the top of the main menu. If this setting is disabled, the behavoir of your voice mod is still as it should be. 

Here's the option within BedrockIfy:
![grafik](https://user-images.githubusercontent.com/122229367/231544379-1f4eeb94-33ff-4821-b36b-339549414e8f.png)

With active panorama screen on all screens:
![grafik](https://user-images.githubusercontent.com/122229367/231544029-55520c61-d2f7-4d3f-9030-a2ca67289eff.png)

Maybe he got already the build-in compat-mode, did the groupscreen has a class name for exclude?

**Comment by Cape-City** [comment]
Found something in your sourcecode, if i add 'de.maxhenkel.voicechat' to the disabled list of BedrockIfy, the glitch within the groupscreen is gone. I can live with this so far. If the string is correct for you too, i can report this to the dev from bedrockify, so he can add this for future updates of his mod or do you want to look into your mod to fix it by yourself?

**Comment by henkelmax** [comment]
This is most likely a bug on their end anyways, so please report it to their issue tracker please.
