### ISSUE TITLE
Plugin version should not require forge on client - that will disable clients from joining if forge isn't installed on server [plugin] [forge] [client] [other mods/plugins included]

### ISSUE THREAD

**Issue by BraveCaperCat2** [henkelmax/simple-voice-chat#566]
**Is your feature request related to a problem? Please describe.**
I want to set up a server for my friends and me to play on - I have Java edition and some of my friends do too, but the rest rely on the geyser plugin to join via bedrock, so mods aren't an option.

**Describe the solution you'd like**
Remove reliance on forge being on the client side, so the Geyser plugin becomes fully compatible

**Describe alternatives you've considered**
no alternatives

**Additional context**
Remove reliance on forge being on the client side, so Geyser Plugin becomes fully compatible

**Comment by henkelmax** [comment]
This was never a thing. All clients are always allowed to join with or without voicechat. This is most likely another mod preventing you from joining.

**Comment by BraveCaperCat2** [comment]
> This was never a thing. All clients are always allowed to join with or without voicechat. This is most likely another mod preventing you from joining.

yes, but I want to be able to use this mod with ALL my friends, not just the ones on java.

**Comment by henkelmax** [comment]
You can't mod bedrock. What do you mean?

**Comment by BraveCaperCat2** [comment]
> You can't mod bedrock. What do you mean?

Yes, you can:
![image](https://user-images.githubusercontent.com/113925022/231850332-70fabd64-9664-4ac7-96a1-3cd56849ca96.png)
(the above image was a Google search for "bedrock mods image" - add-ons, also known as resource packs and behaviour packs can be used to add new things to the game - they are not as powerful as Java edition mods, but try [this website](bedrock.dev) which is an entire documentation of bedrock development tools.)

**Comment by henkelmax** [comment]
Addons and behavior packs are NOT mods. It is not possible to implement anything close to a voice chat mod with this.
