### ISSUE TITLE
Mod lacks automatic detection of device changes

### ISSUE THREAD

**Issue by Owehttamy** [henkelmax/simple-voice-chat#567]
**Bug description**
When in-game, the mod (at least the Fabric version) doesn't detect any changes to the player's output environment unless it's manually changed by the player in the voice chat menu. For example, I only have one 'valid' set of speakers on my device: Bluetooth headphones. If they die or disconnect, the mod doesn't recognize that change.

**Steps to reproduce the issue**
> *This issue has slightly different behavior given different circumstances, so I will list the steps to produce each instance.

**Setting up the environment**
1. For ease of reproducing the issue, go to your settings (in this instance, I'm using Windows)
2. Search for "Sound settings."
3. Scroll down to "All sound devices."
4. Disable all input and output devices except one, preferably ones that are easy to connect/disconnect from your computer quickly.

**Connected -> Disconnected**
1. Ensure your microphone/speaker is connected in the main menu.
2. Join a world or server.
3. Disconnect your microphone/speakers while in-game, leaving no other device to input/output.
4. The mod doesn't mute or deafen you as it still thinks you have your device connected, but not in the microphone/speaker selection menus.

**Disconnected -> Connected (Speakers)**
1. Disconnect your one set of speakers while in the main menu.
2. Join a world or server.
3. Connect your speakers while in-game.
4. Go to the voice chat settings to select your speakers as the output device.
5. The mod claims they're already connected in the "select speaker menu," preventing you from *at least* forcing the mod to check again.

**Disconnected -> Connected (Microphone)**
1. Disconnect your microphone while in the main menu.
2. Join a world or server.
3. Notice that the voice chat mod doesn't state that you're—by a technicality—muted, as you have no microphone to talk with.
4. Connect your microphone while in-game.
5. Attempt to talk, and notice it doesn't output anything.
> This also doesn't work for push-to-talk, muting then unmuting, enabling microphone testing, or switching between push-to-talk and voice activation. Essentially, it doesn't work in any instance.
7. Go to the voice chat settings to attempt to select your microphone as the input device.
8. The mod claims they're already connected in the "select microphone menu," preventing you from at least forcing the mod to check again.

Currently, the only way to fix these issues is by relogging, which—in my opinion—is inconvenient.

**Expected behavior**
The mod detects when the current audio devices are no longer present to reflect the proper, up-to-date detection of the device selection screens.
If there's no reasonable way to do that, then at least provide the ability to 'reselect' the audio device you're already using when there's only one available option to avoid periodic checks.
> Given that the device selection menus are the outlier here, it can be assumed that they're only claiming they are selecting the device because the menu probably *needs* to state that something is chosen if devices are available. Another easy way to allow players to fix this manually (without relogging) is by giving the menu the option not to select anything automatically.

**Versions**
- 1.19.4[^1]
- Fabric v0.14.17 (API v0.78.0)[^2]
- Simple Voice Chat v2.4.4
[^1]: I've been dealing with this since August 2022 (been too lazy to report it), so I'd assume this is apparent on all mod versions, given the nature of the issue.
[^2]: This likely occurs on all other client-side versions of the mod, given the nature of the issue.

**Other mods**
Not rooted in a compatibility issue; it still occurs in an environment with only Fabric API and Simple Voice Chat.

**Comment by henkelmax** [comment]
The mod supports multiple audio backends. There is no way with these libraries to detect if devices connect or disconnect. It is completely intended behavior of the mod to not detect changing audio devices. It is not supported/recommended changing your audio setup while the game is running. We are limited by the libraries, Minecraft itself ships.

**Comment by Owehttamy** [comment]
Gotcha.
Is it still possible to allow players to at least re-select their audio device manually in the voice chat settings then? Because currently, if the menu says it's selected (even if it's not or wonked up because of its inability to detect changes), you can't manually *force* it to reconfigure.
Yes, you shouldn't be fiddling with your audio setup while the game is running, but providing a solution other than relogging would be nice.

**Comment by henkelmax** [comment]
I will look into it.
