### ISSUE TITLE
Mod crashes the server

### ISSUE THREAD

**Issue by Max094Reikeb** [henkelmax/simple-voice-chat#57]
**Bug description**
When I launch my server, the mod makes it crash.

**Steps to reproduce the issue**
1. Put the mod in "mod" folder
2. Launch your server
3. It crashes.

**Expected behavior**
Well, it was supposed to launch but it crashes.

**Log files**
[crash-2021-02-18_19.04.53-server.txt](https://github.com/henkelmax/simple-voice-chat/files/6004929/crash-2021-02-18_19.04.53-server.txt)

**Versions**
- Minecraft version : 1.15.2
- Forge version : 1.15.2-31.2.0
- Mod version : latest (1.0.1)

**Other mods**
My other mods are **Electrona**, **Farm adventures II** and **Charm's Ores**

**Comment by henkelmax** [comment]
Has it been fixed with the latest version?

**Comment by Max094Reikeb** [comment]
> Has it been fixed with the latest version?

I am on the latest version. version 1.0.1

**Comment by henkelmax** [comment]
1.0.2 is the latest

**Comment by Max094Reikeb** [comment]
> 1.0.2 is the latest

the bug was fixed less than an hour ago anyways. how do I download the 1.0.2?

**Comment by henkelmax** [comment]
So its fixed?
https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat/files/3208773

**Comment by Max094Reikeb** [comment]
It still crashes... new log report here: 
[crash-2021-02-18_21.36.02-server.txt](https://github.com/henkelmax/simple-voice-chat/files/6005731/crash-2021-02-18_21.36.02-server.txt)

**Comment by henkelmax** [comment]
Can you try it with the latest forge version?
Also please send me the full logs.

**Comment by Max094Reikeb** [comment]
Are my mods gonna work with latest Forge version even if they were created for an older one?

**Comment by henkelmax** [comment]
They should in most cases

**Comment by Max094Reikeb** [comment]
I changed my Forge version to the last (31.2.45) and it works now.
