### ISSUE TITLE
Incompatibilities with MalisisCore

### ISSUE THREAD

**Issue by davidjimeneztv** [henkelmax/simple-voice-chat#571]
**Bug description**
When I have the Simple Voice Chat mod together with Malisis Core on my Mohist 1.12.2 server, the server doesn't start.

**Steps to reproduce the issue**
1. Create a Mohist server 1.12.2
2. Install Simple Voice Chat and MalisisCore.
3. Try to start and the server shutdown unexpectedly.

**Expected behavior**
After trying to start the server with the mentioned mods, the server shuts down unexpectedly without generating a crash-report but looking at the logs, it indicates problems with the Mixin version. Without the MalisisCore mod, the server runs correctly

**Log files**
https://gist.github.com/davidjimeneztv/675c89687615b284eaf00cf7bb5fbf98

**Versions**
- Minecraft 1.12.2
- Mohist 1.12.2-320
- Latest version of MalisisCore & Simple Voice Chat.

**Comment by henkelmax** [comment]
We don't support hybrid servers.
