### ISSUE TITLE
Microphone Unavailable

### ISSUE THREAD

**Issue by Catomax262** [henkelmax/simple-voice-chat#574]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
It sucks, i was mining then got killed by a skeleton due to the massive lag spike caused by this check.
It then displayed "Microphone Unavailable". I currently have no microphones, but plan to have one.

**Steps to reproduce the issue**
1. Wait for the lag spike to happen
2. See the Microphone unavailable message

**Expected behavior**
Not cause massive lag spikes when checking.

**Log files**
n/a

**Versions**
- Minecraft 1.18.2
- Forge 4.0.2.1
- SVC 2.4.5

**Other mods**
none interfering

**Screenshots (Optional)**
Screenshots of the issue.
![2023-05-01_22 20 57](https://user-images.githubusercontent.com/80112576/235572862-919d9029-ecb5-473c-a6e0-8f27939566f7.png)

**Comment by henkelmax** [comment]
Please provide log files

**Comment by Catomax262** [comment]
latest log: https://gist.github.com/Catomax262/e3139bec4489b5d11af41ad556883b3e
debug log: https://gist.github.com/Catomax262/7d56940909ecff0a70dfd1a60eada2ee

**Comment by henkelmax** [comment]
It looks like your microphone is not compatible with voice chat. Please update your drivers or try another microphone. But there is generally nothing we can do about that, as we are limited to the libraries that are shipped with minecraft.

**Comment by Catomax262** [comment]
> It looks like your microphone is not compatible with voice chat. Please update your drivers or try another microphone. But there is generally nothing we can do about that, as we are limited to the libraries that are shipped with minecraft.

That's the issue, there is no microphone connected. I don't know why it has to lag a lot while checking for a microphone when there is none connected yet.

**Comment by henkelmax** [comment]
I just tested it myself and there is no lag spike at all. This message should also only show up when joining a world or you actively unplugging/disabling the microphone. This should never happen during normal gameplay.
