### ISSUE TITLE
Simple Voice Chat No device permission log keep spamming

### ISSUE THREAD

**Issue by zyxkad** [henkelmax/simple-voice-chat#575]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
When I join the server, simple voice chat will keep spamming the no permission log, the ping will be rising up as well (without this mod my ping is 50ms, but with this it can be up to 2s then timed out).
I'm on Macos 13.3.
This issue just happend in an hour, before the hour, all things fine, and both of the server and client didn't change anything.
Rejoin not help either.

**Steps to reproduce the issue**
1. Install Simple Voice Chat
2. Do not give the device permission to Minecraft
3. Join a server
4. The log will keep spamming

**Expected behavior**
The log only appear once

**Log files**
<https://gist.github.com/zyxkad/1efb9ddf1aadd35facb2edaadc8b936c>

**Versions**
- Minecraft: 1.19.2
- Forge: 43.2.4
- Mod: 2.4.4

**Other mods**
[https://modrinth.com/modpack/automation](https://modrinth.com/modpack/automation/version/v3.3)

**Screenshots (Optional)**
<img width="640" alt="Screenshot 2023-05-03 at 8 13 48 AM" src="https://user-images.githubusercontent.com/91082411/235942127-22c451f4-9c16-488f-8fa4-2244ffc62e33.png">

**Comment by henkelmax** [comment]
Please provide your logs like stated in the template.

**Comment by zyxkad** [comment]
Alr

**Comment by zyxkad** [comment]
And the spam start at <https://gist.github.com/zyxkad/1efb9ddf1aadd35facb2edaadc8b936c#file-latest-log-L2624>

**Comment by henkelmax** [comment]
This message is only shown if you change the server or voice chat disconnects. 
In your logs, your voice chat connection constantly times out. Please check the voice chat server setup or your internet connection.

This message will also not show up if you granted microphone permissions in your settings.

**Comment by zyxkad** [comment]
> Please check the voice chat server setup or your internet connection.

But as I said, without this mod installed on client, the internet don't have any problem. And also server didn't change anything

**Comment by henkelmax** [comment]
As I already said it could aswell be a configuration issue on the server. These are the only two reasons why voice chat could time out.

**Comment by zyxkad** [comment]
> As I already said it could aswell be a configuration issue on the server. These are the only two reasons why voice chat could time out.

But even voice chat timed out, it shoudn't affect the main connection, is that caused by the voice chat do too much work in the main/render thread?

**Comment by henkelmax** [comment]
Not sure what you mean with that.

**Comment by henkelmax** [comment]
The message will now only show up after joining a world in the next version. But as I already said. this is not your actual issue.
