### ISSUE TITLE
Simple Voice Chat randomly crashes JVM on quilt server

### ISSUE THREAD

**Issue by AT14C** [henkelmax/simple-voice-chat#579]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Just by having simple voice chat loaded on a 1.19.4 quilt server it can crash the JVM at any given moment

**Steps to reproduce the issue**
1. Start a 1.19.4 quilt server with simple voice chat 1.19.4 2.4.7
2. Connect to the server
3. Wait for it to crash

**Expected behavior**
Not to crash my server

**Versions**
- Minecraft 1.194
- Quilt 0.18.10
- Simple Voice Chat 1.19.4 2.4.7 Quilt

**Other mods**
Crashes both with my modpack installed and by being the only mod installed

I tested this with both OpenJDK and GraalVM
Full PID dump included (log segment from PID dump)
[hs_err_pid3964.log](https://github.com/henkelmax/simple-voice-chat/files/11496691/hs_err_pid3964.log)

**Comment by henkelmax** [comment]
Please send the full logs with github gist, like described in the bug template

**Comment by AT14C** [comment]
https://gist.github.com/AT14C/0cc3ab355af72b535a3cc0bfb7a1f1e1

**Comment by henkelmax** [comment]
Which OS and OS version are you using? And which CPU architecture are you using?
Please also send me the logs with OpenJDK.

**Comment by AT14C** [comment]
OS: RebornOS Linux ARM aarch64 
Host: Radxa ROCK 5B 
Kernel: 5.10.110-rockchip-rk3588 
CPU: (8) @ 1.800GHz
Memory: 16 GB

**Comment by henkelmax** [comment]
Can you try if it works on a more common linux distro like Ubuntu? RebornOS for ARM seems to be in beta so that might not be very stable.

**Comment by AT14C** [comment]
OpenJDK log
https://gist.github.com/AT14C/e9cab8897250c8bfbb8acc28f99e822c

**Comment by AT14C** [comment]
Will try setting `use_natives` to false

**Comment by henkelmax** [comment]
> Will try setting `use_natives` to false

Thats only for clients. The server doesn't use voice chats natives (if you don't use addon mods).

**Comment by henkelmax** [comment]
The natives of the mod shouldn't be loaded at all and from your logs they also don't seem to be.
This looks like an issue with Java in general. Please try if you are getting the same issue on another distro like Ubuntu or similar.

**Comment by AT14C** [comment]
Still getting JVM crashes even after removing voice chat mod, so it seems to not be simple voice chat
