### ISSUE TITLE
Voice Chat Unavailable

### ISSUE THREAD

**Issue by TrialDragon** [henkelmax/simple-voice-chat#58]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**
Did read the FAQ and Wiki looking into the issue.

[Issue]
When I press any of the Voice chat keys I get the message Voice Chat Unavailable. This is despite me opening the port via router page and then making sure my firewall is allowing it through as far as I know

.

[Expected]
I expected to be able to chat via the mod. 

**Log files**
[latestLog](https://pastebin.com/NTSaZ9Gd).

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.0.42
- Mod version: 1.0.6

**Other mods**
![Modlist](https://user-images.githubusercontent.com/31419708/108475752-fdb8f900-7245-11eb-906e-97a3cb5c4c0a.png)

**Screenshots (Optional)**
![2021-02-19_00 11 40](https://user-images.githubusercontent.com/31419708/108476638-1d045600-7247-11eb-9885-e161f02cee4c.png)

**Comment by henkelmax** [comment]
I can't see any trace of the mod being installed in your logs.

**Comment by TrialDragon** [comment]
Here a log with reference to it. Apologies that the original didn't retain that detail. 
[Log](https://pastebin.com/VNPKCZDR)

**Comment by henkelmax** [comment]
Can you please also send the logs of your client?

**Comment by TrialDragon** [comment]
@henkelmax Here is the [latest.log](https://pastebin.com/CVWL1rbY) in my folder. Hopefully, it has all the necessary info. Do you need a debug.log as well?

**Comment by henkelmax** [comment]
It seems that you don't have your port forwarded correctly. Please read the wiki for more information.

**Comment by TrialDragon** [comment]
@henkelmax  I have read the wiki and done all the steps mentioned there, before and after posting the issue to be sure. Is it possible that the tests provided there do not work if the server is hosted on the same machine as the client? But I tried some other methods for checking ports and you're right, despite having forwarded the port on my router the same way as 25565(which works) 24454 is showing as listening or filtered (which from my understanding means blocked by firewall) even when the inbound rules allow 24454 UDP. Do you have any idea of ways to troubleshoot this? Or is this now an issue beyond the scope you can deal with.

**Comment by henkelmax** [comment]
Have you tried if netcat works?

**Comment by TrialDragon** [comment]
@henkelmax  Yes, it does work the way you say it should in the wiki. But I have concerns it's not actually testing if 24454 is open because the server and client are on the same machine.

**Comment by henkelmax** [comment]
So the voicechat works on your local machine?

**Comment by TrialDragon** [comment]
No, it does not. What I've been testing is my client connecting to a server on the same machine. This is why this is odd as you'd think the client on the same machine as the server would be the most likely to work. Also, I did another test with inbound and outbound exception rules for 24454 UDP, and still the same issue. Also tested netcat again and it does work.

**Comment by henkelmax** [comment]
That's strange!
Can you try it without any other mods on the client and server?

**Comment by TrialDragon** [comment]
Same issue: [debug log](https://paste.ee/p/HNpDO)

**Comment by TrialDragon** [comment]
So, progress. Apparently, GDLauncher thought it preferable to download 1.16.5-1.0.0 on the client instead of the latest. So having updated both server and client to 1.0.8 I can now press capslock, v, and m and access their menus and functionalities. Though I still have not tested whether or not I can hear others or if others can hear me.

**Comment by henkelmax** [comment]
No problem. Happens to everyone :)
Let me know if you can hear each other.

**Comment by TrialDragon** [comment]
@henkelmax  Quick extra, do all who use this mod need to open port 24454? A user on the server is having the same voice chat unavailable when trying to use it.

**Comment by henkelmax** [comment]
It only has to be opened on the server.

**Comment by TrialDragon** [comment]
@henkelmax 
Okay we did the netcat test and I can't type anything serverside and I receive nothing he typed. I'm guessing this means my router is refusing to port forward any port other than 25565?

**Comment by henkelmax** [comment]
Make sure the firewall on your computer is set up correctly. Also check that the router port forwarding has your computers IP. Maybe you set your forwarding to TCP instead of UDP.

**Comment by TrialDragon** [comment]
@henkelmax I believe my firewall is set up correctly. It's Windows Defender. And the router does have the specific machine private IP set for the port and the port is UDP. I genuinely have no clue why this isn't working unless it's something like my ISP blocking most ports other than 25565 and the base common use ones.

**Comment by henkelmax** [comment]
There are many reasons why it wouldn't work. It could be that your ISP uses Dual-Stack Lite or many other reasons. But I can't help you with that.
