### ISSUE TITLE
Connected client has incompatible voice chat version

### ISSUE THREAD

**Issue by maxbrennan** [henkelmax/simple-voice-chat#583]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
I installed the voice chat plugin on my Spigot server, and my friend and I installed it on our clients. My friend uses Questcraft (Minecraft for VR), and I use Forge. Everything works for me, but not for my friend. When he joins, I see this in the logs:

`Connected client SeaBass209 has incompatible voice chat version (server=17, client=15)`

I would probably end up going through a lot of trouble to upgrade my friend's voice chat version if it's even possible (since he's on a VR client). I tried looking this up and couldn't find anything. I know each voice chat has a version (The one for the server is 2.4.8) but the "15" and "17" are really throwing me off.

Can somebody help me find the specific version my friend is using so I can add it to my server?

**Steps to reproduce the issue**
1. Install the most recent version of Simple Voice Chat on a server
2. Install A lower version of Simple Voice Chat onto a client
3. Join the server using the outdated client
4. Find the information dumped into the logs when the person joined.

**Expected behavior**
I kinda expected this to happen. Literally the only thing I need is the version of the voice chat that I need to add to the server.

**Log files**
~Me crossing my fingers that it doesn't count this ticket as invalid because I didn't give a link~
`Connected client SeaBass209 has incompatible voice chat version (server=17, client=15)`

**Versions**
- Minecraft version: 1.19.4 on everything
- Forge/Fabric/Bukkit/Spigot/Paper version: 1.19.4
- Mod/Plugin version: Just read above ^^^

**Other mods**
Don't think this is the problem, but ok:

1. Vivecraft Spigot Extensions (To support VR)
2. World Edit

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Completely intended. You need the most recent minor version as stated in the wiki.
