### ISSUE TITLE
Mac OS Mic Problem

### ISSUE THREAD

**Issue by PleaseHelpWPLIGHTSOS** [henkelmax/simple-voice-chat#584]
I saw that there was already a posted issue about this but no specific terminal sequence for CurseForge?
I can't seem to find any information for how to open Minecraft through curseforge THROUGH the terminal
I also saw that there was a solution but it was outdated? any update on this?

**Comment by marsupialgoddess** [comment]
was this ever fixed?

**Comment by henkelmax** [comment]
https://modrepo.de/minecraft/voicechat/wiki/macos
