### ISSUE TITLE
Compatibility issues between the mod "Simple Voice Chat" and the mod "Locks" in Minecraft 1.12.2

### ISSUE THREAD

**Issue by TitooTVGeilo** [henkelmax/simple-voice-chat#588]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Hi, your mod "Simple Voice Chat" and the Mod "Locks" work not when I this 2 mods have in my mods folder. Only then I play
only with your mod or the "Locks" mod then work Minecraft and start normal. I have it test with other mods and only the "Locks" Mod is the only one mod what a compatibility problem with your mod have. I hope you can a Fix make who the Compatibility of you Mod and the "Locks" Mod is fix.

**Steps to reproduce the issue**
1. Download Mod: Simple Voice Chat  MC 1.12.2 Version 2.4.10 + Mod: Locks MC 1.12.2 Version 3.0.0
2. Put the Mods in the Mods folder
3. Start Minecraft and choose the newest Forge 1.12.2 Version and start it
4. The Game will start but in under 5 seconds the game Crash and the "exit code: 1" massage will show you on your PC Screen

**Expected behavior**
I have a normal start of Minecraft with this 2 mods have hope the Mods work alone very good but so in same time work it not

**Log files**
Minecraft create for "exit code: 1" no Crash Report and say me not why the game crash

**Versions**
- Minecraft version: 1.12.2
- Forge/Fabric/Bukkit/Spigot/Paper version: 1.12.2-forge-14.23.5.2860
- Mod/Plugin version: 2.4.10

**Other mods**
- Fluidlogged API Version 2.2.4-mc1.12.2 - Link: https://www.curseforge.com/minecraft/mc-mods/fluidlogged-api/files/4564413
- paniclecraft-1.12.2-2.12.0.0 - Link: https://www.curseforge.com/minecraft/mc-mods/paniclecraft/files/4569535
- Locks-1.12.2-3.0.0 - Link: https://www.curseforge.com/minecraft/mc-mods/locks/files/3568569

**Screenshots (Optional)**
I have one Screenshot of the Error Massage

![Screenshot 2023-06-13 194455](https://github.com/henkelmax/simple-voice-chat/assets/108121897/f1414117-3b95-403e-838e-19bc392acf74)

**Comment by henkelmax** [comment]
Please provide your logs from `logs/latest.log`

**Comment by TitooTVGeilo** [comment]
Hi, okay her the link to the logs. 
Google Drive Link: https://drive.google.com/drive/folders/1R4UfN3bni5dCFZz1qU3Q4lFKZ6zgpWjJ

**Comment by henkelmax** [comment]
I don't have access to that file. Please upload your logs like stated in the template with github gist

**Comment by TitooTVGeilo** [comment]
Link: https://gist.github.com/TitooTVGeilo/e7eb793d339cdbb433b9bbcda43fa055

**Comment by henkelmax** [comment]
> Mixin config voicechat.mixins.json requires mixin subsystem version 0.8 but 0.7.11 was found. The mixin config will not be applied.

The other mod ships with an outdated mixin version thats not compatible with the voice chat mod.
