### ISSUE TITLE
I can't connect to voicechat on my own server

### ISSUE THREAD

**Issue by that1polish** [henkelmax/simple-voice-chat#589]
**Bug description**
i can't connect to voicechat on my own server and when i try the following error appears in the server console
 Ignoring chat session from nicekid100 due to missing Services public key
**Steps to reproduce the issue**
1. join a server on a new installation of the mod/plugin on both client and server
2. realize your not connected
3. check console

**Expected behavior**
voice chat connects
**Log files**
i already provided the logs
**Versions**
- Minecraft version 1.20.1
- Forge/Fabric/Bukkit/Spigot/Paper version fabric loader 0.14.21
- Mod/Plugin version 1.20.1-2.4.10

**Other mods**
fabric api
mod menu
sodium
**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
This is not a bug. If you need help, visit the Discord.
