### ISSUE TITLE
reverb "feedbacks" back into itself, making an loud highpitch sound when using sound physics

### ISSUE THREAD

**Issue by slovinsqui** [henkelmax/simple-voice-chat#590]
**Bug description**
audio echoes with itself and gets absurdly loud very quickly

**Steps to reproduce the issue**
1.Load world
2. speak in cave 
3. wait for reverbation to make the sound absurdly loud

**Expected behavior**
healthy eardrums

**Versions**
- 1.19.2
- fabric 0.14.21
- voicechat-fabric-1.19.2-2.4.10.jar

**Other mods**
Might have something to do with vc interaction, or sound physics remastered, i also have dynamic sound filters but the reverb function is disabled so I dont think this one is causing the issue

**Comment by henkelmax** [comment]
This isn't caused by the voice chat mod.
