### ISSUE TITLE
Simple Voice X Replay Voice chat Error

### ISSUE THREAD

**Issue by TheRTGGaming** [henkelmax/simple-voice-chat#593]
In the newer versions of the Replay Voice chat mod it requests lower versions. Replay Voice chat 1.19.2-1.2.3 is incompatible with Verson 1.19.2-2.4.0 or later. 

and it also is not updated to handle the newer version of Replaymod. so it requested a version that the Voice chat mod is not compatable with. i know this because i could not hear my voice in the replaymod.

**Comment by henkelmax** [comment]
This is not an issue with the voice chat mod.
