### ISSUE TITLE
No connection if server and client on same machine

### ISSUE THREAD

**Issue by 9ghtX** [henkelmax/simple-voice-chat#594]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
I set up server on my machine and play on it, so server and client on same PC. In VoiceChat server properties there is opened port (as in Wiki - 24454). But UI says there is no connection.
Then I found website (playit.gg, guide - https://discuss.playit.gg/t/how-to-use-simple-voice-chat-for-minecraft-with-playit-gg/70) that makes tunnels (as I thought there is problem that VoiceChat can't connect local-to-local). So it don't work too.

For tunnel method I created new tunnel for localhost:24454. Then used create tunnels' IP and port for voice_host and port properties in voicechat.server.properties.

Other settings haven't been touched.

**Steps to reproduce the issue**
1. Set up voicechat.server.properties (Wiki variant and tunnel server variant)
2. Start server on local machine
3. Join server on same local machine
4. VoiceChat doesn't work (no connection)

**Expected behavior**
Voice chat properly works

**Log files**
Properties without tunnel server:
port=24454
voice_host=

Properties with tunnel server:
port=12547 //this port from tunnel server
voice_host=law-version.at.ply.gg //IP address of tunnel

**Versions**
- Minecraft version - 1.18.2
- Forge version - 40.2.4
- Mod version - 2.4.11

**Other mods**
Maybe some Adaprive Perfomance Tweaks mod (I have Core, GameRules, Items, Player and Spawn mods) breaks something, but there is no issues in logs.

**Comment by henkelmax** [comment]
If you need help setting up the mod, visit the discord.
