### ISSUE TITLE
[forge 1.19.2] crash client

### ISSUE THREAD

**Issue by GitJhopa** [henkelmax/simple-voice-chat#599]
[crash-2023-07-03_19_11_43-client.txt](https://github.com/henkelmax/simple-voice-chat/files/11938724/crash-2023-07-03_19_11_43-client.txt)

**Comment by henkelmax** [comment]
Please fill out the bug template. I can't help you with just the logs. Please open another issue and fill out the provided template. Also please make sure you don't run multiple instances of the game from the same location. Also don't mess with the mod files if the game is running.
