### ISSUE TITLE
Crash when opening menu

### ISSUE THREAD

**Issue by MatthewNeri** [henkelmax/simple-voice-chat#6]
When opening the voice menu the game will "save the world" and proceed to crash to desktop.

Steps to reproduce the issue:
1. Launch game
2. Log onto server
3. press V
4. Wait

Versions:
- Minecraft version: 1.16.4
- Forge version: 35.1.4
- Mod version: 1.0.1
[crash-2020-12-10_22.23.54-client.txt](https://github.com/henkelmax/simple-voice-chat/files/5676927/crash-2020-12-10_22.23.54-client.txt)

**Comment by henkelmax** [comment]
Does this also happen without any other mods?

**Comment by henkelmax** [comment]
Please try the latest version.

**Comment by MatthewNeri** [comment]
> Please try the latest version.

Thank you so much for the fast response time, the new version seems to have resolved the issue!
