### ISSUE TITLE
Client not connected

### ISSUE THREAD

**Issue by ProBlox42R** [henkelmax/simple-voice-chat#600]
**Bug description**
I wanted to play minecraft on my server with voicechat and I installed that mod.
then I joined and it showed this icon.
![image](https://github.com/henkelmax/simple-voice-chat/assets/125913836/2274efcf-1f98-481f-a29b-51db0928d575)
I don't know how to fix it.
PLEASE HELP!

**Steps to reproduce the issue**
1. Installed Simple Voice Chat on client and server.
2. I tried to test it with /voicechat test [my name].
3. It showed Client not connected.

**Versions**
- Minecraft version - 1.20.1
- fabric/bukit/spigot/paper - 1.20.1
- Mods - 1.20.1

**Other mods**
Fabric API
Controlable
Framework

**Comment by henkelmax** [comment]
This is not a bug. Visit the discord for help setting up the mod.
