### ISSUE TITLE
viaversion dependecy has incompatibility with kyrpton

### ISSUE THREAD

**Issue by stag-enterprises** [henkelmax/simple-voice-chat#603]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
basically this thing needs [viaversion](https://www.modrinth.com/mod/viafabric).
thats fine but viaversion doesnt work with [krypton](https://www.modrinth.com/mod/krypton) as you can see here astei/krypton#12 and ViaVersion/ViaFabric#89

**Steps to reproduce the issue**
1. install viafabric
2. install krypton
3. install simple voice chat
4. see error

**Expected behavior**
no error

**Log files**
see this: https://ambigious.hypixel.pro/e3k411k9svj5vhr8xa.png

**Versions**
- Minecraft version
- Forge/Fabric/Bukkit/Spigot/Paper version
- Mod/Plugin version

**Other mods**
im pretty sure its not becuase of other mod

**Screenshots (Optional)**
none

**Comment by henkelmax** [comment]
This is a soft dependency:

https://github.com/henkelmax/simple-voice-chat/blob/1.20.1/fabric/src/main/resources/fabric.mod.json#L39-L43

![image](https://github.com/henkelmax/simple-voice-chat/assets/13237524/d204a30d-e4e3-4047-961a-19df7f06a0ab)
![image](https://github.com/henkelmax/simple-voice-chat/assets/13237524/ea49f6d8-d40f-4640-b821-beb4fc49be95)


For bukkit aswell:

https://github.com/henkelmax/simple-voice-chat/blob/999436b9b067500794b299775784f73341733e24/bukkit/src/main/resources/plugin.yml#L23


But even if this would be a hard dependency, this seems to be a krypton issue. So we won't change anything here.
