### ISSUE TITLE
PTT & whisper keys handled incorrectly

### ISSUE THREAD

**Issue by isXander** [henkelmax/simple-voice-chat#604]
**Bug description**
The afformentioned binds are handled inside of [a keyboard event](https://github.com/henkelmax/simple-voice-chat/blob/1.20.1/common/src/main/java/de/maxhenkel/voicechat/voice/client/PTTKeyHandler.java#L16C1-L16C1). This is incorrect. Usually, mods handle this inside the game tick, which you have done for all other binds. This is an issue for me as it breaks compatibility with mods that emulate key presses. Namely, my mod, [Controlify](https://modrinth.com/mod/controlify). This prevents the use of controller bindings on SVC as no key event is actually invoked.

**Steps to reproduce the issue**
1. Install Controlify with SVC
2. Bind PTT or whisper
3. Attempt to use

**Expected behavior**
PTT and whisper should be handled like all other keybinds so they work correctly.

**Versions**
- Minecraft version - 1.20.1
- Quilt loader
- v2.4.16

**Comment by henkelmax** [comment]
This is done on purpose, as these keys need to work globally. This means, it has to work, when Minecraft key input events are blocked, like when you are in a text box.
