### ISSUE TITLE
crash client 1.19.2 Forge

### ISSUE THREAD

**Issue by GitJhopa** [henkelmax/simple-voice-chat#605]
crash client 1.19.2 Forge
[crash-2023-07-28_08.04.13-client.txt](https://github.com/henkelmax/simple-voice-chat/files/12190402/crash-2023-07-28_08.04.13-client.txt)

**Comment by GitJhopa** [comment]
In general, I don’t understand why you are closing my tickets, your mod always crashes on 1.19.2 Forge when a player tries to invite someone to the group or even random crashes happen

**Comment by henkelmax** [comment]
Please fill out the bug template when reporting issues. And make sure you don't change anything in your mod folder while the game is running.
