### ISSUE TITLE
crash client 1.19.2

### ISSUE THREAD

**Issue by GitJhopa** [henkelmax/simple-voice-chat#607]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Client crashes

**Steps to reproduce the issue**
1. The player just plays and activates the voice chat and the game crashes.
2. Sometimes tries to create a group or select group settings.
3. These bugs appeared after adding the ability for groups to hear other players

**Expected behavior**

**Log files**
https://gist.github.com/GitJhopa/526430dec1a81ec99694e880c929bc73

**Versions**
Minecraft 1.19.2
- Forge
- Mod

**Other mods**
voice chat
sound physic

**Screenshots (Optional)**
nope

**Comment by henkelmax** [comment]
> java.lang.NoClassDefFoundError: de/maxhenkel/voicechat/voice/client/TalkCache$Talk

This usually happens when you remove or replace the mod file while the mod is running. This isn't a bug with the mod.
