### ISSUE TITLE
Voicechat broken But I can't break

### ISSUE THREAD

**Issue by NotaJojofan** [henkelmax/simple-voice-chat#610]
Bug doesnt let player Hit or break because any Mods that start with b

https://gist.github.com/NotaJojofan/a062470a9b5a19e64a7b6addb92aa544/revisions

1.20.1
Fabric 0.14.22
2.4.18

![resim_2023-08-10_210105942](https://github.com/henkelmax/simple-voice-chat/assets/127620002/21a0e078-7280-4144-bfc7-b38fb3701ed8)

**Comment by henkelmax** [comment]
Can you please actually fill out the bug template and describe the steps to reproduce your issue.

And also please describe the actual issue you are having. Your description is not helpful AT ALL!

**Comment by NotaJojofan** [comment]
well sorry ur mod doesnt let player (client side) break or hit when u have any mod that start with B
example :Bedrockify,Blanket,AnyB mod
I dont know why it is

**Comment by henkelmax** [comment]
And everything works when voice chat is removed?

**Comment by NotaJojofan** [comment]
yes surely just voicechat hate B

**Comment by henkelmax** [comment]
Just tested it and everything works fine. I'm almost 100% sure that this is not because of the letter B.

**Comment by NotaJojofan** [comment]
you need video or what

**Comment by NotaJojofan** [comment]
I literally tried million times

**Comment by henkelmax** [comment]
I ran my instance that has bobby installed and voice chat 2.4.18 and everything worked fine. I can assure you its not because of the letter B.

**Comment by NotaJojofan** [comment]
Or Its because of these mods

**Comment by NotaJojofan** [comment]
I will try again

**Comment by NotaJojofan** [comment]
Its doesnt work on Bedroidum and Blanket
I believe anything like Beecraft Birchtweak Bxxx  wont work these mods dont have any similarty but being client side
Its maybe java problem But I dont think so

**Comment by NotaJojofan** [comment]
Last Change I updated java didnt work out Its all about your mod now I guess @henkelmax

**Comment by henkelmax** [comment]
Please give me a minimal reproducible example. Which other mod than the voice chat mod do I need to install?

**Comment by NotaJojofan** [comment]
I tried again try something else only voicechat doesnt incompatibility with B theres a mod supporting this. sorry for bad grammer

**Comment by NotaJojofan** [comment]
I will find it I promise

**Comment by NotaJojofan** [comment]
I found it is Dynamic fps mod this mod and your mod makes Fabric Minecraft to hate mods that start with B 
1 Install voicechat,dynamic fps, any B mod 
2 Start minecraft and Get in any Multiplayer server
3 Press Mouse 1 U will see U cant break or hit

**Comment by henkelmax** [comment]
I am using dynamic FPS in my Minecraft instance. (Also the one I tested before). There is no issue.

**Comment by NotaJojofan** [comment]
Maybe It doesnt works on bobby ? Can u try with Bedrockify or blanket I literally Tried hard for this come on

**Comment by henkelmax** [comment]
Tested it and still nothing.

**Comment by NotaJojofan** [comment]
you playing original minecraft right I mean not cracked I am playing crack and this can be problem ? or Windows 7 I dont really know anymore

**Comment by NotaJojofan** [comment]
I just wanted play normally soooooooooooooo good game

**Comment by henkelmax** [comment]
We don't provide support for people that pirate the game.
