### ISSUE TITLE
Game Crashed With Other Mods Enabled in 1.16.5

### ISSUE THREAD

**Issue by ENDlezZenith** [henkelmax/simple-voice-chat#611]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
The game crashed with other mods enabled in 1.16.5

**Steps to reproduce the issue**
1. launch game with (Latest, and prior version tested with the same error): 
  I. malilib-fabric-1.16.5-0.10.0-dev.21+arne.8 (Library, ignore)
  Disable any one of the follow three mods would stop the crash, I have no idea:
  II. voicechat-fabric-1.16.5-2.4.18
  III. litematica-fabric-1.16.5-0.0.0-dev.20210917.192300
  IV. minihud-fabric-1.16.5-0.19.0-dev.20210917.191825
2. Game crashed.

**Expected behavior**
Game crashed.

**Versions**
- 1.16.5
- Fabric 0.14.22 (Latest, and prior version tested with the same error)
- voicechat-fabric-1.16.5-2.4.18 (Latest, and prior version tested with the same error)

**Other mods**
  I. malilib-fabric-1.16.5-0.10.0-dev.21+arne.8 (Latest, and prior version tested with the same error)
  II. litematica-fabric-1.16.5-0.0.0-dev.20210917.192300 (Latest, and prior version tested with the same error)
  III. minihud-fabric-1.16.5-0.19.0-dev.20210917.191825 (Latest, and prior version tested with the same error)

**Screenshots (Optional)**
![image](https://github.com/henkelmax/simple-voice-chat/assets/69727714/c20bdbaa-9c32-44f4-860c-87ef03182b7b)

**Comment by henkelmax** [comment]
Please upload your logs with GitHub gist, as stated in the template.

**Comment by ENDlezZenith** [comment]
https://gist.github.com/Na3MnO4/86e1e8353ad6c57f88e6683429b90d7c

**Comment by henkelmax** [comment]
Thank you, I was able to reproduce this issue myself.
