### ISSUE TITLE
Server Can't Be Stopped With Some Mod in 1.16.5

### ISSUE THREAD

**Issue by ENDlezZenith** [henkelmax/simple-voice-chat#612]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Server can't be stopped with the mod in 1.16.5.

**Steps to reproduce the issue**
1. Using 1.16.5-Fabric-0.14.22 Server. (Latest)
2. Add voicechat-fabric-1.16.5-2.4.19.jar and fabric-api-0.42.0+1.16.jar to the mod dictionary. (Latest)
3. Start the server.
4. See error.

**Expected behavior**
When you try to type "stop" in the shell, server can't be stopped, the only way to force stop the server is Ctrl+C, and that's not a good way.

**Log files**
https://gist.github.com/Na3MnO4/f78df81215d6e2af8682426d0674ff85

**Versions**
- 1.16.5
- Fabric 0.14.22
- voicechat-fabric-1.16.5-2.4.19.jar
-  fabric-api-0.42.0+1.16.jar

**Other mods**
voicechat-fabric-1.16.5-2.4.19.jar
fabric-api-0.42.0+1.16.jar

**Screenshots (Optional)**
<img width="861" alt="Screenshot 2023-08-16 043512" src="https://github.com/henkelmax/simple-voice-chat/assets/69727714/85a334dd-fd3d-4c0c-ae63-dacff987b427">
↑What actually happened is just stuck at RCON stopped, without seeing the username of the computer in the next line meaning that the server was not stopped for some reason. But I saw nothing error in the log? But when removing the voicechat mod, the username could be displayed normally, meaning that the server is totally stopped, which looks like↓
<img width="864" alt="Screenshot 2023-08-16 043530" src="https://github.com/henkelmax/simple-voice-chat/assets/69727714/778d9327-11bd-405d-8bfc-eac42261ccb1">

**Comment by ENDlezZenith** [comment]
And here is my server.properties settings, hope it could help you!
If you need any more details, I'm always here to help!
#Minecraft server properties
#Wed Aug 16 04:48:15 CST 2023
enable-jmx-monitoring=false
rcon.port=25579
level-seed=
gamemode=creative
enable-command-block=true
enable-query=false
generator-settings=
level-name=world
motd=A Minecraft Server
query.port=30002
pvp=true
generate-structures=true
difficulty=hard
network-compression-threshold=256
max-tick-time=60000
max-players=500
use-native-transport=true
online-mode=false
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
max-build-height=256
server-ip=
allow-nether=true
server-port=25569
enable-rcon=true
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
resource-pack=
entity-broadcast-range-percentage=100
rcon.password=password
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
snooper-enabled=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
max-world-size=29999984

**Comment by henkelmax** [comment]
I can't see any errors in your screenshots and logs.
Please check if this happens without the mod too.

**Comment by ENDlezZenith** [comment]
When you type “stop”, it won’t exit the minecraft server command line. You may reproduce it, pretty easy to. I’m reporting this issue since I found that the server can’t be restarted, and the status stuck at stoping the minecraft server, thus targeted at this mod.

**Comment by ENDlezZenith** [comment]
The first screenshot showed that the server is still in the minecraft server command line even if I typed “stopped”, the second screenshot without the mod showed that the server is successfully stopped and return to the Windows PowerShell command line

**Comment by ENDlezZenith** [comment]
I’ve checked that delating the mod would make everything normal. Have a look at the bottom of the both screenshot, that’s two different situation just as mentioned in the last comment.

**Comment by henkelmax** [comment]
I can confirm, this happens with 2.4.19+ in every Minecraft version.
