### ISSUE TITLE
macOS Microphone Permissions

### ISSUE THREAD

**Issue by 0PandaDEV** [henkelmax/simple-voice-chat#614]
**Bug description**
The bug occurs when playing minecraft on a server or single player with Simple Voice Chat installed. It throws an error in the in game chat that says "Your Launcher does not support Microphone Permissions".

**Steps to reproduce the issue**
1. Install fabric and simple voice chat
2. Start minecraft
3. Join a server that has the plugin installed.
4. The message should appear in the chat

**Expected behavior**
It should open a popup that says Requesting permission for Microphone or when starting minecraft it should open a window where it says you should drag the launcher into

**Log files**
https://gist.github.com/0PandaDEV/6087496b8182b2296e6a5b7554fce726

**Versions**
- minecraft 1.20.1
- fabric 0.14.22
- simple voice chat 2.4.20

**Other mods**
fabric-api-0.87.0+1.20.1.jar
reeses_sodium_options-1.6.4+mc1.20.1-build.94.jar
simple-voice-chat-macos-workaround.jar
sodium-extra-0.5.0+mc1.20.1-build.111.jar
sodium-fabric-mc1.20.1-0.5.0.jar
voicechat-fabric-1.20.1-2.4.20.jar

**Screenshots (Optional)**
![image](https://github.com/henkelmax/simple-voice-chat/assets/70103896/4d663453-c0ad-4534-b394-f1d263c5bcce)

**Comment by henkelmax** [comment]
https://modrepo.de/minecraft/voicechat/wiki/macos
