### ISSUE TITLE
Polymer + Velocity breaks Voicechat 

### ISSUE THREAD

**Issue by Dev0Louis** [henkelmax/simple-voice-chat#615]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
When Simple Voicechat are installed together, Voicechat behaves weird.
Connections do not work 99% of the time

**Steps to reproduce the issue**
1. Install Velocity and a Server with these [Mods](https://discord.com/channels/854659575324344340/1134489636555735160/1134909495336775811)
2. Join the Server.
3. Leave the Server.
4. Join the Server.
5. No Voicechat connection.

**Expected behavior**
Everything should connect and work.

**Log files**
[Client](https://discord.com/channels/854659575324344340/1134489636555735160/1134865256427032676).
[Server](https://discord.com/channels/854659575324344340/1134489636555735160/1134860542385856582)

**Versions**
- 1.20.1
- 1.20.1-2.4.16

**Other mods**
Fabric API, Proxy Lite, Polymer

**Comment by henkelmax** [comment]
Does this only happen with velocity?

**Comment by Dev0Louis** [comment]
Yes, at least never observed it without it.

**Comment by henkelmax** [comment]
I tried to reproduce your issue and managed to get this to happen without a proxy.
It also happens with just 

- polymer-autohost-0.5.13+1.20.1
- polymer-core-0.5.13+1.20.1
- polymer-resource-pack-0.5.13+1.20.1

and the voice chat mod.

**Comment by henkelmax** [comment]
I made a fix that makes voice chat work with polymer, but the root cause seems to be polymer causing fabrics `ClientPlayConnectionEvents.JOIN` event to be called twice on login (Once on login and a second time when the resource pack finished loading). **You should also report this issue to polymer**.

**Comment by Patbox** [comment]
From technical view, it's not "fixable" on my side either, through the same behavior can be seen with proxies like velocity. I need to send first one to initialize player for velocity/resource pack sending and second one is the vanilla one

**Comment by henkelmax** [comment]
> From technical view, it's not "fixable" on my side either, through the same behavior can be seen with proxies like velocity. I need to send first one to initialize player for velocity/resource pack sending and second one is the vanilla one

I fixed it on my side anyways. It might just be an issue for other mods that rely on that event being fired once.

**Comment by Dev0Louis** [comment]
The Issue is not solved.
It still does not connect.

**Comment by henkelmax** [comment]
> The Issue is not solved. It still does not connect.

It should now be properly fixed
