### ISSUE TITLE
Hard crash after death by creeper.

### ISSUE THREAD

**Issue by Faeranne** [henkelmax/simple-voice-chat#619]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Strange hard crash after a creeper exploded.  Unsure of other causes, but Simple Voice Chat is the only referenced mod for the error.  It did manage to crash out not just Minecraft, but the launcher as well (Prism in this case, but it's also killed the Modrinth launcher and MultiMC).

**Steps to reproduce the issue**
Unsure of the exact steps needed, as it doesn't appear to happen consistently, but both times this error was thrown it was immediately after dying to a creeper explosion.  All crashes occurred while on a multiplayer server.

**Expected behavior**
Not sure what to put here except that it should definitely not be crashing out this hard.

**Log files**
[Debug Log](https://mclo.gs/bM0kE1U)

**Versions**
- Minecraft version: 1.18.2 
- Forge: 40.2.9 
- Mod version: 2.4.20

**Other mods**
As this only occurs sporadically, and in a multiplayer environment, narrowing down the list is not simple, and I'd rather not go through the process of dismantling the server unless absolutely necessary.
[Installed mods](https://gist.github.com/Faeranne/e2d41abb7acab1bdd23e03dc70a7015c)

**Comment by Faeranne** [comment]
This isn't my client that crashed (I'm the server owner), so I don't have the full logs right now, but I can request them if it happens again.

**Comment by Faeranne** [comment]
Clarification from the player, they attempted to hit the creeper when it exploded.

**Comment by henkelmax** [comment]
Your crash looks like you replaced or deleted the mod jar while the server/game was running.
Please restart everything and check if this happens again.
