### ISSUE TITLE
how do i change the port?

### ISSUE THREAD

**Issue by bobyjones** [henkelmax/simple-voice-chat#62]
I read the FAQ and it said to edit `voice_chat.port` in the server properties, first of all, it's not there, I added it and it did not change the port, I've restarted and everything! where do I put it??

**Comment by bobyjones** [comment]
nevermind I found that the port is stored in config in the world, I recommend you put this on the FAQ

**Comment by Redev837** [comment]
> nevermind I found that the port is stored in config in the world, I recommend you put this on the FAQ

Could you help me with this?
