### ISSUE TITLE
Proximity Voice Chat Stuttering with More Than 2 Players

### ISSUE THREAD

**Issue by Decryptu** [henkelmax/simple-voice-chat#622]
**Bug description**
When more than two players are in close proximity to each other, the voice chat starts to stutter, making it unclear and difficult to understand what is being said.

**Steps to reproduce the issue**
1. Have three players connect to the server.
2. Ensure that all three players are in close proximity to each other.
3. Start a voice chat session.

**Expected behavior**
Voice chat should work clearly and smoothly, regardless of the number of players in close proximity.

**Actual Behavior**
Voice chat starts to stutter and becomes unclear when more than two players are in close proximity. The issue resolves when one of the three players mutes themselves. The issue does not occur when the players are far apart.

**Log files**
Nothing in the logs except player connecting / disconnecting from the voice mod when joining or leaving the server, nothing that is not expected.

**Versions**
- Minecraft 1.19.2
- Forge 43.2.21
- Mod voicechat-forge-1.19.2-2.4.24

**Server Information**
Hosting Service: Bisect Hosting
Server RAM: 8GB
Maximum Players: 4
IP and Port: Configured in mod settings

**Other mods**
Bug is still present with no other mods, but here is the full list anyway : https://gist.github.com/Decryptu/b42f724d8f199449c8d818fb1e1dc594

I saw some people talking about reducing the bitrate, but after having ctrl+f "bitrate" across all the wiki I could not find how we could change it. I don't see it in voicechat-server.properties neither

**Comment by henkelmax** [comment]
This is not a mod issue. Please visit the discord for support.
