### ISSUE TITLE
Support for velocity proxy

### ISSUE THREAD

**Issue by bjcosta** [henkelmax/simple-voice-chat#623]
**Bug description**
Please add support for using this plugin/mod with a velocity proxy such that it is possible for an admin to broadcast voice to all players connected to the proxy regardless of the server people are joined to at the time. 

Also proxy support should permit having a single exposed UDP port for voice data when there are multiple servers that are behind the proxy (I.e. voice data is proxied through the proxy as well).

IMO simple voice chat is far superior to plasmovoice due to the simpler/cleaner GUI, however the only reason I use plasmovoice over simple voice chat is that I want to expose a single UDP port for all voice chats across multiple servers and the ability to broadcast to all users connected to the proxy occasionally.

Sorry for reporting this as a bug and not a feature request as I don't seem to be able to choose a feature request as a issue type and the FAQ said to report in GitHub or Discord and this seemed the only way to report in github.

**Comment by henkelmax** [comment]
This won't happen, sorry.

**Comment by voruti** [comment]
I was very confused, because I thought this is what the current Velocity plugin does, until I found out, what it [actually does](https://modrepo.de/minecraft/voicechat/wiki/proxy_setup).
