### ISSUE TITLE
mic icon not showing up and no one can hear me

### ISSUE THREAD

**Issue by kenellenalex** [henkelmax/simple-voice-chat#624]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
I have been using this mod for over a year now with a server I do not own. I was talking with it fine the morning of the issue, and now it's all weird. I have my mic plugged in, linked, and it works on my other computer. But, the mic icon when I am speaking will not show up, nor can anyone hear me. I cannot find out how to fix this issue, no one seems to have had it before. I can mute myself, but the mod seems to not recognize that I am using a microphone. I have made sure the mic I always use is the one chosen, but there is only one option for my mic. This has never happened before and I'm desperate for solutions.

**Steps to reproduce the issue**
1. Log onto the server
2. Try to speak
3. Look for mic icon
4. it's not there and no one can hear me ( I can hear others and everything else works fine)

**Expected behavior**
My mic is supposed to work because I changed nothing when this happened. My headphones are beats headphones with the optional chord, which I use. They are not bluetooth. My mic has never not worked before and there are no other options for mic when I log on. 

**Log files**
[2023-09-08-1.log.gz](https://github.com/henkelmax/simple-voice-chat/files/12564133/2023-09-08-1.log.gz)

**Versions**
- Minecraft version: 1.20.1
- Forge
- Mod/Plugin version: 1.20.1

**Other mods**
This is a heavily modded server with 298 mods.

**Comment by henkelmax** [comment]
If you need help, visit the discord. This is the wrong place for support.
