### ISSUE TITLE
[Incompatability] Forward forge client reset packet

### ISSUE THREAD

**Issue by wolflord212312** [henkelmax/simple-voice-chat#625]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
When atempting to use Forward Forge Client Reset packet with Simple VC on 1.19.2 IT errors out and fails works fine with other mods just seems to be this one.

**Steps to reproduce the issue**
1. Download [SimpleVC](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
2. Download [Forward- Forge-Client-Reset-Packet](https://www.curseforge.com/minecraft/mc-mods/forge-client-reset-packet-forward)
3. Make a velocity network with ambassador
4. make a backend server after the hub
5. Connect to the backend server with the two mods above get serialization Error no error in logs on any server client backend servers

**Expected behavior**
Would connect to the backend server no errors

**Log files**
https://github.com/wolflord212312/Forge-Client-Reset-Packet/issues/2(will all be logged here)

**Versions**
- 1.19.2
- Forge
- Latest for 1.19.2 as of 9/14/2023

**Other mods**
 [Forward- Forge-Client-Reset-Packet](https://www.curseforge.com/minecraft/mc-mods/forge-client-reset-packet-forward)

**Screenshots (Optional)**
https://user-images.githubusercontent.com/73399986/265201077-a22dd7b5-f278-4614-852e-c7014f2e50df.png

**Comment by henkelmax** [comment]
I need the full logs.

**Comment by henkelmax** [comment]
The issue should be fixed for the voice chat mod. But *Forge-Client-Reset-Packet* should look into how they handle the reset packet.
