### ISSUE TITLE
Double UI Icons

### ISSUE THREAD

**Issue by MuhammadRehan5885** [henkelmax/simple-voice-chat#629]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
I am facing a problem while using simple voice chat plugin in my Aternos server which is showing double info icons mean its like there is two different simple voice chat plugins at the same time but it's not pls solve this error or if its clinte side then tell me how to solve this problem.

**Expected behavior**
I think there should be one icon for every info at the point.

**Versions**
- Minecraft JAVA Edition 1.20.1
- Bukkit/Spigot 1.20.1 (3871)
- Mod/Plugin 2.4.26

**Other mods**
There is no other mode I am currently using.

**Comment by henkelmax** [comment]
If you are not having any other mods or plugins installed, this is impossible.
Please provide your client and server logs like described in the template.

**Comment by henkelmax** [comment]
Closed due to inactivity
