### ISSUE TITLE
PlaceholderAPI always reports voicechat_prefix_no_voicechat

### ISSUE THREAD

**Issue by ondrejnedoma** [henkelmax/simple-voice-chat#630]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
PlaceholderAPI placeholder %voicechat_prefix_no_voicechat% is always active, the other ones are never.

**Steps to reproduce the issue**
1. Start a server with the latest version of simple voice chat, PlaceholderAPI 2.11.4 and your own custom plugin
2. Write simple code to get all the placeholders (%voicechat_prefix_uses_voicechat%, %voicechat_prefix_no_voicechat%, %voicechat_prefix_disabled%)
3. See that no matter what, the only active placeholder is always voicechat_prefix_no_voicechat

**Expected behavior**
When connecting with the mod, %voicechat_prefix_uses_voicechat% should be active, and with the mod disabled, but still installed, %voicechat_prefix_disabled% should be active

**Log files**
Not really client related, /voicechat test report success

**Versions**
- Minecraft version 1.20.2
- Fabric version 0.14.22
- Mod/Plugin version 2.4.26

**Other mods**
None

**Screenshots (Optional)**

**Comment by henkelmax** [comment]
![image](https://github.com/henkelmax/simple-voice-chat/assets/13237524/836427b9-a929-447d-875b-4ceb152fa11a)
![image](https://github.com/henkelmax/simple-voice-chat/assets/13237524/daa6b654-8b9a-4d52-b38a-7c43954149de)
![image](https://github.com/henkelmax/simple-voice-chat/assets/13237524/5e89aab1-9f40-408c-88b4-35858a593e59)

Works perfectly fine with the latest placeholder API version and latest paper version.
