### ISSUE TITLE
port forwarding not working 

### ISSUE THREAD

**Issue by Jxulian1** [henkelmax/simple-voice-chat#632]
I am trying to run it on a paper 1.20.2 server just set up port forwarding for port 24454 tcp and udp i open the server and then it says voice chat is not connected. it says it ruining on the right port.
![image](https://github.com/henkelmax/simple-voice-chat/assets/106756844/442bfd9e-8a5c-4210-9371-4d91519495ef)

when i do /voicechat test it says client not connected. 
![image](https://github.com/henkelmax/simple-voice-chat/assets/106756844/a5682231-bb9f-4c20-9569-1a3eaffc4931)

**Comment by henkelmax** [comment]
This is not for support. Just for bug reports. Please visit the discord for help.
