### ISSUE TITLE
Player cannot hear other players after they left & rejoined

### ISSUE THREAD

**Issue by ant14181** [henkelmax/simple-voice-chat#633]
**Bug description**
When a player leaves the server, one or more player(s) cannot hear again after him rejoining. The only way to hear the player again is for the player to leave and re-join too. Note that this happens even if the player is in a group and he left/joined the group, too.

**Steps to reproduce the issue**
0. Make sure that there are two or more players online and Simple Voice Chat is working properly;
1. Make one player leave;
2. Player cannot be heard anymore. The only way to hear him again is by leaving and re-joining the server.

**Expected behavior**
Player can hear other players who left and re-joined.

**Log files**
Server: [voicechat.logs](https://gist.githubusercontent.com/AntoninoScordino/6caff670f9dd001f6e49bdc98f58aade/raw/voicechat.log)
Client: [voicechat.logs](https://gist.githubusercontent.com/AntoninoScordino/3e83d9a1f5f88a203fcfdbc1d6d4234d/raw/voicechat.log)

**Versions**
- Minecraft version: 1.20.2
- Forge/Fabric/Bukkit/Spigot/Paper version: 
    - Server: git-Paper-249
    - Fabric: 0.14.24
- Mod/Plugin version: 2.4.27

**Other mods**
No other mods or plugins were installed.

**Comment by ant14181** [comment]
Looks like that this problem is fixed whenever I change output (e.g from my headphones to my monitor and back to my headphones), but the player can hear me if I leave and re-join. Don't know whether it's my issue (system-wide?) or the plugin's or mod's.

**Comment by henkelmax** [comment]
Please provide proper logs of your client AND server.
Please also state the version and loader you are using on your client.

**Comment by ant14181** [comment]
Hey, sorry. Edited my issue with all the required resources.

**Comment by henkelmax** [comment]
Your logs are still incomplete.

I just tested it with the latest paper version on the server and latest fabric version of the client and it works perfectly fine.

**Comment by ant14181** [comment]
> still incomplete

I don't know what I should provide more. I've included only the relevant mentioning `voicechat` and player leaving and joining. I guess it'll remain a mystery.

**Comment by henkelmax** [comment]
I can only help you with the full logs. Just let me decide what's relevant and what isn't please.

Can you provide more accurate steps on how to reproduce it?

**Comment by ant14181** [comment]
> I can only help you with the full logs. Just let me decide what's relevant and what isn't please.

Sorry, I've updated the logs. You can re-check them.

> Can you provide more accurate steps on how to reproduce it?

I've said it all, once the player (in the case of the logs, `player2`) leaves the server, and I (`player1`) cannot hear them anymore. Only way to hear them again is by leaving the server and re-joining by myself. I am afraid that this is an hardware issue (or even my operating system's), considering I can hear the game's audio just fine.

**Comment by henkelmax** [comment]
> I've said it all, once the player (in the case of the logs, player2) leaves the server, and I (player1) cannot hear them anymore. Only way to hear them again is by leaving the server and re-joining by myself. I am afraid that this is an hardware issue (or even my operating system's), considering I can hear the game's audio just fine.

Hmm thats weird. Which OS are you using? Any special audio setup?

It seems that the client logs aren't updated.

**Comment by ant14181** [comment]
> Hmm thats weird. Which OS are you using? Any special audio setup?

I am using Windows 10 LTSC (21H1, 19044.3570) without any Realtek-related drivers. I suppose that this is a common VoIP issue that happens with (maybe?) other applications. But never happened on Discord and such services.

As for the client logs, I've updated them by removing the hardcoded revision hash. Sorry!

**Comment by henkelmax** [comment]
Yeah I'm on Windows 10 too. Your logs also don't show any major errors...

**Comment by ant14181** [comment]
> Yeah I'm on Windows 10 too. Your logs also don't show any major errors...

I don't really know. I will close this issue until I actually find the cause of this problem, considering it seems to be a system-side issue...

**Comment by thehamish555** [comment]
Just wanna reopen this, i'm not sure what logs you would like me to provide, but the server the server mods are
![image](https://github.com/henkelmax/simple-voice-chat/assets/89168856/752fdc44-cdd0-40ea-b263-a2cb95b9d935)
This bug still happens on windows 10 and windows 11 operating systems (and possibly mac). As OP stated, whenever using a group chat, and a user relogs, other users within the chat cant hear them and have to relog as well (or change audio inputs/outputs as OP stated)

**Comment by henkelmax** [comment]
@thehamish555 Can you reproduce this without any other mods?

**Comment by thehamish555** [comment]
When I remove all mods (client side) my friends can continue to hear me when I relog, however after they relog I can no longer hear them (they can hear me). So the answer is yes, it does still happen but my end is fixed

friends mod list (with mine just with fapi and svc)
![image](https://github.com/henkelmax/simple-voice-chat/assets/89168856/b2ec7845-25ad-4dd0-9841-67ac32ad95d3)

**Comment by thehamish555** [comment]
should be noted that i didnt touch the server mods during that test

**Comment by henkelmax** [comment]
Does this also happen if nobody has any other mods installed?

**Comment by thehamish555** [comment]
Two of my friends who only use the svc mod, don't have the issue (or at least to my knowledge), and its late where I am, so I cant test it as of now

**Comment by henkelmax** [comment]
Ok, so this is an incompatibility with another mod. Can you try to rule out the mod that causes it?

**Comment by thehamish555** [comment]
as i already mentioned, none of my friends are available, but I do have some information that might be helpful.

My friend (screenshot of mods folder above) has not updated their mods in 2 months, where I have mine on the latest version (using ferium). The issue only started happening recently and lines up with this tweet from Mojang https://twitter.com/MojangStatus/status/1717234664585224559 although that's about edu/bedrock edition so it might not be related. Another thing, the server mods are all also on the latest version, would be great to see what mods OP has on their server to see if their are any comparing conflicts, as I believe based on my friend not updating their mods and experiencing the same issue as someone who has updated their mods, it most likely is server sided? Hope that makes sense as I cant test fully atm

**Comment by henkelmax** [comment]
> https://twitter.com/MojangStatus/status/1717234664585224559

First of all this is bedrock related. This also does not have anything to do with self hosted servers in Java edition and voice chat does not use any Mojang servers. This also is not related to connection at all since you don't get disconnected from the voice chat.

**Comment by thehamish555** [comment]
> although that's about edu/bedrock edition so it might not be related. 

not to be mean but i did mention that i wasnt too sure if it was related

**Comment by thehamish555** [comment]
After testing, it appears to be client sided, and the lithium mod

**Comment by henkelmax** [comment]
I can't confirm that. I'm on the latest voice chat version and on Minecraft 1.20.2 with Lithium just installed on one client and it works fine.

**Comment by thehamish555** [comment]
we are on a 1.20.1 (OP talks about being 1.20.2 but clearly that's not a factor in this) server, both clients have lithium, but when one client removes lithium, the client without lithium can relog properly, while the player with lithium when relogging still has the issue of not being heard. Latest svc and only lithium 1.20.1 version (server also has lithium)

**Comment by ant14181** [comment]
I do not have Lithium, and nor does the server and/or my friends. I think this is system-side rather than client-side.

**Comment by henkelmax** [comment]
> we are on a 1.20.1 (OP talks about being 1.20.2 but clearly that's not a factor in this) server, both clients have lithium, but when one client removes lithium, the client without lithium can relog properly, while the player with lithium when relogging still has the issue of not being heard. Latest svc and only lithium 1.20.1 version (server also has lithium)

Tried that and also works fine.
