### ISSUE TITLE
impossible to download quilt version from Prism Launcher

### ISSUE THREAD

**Issue by wanesty** [henkelmax/simple-voice-chat#636]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
The current naming scheme of versions makes it near impossible to select and download a quilt build from modrinth, using prism launcher.

**Steps to reproduce the issue**
Clicking the download mods on an instance in Prism launcher, and searching for Simple Voice Chat and selecting it for download will default to the Fabric build.
Even tho two build of said version are shown when picking a version, selecting either one will default to the fabric build.
I'd guess this is because they both have the same name so Prism just default to the first alphabetical occurrence.

**Expected behavior**
Being able to choose and download a precise version-modloader from Prism Launcher without it defaulting to Fabric. 

**Log files**
irrelevant

**Versions**
irrelevant

**Other mods**
irrelevant

**Screenshots (Optional)**

![image](https://github.com/henkelmax/simple-voice-chat/assets/98633588/2cc940b9-8af3-44da-be24-05bd95d0edfb)

**Comment by henkelmax** [comment]
Thats an issue with the prism launcher, not with us.
