### ISSUE TITLE
Minecraft stops loading at `[Render thread/INFO]: Loading Opus`

### ISSUE THREAD

**Issue by JustNeoNixy** [henkelmax/simple-voice-chat#638]
**Bug description**
Minecraft stops loading at `[Render thread/INFO]: Loading Opus`

**Steps to reproduce the issue**
1. Click Launch button
2. Go to /Users/{username}/Library/Application Support/minecraft/hoplite_1.20/logs
3. open latest.log

**Expected behavior**
I expected minecraft... bruh

**Log files**
https://gist.github.com/Badless/6d1b157ceb4c8f70c1259e6676a46fd3

**Versions**
- Minecraft version: 1.20.1
- Forge/Fabric/Bukkit/Spigot/Paper version: Fabric 0.14.24
- Mod/Plugin version: 1.20.1-2.4.16

**Other mods**
everything is in log file.

**Comment by henkelmax** [comment]
Which OS are you on?
Which launcher are you using?

Also your mod version is very outdated. Please check if this still happens with the latest version.

**Comment by JustNeoNixy** [comment]
> Which OS are you on? Which launcher are you using?
> 
> Also your mod version is very outdated. Please check if this still happens with the latest version.

I'm using macOS Catalina (10.15.7)
Default Minecraft Launcher from minecraft.net

alright, ill check it out

**Comment by henkelmax** [comment]
This MacOS version is very old and might cause issues. Please update your system.
We also don't support any launchers on MacOS except Prism. See https://modrepo.de/minecraft/voicechat/wiki/macos and https://modrepo.de/minecraft/voicechat/wiki/compatibility

**Comment by JustNeoNixy** [comment]
> This MacOS version is very old and might cause issues. Please update your system. We also don't support any launchers on MacOS except Prism. See https://modrepo.de/minecraft/voicechat/wiki/macos and https://modrepo.de/minecraft/voicechat/wiki/compatibility

I don't think thats the main reason, I have been using simple voice chat mod before. I got those issues after I reinstalled my entire system

**Comment by JustNeoNixy** [comment]
also updating the mod did nothing

**Comment by henkelmax** [comment]
People had issues before with the mod when having system integrity protection disabled. You could check that.
Another way to avoid this issue would be to set `use_natives` to `false` (see https://modrepo.de/minecraft/voicechat/wiki/configuration).

**Comment by JustNeoNixy** [comment]
> People had issues before with the mod when having system integrity protection disabled. You could check that. Another way to avoid this issue would be to set `use_natives` to `false` (see https://modrepo.de/minecraft/voicechat/wiki/configuration).

thanks, setting `use_natives` to `false` helped :)
