### ISSUE TITLE
[FORGE][1.12.2] Server crashes when starting up

### ISSUE THREAD

**Issue by SackMathen** [henkelmax/simple-voice-chat#640]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
FTB: Ultimate Reloaded
Linux mint server crashes when trying to start the server with this mod.

**Steps to reproduce the issue**
1. install the mod in the mods folder
2. Start server
3. server cant continue and crashes

**Expected behavior**

**Log files**
https://gist.github.com/).](https://gist.github.com/SackMathen/29693af72de478da549d16709df9ac50

**Versions**
- Minecraft version: 1.12.2
- Forge: forge-1.12.2-14.23.5.2855
- Mod/Plugin version 2.4.26 and 2.4.28

**Other mods**
add this to the modpack on top of the other mods. this is the only one that I have added to the pack.

**Comment by henkelmax** [comment]
This crash is not caused by the voice chat mod.

**Comment by SackMathen** [comment]
It doesn’t happen unless the mod is installed on the server. It also
happens when I launch the client version.
