### ISSUE TITLE
"Client not connected"

### ISSUE THREAD

**Issue by Y4nni24** [henkelmax/simple-voice-chat#641]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Hello i have my own minecraft server its on paper 1.20.2 and i have the voicemod plugin installed and me and my friends have the mod also installed and  i have in the config the right server adress and the right port and the port is forwarded in my fritzbox and when we want to talk than there is a plug that is crossed by a X and when i make the test command than there stand "Client not connected" but me myself i can talk but its not my frind faults there config is the same pls help me ive read the wiki and all the reports here nothing helped

**Steps to reproduce the issue**
I went to my server
I saw a plug that is crossed by a X on my friends screen
I typed in chat "/voicechat test (my nick)
And it said: "Client not connected"

**Expected behavior**
I expected Simple Voice Chat mod to work

**Log files**
[Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
You can use [https://gist.github.com/](https://gist.github.com/).](https://gist.github.com/Y4nni24/37c711c22dd75b022020b8f93a741eaa)

**Versions**
- Minecraft version
- Paper version
- Mod/Plugin version

**Other mods**
A list of the other mods/plugins that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod/plugin is installed.
If not, please narrow down the mod(s)/plugin(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please visit the discord for help. This is only for bug reports.

**Comment by Y4nni24** [comment]
where is the discord

**Comment by henkelmax** [comment]
It's linked literally everywhere. Even when creating an issue.
