### ISSUE TITLE
I cannot get voice chat permissions to work

### ISSUE THREAD

**Issue by XDom367** [henkelmax/simple-voice-chat#643]
**Bug description**
I've used Luckperms to grant non-ops all of the voice chat perms, but they still don't have permission to speak. When a player is opped they can speak just fine. For a non-opped player, a warning pops up that says "You do not have permission to speak", and "You do not have permission to hear".

**Steps to reproduce the issue**
I can't figure out what causes the issue, so I don't know how to reproduce it. Permissions for voice chat just aren't working.

**Expected behavior**
I expected the use Luckperms to grant voice chat permissions would grant players the ability to use voice chat. Giving players all the voice chat permissions does nothing, they can only speak when opped.

**Log files**
[<script src="https://gist.github.com/XDom367/74304be9b12847c729cb631707298042.js"></script>](https://gist.github.com/XDom367/74304be9b12847c729cb631707298042)
(I'm aware of my messy log file. I made some mistakes setting the server up, but it works.)

**Versions**
- Minecraft 1.20.1
- Paper-196
- Simple Voice Chat 2.4.28

**Other Plugins**
AnimalTamer, Chunky, ChunkyBorder, Corpses, CommandAPI, CraftBook, CustomDiscs, DiscordSRV, DiscordSRVUtils, DiscordUtils, DynamicLights, EntityClearer, EpicPluginLib, Essentials, EssentialsAntiBuild, EssentialsDiscord, EssentialsProtect, floodgate, FreedomChat, Geyser-Spigot, GeyserHacks, GeyserSkinManager, GeyserUpdater, GriefPrevention, GSit, HorseEnhancer, HorseSwim, InstantRestock, LevelledMobs, LuckPerms, MoreMobHeads, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NotTooExpensive, PlaceholderAPI, PlayerNPC, PowerRanks, ProtocolLib, RHLeafDecay, SimpleTpa, SkinsRestorer, Skript, sleep-most, spark, SpawnerSilk, squaremap, Tweakin, UltimateAutoRestart, ViaBackwards, ViaRewind, ViaVersion, voicechat, voicechat_interaction, WorldEdit, WorldGuard

**Screenshots (Optional)**
![image](https://github.com/henkelmax/simple-voice-chat/assets/126047992/9cfa7251-e919-45f8-b165-dbed03881ff5)

**Comment by XDom367** [comment]
I used the wrong label and can't figure out how to change it, my mistake

**Comment by henkelmax** [comment]
This issue tracker is just for bugs. Please visit the discord for help.

**Comment by XDom367** [comment]
Alright
