### ISSUE TITLE
Why haven't any recording files been saved?

### ISSUE THREAD

**Issue by Koalemon** [henkelmax/simple-voice-chat#646]
I am testing it in a single player game and after testing, the microphone is working properly. But the file was not saved, and the system prompts that it was saved successfully, but there are no audio files in the folder.

![test](https://github.com/henkelmax/simple-voice-chat/assets/127819800/56faf0fb-5e43-4a27-b546-36ae89587971)
![test2](https://github.com/henkelmax/simple-voice-chat/assets/127819800/627e9b18-87f9-4f41-af7f-a6869b902388)

**Comment by henkelmax** [comment]
Please fill out the bug template and include your logs.

**Comment by Koalemon** [comment]
Sorry, this is my setup issue. It has been resolved now and is working properly.
