### ISSUE TITLE
1.19.2 crash

### ISSUE THREAD

**Issue by myrukun** [henkelmax/simple-voice-chat#649]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
new 1.19.2 update pushed today or yesterday crashes your game if you make a group and try to leave it

**Steps to reproduce the issue**
1. Create a group and set it to "Open"
2. Have someone join your group
3. You will not be able to hear them, or they will not be able to hear you.
4. Try leaving the server, your game will immediately crash.

**Expected behavior**
Players should be able to hear eachother in the group and not crash

**Log files**
[crash-2023-12-08_16.20.43-client.txt](https://github.com/henkelmax/simple-voice-chat/files/13622049/crash-2023-12-08_16.20.43-client.txt)

**Versions**
- 1.19.2
- Forge
- 2.4.30 Mod Version

**Other mods**
A list of the other mods/plugins that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod/plugin is installed.
If not, please narrow down the mod(s)/plugin(s) that are causing the problem.

**Screenshots (Optional)**
![image](https://github.com/henkelmax/simple-voice-chat/assets/72015194/add36c2d-429a-4a6b-bedc-5881d0e22eaa)

**Comment by henkelmax** [comment]
The crash is not related to the changes that were made in that update.
It hints that you replaced the mod jar while the game was running. Please restart your game and check if this consistently happens
