### ISSUE TITLE
Binded the port and Successfully authenticated player but still not working?

### ISSUE THREAD

**Issue by SharkieTV** [henkelmax/simple-voice-chat#65]
So I added it to my server, I changed the port to 25565 and it does say it is Binding the port and Successfully authenticated player but it doesn't work when in the server? I press M to make sure and it doesn't give me the prompt its unavailable so it must be working but me or my friends cant hear me or I cant hear them. The icon does show up at the bottom left of the screen but not next to the player name. So what am I missing?

**Comment by henkelmax** [comment]
Please send me the logs of the client and the server. Please use github gist or something similar to send a link of the logs.

**Comment by SharkieTV** [comment]
Hi have no idea how to use Github Gist and it lags my Web Browser.
Hope this works:
https://drive.google.com/drive/folders/1shPhmj_6YyD2NNukxL1p8A6izr6TiH8N?usp=sharing

**Comment by henkelmax** [comment]
The server logs are incomplete and the client logs don't contain anything about the voice chat.

**Comment by SharkieTV** [comment]
Are these this correct? I'm just sending the latest logs?
https://drive.google.com/drive/folders/1shPhmj_6YyD2NNukxL1p8A6izr6TiH8N?usp=sharing

**Comment by henkelmax** [comment]
Sorry, but I can't find anything in your logs. Did you even connect to a server?

**Comment by SharkieTV** [comment]
Yeah I did, check the link again with another new latest.log, I do see that it says I connected to a server

**Comment by henkelmax** [comment]
Everything seems to be fine. Can you explain what doesn't work in more detail?

**Comment by SharkieTV** [comment]
I cant hear them they cant hear me? When pressing CAPS the symbol comes up on the bottom left on both our ends but we cant see the speaker symbol come on, so it doesn't work? We even tried changing the microphone and output and still nothing. Testing our microphone in the voice settings works.

**Comment by henkelmax** [comment]
Does it work without any other mods installed?
Does the test command work?

**Comment by SharkieTV** [comment]
its working now all g

**Comment by henkelmax** [comment]
What was the problem?

**Comment by SharkieTV** [comment]
dont know it just started working

**Comment by henkelmax** [comment]
Oh ok :D
