### ISSUE TITLE
[Forge]My friend is disconnected for some reason, but other ones are connected and can talk normally

### ISSUE THREAD

**Issue by DrPHDCat** [henkelmax/simple-voice-chat#654]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
My friend is disconnected for some reason, but other ones are connected and can talk normally

**Steps to reproduce the issue**
Play minecraft with 3 people on an aternos server with the simple voice chat mod

**Expected behavior**
For my friend to be able to talk and hear

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- 1.19.2
- 43.30
- 2.4.32

**Other mods**
None
**Screenshots (Optional)**
![image](https://github.com/henkelmax/simple-voice-chat/assets/107643253/6c6a46c8-23ec-49ca-86d2-f91eb8b91a35)

**Comment by henkelmax** [comment]
Please visit the discord for help. This is the wrong place.
