### ISSUE TITLE
[FIGURA CONFLICT] GUI symbol duplicates, increases in size, and floats on the left side of players 

### ISSUE THREAD

**Issue by Skeithh** [henkelmax/simple-voice-chat#656]
**Please read the [wiki](https://modrepo.de/minecraft/voicechat/wiki) before submitting a bug report!**

**Bug description**
Due to figura's custom nameplates feature, the "speaker" symbol for players that are speaking duplicates and floats oddly to the left side. This is only seen from certain angles.

**Steps to reproduce the issue**
1. Have figura and simple voice chat installed
2. log in with two players
3. have one speak, walk around them while they speak and you will notice the floating symbol

**Expected behavior**
Whatever odd conflict between the figura nametags system and SVC to not happen.

**Log files**
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/13956490/latest.log)

**Versions**
- 1.20.1
- Forge 1.20.1 - 47.2.20
- voicechat-forge-1.20.1-2.4.31.jar

**Other mods**
There's a lot of mods, but the only relevant one seems to be **Figura** as messing with its nameplate settings to set it all to none/vanilla fixed the issue.
_Ignore the presence of optifine, issue persisted with it removed._

**Screenshots (Optional)**
![image](https://github.com/henkelmax/simple-voice-chat/assets/74820899/632e41e9-7211-4811-a97a-24b8e479801a)

**Comment by henkelmax** [comment]
It seems that this is an issue with Figura. It does not use Forges event to hook into the players name rendering.

**Comment by gingershaped** [comment]
This issue was closed as a problem with Figura, and [Figura's issue](https://github.com/FiguraMC/Figura/issues/222) was closed as a problem with Simple Voice Chat. The issue is still present. What gives?
