### ISSUE TITLE
[1.20.1] Crash on Startup

### ISSUE THREAD

**Issue by AetheriMC** [henkelmax/simple-voice-chat#657]
**Bug description**
The game crashes on startup with Simple Voice Chat installed. 

Attempting to troubleshoot by searching the latest logs, I ran a search for "henkelmax" and found the following:

"[10:06:22] [main/WARN]: Error loading class: de/maxhenkel/easyvillagers/blocks/tileentity/TraderTileentityBase (java.lang.ClassNotFoundException: de.maxhenkel.easyvillagers.blocks.tileentity.TraderTileentityBase)"

Easy Villagers is not installed on this instance of the game. Is this somehow related?

**Log files**
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/14012691/latest.log)

**Versions**
- Minecraft v1.20.1
- Forge v47.2.4
- Mod v1.20.1-2.4.32

**Other mods**
[mods.txt](https://github.com/henkelmax/simple-voice-chat/files/14012712/mods.txt)

**Comment by henkelmax** [comment]
Your logs don't mention the voice chat mod at all. There is also no crash or anything else.
The line you mentioned is also not present. Please check if you sent the correct files.

**Comment by AetheriMC** [comment]
The crash is happening at start up, so unfortunately a crash report is not being generated. The crash is happening specifically after adding SVC to the modlist.

I just downloaded the latest.log file provided and CTRL + F for "henkel". The referenced text is on line 114. Easy Villagers is not installed.

![image](https://github.com/henkelmax/simple-voice-chat/assets/64112227/7d399c13-8728-4bcc-9fa8-5c7bc543c416)

**Comment by henkelmax** [comment]
There is no mention of the voice chat mod at all. Without logs or a crash report I can't help you.
Can you check if the same happens with just the voice chat mod installed?

**Comment by AetheriMC** [comment]
Running a clean install of 1.20.1 with SVC only does not crash the game, and there's no mention of Easy Villagers.

[latest.log](https://github.com/henkelmax/simple-voice-chat/files/14013480/latest.log)

This may not be _directly_ related to SVC but in troubleshooting this, is the crash I'm experiencing related to the line mentioned above regarding Easy Villagers?

Please understand that identifying the cause for crashes is never easy, and so far SVC and the fact that Easy Villagers is not installed are about the only leads I have.

**Comment by henkelmax** [comment]
The part about easy villagers is from another mod trying to interact with easy villagers. This is completely unrelated.

Can you check which mod causes the crash?
