### ISSUE TITLE
Is there some special setup required for windows users?

### ISSUE THREAD

**Issue by asdfghjkl403622** [henkelmax/simple-voice-chat#66]
**Make sure your question hasn't been answered in the [FAQ](https://modrepo.de/minecraft/voicechat/faq)!**
Hello!

I Have some people who are trying to use the mod on windows, and they get "voice chat unavailable" but on mac and Linux, they get to access all of the settings. I opened an issue a little while ago stating that voice chat was not working at all, but as it turns out, the previous version works for Linux and mac, but not windows. And now the new version does not even allow them to connect. Do I have to do something on my end or the client's end to allow windows users to access the voice chat? Also, voice chat only allows small snippets of audio at a time when on non-windows. 

can provide logs at a later date

Thanks!

**Comment by henkelmax** [comment]
Have you followed every step in the wiki?

**Comment by asdfghjkl403622** [comment]
yes

**Comment by henkelmax** [comment]
Please send me the logs of your server and client.

**Comment by asdfghjkl403622** [comment]
well at the time of writing this I don't have logs, but the test command before the mod update pinged them but did not receive a response. now it just doesn't give anything at all, saying that they are unavailable. And I know for a fact that I port forwarded it properly, because when I tried it with my Linux computer to my mac, I got audio, although it only came in small snippets and was nowhere near usable.

**Comment by henkelmax** [comment]
Which version are you using?

**Comment by asdfghjkl403622** [comment]
forge 1.16.5

**Comment by asdfghjkl403622** [comment]
wait, do I need to be on the latest version of forge?

**Comment by henkelmax** [comment]
I mean the mod version.

**Comment by asdfghjkl403622** [comment]
voicechat-1.16.5-1.0.7.jar

**Comment by henkelmax** [comment]
Please update the server and all clients to the latest version.

**Comment by asdfghjkl403622** [comment]
ok, I'll get back to you with whatever happens next and logs

**Comment by henkelmax** [comment]
Any update on this?

**Comment by henkelmax** [comment]
Closed due to inactivity
