### ISSUE TITLE
Crash when adjusting someone else's volume on my server.

### ISSUE THREAD

**Issue by MoonlitLamps** [henkelmax/simple-voice-chat#660]
### Confirmation

- [X] I have read the wiki

### Bug description

Whenever I attempt to boost someone's voice in the server I am in, it causes a crash and kicks me to the main menu. I am using a variety of mods, but I can't find what's causing the issue.

### Minecraft version

1.12.2

### Mod/Plugin version

1.12.2-2.5.1.jar

### Mod/Plugin loader and version

Forge - 14.23.5.2860

### Steps to reproduce

1. Join a server
2. Attempt to amplify someone's voice
3. Crash

### Expected behavior

It will crash to the main menu with a weird rendering issue.

### Log files

https://gist.github.com/starplasam626/b43fd61e8306ca5ff1db0912a0200fb0

### Screenshots

![image](https://github.com/henkelmax/simple-voice-chat/assets/49560377/7078f7cd-f62a-47e7-b568-8d05f4083a2f)
![image](https://github.com/henkelmax/simple-voice-chat/assets/49560377/aeaf4621-b979-4fd9-84d3-aec53b1ad927)

**Comment by henkelmax** [comment]
Does this happen without mods? I am not able to reproduce this at all.
Also please update to the latest version of the mod.

**Comment by henkelmax** [comment]
Closed due to inactivity. Feel free to reopen if it still happens on the latest version.
