### ISSUE TITLE
Activation Type: Voice does not work

### ISSUE THREAD

**Issue by jewlexx** [henkelmax/simple-voice-chat#662]
### Confirmation

- [X] I have read the wiki

### Bug description

The option `Activation Type: Voice` does not seem to be working.

This is true for both my computer and my friends, when we tested this the other night. We could both hear each other using push to talk, but voice activation was not working.

I have ensured that the threshold is low enough, and using the microphone tester shows that the mic levels go way beyond the activation threshold.

I have tested both on my main instance, with lots of mods, and on a blank instance with no mods, using both Fabric and Quilt, both in singleplayer and on a paper sever with the correct plugin version.

This bug report is in reference to version `1.20.1-2.4.30` but I have also tested it on the latest version using 1.20.4 and it does not work.

### Minecraft version

1.20.1

### Mod/Plugin version

1.20.1-2.4.30

### Mod/Plugin loader and version

Fabric Loader 0.15.6

### Steps to reproduce

1. Complete the intial setup
2. Set the activation method to voice
3. Try speaking

### Expected behavior

It should be broadcasting my voice when I speak using voice activation.

### Log files

https://mclo.gs/rTaGZuR

**Comment by henkelmax** [comment]
Can you send a video showing your issue?
Does it activate your microphone when you move the slider completely to the left?
Make sure you are not muted in game and have the latest version of the mod installed.

**Comment by jewlexx** [comment]
I can send a video in the morning (its 3 am here).

I am not muted, and yes I've tested it with the slider completely to the left.
As I said it works with push-to-talk, and I've tested it on both my mic and my webcam mic, so it's not an issue with my mic.

**Comment by henkelmax** [comment]
And when you are testing your microphone, do you see the green bar moving?

**Comment by jewlexx** [comment]
Here is the promised video: https://www.youtube.com/watch?v=fgymBh5jCCo

The green bar does indeed move.

**Comment by henkelmax** [comment]
![image](https://github.com/henkelmax/simple-voice-chat/assets/13237524/e4e620ce-af34-4bcf-a31a-a29fbd801ef5)

You are muted...
