### ISSUE TITLE
[1.20.1] The game crash at launch

### ISSUE THREAD

**Issue by RayoBlanco07** [henkelmax/simple-voice-chat#663]
### Confirmation

- [X] I have read the wiki

### Bug description

If I open the launcher with the mod SVC at the minecraft version 1.20.1 and with only the mod SVC at Forge it crashes. 
The launcher load de mods and the game, then when the launcher closes to open the minecraft windows it crashes and give the error code "1".  (I can't open the game)

### Minecraft version

1.20.1

### Mod/Plugin version

1.20.1-2.4.18

### Mod/Plugin loader and version

Forge 47.2.0

### Steps to reproduce

1.Go to minecraft launcher
2.Select the instance
3.Open the instance
4.The launcher loads
5.The launcher closes and open another time with the error code "1"

### Expected behavior

The launcher open the minecraft and I can play it.

### Log files

https://gist.github.com/RayoBlanco07/8cde986b6cf7a6a952d4e74f43614489

### Screenshots

The launcher when the error happens:
![imagen_2024-02-17_210534135](https://github.com/henkelmax/simple-voice-chat/assets/112699365/03510b6c-d99a-4795-9cc0-5a1e3eb500ae)
The mods folder with only SVC (the mod folder I'm using)
![image](https://github.com/henkelmax/simple-voice-chat/assets/112699365/1eda9a62-6486-4b7e-b100-c09b5d7dd629)

**Comment by RayoBlanco07** [comment]
idk if the log files are correct, in case I uploaded the last here: 
https://gist.github.com/RayoBlanco07/7b331c8e8dff3d3487d890e69ee6362a

**Comment by henkelmax** [comment]
This version is very outdated. Please update the mod.
