### ISSUE TITLE
Insane Log Spam when Client is playing on server

### ISSUE THREAD

**Issue by ghost** [henkelmax/simple-voice-chat#664]
### Confirmation

- [X] I have read the wiki

### Bug description

On a server I'm running, players are getting spammed in the logs with `Unknown custom packet identifier: voicechat:player_state`. I'm not entirely sure why, but nothing appears in the server log.
Voice chat still works fine, but this wastes disk space extremely fast.

### Minecraft version

1.18.2

### Mod/Plugin version

1.18.2-2.5.1

### Mod/Plugin loader and version

Forge 40.2.17

### Steps to reproduce

1. Install the same mods on client/server
2. Client joins server.
3. Log is spammed with `Unknown custom packet identifier: voicechat:player_state`

### Expected behavior

The log shouldn't be spammed with the error constantly.

### Log files

https://mclo.gs/Kvr4SQF

### Screenshots

N/A

**Comment by ghost** [comment]
In-case you need the exact mod setup, this can be imported into any launcher. [redacted]

**Comment by henkelmax** [comment]
Forge logs this whenever a custom packet is sent. Report that to their issue tracker.
