### ISSUE TITLE
Voice chat doesnt work for host on server

### ISSUE THREAD

**Issue by ZP-Gaming** [henkelmax/simple-voice-chat#666]
### Confirmation

- [X] I have read the wiki

### Bug description

The voice chat works for my friends on the server but me as the server host cant connect to the servers vc server and wont let me reconnnect

in short the logs say this and keeps saying it while authenticating
Failed to authenticate voice chat connection: Cannot assign requested address: Datagram send failed

### Minecraft version

1.12.2

### Mod/Plugin version

2.4.32

### Mod/Plugin loader and version

Forge 14.23.5.2859

### Steps to reproduce

join the server as server host

### Expected behavior

It to work fine and all goes well

### Log files

https://gist.github.com/ZP-Gaming/ae806719c39674a819fef0a530ca255c#file-gistfile1-txt

### Screenshots

![Minecraft 1 12 2 2_19_2024 5_30_22 PM](https://github.com/henkelmax/simple-voice-chat/assets/160547666/e7d3cd74-3dbd-4f53-a118-8d01fb80a2c0)

**Comment by ZP-Gaming** [comment]
server and client config for port is set to -1 to use minecrafts port

**Comment by CrypticVerse** [comment]
@ZP-Gaming I had the same thing happen to me. Do you use your computer as the server? 
If so, is your port to connect to the server on your computer localhost or 127.0.0.1?

**Comment by ZP-Gaming** [comment]
i use my computer as the server and im not sure exactly what you mean by the second part but are you talking about the port forwarding? I dont really think the port forwarding would be the cause and i connect to the server via localhost or typing 0 into the server address

**Comment by ZP-Gaming** [comment]
ok so i figured it out, it was instead of using 0 for local host on the server address actually type localhost as address, not sure if it will work for you CrypticVerse or not.
