### ISSUE TITLE
Crash when exiting hosted LAN world (1.12.2)

### ISSUE THREAD

**Issue by Titoo8899** [henkelmax/simple-voice-chat#667]
### Confirmation

- [X] I have read the wiki

### Bug description

Hi,

my Problem is simple and I hope you can fix it. I open a Map in the Singleplayer and then I finish I go out and the Game close normal with your Mod. But then I open a Map and press "ESC" on Keyboard for open the Game Menu and click "Open to LAN" the Mod works normal but then I will close now Minecraft the Game Freeze and Crash and I become the Exit-Code: -805306369 with the Massage of a Crash of the Game.

P.S. the link by Log Files is the debug log her is the link to the latest log:

Latest Log Link: https://gist.github.com/Titoo8899/a1baf13c5e44657a64a02588dd902e69

### Minecraft version

1.12.2

### Mod/Plugin version

Version: 2.5.5 for Minecraft 1.12.2

### Mod/Plugin loader and version

Forge 1.12.2 - 14.23.5.2860

### Steps to reproduce

1. Open a Singleplayerworld
2. Then the World have load press "ESC" on Keyboard
3.  Click the "Open the LAN" button
4. Change the Gamemode to "Creative" and change the Allow Cheats "On"
5. The Game works in this time Normal
6. Press "ESC" on the Keyboard
7. Press Save and Quit to Title
8. The Game will Freeze and Crash with the Massage "Exit-Code: -805306369"

### Expected behavior

I have hope then I make a LAN World the World Close normal and Freeze not and make then a big Crash. This is for me a Bug

### Log files

https://gist.github.com/Titoo8899/8f1ba0e7a6f063d5d22330d1d61d7b83

### Screenshots

![Screenshot 2024-02-21 190044](https://github.com/henkelmax/simple-voice-chat/assets/42325138/ec3068aa-cae9-43eb-aac8-1dfcbf07262b)

**Comment by Titoo8899** [comment]
I have this Problem fix with MixinBooter and Vintagefix and censoredasm Mods. This Mod with your mod works fine. The Mods reduce the RAM of the Game and the Code have i Check and yes the Exit Code is a RAM Problem. By this Problem is your mod from the Ram to high and I have the RAM by 12GB and your mod make it to high. Then I open a LAN WORLD.

**Comment by henkelmax** [comment]
Your logs don't contain any crash and successfully connect to the voice chat. Can you send me the crash report?

**Comment by Titoo8899** [comment]
By the Crash and the Exit-Code: -805306369 generate Minecraft no Crash Report the Crash Report Folder is empty

**Comment by henkelmax** [comment]
Ok, I think I can reproduce the issue, but for me the game just infinitely hangs instead of crashing.

**Comment by Titoo8899** [comment]
![Screenshot 2024-02-21 201106](https://github.com/henkelmax/simple-voice-chat/assets/42325138/679cd3b0-f6bb-48ba-ad94-3a6cb94a9cc5)


Her a Picture of the Crash Report Folder no File

**Comment by Titoo8899** [comment]
By me was it so then the game freeze and I click on the screen a Java massage comes with will you close the Process of the Program and then I click yes the game close and the massage with Exit-Code: -805306369 pop up on the screen

**Comment by henkelmax** [comment]
Ok, yeah that makes sense, thank you for reporting this issue!

**Comment by Titoo8899** [comment]
Thanks for the fast answer and thanks for help the problem to fix.

**Comment by henkelmax** [comment]
Should be fixed with the next version.
Here's a preview version (Please make sure to extract the jar from the zip file before adding it to the mods folder):
[[PLEASE UNZIP] voicechat-forge-1.12.2-2.5.6-pre1.zip](https://github.com/henkelmax/simple-voice-chat/files/14364197/PLEASE.UNZIP.voicechat-forge-1.12.2-2.5.6-pre1.zip)

Please let me know if this version works for you.

**Comment by Titoo8899** [comment]
okay I will test it and give feedback

**Comment by Titoo8899** [comment]
I have testet it and only on new createt Worlds work it now. my second test was on the Testworld 1 who my Report comes and have look and old worlds work with the old config of the last config and your mod can not change it. I hope you can a way found who all world change the config to the newes config of the voice chat.

**Comment by henkelmax** [comment]
I don't really understand what you mean.

**Comment by Titoo8899** [comment]
Squizzle have me by the other Problem help on Discord but thanks for the Fix this work fine
