### ISSUE TITLE
internal exception: io.netty.handler.codec.EncoderException: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by macaroni0423** [henkelmax/simple-voice-chat#669]
### Confirmation

- [X] I have read the wiki

### Bug description

I'm joining my friend's server and playing, but I keep getting disconnected from the server and get the following message.
I used a translator, so the vocabulary may be wrong.

### Minecraft version

1.20.1

### Mod/Plugin version

1.20.1-2.5.6

### Mod/Plugin loader and version

Fabric loader 0.15.7

### Steps to reproduce

1. Connect to someone else's LAN server.
2. After some time has passed...
3. disconnected! and get the message..

### Log files

https://pastebin.com/wSX6QH5C

### Screenshots

![image](https://github.com/henkelmax/simple-voice-chat/assets/91307576/67d24f32-593c-4964-8aae-ec65f20f9392)

**Comment by henkelmax** [comment]
This error does not seem to come from the voice chat mod. Please check if you also encounter any issues if you are just running the voice chat mod without any other issues.
