### ISSUE TITLE
i can't hear my fred and thay cant hear me

### ISSUE THREAD

**Issue by iz-gaming** [henkelmax/simple-voice-chat#67]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
i can't hear anyone and nobudy can hear me

**Versions**
- Minecraft version: 1.16.4
- Forge version: 36.0.14
- Mod version: 1.0.3
- java version: jdk 15.0.1
- os: mac os big sur

Hi i have chekt the ather issu about this but it dident help so i open a new issue to i hope keep it more orenized

**Comment by henkelmax** [comment]
Update your mod to the latest version.
Also take a look at #24
