### ISSUE TITLE
Possibility to disable icon (server side)

### ISSUE THREAD

**Issue by taagada** [henkelmax/simple-voice-chat#675]
### Confirmation

- [X] I have read the wiki

### Bug description

If possible to add an configuration to the server configuration file an boolean value to force mod client to hidde the nametag icon
![image](https://github.com/henkelmax/simple-voice-chat/assets/44299011/4dcc2ecd-b28f-4f9e-aaa1-f66a0a97fb2f)

### Minecraft version

1.12.2

### Mod/Plugin version

1.12.2-2.4.32

### Mod/Plugin loader and version

Server: Spigot, Client: Forge

### Steps to reproduce

don't need step to reproduce

### Expected behavior

add an configuration to the server configuration file an boolean value to force mod client to hidde the nametag icon

### Log files

none

### Screenshots

![image](https://github.com/henkelmax/simple-voice-chat/assets/44299011/4dcc2ecd-b28f-4f9e-aaa1-f66a0a97fb2f)

**Comment by henkelmax** [comment]
This is completely client side and can't be controlled server side.

**Comment by taagada** [comment]
if you send the server config file (already the case) is possible

**Comment by henkelmax** [comment]
This is such a niche setting that almost nobody would use, sorry. I won't add that.

**Comment by taitep** [comment]
@henkelmax  what is the setting client side? is it hide_icons or something else?

**Comment by henkelmax** [comment]
Either press `H` or change the value in the config. More information is available on the wiki.

**Comment by taitep** [comment]
like what value?

**Comment by henkelmax** [comment]
> More information is available on the wiki.
