### ISSUE TITLE
ConcurrentModificationException in onKeyInput

### ISSUE THREAD

**Issue by shartte** [henkelmax/simple-voice-chat#678]
### Confirmation

- [X] I have read the wiki

### Bug description

ConcurrentModificationException in `onKeyInput` handler

### Minecraft version

1.20.4

### Mod/Plugin version

1.20.4-2.5.5

### Mod/Plugin loader and version

NeoForge 20.4.198

### Steps to reproduce

It's intermittent and not reproducible

### Log files

https://gist.github.com/shartte/929d87ea2e4d00e058a0c3a7905fe58c

**Comment by henkelmax** [comment]
Does that issue happen when doing anything specific?

**Comment by shartte** [comment]
I launched the instance from the Vanilla launcher and let it launch in the background while doing other stuff in the foreground.
The launcher then presented me with a crash report, so this must have been while it was still in the main menu and while it was producing key events from things I was doing in other windows.
That however makes it hard to pin down what exactly I pressed.

**Comment by henkelmax** [comment]
Ok, that's at least something I can work with that. I'll try to reproduce it.

**Comment by henkelmax** [comment]
I didn't manage to reproduce the issue, but I'm pretty sure that fixes it.

**Comment by shartte** [comment]
Yes that would probably do it, but I have no idea how this is possible either.

The only thing I could find is that you are registering the ClothConfig tick callback twice in NeoForge.
Once in `initializeClient` and once in `clientSetup` itself.
But that on its own will not cause this  🤔 

It's certainly possible that some other mod interfered here, but reproducing this after the fact is likely impossible. :-(
