### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by pjohnnn** [henkelmax/simple-voice-chat#681]
### Confirmation

- [X] I have read the wiki

### Bug description

I'm trying to use this mod on my apex hosting server on java and I finally got it up and running, but now I'm getting a message that "launcher does not support macOS permissions". I'm not quite sure what to do.

### Minecraft version

1.20.4

### Mod/Plugin version

1.20.4

### Mod/Plugin loader and version

Forge

### Steps to reproduce

Set up mod on a MacBook
Open game

### Expected behavior

I expected my AirPods to be able to serve as my mic and speaker with this mod. 

### Log files

<script src="https://gist.github.com/pjohnnn/789d49ddfcac5b891a923ff234b34f6f.js"></script>

### Screenshots

![Screenshot 2024-03-22 at 12 52 59 PM](https://github.com/henkelmax/simple-voice-chat/assets/164555462/d4bb808b-ecfa-40f2-b5bf-a5e7e42ed941)

**Comment by pjohnnn** [comment]
Also I'm very bad at computer-y stuff and didn't really understand what a couple of the things I was supposed to fill out were so I'm so sorry if I end up wasting anyones time.

**Comment by henkelmax** [comment]
This is not a bug. Please visit the discord if you need help-
