### ISSUE TITLE
i don't know what's wrong help

### ISSUE THREAD

**Issue by dedreacx** [henkelmax/simple-voice-chat#686]
### Confirmation

- [X] I have read the wiki

### Bug description

I followed the instructions it told me to follow in installing the voice chat on aternos (via: https://support.aternos.org/hc/en-us/articles/360019336497-Installing-Voice-Chat-Mods)

Here is the console/log message after turning on the server and changing the port to =-1.
![Screenshot 2024-04-02 6 43 56 PM](https://github.com/henkelmax/simple-voice-chat/assets/165609188/b4791c26-50df-4ed9-a574-bc9efe0394af)
[Voicechat-Server Config.txt](https://github.com/henkelmax/simple-voice-chat/files/14845336/Voicechat-Server.Config.txt)

### Minecraft version

1.20.4

### Mod/Plugin version

1.20.4/ 2.5.10

### Mod/Plugin loader and version

Paper 1.20.4 (464)

### Steps to reproduce

I have no clue I just followed the instructions through the wiki and then the installation link for aternos.

### Expected behavior

Obviously, I thought it would run smoothly because the installation guide told me to do that and I expected nothing of it. But now there's a predicament.

### Log files

https://gist.github.com/dedreacx/2197171692923a97dcb2bd35ec2d0620

### Screenshots

![Screenshot 2024-04-02 6 43 56 PM](https://github.com/henkelmax/simple-voice-chat/assets/165609188/41c1bb07-fe5c-4e01-b8fd-794197be0703)
[Voicechat-Server Config.txt](https://github.com/henkelmax/simple-voice-chat/files/14845345/Voicechat-Server.Config.txt)

**Comment by henkelmax** [comment]
This is not a bug. Visit the discord if you need help.
