### ISSUE TITLE
Quilt 1.20.4 not working in single-player

### ISSUE THREAD

**Issue by Player505** [henkelmax/simple-voice-chat#687]
### Confirmation

- [X] I have read the wiki

### Bug description

Using the quilt version of the mod results in no being able to connect to single player howver using the fabric version resulvoes the issue.

### Minecraft version

1.20.4

### Mod/Plugin version

2.5.11

### Mod/Plugin loader and version

Quilt Loader 0.24.0

### Steps to reproduce

1. Install voicechat-quilt-1.20.4-2.5.11 and boot up minecraft
2. play single player world

### Expected behavior

Being able to play single player

### Log files

https://mclo.gs/ZJFYsdA

### Screenshots

![image](https://github.com/henkelmax/simple-voice-chat/assets/20302958/cfb49926-4b50-46c5-8c51-4c4a0173048a)

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
