### ISSUE TITLE
Crash of Voice chat using Sinytra Connector using VC Fabric

### ISSUE THREAD

**Issue by TheRTGGaming** [henkelmax/simple-voice-chat#688]
### Confirmation

- [X] I have read the wiki

### Bug description

I have downloaded the following mods to test to see the list would work with Voice chat
Architectury API: 9.2.14+forge
Connector Extras: 1.10.0+1.20.1
Fabric API: 0.92.1+1.20.1
Forgified Fabric API: 0.92.1+1.11.7+1.20.1
ReplayMod: 1.20.1-2.6.13
Simple Voice chat: fabric-1.20.1-2.4.32
Sinytra Connector: 1.1.0-beta.42+1.20.1
Sound Physics Remastered: fabric-1.20.1-1.3.1
Voice Chat Interaction: fabric-1.20.1-1.0.5
Walkie-Talkie By Flaton: fabric-1.2.2

### Minecraft version

1.20.1

### Mod/Plugin version

Fabric-1.20.1-2.4.32

### Mod/Plugin loader and version

Forge 1.20.1-47.2.17

### Steps to reproduce

1: use modrinth
2: make new profile.
3: download the versions
4: load profile.
5: crashed.

### Expected behavior

game will start loading normally then crash

### Log files

https://mclo.gs/FTyuFnk

**Comment by henkelmax** [comment]
We don't support any software that makes mods work on another loader. Just use the forge version of Simple Voice Chat.

You should also report such incompatibilities to [their issue tracker](https://github.com/Sinytra/Connector/issues).
