### ISSUE TITLE
People are cutting in and out

### ISSUE THREAD

**Issue by ItsInfernoLive** [henkelmax/simple-voice-chat#69]
I read most of the question that are like this one and cant find one to help me.

When I'm in game people can hear me but they are cutting in and out for me.
I can hear every other word and am trying to stream an SMP with this and its not working.
Please help me fix this!

When I talk in game, they tell me in discord that it is workig fine. 
But when I am in game listening to them all I hear is (L-**s *o- Bui-** H****!_) *Lets go build a house!*

**Comment by henkelmax** [comment]
Please fill out the complete bug template.
