### ISSUE TITLE
Simple voice chat and spartan weaponry Doesn't work together

### ISSUE THREAD

**Issue by Krissoh** [henkelmax/simple-voice-chat#690]
### Confirmation

- [X] I have read the wiki

### Bug description

When you open the mod together with Spartan weaponry minecraft crashes

### Minecraft version

1.12.2

### Mod/Plugin version

All

### Mod/Plugin loader and version

Forge

### Steps to reproduce

1.Download The mods (Spartan weaponry and simple voice chat) and put them in the appropriate folder
2.Open minecraft
3.Minecraft crashes

### Log files

https://gist.github.com/Krissoh/9e240fb1e236dc934e2ab1e9a43380b0

**Comment by henkelmax** [comment]
I can only help you if you send me the full logs.

**Comment by henkelmax** [comment]
Also please read this. This might already fix your issue:
https://modrepo.de/minecraft/voicechat/wiki/troubleshooting#mixin-config-voicechat-mixins-json-requires-mixin-subsystem-version-0-8-but-0-7-x-was-found-the-mixin-config-will-not-be-applied

This mod will resolve this conflict:
https://modrinth.com/mod/mixincompat

**Comment by henkelmax** [comment]
Update: I tested it and yes, that's your issue.

**Comment by Krissoh** [comment]
> Update: I tested it and yes, that's your issue.
no problem thanks
