### ISSUE TITLE
Game marked as crashed upon exit

### ISSUE THREAD

**Issue by TheBluekr** [henkelmax/simple-voice-chat#691]
### Confirmation

- [X] I have read the wiki

### Bug description

Upon exiting the client the launcher will reopen stating the game has crashed with `Exit code: -1073740791` after connecting to a server.

### Minecraft version

1.20.6

### Mod/Plugin version

1.20.6-2.5.14

### Mod/Plugin loader and version

Fabric Loader 0.15.11

### Steps to reproduce

1. Launch game as normal
2. Connect to a server
3. Disconnect and quit game
4. Minecraft launcher reopens stating the game crashed

### Expected behavior

The game exits normally without the launcher reopening due to a "crash".

### Log files

N.A.

**Comment by henkelmax** [comment]
Please provide logs and/or the crash report.

**Comment by TheBluekr** [comment]
No crash report exists, I've checked.
As for the log it provides nothing useful either.
[2024-05-19-1.log](https://github.com/henkelmax/simple-voice-chat/files/15369544/2024-05-19-1.log)
Launcher shows this upon exiting Minecraft, it only happens when SVC is installed.
![Launcher](https://github.com/henkelmax/simple-voice-chat/assets/16746102/b216f35c-711e-4aae-bf56-e925ffb310ff)

**Comment by henkelmax** [comment]
Thanks! It will be fixed in the next release.
