### ISSUE TITLE
Group is empty and can't be join or deleted.

### ISSUE THREAD

**Issue by ShulkerSakura** [henkelmax/simple-voice-chat#692]
### Confirmation

- [X] I have read the wiki

### Bug description

When player create a group and quit the game and re-join the server the group will be there says "Group is empty" and can't be join or deleted. Also '/voicechat join GroupName' show the group is not exist.

### Minecraft version

1.20.6

### Mod/Plugin version

Client Mod 1.20.6-2.5.14 Server Plugin 2.5.13

### Mod/Plugin loader and version

Fabric Loader 0.5.10 Server Spigot

### Steps to reproduce

1.Join a spigot server which installed voicechat plugin.
2.Create a group by "V" menu.
3.Quit the game.
4.Re-join the game.
5.Use "G" group menu  or command '/voicechat join GroupName'

### Expected behavior

Group should be keep available when player re-join the game,when there is no player in the group, group should be automatically deleted.

### Log files

Sorry for can't provide the log for now.

### Screenshots

![2024-05-21_03 46 31](https://github.com/henkelmax/simple-voice-chat/assets/50770360/5205bd41-dd04-4d6c-bdc4-7eb117045c10)

**Comment by henkelmax** [comment]
This has already been fixed with 98da8a86bd017fff4385cab90bfb8713a2e7bc68
