### ISSUE TITLE
Exception on Paper when voicechat and the latest ViaVersion (Dev Branch) is installed

### ISSUE THREAD

**Issue by Brokkonaut** [henkelmax/simple-voice-chat#696]
### Confirmation

- [X] I have read the wiki

### Bug description

There is an exception in the console, complaining about a no longer existing class in viaversion

### Minecraft version

1.20.6

### Mod/Plugin version

2.5.13

### Mod/Plugin loader and version

Paper version 1.20.6-DEV-master@377733d

### Steps to reproduce

Paper 1.20.6 server, latest ViaVersion/ViaBackwards from the dev branch, latest voicechat plugin, start the server, exception

### Expected behavior

No exception

### Log files

https://cpaste.de/wixogefuma.properties

**Comment by henkelmax** [comment]
The plugin only works with released versions of ViaVersion.

**Comment by Brokkonaut** [comment]
but released versions of viaversion currently do not really work with 1.20.6.

**Comment by henkelmax** [comment]
We can't break existing stuff and force users to use a development version.

**Comment by henkelmax** [comment]
Just FYI, ViaVersion 4.10.2 works with 1.20.6, but the changes in the 5.0.0 snapshots are very minor, so I did a small hack to support both versions.
