### ISSUE TITLE
'force_voice_chat=false' not work in 1.12.2-2.5.15 version.

### ISSUE THREAD

**Issue by onenok** [henkelmax/simple-voice-chat#697]
### Confirmation

- [x] I have read the wiki

### Bug description

'force_voice_chat=false' but can't join server without this mod
![image](https://github.com/henkelmax/simple-voice-chat/assets/83169133/e6590c96-dd5a-40a3-98b7-c8bbdb847b52)

### Minecraft version

1.12.2

### Mod/Plugin version

1.12.2-2.5.15

### Mod/Plugin loader and version

forge-1.12.2-14.23.5.2860

### Steps to reproduce

1. Make sure all versions are the same as above
2. Make sure 'force_voice_chat=false'
3. start the server
4. join the server without this mod

### Expected behavior

SERVER KICK YOU

### Log files

https://gist.github.com/onenok/600b92f70126fda6a76afcd9bb4d6c35

### Screenshots

![image](https://github.com/henkelmax/simple-voice-chat/assets/83169133/4eef5e0f-ee78-43c8-a671-79e4fca807fd)

**Comment by onenok** [comment]
Hasn't this issue been fixed in this version?
https://github.com/henkelmax/simple-voice-chat/issues/392

**Comment by henkelmax** [comment]
This kick message has nothing to do with the config option. If you are also running a Forge server, it will match the clients and servers modlist. This is not a feature of the mod, this is done by forge. You can get around this issue by for example running bukkit on the server.

If you need help, visit the Discord server.
