### ISSUE TITLE
Sound executor delay randomly upon dimension load/unload

### ISSUE THREAD

**Issue by toralol** [henkelmax/simple-voice-chat#699]
### Confirmation

- [X] I have read the wiki

### Bug description

As a client playing on a server with the fabric mod loaded on both sides, occasionally upon loading/unloading a dimension the game log will spam with "Sound executor delay", and the game will stutter and lock up until it either crashes or you force quit. 

### Minecraft version

1.20.4

### Mod/Plugin version

1.20.4-2.5.15

### Mod/Plugin loader and version

Fabric Loader 0.15.10

### Steps to reproduce

1. Go through a Nether Portal on a server with Simple Voice Chat Fabric.
2. Repeat until the game starts stuttering and spams the log with "Sound executor delay".

### Log files

https://gist.github.com/NineNates/0ded7a387e0d669ea23309ed3bb112a8

**Comment by henkelmax** [comment]
Can you check if this also happens without the mod? This doesn't look like its caused by the voice chat mod. It all happens in a thread which should not lock up the game.

**Comment by henkelmax** [comment]
Closed due to inactivity
