### ISSUE TITLE
The voice of another player doesn't fade away.

### ISSUE THREAD

**Issue by ILIKEMCA** [henkelmax/simple-voice-chat#7]
The voice just disappears, and there's no such config file to edit. How do I make the voice fade away because you said it is a thing.

**Comment by henkelmax** [comment]
This option is located in the server config (For more information read the FAQ). Set the voice chat distance to a higher value and adjust the fade distance accordingly.

**Comment by henkelmax** [comment]
It should be fixed in 1.16.4-1.0.3.
Let me know if it works.

**Comment by ILIKEMCA** [comment]
nah, it's not working for me. I don't if it's my fault

**Comment by henkelmax** [comment]
Can you send me your server and client logs?
