### ISSUE TITLE
The server cannot start normally

### ISSUE THREAD

**Issue by QianMuu** [henkelmax/simple-voice-chat#700]
### Confirmation

- [X] I have read the wiki

### Bug description

I have the "voicechat" mod added to my "mods", but it won't let me start the server properly.

[debug.log](https://github.com/user-attachments/files/15659792/debug.log)
[latest.log](https://github.com/user-attachments/files/15659800/latest.log)

![904003e1-ac55-4135-8a22-4a784e5f826f](https://github.com/henkelmax/simple-voice-chat/assets/50398180/3c8667bf-0482-49b8-9b91-648c015115d1)

### Minecraft version

1.20.1

### Mod/Plugin version

voicechat-forge-1.20.1-2.5.15

### Mod/Plugin loader and version

forge-1.20.1-47.2.32

### Steps to reproduce

1. Start the server
2. Server is starting
3. Server crash save

### Expected behavior

Check the logs and point out the problem. It would be best if there is a way to solve this problem

### Log files

I have uploaded the "log"

### Screenshots

s

**Comment by henkelmax** [comment]
Not a bug. If you need help visit the discord.
