### ISSUE TITLE
Simple Voice Chat reconnecting every dead.

### ISSUE THREAD

**Issue by burza1337** [henkelmax/simple-voice-chat#702]
### Confirmation

- [X] I have read the wiki

### Bug description

Hello I have some bug which makes when every time player die, the voicechat mod is disconnecting for a moment and then reconnecting. Ngl it is kinda annoying. It happens on my RLCraft server and this is dedicated server on google cloud, if it makes any difference. I don't really know if it can be caused by other mods but I'm sure it shouldn't happen.

### Minecraft version

1.12.2

### Mod/Plugin version

voicechat-forge-1.12.2-2.5.15

### Mod/Plugin loader and version

forge-1.12.2-14.23.5.2860

### Steps to reproduce

Set up a RLCraft server (I have it on dedicated virtual machine from google cloud) and add simple voice chat to mods.

### Expected behavior

It shouldn't reconnect the player everytime he dies.

### Log files

https://gist.github.com/burza1337/4e5aa93a6bab43b0e23bd924ea191e8c

**Comment by henkelmax** [comment]
This has already been fixed with cdf886c5c39c09d8a3891d44ef020a02259857c9

**Comment by burza1337** [comment]
tbh i dont know what to do next with it, could you help?

**Comment by burza1337** [comment]
Please brother help me

**Comment by henkelmax** [comment]
Just be patient and wait until the version is released.
