### ISSUE TITLE
simplevoicechat on forge 1.21 crashes the server

### ISSUE THREAD

**Issue by farlands69** [henkelmax/simple-voice-chat#704]
### Confirmation

- [X] I have read the wiki

### Bug description

I tried to install the forge version of Simple Voice Chat on our server hosted by Winternode, following the steps provided on the official wiki](https://modrepo.de/minecraft/voicechat/wiki/installation#forge) and on [Winternode's guidance section](https://help.winternode.com/Games/Minecraft/Plugins/Simple-VoiceChat). Simply having the mod in the mods folder causes the server to crash. Natalie Trinket (someone from Winternode's support team) also tried installing the mod (using the same steps) on our server to get it to work, and it crashed then also.

The fabric version of the mod runs perfectly fine, there was no issue trying to get that to work so I think there's a problem with specifically the forge version of the mod and not something up with our server host or anything.  

### Minecraft version

1.21

### Mod/Plugin version

1.21

### Mod/Plugin loader and version

Forge 51.0.5

### Steps to reproduce

1. Install Simple Voice Chat in the mods folder of our 1.2151.0.5 Forge server (hosted by Winternode, if that affects anything?)
2. Try to run server to create the voice chat config file
3. Config file is created, but server crashes immediately

### Expected behavior

1. Install Simple Voice Chat in mods server of Winternode 1.21 Forge server
2. Run server to create the voice chat config file
3. Server runs fine, config file is created. Would be able to set up the port and run the server as normal after this.

### Log files

https://gist.github.com/farlands69/1414b7e782a02ef2650780054612ebd7

**Comment by henkelmax** [comment]
Fixed with 21216c326d9be2c08952e4c749515d3b58dd629b
