### ISSUE TITLE
1.21 Lauching Issue

### ISSUE THREAD

**Issue by tobezdev** [henkelmax/simple-voice-chat#706]
### Confirmation

- [x] I have read the wiki

### Bug description

Using `Lunar/v1.21` & `Simple Voice Chat v1.21 (voicechat-fabric-1.21-2.5.17.jar)`, the entire client crashes when a world or server is fully loaded. I've gone through the crash logs and found this line: 
```
[2024-06-18 23:22:19.059] [info]  [23:22:19] [Render thread/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "de.maxhenkel.voicechat.resourcepacks.IPackRepository.addSource(net.minecraft.server.packs.repository.RepositorySource)" because "repository" is null
```
so I'm assuming it might be something to do with the plugin configuration?

### Minecraft version

1.21.0 with Lunar Client

### Mod/Plugin version

1.21-2.5.17

### Mod/Plugin loader and version

0.15.11 with Installer v1.0.1

### Steps to reproduce

1. Launch Minecraft v1.21 with Lunar Client
2. Connect to a server or open a world
3. Game crashes upon rendering the first frame of the world (after the loading screen)

### Expected behavior

Well I should realistically be able to play the world or server which I selected.

### Log files

https://gist.github.com/tobezdev/5b9bb733915ae90892727eb98be756da

### Screenshots

No screenshots to attach (not available with Lunar Client)

**Comment by henkelmax** [comment]
We don't support Lunar
