### ISSUE TITLE
The Lunar problem

### ISSUE THREAD

**Issue by TheKnoldi** [henkelmax/simple-voice-chat#707]
### Confirmation

- [X] I have read the wiki

### Bug description

It is not working with Lunar Client 1.21. This happens on MacOS and I com from Germany. So sorry about my language.

### Minecraft version

1.21

### Mod/Plugin version

1.21-2.5.17

### Mod/Plugin loader and version

Fabric Loader 0.15.11

### Steps to reproduce

1. Open Lunar Client Launcher.
2. Click on "Versions".
3. Click on 1.21.
4. Click on the Gears.
5. Click on "Mods"
6. Drag and drop the mod there.
7. Launch the game.
8. Go to singleplayer or multiplayer.
9. The configuration instructions wont appear and the key assingments will not work.

### Expected behavior

I would like to be able to use this mod with Lunar Client in 1.21.

### Log files

https://gist.github.com/TheKnoldi/b800ba4e4d95871ecf0a4ccc2b675485

### Screenshots

How?

**Comment by henkelmax** [comment]
We don't support Lunar. Please also read the wiki.
