### ISSUE TITLE
The system reports an error when the player connects to or disconnects from the server.

### ISSUE THREAD

**Issue by 233laoliu** [henkelmax/simple-voice-chat#708]
### Confirmation

- [X] I have read the wiki

### Bug description

[Server] [08:09:33] [Server thread/INFO]: Killed [bot] steve_bot
[Server] [08:09:33] [Server thread/INFO]: steve_bot lost connection: Killed
[Server] [08:09:33] [Server thread/INFO]: [bot] steve_bot left the game
[Server] [08:09:34] [Server thread/INFO]: [voicechat] Disconnecting client [bot] steve_bot
[Server] [08:09:34] [Server thread/ERROR]: Error executing task on Server
[Server] java.lang.NullPointerException: Cannot invoke "de.maxhenkel.voicechat.voice.common.PlayerState.toBytes(net.minecraft.class_2540)" because "this.playerState" is null
[Server]        at de.maxhenkel.voicechat.net.PlayerStatePacket.toBytes(PlayerStatePacket.java:39) ~[voicechat-fabric-1.20.4-2.5.17.jar:?]
[Server]        at me.senseiwells.replay.compat.voicechat.ReplayVoicechatPlugin.toClientboundPacket(ReplayVoicechatPlugin.kt:271) ~[ServerReplay-1.0.8+mc1.20.4.jar:?]
[Server]        at me.senseiwells.replay.compat.voicechat.ReplayVoicechatPlugin.onPlayerStateChanged$lambda$3(ReplayVoicechatPlugin.kt:193) ~[ServerReplay-1.0.8+mc1.20.4.jar:?]
[Server]        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_4093.wrapOperation$clg000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting(class_4093.java:570) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:757) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Minecraft version

1.20.4

### Mod/Plugin version

1.20.4-2.5.17

### Mod/Plugin loader and version

Minecraft 1.20.4 with Fabric Loader 0.15.11

### Steps to reproduce

Players join and exit the server

### Log files

https://mclo.gs/9Sm7cMs

**Comment by henkelmax** [comment]
First of all, we don't provide any support for cracked servers. And your issue is caused by a broken addon mod.
