### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by MooZonkey** [henkelmax/simple-voice-chat#710]
### Confirmation

- [X] I have read the wiki

### Bug description

I am unable to execute the installer with java on my system. I have installed other mods without any errors, but for this one specific mod I receive the error ``no main manifest attribute, in voicechat-neoforge-1.21-2.5.17.jar`` . 
I am running a custom build of Linux with java and dependencies installed. The command I run is ``java -jar voicechat-neoforge-1.21-2.5.17.jar``

### Minecraft version

1.20.4

### Mod/Plugin version

1.21-2.5.17

### Mod/Plugin loader and version

Neoforge 21.0.42

### Steps to reproduce

Explained in the bug description

### Expected behavior

The expected behavior is that the jar file executes and allows me to install the mod. 

### Log files

Logs are N/A

**Comment by henkelmax** [comment]
No idea why you think the mod is/has an installer. Read the wiki or visit the mod loaders support if you don't know how modding works.
