### ISSUE TITLE
Server log spam

### ISSUE THREAD

**Issue by kalevaz** [henkelmax/simple-voice-chat#714]
### Confirmation

- [x] I have read the wiki

### Bug description

The server logs provide a reconnection on a single player every minute, this not only makes reading the log a nuisance, but also makes it larger than it needs to be. Only 1 person on the server has this problem, he has a good pc. This can be seen in the log file from 16:24:00 onwards, which is when the user (vr_luisito) installed the mod.

### Minecraft version

1.21

### Mod/Plugin version

1.21-2.5.18

### Mod/Plugin loader and version

Fabric loader 0.15.11 (server)

### Steps to reproduce

Read "latest.log" or any other log after mod install in the "server/logs/" folder.

### Expected behavior

I expect one successful connection when joining the game, but not one every minute or so.

### Log files

https://gist.github.com/kalevaz2312/446f138b43aa615969da47bf8c09b871

### Screenshots

![Screenshot 2024-07-14 191839](https://github.com/user-attachments/assets/fa7a3b60-0296-4544-9aac-fbbc4479b9b4)

**Comment by kalevaz** [comment]
Update: user has 261mb/s download and 161mb/s upload, which seems to be a very good connection

**Comment by henkelmax** [comment]
This is not a bug. Please visit the Discord for help with this issue.
