### ISSUE TITLE
Icons are invisible on Lunar client and I can't get them back.

### ISSUE THREAD

**Issue by ASignificantSpek** [henkelmax/simple-voice-chat#716]
### Confirmation

- [x] I have read the wiki

### Bug description

On Lunar client, none of the icons show up at all on the screen nor above player heads. I can still open the menus and go into voice chats and the actual functionality works fine, but I can't see anything on my screen directly without going into a menu for it. I had this issue before I updated to 1.21 too, so it isn't new, I just haven't gotten around to filing a report until now.

### Minecraft version

1.21

### Mod/Plugin version

1.21

### Mod/Plugin loader and version

Fabric with Lunar Client

### Steps to reproduce

1. Go to the Lunar Client Launcher
2. Press the triangle to the right of the version number
3. Press the gear icon on the bottom right
4. Press the blue folder icon and add simple voice chat to the folder
5. Run the game

### Expected behavior

For months it worked fine but now it doesn't even after deleting the mod and reinstalling, so I don't know if it'll be reproduceable. You shouldn't be able to see any mod related icons.

### Log files

https://gist.github.com/ASignificantSpek/90761884da06a191f1c28aa1f0a781c1

### Screenshots

![2024-07-18_18 00 48](https://github.com/user-attachments/assets/565c1df0-9280-4a2d-8015-6fe05f1cbcf2)
![2024-07-18_18 00 54](https://github.com/user-attachments/assets/91ba5ec3-c51c-4ca2-94c5-7808bd8a297a)

**Comment by henkelmax** [comment]
We don't support lunar.
