### ISSUE TITLE
noise reduction

### ISSUE THREAD

**Issue by Qwarux** [henkelmax/simple-voice-chat#717]
### Confirmation

- [X] I have read the wiki

### Bug description

My noise reduction is always disabled and I can't do anything about it, it's too painful for other players to hear me. What should I do?? Even if you change everything else, nothing changes

### Minecraft version

1.17.1

### Mod/Plugin version

1.17.1-2.5.12

### Mod/Plugin loader and version

Forge 1.17.1-37.1.1

### Steps to reproduce

1. V
2. settings
3. noise reduction (it is always disabled, there is no way to turn it on no matter how much you press)

### Expected behavior

the ability to turn on noise reduction, for some reason it is not available (always disabled, this cannot be changed)

### Log files

It always happens that way and everywhere

**Comment by henkelmax** [comment]
This Minecraft version is no longer supported.
