### ISSUE TITLE
Wrong audio

### ISSUE THREAD

**Issue by Bober55** [henkelmax/simple-voice-chat#718]
### Confirmation

- [X] I have read the wiki

### Bug description

I can hear all of the audio on my friends pc through his mic including my own microphone it only happens for him and it only happens when using this mod in Minecraft (i can hear him but i can hear everything else like game audio etc aswell).

### Minecraft version

1.20.1

### Mod/Plugin version

1.20.1-2.5.19

### Mod/Plugin loader and version

forge 47.30

### Steps to reproduce

No matter the setting it always does it not sure what to put here.

### Expected behavior

To only hear his voice.

### Log files

Not sure what to put cant get his log.

### Screenshots

Cant screen shot due to it being a audio issue

**Comment by henkelmax** [comment]
This is not a bug. If you want help configuring your mod, visit the discord.
