### ISSUE TITLE
IPv6 connection bug

### ISSUE THREAD

**Issue by SharwOrange** [henkelmax/simple-voice-chat#719]
### Confirmation

- [X] I have read the wiki

### Bug description

display timed out on the server side
IPv6 connection error on the client side

### Minecraft version

1.20.1

### Mod/Plugin version

1.20.1-2.5.19

### Mod/Plugin loader and version

forge 47.3.5

### Steps to reproduce

connecting to a Minecraft server using IPv6

### Expected behavior

Mods working properly

### Log files

latest.logs on the server side
https://gist.github.com/SharwOrange/0edd3305ade990a2afe5cdc4e6b94b63

latest.logs on the client side
https://gist.github.com/SharwOrange/284204cefd80f7c824f02e9d02a772c8

**Comment by SharwOrange** [comment]
In line 2916 of latest.log on the client side, the correct IPv6 connection should be '[240e:3b1:6c60:1c50:0:0:0:6a1]:25565', not '240e:3b1:6c60:1c50:0:0:0:6a1:25565'

**Comment by henkelmax** [comment]
Please visit the discord server for help with connection issues.
