### ISSUE TITLE
Spigot VoiceServer Plugin

### ISSUE THREAD

**Issue by fantahund** [henkelmax/simple-voice-chat#72]
would there be a possibility that you provide a spigot version as a voice server?
I know that the mod is still needed on the client side, but it would be very practical.

**Comment by fantahund** [comment]
Ok Schreibe deine Antwort einfach auf Deutsch macht es einfacher habe es zu spät gesehen :/

**Comment by henkelmax** [comment]
Creating a Bukkit/Spigot plugin would be completely useless as you would still need a modded client. That defeats the whole purpose of a plugin instead of a mod.

**Comment by GJungle1** [comment]
> Creating a Bukkit/Spigot plugin would be completely useless as you would still need a modded client. That defeats the whole purpose of a plugin instead of a mod.

What he meant is that you make a pulgin that doesn't require you to put the mod onto a server, but if you have it installed to your client it would work.

**Comment by fantahund** [comment]
You can try this version. But it is not tested yet.

https://github.com/Brokkonaut/simple-voice-chat

**Comment by emielderckx** [comment]
It would not defeat the purpose. If you can run a bukkit (paper) plugin and the a fabric mod on the client. This would make it so server owners can use all the good bukkit/paper server side stuff. And still have a nice voice chat.

**Comment by henkelmax** [comment]
As I already said multiple times: There are a lot of tools to make mods work with plugins.

**Comment by KPidS** [comment]
We just released Plasmo Voice. It's a proximity Voice Chat mod with a server-side made with Spigot. It's based on Simple Voice Chat. You don't need to sacrifice Spigot plugins and the convenience of players who don't use mods. Besides that, it's just a great proximity voice chat with 3D audio and lots of features.

https://www.spigotmc.org/resources/plasmo-voice-server.91064/

Check it out, you might find it useful.
