### ISSUE TITLE
Laggy when more then 2 people

### ISSUE THREAD

**Issue by Fallrl** [henkelmax/simple-voice-chat#720]
### Confirmation

- [X] I have read the wiki

### Bug description

On my server (bisecthosting) whenever there is more then 2 people in a group everybody starts lagging out like crazy and it is basicallly impossible for you to understand eachotther 

### Minecraft version

1.21

### Mod/Plugin version

1.21-2.5.19

### Mod/Plugin loader and version

Fabric loader

### Steps to reproduce

https://www.bisecthosting.com/clients/index.php?rp=/knowledgebase/1301/How-to-setup-voice-chat-on-a-ForgeorFabricorSpigot-Minecraft-serverLegacy.html&srsltid=AfmBOoqLS5Go8UwrXV2UJLtddOo13lBiTsb2vYJ_nxTZc276l-gNyvhM

then get 3 people online and as soon as they join a vc it will start lagging 

### Expected behavior

For the Voice chat to be clear and no lag as thats what i have seen before 

### Log files

https://gist.github.com/Fallrl/43bbd830049875c81896b33c33a5802f

**Comment by henkelmax** [comment]
This is not a bug. Visit the discord if you need help with the setup.
