### ISSUE TITLE
1.21 Neo variant crashes when clicking `Config` in the mods list

### ISSUE THREAD

**Issue by 3gf8jv4dv** [henkelmax/simple-voice-chat#721]
### Confirmation

- [X] I have read the wiki

### Bug description

Yes, it is just like the title says.

### Minecraft version

1.21

### Mod/Plugin version

1.21-2.5.19

### Mod/Plugin loader and version

NeoForge 21.0.164

### Steps to reproduce

1. Install the newer NeoForge
2. Install this mod and its dependencies
3. Launch the game
4. Enter the `Mods` list and click the `Config` button of this mod

### Expected behavior

Normally enter the config interface.

### Log files

*(Deleted)*

**Comment by henkelmax** [comment]
I am not able to reproduce it with NeoForge `21.0.164` with or without Cloth Config.

EIDT: Nevermind, it seems to only happen in a production environment. I get the crash now too.
