### ISSUE TITLE
Crash minecraft fabric 1.21

### ISSUE THREAD

**Issue by inseym-1** [henkelmax/simple-voice-chat#723]
### Confirmation

- [X] I have read the wiki

### Bug description

Because of some players, errors appear, and after some time the game crashes, below I have provided a log, it is short because logs with this error go further than 1000

### Minecraft version

1.21

### Mod/Plugin version

1.21-2.5.19

### Mod/Plugin loader and version

Fabric loader 0.15.11

### Steps to reproduce

I don't know how this error is reproduced, it is random by itself

### Log files

https://gist.github.com/inseym-1/36d1dc099e59550dcc4bdc328aaf4a4e

**Comment by henkelmax** [comment]
Please send me your crash report

**Comment by inseym-1** [comment]
there is no crash report, but there was a window, but it is not in the game folder

**Comment by henkelmax** [comment]
I can't help you without a crash report. If you need further help with that please visit the discord.
