### ISSUE TITLE
Fabric 1.21 - Java Exception Access Violation caused by VoiceChat (or addons)?

### ISSUE THREAD

**Issue by NovaLynxie** [henkelmax/simple-voice-chat#724]
### Confirmation

- [X] I have read the wiki

### Bug description

I am getting a very annoying crash which am unsure if its voicechat or another mod that interacts with this mod. Please can anyone help me as its getting increasingly frustrating since its one of those "hs_err_pid" crashes Java throws.
The following log is generated alongside the hs_err_pid crashlog.

If the hs_err_pid log is required, I will upload it on request for analysis if this helps.

Note: I have tried to check for driver updates as per my own debugging into this issue but as of right now I do not have any updates and am unsure if a reinstall will really fix it but will try if necessary.

### Minecraft version

1.21

### Mod/Plugin version

1.21-2.5.16

### Mod/Plugin loader and version

1.21-0.16.0

### Steps to reproduce

1. Install VoiceChat mod and any client-side addons of your choice.
2. Run the game in either singleplayer or multiplayer mode.
3. Keep playing till Java crashes. (May be inconsistent but for me it crashes after say 10-20 mins)
4. Find the log file marked as hs_err_pidXXXXX.log in your .minecraft folder, there is also brief details in the latest.log as well.

### Expected behavior

The game runs as normal without crashing, playing normally and still functioning as normal without crashing or freezing.

### Log files

https://gist.github.com/NovaLynxie/13c2c984571ac7b7d73b760fc57aefb4

### Screenshots

Not Applicable (game just freezes and dies)

**Comment by henkelmax** [comment]
Which operating system are you using?
Are you using sound physics remastered?
Please always send the FULL logs

**Comment by NovaLynxie** [comment]
Sorry, I'll go grab the full log now. Should I attach both the hs_err_pid and latest logs?
Also, yes, I am using Sound Physics Remastered. I have been suspecting that something Sound Physics is doing may be causing my crashes.

**Comment by NovaLynxie** [comment]
Full latest log: https://gist.github.com/NovaLynxie/284fb17a880f084fa1924bd133d612c3
Also adding the hs_err_pidXXXXX.log I got, unsure if this will help but providing as well below.
hs_err_pid log: https://gist.github.com/NovaLynxie/a71d7361d7b921eef5d6dfb9fef8d44d

Operating System is Windows 11 64-bit Home Edition v10.0.22631

**Comment by henkelmax** [comment]
Can you confirm that this issue also occurs with just the voice chat mod installed?

**Comment by NovaLynxie** [comment]
I have done that, and there have been no further crashes with just the voice chat mod.

**Comment by NovaLynxie** [comment]
Well... it turns out it had something to do with shaders and my computer setup, misinterpreted the crash as this. Sorry about that.

**Comment by henkelmax** [comment]
No worries :)
