### ISSUE TITLE
Cant't Join Server with ViaFabric/ViaFabricPlus

### ISSUE THREAD

**Issue by DreiPixel** [henkelmax/simple-voice-chat#730]
### Confirmation

- [X] I have read the wiki

### Bug description

Joining a Server with SimpleVoiceChat and ViaFabric or ViaFabricPlus (Same Error) Results in a Decoder Exception.
Client is 1.21 and Server is 1.20.4.
according to the Wiki this should be supported.

also reported the issue to the ViaFabricPlus Git https://github.com/ViaVersion/ViaFabricPlus/issues/532

### Minecraft version

1.21

### Mod/Plugin version

1.21-2.5.20

### Mod/Plugin loader and version

Fabric 0.16.2

### Steps to reproduce

1. Have ViaFabricPlus and Simple Voice Chat installed (Client and Server)
2. Try to Join Server
3. Error

### Expected behavior

Not having that error and join the server WITH Simple Voice Chat.

### Log files

https://gist.github.com/DreiPixel/921927dc5c8bf7cccaf6ab8c3b3e65f4

**Comment by DreiPixel** [comment]
Build the Jar with this fix and it doesnt work. Still shows the same error.
https://gist.github.com/DreiPixel/94b4dfdcd4129c95dfb8df19eadee743

**Comment by henkelmax** [comment]
The error you are getting seems to be a general issue, since it also seems to be happening for non-custom payload packets.
