### ISSUE TITLE
Log spam on disconnect

### ISSUE THREAD

**Issue by N-Montana** [henkelmax/simple-voice-chat#739]
### Confirmation

- [X] I have read the wiki

### Bug description

On occasion when a player disconnects from the server the log is spammed with the error in the log I've linked to (file ended up being 6gb, error starts around line 5155) and the server becomes unresponsive until restarted.

### Minecraft version

1.18.2

### Mod/Plugin version

2.5.20

### Mod/Plugin loader and version

Forge 40.2.21

### Steps to reproduce

1. Log out from server
2. Occasionally begins spamming log that player "timed out" from voice chat

### Expected behavior

Presumably, the mod acknowledges the disconnect

### Log files

https://drive.google.com/file/d/1TzOFf87fggdR6p37b7m-XvgXFjUtFoFM/view?usp=drive_link

**Comment by henkelmax** [comment]
Please post your logs through github gist. I won't open random drive links.
Does this happen with just the voice chat mod installed on the server?

**Comment by N-Montana** [comment]
Well I can't get the log I have to reopen to trim it enough to upload through github. So I'll have to wait until it next happens to get a better one.

I can't really test it on it's own since it's happening once a day at most, I'm almost certain it's some weird interaction I just don't know what exactly.

**Comment by henkelmax** [comment]
> Well I can't get the log I have to reopen to trim it enough to upload through github. So I'll have to wait until it next happens to get a better one.

You can remove the duplicate spammed lines.

Also I'm not able to reproduce the issue. So please check if this also happens without any other mods installed, like I said before.

**Comment by N-Montana** [comment]
[2024-09-17-2.log](https://github.com/user-attachments/files/17022289/2024-09-17-2.log)

Finally got one short enough, had to remove ~8 million lines of spam that occurred in less than 2 minutes. The debug log is irrelevant since it was auto-clearing meaning it's just the last 3 lines on repeat.

Of course it won't reproduce as I said before this is almost certainly an incompatibility. Removing everything else will not give any information more than that. So why do you want me to remove every mod from an active server and just wait to see if something that occasionally happens... happens? When do I stop waiting days? Weeks? It's clear that it's an interaction with something, else this would've been reported before.

I would give you the modpack so you can test it yourself, but it's hosted on Drive which you don't trust downloading a text file from.

**Comment by henkelmax** [comment]
If its an incompatibility with another mod, I need to know which mod in order to fix it. I can try to blindly fix the issue, but don't get your hopes too high.

**Comment by henkelmax** [comment]
According to your logs its an error that occurs in the vault hunters mod. Please report it to their issue tracker.

**Comment by henkelmax** [comment]
This Should technically fix it buts 100% an issue with the vault hunters mod.

**Comment by N-Montana** [comment]
Thank you, I appreciate your time looking into this.
