### ISSUE TITLE
Data not being sent even while the port is open and functions properly

### ISSUE THREAD

**Issue by PentBeear** [henkelmax/simple-voice-chat#74]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
Even with the port open and working properly, the client can't seem to send or receive any information.

**Expected behavior**
The port 25554 was open and was successfully allowing me to send messages back and forth, therefor I thought it should work fine.

**Log files**
[https://gist.github.com/PentBeear/ae859ae63a0ae5fdc7b2d442eaac8394](url)
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.16.5
- Forge version 1.16.5-36.0.43
- Mod version 1.16.4-1.0.8

**Other mods**
ViveCraft 1.16.5-1.3.3

**Comment by henkelmax** [comment]
> Mod version 1.16.4-1.3.3

There is no version 1.3.3

Have you tested everything in the wiki?

**Comment by PentBeear** [comment]
Sorry about that typo it's actually 1.0.8 ill go ahead and edit it. And yes i did everything in the wiki

**Comment by henkelmax** [comment]
Can you send me the logs of the clients and the server when you use the test command?

**Comment by PentBeear** [comment]
Ah, i see the server log just says
Client not Connected, while the client is spamming
[VoiceChatAuthenticationThread/INFO] [voicechat/]: Trying to authenticate voice connection
every second or so

**Comment by henkelmax** [comment]
So this means your port isn't forwarded correctly.

**Comment by PentBeear** [comment]
Ah, you are correct the port decided to never open even though I specified it. Thanks for your time and assistance
