### ISSUE TITLE
Odd Icon Rendering Issue (Forge)

### ISSUE THREAD

**Issue by ghost** [henkelmax/simple-voice-chat#746]
### Confirmation

- [X] I have read the wiki

### Bug description

Was playing on a server with some friends on a 1.20.1 version of Minecraft. Using update 2.5.24 for Forge. Not entirely sure what the source of this is but it occurs even with shaders off.

### Minecraft version

1.20.1

### Mod/Plugin version

1.20.1-2.5.24

### Mod/Plugin loader and version

Forge-47.3.0

### Steps to reproduce

1. Launch Server
2. Player Joins
3. Player is either deafened or speaking.
4. Look along the x-coordinate to see the oversized icons.

### Expected behavior

The icon to restrict itself to the nametag instead of rendering a scaled up version away from the player that follows along on the x axis.

### Log files

Logs show nothing related to it.

### Screenshots

![Screenshot 2024-10-16 225643](https://github.com/user-attachments/assets/23bdba95-bddb-4c39-ab6e-8f5ddb6ad873)

**Comment by henkelmax** [comment]
This is a bug of the Figura mod.
