### ISSUE TITLE
Voice chat unavailable

### ISSUE THREAD

**Issue by Yucareux** [henkelmax/simple-voice-chat#75]
Server: 
[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: java.util.ConcurrentModificationException

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: at java.util.HashMap$ValueIterator.next(HashMap.java:1474)

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: at de.maxhenkel.voicechat.voice.server.Server.keepAlive(Server.java:205)

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: at de.maxhenkel.voicechat.voice.server.Server.access$100(Server.java:18)

[INFO] .... [STDERR/]: [de.maxhenkel.voicechat.voice.server.Server$ProcessThread:run:192]: at de.maxhenkel.voicechat.voice.server.Server$ProcessThread.run(Server.java:113)

Latest log: 
https://pastebin.com/6uHBr9HG

The situation here is that it's actually working for everyone, except for this player (Larisa123789)

**Comment by Yucareux** [comment]
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/6056290/latest.log)
(Client side log)

**Comment by henkelmax** [comment]
This is already a known issue (#70)

**Comment by henkelmax** [comment]
It should be fixed with the latest version.

**Comment by Yucareux** [comment]
We are currently playing on 1.16.4

**Comment by henkelmax** [comment]
I will port this fix to 1.16.4 if I know it works. Please consider updating, since almost every 1.16.4 mod is compatible with 1.16.5

**Comment by Yucareux** [comment]
yep, Im just waiting for a stable version of forge for 1.16.5

**Comment by henkelmax** [comment]
The fix is now also out for 1.16.4
