### ISSUE TITLE
Crashing on Launch again and again

### ISSUE THREAD

**Issue by Zenstrike0** [henkelmax/simple-voice-chat#750]
### Confirmation

- [X] I have read the wiki

### Bug description

my minecraft is repeatedly crashing when using the simple voice chat mod.
I have installed the correct version but still it crashes

heres the log file
[hs_err_pid1668.log](https://github.com/user-attachments/files/17727578/hs_err_pid1668.log)

### Minecraft version

1.20.1

### Mod/Plugin version

1.20.1

### Mod/Plugin loader and version

Latest Fabric Loader for Minecraft 1.20.1

### Steps to reproduce

idk

### Expected behavior

crash

### Log files

[hs_err_pid1668.log](https://github.com/user-attachments/files/17727578/hs_err_pid1668.log

**Comment by Zenstrike0** [comment]
@henkelmax pls help

**Comment by henkelmax** [comment]
Please properly answer all questions. I don't even know which mod version you are using. I also need the actual game logs!

**Comment by henkelmax** [comment]
I'm closing this for now. Please feel free to reopen once you provided the missing stuff.
