### ISSUE TITLE
renderPlayerIcon crash report

### ISSUE THREAD

**Issue by SamuelCharasse** [henkelmax/simple-voice-chat#752]
### Confirmation

- [X] I have read the wiki

### Bug description

We installed the mod correctly, made the right configuration. Crashes occurred when we created a group and a third person joined us in the same group. Since some players crash with the same crashreport logs. I think it could be from loading player heads for groups. But by having disabled groups from the server config the problem is not solved. We think that when you approach players, the icon next to the nickname can not load and it crashes. But this is still a hypothesis.

### Minecraft version

1.21.3

### Mod/Plugin version

1.21.3-2.5.25

### Mod/Plugin loader and version

Forge 53.0.19

### Steps to reproduce

1. Leaving an area too quickly with elytra 
2. Randomly

### Log files

https://gist.github.com/SamuelCharasse/5b41f20f0ac0d49325ffa0a7233a830d

**Comment by henkelmax** [comment]
Please describe the exact steps to reproduce the issue.
Also please test if this happens without any other mods installed.

**Comment by henkelmax** [comment]
Should be fixed in the next version
