### ISSUE TITLE
Minecraft 1.21.1 crashes when you tab out of the game.

### ISSUE THREAD

**Issue by Lice2** [henkelmax/simple-voice-chat#754]
### Confirmation

- [X] I have read the wiki

### Bug description

Everything works perfectly, you can also talk to each other via Simple Voice Chat in the game.
But as soon as you click on another program with ALT-TAB or with the mouse, e.g. Discord, the game crashes.
I have also attached the crash log.

### Minecraft version

1.21.1

### Mod/Plugin version

voicechat-fabric-1.21.1-2.5.26

### Mod/Plugin loader and version

fabric 0.16.9

### Steps to reproduce

In the game, use the mouse or ALT TAB to switch to Discord, for example. Then the game crashes.

### Expected behavior

The game crashes with the message
A fatal error has been detected by the Java Runtime Environment:

### Log files

https://gist.github.com/Lice2/17ebd0bf408ad21c9a098613e4b5b353

**Comment by henkelmax** [comment]
I am not able to reproduce this issue. Please provide a detailed description on how to reliably reproduce this issue. Also please provide your OS, java distro, launcher, etc

**Comment by Lice2** [comment]
i use Windows 10, Java 21 JDK 21,  and TLauncher

**Comment by henkelmax** [comment]
We don't support piracy

**Comment by henkelmax** [comment]
See #766
