### ISSUE TITLE
Crash 1.19.2 Forge SimpleVoiceChat

### ISSUE THREAD

**Issue by kitovoi111** [henkelmax/simple-voice-chat#755]
### Confirmation

- [X] I have read the wiki

### Bug description

I no found micro and my friend invite me in your group Voice, i click button Settings voice and my game crashed 
[crash-2024-11-30_04.46.08-client.txt](https://github.com/user-attachments/files/17963817/crash-2024-11-30_04.46.08-client.txt)

### Minecraft version

1.19.2

### Mod/Plugin version

voicechat-forge-1.19.2-2.5.26

### Mod/Plugin loader and version

Forge 1.19.2

### Steps to reproduce

I no found micro and my friend invite me in your group Voice, i click button Settings voice and my game crashed 

### Log files

https://gist.github.com/kitovoi111/58bf6cb7cdcc62c2722cb1d1a98e1d4c

**Comment by henkelmax** [comment]
The logs hint at a broken mod file. Please re-download the mod and make sure you don't do anything to the mod files while the game is running.
