### ISSUE TITLE
Occasional Crashes

### ISSUE THREAD

**Issue by EnderBoy9217** [henkelmax/simple-voice-chat#758]
### Confirmation

- [X] I have read the wiki

### Bug description

Game occasionally crashes, error points to the voice chat connection thread. My TCP and UDP port 25565 are open for this machine.

I believe Valkyrien Skies has the option to use UDP but again this is a singleplayer world, there shouldn't be any connecting. I don't believe it is a compatibility issue but I'll dump my modlist here regardless in case it is a different library version or something.
Full mod list (excluding voicechat cause I removed it).

fabric-language-kotlin - 1.13.0+kotlinc.2.1.0
ferritecore - 6.0.1-fabric
grabbymobs - 1.20.1-1.6
HorseCombatControls-f1 - 1.20.1-1.0.8
huskspawn - 1.20.1-3.6
ImmersiveThunder - 1.20.1+1.12.2
indium - 1.0.34+mc1.20.1
iris - 1.7.5+mc1.20.1
krypton - 0.2.3
lithium-fabric - mc1.20.1-0.11.2
modmenu - 7.2.2
mooshroomtweaks - 1.20.1-3.5
naturallychargedcreepers - 1.20.1-3.5
nysfsspiders-fabric - 1.20.1-2.1.11
owo-lib - 0.11.2+1.20
player-animation-lib-fabric - 1.0.2-rc1+1.20
sodium-fabric - 0.5.11+mc1.20.1
sound-physics-remastered-fabric - 1.20.1-1.5.4
spiritarrows-fabric - 1.20-1.0.4
strayspawn - 1.20.1-3.7
ValkyrienPirates - 1.20.1
ValkyrienLogs-shiprespawn - 1.20.3.0-beta.5
ValkyrienSkies - 1.20.3.0-beta.5
vscrumbles - 1.3-1.20.1
YungApi - 1.20-Fabric-4.0.6
YungsBetterDesertTemples - 1.20-Fabric-3.0.3
YungsBetterDungeons - 1.20-Fabric-4.0.4
YungsBetterEndIslands - 1.20-Fabric-1.0.6
YungsBetterJungleTemples - 1.20-Fabric-2.0.5
YungsBetterMineshafts - 1.20-Fabric-4.0.3
YungsBetterNetherFortresses - 1.20-Fabric-2.0.6
YungsBetterOceanMonuments - 1.20-Fabric-3.0.4
YungsBetterStrongholds - 1.20-Fabric-4.0.3
YungsBetterWitchHuts - 1.20-Fabric-3.0.3
YungsBridges - 1.20-Fabric-4.0.3
YungsExtras - 1.20-Fabric-1.0.4
YungsMenuTweaks - 1.20-Fabric-1.0.2
zombiehorsespawn - 1.20-1.5.1
Zoomify - 2.14.2+1.20.1
bettercombat-fabric - 1.8.6+1.20.1
betterspawncontrol - 1.20.1-4.6
cavespiderspawn - 1.20.1-1.2
cleanview - 1.20.1-v1-fabric
Clumps-fabric - 1.20.1+2.0.4
collective - 1.20.1-7.87
crawl - 0.12.0
cryingportals - 1.20.1-2.8
cupboard-fabric - 1.20.1-3.2
DistantHorizons - 2.2.1-a.1.20.1-forge-fabric
dragonflight-fabric - 1.20.1-4.6
eureka - 1.20.1-5.1-beta.3
fabric-api - 0.92.2+1.20.1
YetAnotherConfigLib - 3.6.1+1.20.1-fabric

### Minecraft version

1.20.1

### Mod/Plugin version

2.5.25

### Mod/Plugin loader and version

Fabric Loader 0.16.9

### Steps to reproduce

Create singleplayer world with the mod, 5-10 minutes in it crashes. I was in spectator mode during both of my crashes but didn't thoroughly investigate.

### Log files

https://gist.github.com/EnderBoy9217/e25561ca980193ce81ab1e8bcfedf414

**Comment by henkelmax** [comment]
Does that also happen with just the mod installed?


EDIT: I just did your steps to reproduce and it did not crash for me. Please check if this happens for you without any other mods and if yes, please give me the exact steps you did for causing the crash.

Feel free to reopen the issue then.
