### ISSUE TITLE
Error Console Spam

### ISSUE THREAD

**Issue by ZandercraftGames** [henkelmax/simple-voice-chat#76]
**Bug description**
During regular play, other than time-outs of all players happening quite regularly, even when there are no connectivity issues, the console gets spammed with this error: https://gist.github.com/ZandercraftGames/55f67f59114ab5a59d64e97f79cd732b

**Steps to reproduce the issue**
1. Run on server
2. Have multiple users connected
3. See errors in console.

**Log files**
https://gist.github.com/ZandercraftGames/55f67f59114ab5a59d64e97f79cd732b

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.0.43
- Mod version: 1.0.8

**Comment by henkelmax** [comment]
Please update to the latest version. This was already fixed.
