### ISSUE TITLE
game crashes when simple voice chat mod.

### ISSUE THREAD

**Issue by Eduronco** [henkelmax/simple-voice-chat#760]
### Confirmation

- [X] I have read the wiki

### Bug description

When simple voice chat is installed the game doesn't start.

PD: I'm using the modpack "Karmalnd 4 no oficial"

### Minecraft version

1.12.2

### Mod/Plugin version

all versions of 1.12.2

### Mod/Plugin loader and version

1.12.2-forge-14.23.5.2860

### Steps to reproduce

1. Install the modpack
2. start the game
3. download simple voice
4. start the game again and it should crash

### Log files

https://gist.github.com/Eduronco/ebb678197d3716d422531693332ed270#file-gistfile1-txt

### Screenshots

![Desktop Screenshot 2024 12 02 - 21 37 45 58](https://github.com/user-attachments/assets/378634d8-1679-4343-bad7-0d928b43ffa4)

**Comment by henkelmax** [comment]
You are running a mod which is shipping an outdated version of the mixin subsystem. 
SVC Ships with mixin 0.8. The other mod loads an older mixin version which causes the mod to not be able to load.
See https://modrepo.de/minecraft/voicechat/wiki/troubleshooting#mixin-config-voicechat-mixins-json-requires-mixin-subsystem-version-0-8-but-0-7-x-was-found-the-mixin-config-will-not-be-applied
