### ISSUE TITLE
The server crashes when i try to start it

### ISSUE THREAD

**Issue by Eduronco** [henkelmax/simple-voice-chat#761]
### Confirmation

- [X] I have read the wiki

### Bug description

When I try to start the server with voice chat and mixin compability installed it crashes.
PD: I'm using the modpack called "Karmaland 4 no oficial"

### Minecraft version

1.12.2

### Mod/Plugin version

all versions of 1.12.2

### Mod/Plugin loader and version

1.12.2-forge-14.23.5.2860

### Steps to reproduce

1. install the modpack with the mods in falix
2. start the server
3. server crashed

### Log files

https://gist.github.com/Eduronco/7362ef535a44cdd5bcc3ede57244a092#file-gistfile1-txt

### Screenshots

![image](https://github.com/user-attachments/assets/11df94ba-f95a-4c49-93f7-22657fc79f7c)

**Comment by henkelmax** [comment]
This crash is not caused by the voice chat mod.
