### ISSUE TITLE
Bug Report: Constantly crashes out my game while I TAB out

### ISSUE THREAD

**Issue by Nexuss0** [henkelmax/simple-voice-chat#764]
### Confirmation

- [X] I have read the wiki

### Bug description

Bug Report
My game is crashing constantly when I try to TAB out, Eg: ALT+TAB

Mod Version: 1.21.3 (fabric) 

### Minecraft version

1.21.3

### Mod/Plugin version

1.21.3

### Mod/Plugin loader and version

Fabric 

### Steps to reproduce

!. open Minecraft
2.join a server with simple voice chat mod
3.press ALT+TAB
4.Game crashes

### Expected behavior

I hope i get a quick response and don't have to face the a lot time waiting!

### Log files

https://github.com/user-attachments/files/18156265/tl-logger10608809286939293246.txt

**Comment by henkelmax** [comment]
Please provide steps to reproduce this issue. Also your logs don't contain any errors. Please provide the crash report if the game crashes.
(I'll reopen the issue if you provide steps, so I can actually reproduce the issue.)

**Comment by henkelmax** [comment]
See #766
