### ISSUE TITLE
Incompatibility with Flashback

### ISSUE THREAD

**Issue by FeineKatze** [henkelmax/simple-voice-chat#765]
### Confirmation

- [X] I have read the wiki

### Bug description

When trying to start Minecraft with just Simple Voice Chat, Flashback and FabricAPI (Dependency of Flashback) it crashes during the early startup with an error. I don't know on which side the error is, I have made an issue in Flashbacks Discord as well. Let me know if I should close this issue.

### Minecraft version

1.21.4

### Mod/Plugin version

1.21.4-2.5.27

### Mod/Plugin loader and version

Fabric Loader 0.16.9

### Steps to reproduce

1. Install Simple Voice Chat, Flashback and Fabric API
2. Try to start the game

### Expected behavior

Game starts normally with both mods enabled

### Log files

https://gist.github.com/FeineKatze/4e60d5fc7d87e57c51b472ce9b8da177

**Comment by henkelmax** [comment]
This is an issue with flashback. Please report it to their issue tracker

**Comment by henkelmax** [comment]
I made a PR to Flashback that should fix the issue.
