### ISSUE TITLE
Game crashes on alt+tab with NVIDIA GPU

### ISSUE THREAD

**Issue by mjwells2002** [henkelmax/simple-voice-chat#766]
### Bug description

For some users the game will crash if some unknown conditions are met when using voicechat and an nvidia gpu, in most cases its more common when sodium is installed, but it is not required

not much is known about why it crashes, but the issue seems to be caused by the nvidia drivers, 

## Potential workaround

setting the following setting to prefer native solves the crash for some users, but not everyone has the minecraft profile to configure this setting in

![image](https://github.com/user-attachments/assets/e751a7fd-1a15-47f7-82f5-2a6d0a873e20)

the crash will look like the following

```
---------------  T H R E A D  ---------------

Current thread (0x000002047b10ad40):  JavaThread "VoiceChatConnectionThread" daemon [_thread_in_native, id=10824, stack(0x000000fabbb50000,0x000000fabbc50000) (1024K)]

Stack: [0x000000fabbb50000,0x000000fabbc50000],  sp=0x000000fabbc4ee78,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007ff8b1cc0ec4

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.nio.ch.DatagramChannelImpl.receive0(Ljava/io/FileDescriptor;JIJZ)I+0 java.base@21.0.3
j  sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(Ljava/nio/ByteBuffer;IIZ)I+35 java.base@21.0.3
j  sun.nio.ch.DatagramChannelImpl.receive(Ljava/nio/ByteBuffer;Z)I+65 java.base@21.0.3
j  sun.nio.ch.DatagramChannelImpl.tryBlockingReceive(ZIJ)Ljava/nio/ByteBuffer;+18 java.base@21.0.3
j  sun.nio.ch.DatagramChannelImpl.blockingReceive(Ljava/net/DatagramPacket;J)V+142 java.base@21.0.3
j  sun.nio.ch.DatagramSocketAdaptor.receive(Ljava/net/DatagramPacket;)V+16 java.base@21.0.3
j  java.net.DatagramSocket.receive(Ljava/net/DatagramPacket;)V+5 java.base@21.0.3
j  de.maxhenkel.voicechat.plugins.impl.VoicechatSocketBase.read(Ljava/net/DatagramSocket;)Lde/maxhenkel/voicechat/plugins/impl/RawUdpPacketImpl;+19
j  de.maxhenkel.voicechat.plugins.impl.ClientVoicechatSocketImpl.read()Lde/maxhenkel/voicechat/api/RawUdpPacket;+22
j  de.maxhenkel.voicechat.voice.client.ClientVoicechatConnection.run()V+11
v  ~StubRoutines::call_stub 0x00000204639d100d

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), data execution prevention violation at address 0x00007ff8b1cc0ec4
```

## Attempted fixes

we have attempted to fix this issue by replacing the normal datagram socket with a new implentation provided by a native libary, this crashed in the exact same way 

this issue seems to be unsolveable

## Additional info required

anyone who can reproduce this issue and has the ability and knowledge to help debug exactly what is going wrong, should comment on this thread with any additonmal data they may have, as currently neither of us are able to reproduce this issue, from all collected logs, this issue seems unsolveable

Also please report your OS version, nvidia driver version, sodium version and voicechat version on this thread if you run into this problem driver version, sodium version and voicechat version on this thread if you run into this problem

**Comment by vogon-poetry** [comment]
I should note that having the minecraft.exe profile is not necessary to reproduce because the default setting on that profile is to use the global setting. 
![image](https://github.com/user-attachments/assets/3f4e1272-3f0e-459e-8d1c-1ce029d2c1cb)

On the Global tab, the default is Auto but of course we dont know what that means. I suspect Auto might use DXGI on Optimus laptops. But in my case I dont get the crash until I change it to DXGI, or I can change it to Native and its fine again.

**Comment by mjwells2002** [comment]
info gathered from a discord support thread

game crashes went away on older driver 555.99, crashed all the time on 566.36, crashed without sodium on either driver the present method had no effect 

on an Acer Nitro ANV15-51 with Intel i5 13420H and 4050

edit:

now reported, that a clean install of 566.36 is not crashing anymore
