### ISSUE TITLE
Have the forge and fabric versions of your mod on separate curseforge pages

### ISSUE THREAD

**Issue by NJL5390** [henkelmax/simple-voice-chat#79]
**Is your feature request related to a problem? Please describe.**
This is mainly related to updating mods and modpacks through the curseforge app or other 3rd party minecraft launchers and that they can't always differentiate between forge and fabric mods so if a mod has both forge and fabric versions on the same page, then the app will just download the latest one, which can lead to modpacks not working correctly.

**Describe the solution you'd like**
Have forge and fabric versions of your mod on different curseforge pages (i.e one page for the fabric version and another for the forge version). This is a solution that many other mods have used and it has worked pretty well.

**Describe alternatives you've considered**
Having the forge and fabric versions on the same page leads to trouble updating mods within modpacks and modpacks sometimes not working correctly because an incompatible version has been accidentally or unknowingly installed, this is especially true among those who are newer to modded minecraft.

**Additional context**
To demonstrate what I am talking about I took a couple of screenshots.
This shows the mod list in the app and the fact that an update is available for your mod:
![Screenshot 2021-03-02 19 23 38](https://user-images.githubusercontent.com/64381954/109703084-f9b5a100-7b8c-11eb-834d-42cc585ee719.png)
The screenshot below this shows that if I had just pressed the update button (which some people would have) instead of checking the version of the mod I would have downloaded the fabric version and my modpack (which is for forge) would no longer be working:
![Screenshot 2021-03-02 19 24 14](https://user-images.githubusercontent.com/64381954/109703271-2bc70300-7b8d-11eb-9bd8-0bb1ed38b9d1.png)

**Comment by henkelmax** [comment]
Curseforge has tags to specify what modloader the file is for especially for this.
How about reporting this to curseforge?
They should be able to separate files based on the modloader used.

**Comment by NJL5390** [comment]
Ok,
I have just checked their feedback page and this issue has already been reported to curseforge many times over, so I'll just wait for them to do something about it.

What I will say in relation to feedback about your mod is that it's fantastic and it works incredibly well! 
I've never seen a mod like this before and it's a mod I never knew I needed! I've been using it on a server with all my friends and we all love it! We've had no issues with it and it's an incredibly immersive experience!

10/10 - Would recommend to any modded server!

Thanks for your help and keep up the great work!

**Comment by henkelmax** [comment]
Thank you!
