### ISSUE TITLE
Activation Type: Voice does not work

### ISSUE THREAD

**Issue by MaximizationDF** [henkelmax/simple-voice-chat#8]
Expected: It Works
Reality: It Doesn't
I'm not the latest version, I have no errors on either my server or my client console... Also while I'm at it, can you add the ability to change the input? I had to figure out it was selecting my default mic by default, but since I have multiple emulated microphones on my computer, it was selecting one that I wasn't using at the time... Thanks much!

**Comment by henkelmax** [comment]
Please use the provided bug template and also add your logs even if there is no crash.
