### ISSUE TITLE
Reconnecting constantly

### ISSUE THREAD

**Issue by linx80** [henkelmax/simple-voice-chat#81]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
The mod keeps reconnecting players every other second.

**Steps to reproduce the issue**
Set up an server on Bisect Hosting and test the mod.

**Expected behavior**
That it shouldn't reconnect the players all the time.

**Log files**
https://gist.github.com/linx80/60828104b2c7aeabb0d1f967972ba180

**Versions**
- Minecraft version 1.16.5
- Forge version 36.0.45
- Mod version voicechat-1.16.5-1.0.10

**Other mods**
Any other mod shouldn't cause this problem since the modpack, NTI Modded, worked with previous versions of your mod.
And, it worked on a local server but not when hosted at Bisect Hosting.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please send me the full logs. But it seems that the server cannot reach the client via UDP. Make sure your port forwarding setup is correct.
Please also try the test command a few times and send me the logs of that from the server and the client you pinged with it.

Does this happen to every connected client?

**Comment by henkelmax** [comment]
So I just had someone that had the same problem. Please try and set the bind address in the server config to your servers IP.

**Comment by BestOcean-bit** [comment]
Hey how do I bind address

**Comment by henkelmax** [comment]
Read the wiki

**Comment by BestOcean-bit** [comment]
Where can I find that lmao i really dont know

**Comment by Weltz24K** [comment]
years later I got the same issue as this
