### ISSUE TITLE
Immersive voice directions

### ISSUE THREAD

**Issue by Asphahyre** [henkelmax/simple-voice-chat#82]
I’m an old mumble link player for immersive games, and it always have been a concern when hearing people talking from the surface while being 40m underground.

Now that voice chat is brought by a game mod rather than by external software, I wonder if there is a way to get directions and/or distances with some sort of pathfinding.

Ex: you’re on a cave, 10m below your comrade. The entrance is 30m behind you: when speaking, your comrade will hear you a bit low, and from the cave entrance, rather than behind him.

I believe the actual magic happens here:
https://github.com/henkelmax/simple-voice-chat/blob/9031c1bcc2b161c9bae64e012af4394666c88e51/src/main/java/de/maxhenkel/voicechat/voice/client/AudioChannel.java#L96-L110

Replacing distance fetching and direction vector computing by an separate class/component could also allow more sophisticated stuff:
- echoes you could have when in a cave, or mountains
- muffled sound depending on the blocks you’re behind (doors, glass, 1m of stone/dirt, water)
- [a more realistic sound attenuation](https://www.acoustical.co.uk/distance-attenuation/distance-attenuation/)
- could add some items such as phone blocks or cellulars to bypass proximity chat

This is a suggestion, on which I can propose my help, but it may not be appropriated to include everything in this mod.
Here are some **cons**:
- it brings completely different mechanics to Minecraft sound system
- it may be more suitable inside one or multiple distinct mod(s) which entirely rework Minecraft sound system

But there’s some **pros** too:
- it seems fairly easy to implement it here
- it’s not really bad if immersive sound only works for voice chat
- I can easily bring some PR on an already existing mod, but I still fear starting/maintaining a mod reworking all Minecraft sound system

**Comment by henkelmax** [comment]
I'm sorry, but I believe such calculations are way too intensive for every voice packet (Multiple times per second).
As you can see in #70 the voice chat struggles as is with many connected clients.
