### ISSUE TITLE
AFK Detection when using Voice activation

### ISSUE THREAD

**Issue by Marfjeh** [henkelmax/simple-voice-chat#86]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Many people i know uses Voice activation. but sometimes when a player goes AFK, everyone near the person can hear what is going on. maybe it would be nice if there is a optional option to enable a timer that a player did not interact with anything to be considered to be AFK, and that Voice activation is no longer working until the player starts interacting, for example moving the mouse, or walk etc.

**Describe alternatives you've considered**
If the person uses PTT, then it has built-in AFK detection, but in my experience not everyone likes to use PTT.

**Additional context**

Issues to consider:
Only issues i can think that will happen is that when a player is not moving or interacting with anything but is actually still there can be considered AFK by the system as a mistake.  maybe giving a notice somewhere that AFK mode will kick in and that you somehow can cancel it, for  example walking, move the camera, or interact with something.
and it will be maybe a good idea to disable this feature by default but have it an option in the settings for the people that wants this. to prevent confusion

**Comment by henkelmax** [comment]
> If the person uses PTT, then it has built-in AFK detection, but in my experience not everyone likes to use PTT.

I don't know what you mean with that.

You can just use the mute button.
