### ISSUE TITLE
List Forge and Fabric under separate mods

### ISSUE THREAD

**Issue by txm3278** [henkelmax/simple-voice-chat#87]
**Is your feature request related to a problem? Please describe.**
Putting both Fabric and Forge mods under a single curseforge project breaks modloaders ability to find the mod

**Describe the solution you'd like**
Separate the projects into a Forge and Fabric project

**Additional context**
The modloader tried was gdlauncher, but as I understand it, other modloaders have this issue due to curseforges api

**Comment by henkelmax** [comment]
Duplicate of #79
