### ISSUE TITLE
I have an issue with launching the mod - Requires FabricLoader

### ISSUE THREAD

**Issue by joshuaepstein** [henkelmax/simple-voice-chat#88]
When I try to launch the game with voicechat installed it gives me the error:
![image](https://user-images.githubusercontent.com/55663195/110385583-020f4f80-8057-11eb-8540-f0a5a1b64196.png)

-Thanks
Josh

**Comment by henkelmax** [comment]
You need the Fabric API

**Comment by joshuaepstein** [comment]
I have that installed and it doesnt work

**Comment by henkelmax** [comment]
Your Fabric version seems to be outdated or for the wrong version.

**Comment by joshuaepstein** [comment]
Thank you, that was the issue.
