### ISSUE TITLE
Unsure on how to download on server

### ISSUE THREAD

**Issue by Yasperko** [henkelmax/simple-voice-chat#9]
I am not really sure how to download this onto my server.

I have a server up and running ( hosted from apexminecrafthosting.com/uk/ ), but I do not know how to install the mod onto the server. I have got it to work client-side, its just server-side that is the issue.

I am new to this, so any help would be much appreciated

**Comment by henkelmax** [comment]
Just put it into your mod folder and start the server. But you have to make sure that the voice chat port is opened. This is not always possible when you are renting a minecraft server.
