### ISSUE TITLE
1.12.2 Support?

### ISSUE THREAD

**Issue by martino-dot** [henkelmax/simple-voice-chat#90]
**Is your feature request related to a problem? Please describe.**
Yes, there is no 1.12.2 support and almost all of my plugins for my server are only for 1.12.2.

**Describe the solution you'd like**
There is 1.12.2 support added into the mod.

**Describe alternatives you've considered**
None, there really isn't any other alternatives I can think of.

**Additional context**
I use 1.12.2 forge and want to use this mod on 1.12.2, but I unfortunately can't.

**Comment by henkelmax** [comment]
There are already 4 different versions I am maintaining. So adding a fifth one isn't really an option for me.
