### ISSUE TITLE
one player is getting "voice chat is unavailable" while the rest are not having an issue

### ISSUE THREAD

**Issue by jSdCool** [henkelmax/simple-voice-chat#91]
**Bug description**
one player on my server gets "voice chat is unavailable". 
everyone else on the server is having no problem with voice chat.
the problem player could hear the other people around him but could not use push to talk or open the voice chat options menu. 
we had the player restart minecraft and he could briefly open the options menu but it quickly went back to "voice chat is unavailable" and this time he could not hear us.

**Steps to reproduce the issue**
I have no idea why this is happening 

**Expected behavior**
the player would be able to use voice chat 

**Versions**
- Minecraft version 1.16.5
- fabric version 0.11.2
- Mod version 1.0.9

**Other mods**
opti fabric

**Comment by henkelmax** [comment]
Please update to the latest version and test it again.
Also please provide log files and do everything stated in the wiki.

**Comment by lilphantom25** [comment]
I'm on the latest version and I'm having issues, Just keep getting voice is unavailable when I use the keybinds in game.

**Comment by henkelmax** [comment]
As I already said. I need log files.
Also make sure your port is forwarded correctly.

**Comment by lilphantom25** [comment]
[latest.log](https://github.com/henkelmax/simple-voice-chat/files/6125708/latest.log)
Here is my latest log.

**Comment by henkelmax** [comment]
Yeah this is definately a duolicate of #81

**Comment by lilphantom25** [comment]
I have set the bind-address to the server IP and im still getting the same issue

**Comment by henkelmax** [comment]
Have you done everything in the wiki?
