### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by srnyx** [henkelmax/simple-voice-chat#94]
**Please read the [FAQ](https://modrepo.de/minecraft/voicechat/faq) before submitting a bug report!**

**Bug description**
I get an error when I try to launch Minecraft.

**Steps to reproduce the issue**
1. Install the mod

**Expected behavior**
Minecraft should start

**Log files**
Could not find required mod: voicechat requires {fabricloader @ [>=0.11.2]}

**Versions**
- 1.16.5
- Forge with JumpLoader (so Fabric)
- 1.0.9

**Other mods**
- JumpLoader
- Fabric API 0.32.0
_I'm using a custom modpack, so I only included mods that I thought would be conflicting_

**On a completely unrelated note:**
You may want to update the FAQ to say there already is a Fabric port: https://modrepo.de/minecraft/voicechat/faq

**Comment by srnyx** [comment]
Here's the modpack I'm using with a few extra ones: https://www.curseforge.com/minecraft/modpacks/simpearth/files/3209728

**Comment by henkelmax** [comment]
I'm not supporting other loaders.

**Comment by srnyx** [comment]
> I'm not supporting other loaders.

Why's that?

**Comment by henkelmax** [comment]
Because they introduce weird side effects.

**Comment by srnyx** [comment]
> Because they introduce weird side effects.

Aw, ok :(
Dang, I was really hoping to use this cause I currently use Mumble and Mumble-Link, which costs money.

**Comment by srnyx** [comment]
> I'm not supporting other loaders.

When you said this, I thought you meant *launchers* (like GDLauncher). 🤦‍♂️
