### ISSUE TITLE
Integration with Dynamic Surroundings

### ISSUE THREAD

**Issue by alpharou** [henkelmax/simple-voice-chat#96]
**Is your feature request related to a problem? Please describe.**
Something vaguely similar to #82

**Describe the solution you'd like**
Pass audio to Dynamic surroundings engine to get simple reverberations in caves without all the computational overhead.
I don't know if Dynamic Surroundings has that kind of api, but would be a major step in immersion.

https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings

It would not happen that voice could turn the corner, and depending on the implementation block obfuscation per voice/player location would be impossible... (be it, all voices merged into one channel and sent to recipients).

**Describe alternatives you've considered**
None.

**Comment by henkelmax** [comment]
This mod does not use Minecraft's sound engine.
